#!/bin/bash

exec 2>&1
sleep 1200
while [ 1 ]
do
    echo "check then cocaine-runtime is runing"
    while [ `/usr/local/bin/cocaine-depth.py | sed 's/1;\ error\ while\ connect\ to\ service\ node/2;pidor/g' | grep "^2;" | wc -l` -ne 0 ]
    do
        sleep 60
    done
    sleep 15
    echo "check then all apps is spooling"
    while [ `cocaine-tool i | grep spooling | wc -l` -ne 0 ]
    do
        sleep 60
    done
    /usr/local/bin/cocaine-depth.py | grep -o broken.* | awk '{print $2}' | sed 's/,/\n/g' | sed '$d' | while read name
    do
        rm -rv "/var/run/cocaine/$name"*
        cocaine-tool app restart -n $name --profile `cocaine-tool runlist view -n default-12 | grep $name | cut -d\" -f4`
    done
    sleep 600
done

