#!/bin/bash
exec 2>&1
ulimit -c unlimited
#ulimit -p 131072
if [ ! -p /tmp/cocaine_pushclient.pipe ]
then
    mkfifo /tmp/cocaine_pushclient.pipe
    touch /var/tmp/pushclient_ok
fi
while :; do /usr/bin/push-client  -f --ident=cocaine-test-backend '--logger:timeformat=[%d/%b/%Y:%T %z]' --files=/var/log/runit/cocaine-runtime/current --logtype=cocaine-log --network:master-addr=logbroker.yandex.net; done
#while :; do cat < /tmp/cocaine_pushclient.pipe; done | /usr/local/bin/cocs2tskv.pl | /usr/bin/push-client  -f --stdin --ident=cocaine-backend '--logger:timeformat=[%d/%b/%Y:%T %z]' --logtype=cocaine-testing-log --network:master-addr=logbroker.yandex.net
