#!/bin/bash
set -e

case "$1" in
    remove|upgrade|deconfigure)
        /opt/yandex/dbaas-worker/bin/dbaas-worker --remove-symlinks || exit $?
    ;;

    failed-upgrade)
    ;;

    *)
        echo "preinst called with unknown argument $1" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
