LIBRARY()

OWNER(g:snippets)

PEERDIR(
    kernel/dssm_applier/nn_applier/lib
    kernel/factor_storage
    kernel/factors_util
    kernel/facts/common
    kernel/facts/dssm_applier
    kernel/info_request
    kernel/lemmer
    kernel/lemmer/alpha
    kernel/lemmer/core
    kernel/lemmer/dictlib
    kernel/lemmer/untranslit
    kernel/matrixnet
    kernel/pure_lib
    kernel/qtree/richrequest
    kernel/relevfml
    kernel/search_daemon_iface
    kernel/segmentator/structs
    kernel/snippets/algo
    kernel/snippets/archive
    kernel/snippets/archive/chooser
    kernel/snippets/archive/markup
    kernel/snippets/archive/unpacker
    kernel/snippets/archive/view
    kernel/snippets/archive/zone_checker
    kernel/snippets/calc_dssm
    kernel/snippets/config
    kernel/snippets/custom
    kernel/snippets/custom/data
    kernel/snippets/custom/forums_handler
    kernel/snippets/custom/opengraph
    kernel/snippets/custom/preview_viewer
    kernel/snippets/custom/remove_emoji
    kernel/snippets/custom/canonize_unicode
    kernel/snippets/custom/schemaorg_viewer
    kernel/snippets/custom/sea_json
    kernel/snippets/custom/trash_classifier
    kernel/snippets/cut
    kernel/snippets/data
    kernel/snippets/delink
    kernel/snippets/dynamic_data
    kernel/snippets/entityclassify
    kernel/snippets/explain
    kernel/snippets/factors
    kernel/snippets/formulae
    kernel/snippets/hits
    kernel/snippets/i18n
    kernel/snippets/idl
    kernel/snippets/iface
    kernel/snippets/iface/archive
    kernel/snippets/markers
    kernel/snippets/plm
    kernel/snippets/qtree
    kernel/snippets/read_helper
    kernel/snippets/replace
    kernel/snippets/schemaorg
    kernel/snippets/schemaorg/factor_calcer
    kernel/snippets/schemaorg/question
    kernel/snippets/sent_info
    kernel/snippets/sent_match
    kernel/snippets/simple_cmp
    kernel/snippets/simple_textproc/capital
    kernel/snippets/simple_textproc/decapital
    kernel/snippets/simple_textproc/deyo
    kernel/snippets/smartcut
    kernel/snippets/snip_builder
    kernel/snippets/snip_proto
    kernel/snippets/span
    kernel/snippets/static_annotation
    kernel/snippets/strhl
    kernel/snippets/telephone
    kernel/snippets/title_trigram
    kernel/snippets/titles
    kernel/snippets/titles/make_title
    kernel/snippets/uni_span_iter
    kernel/snippets/urlcut
    kernel/snippets/urlmenu/common
    kernel/snippets/urlmenu/cut
    kernel/snippets/urlmenu/dump
    kernel/snippets/util
    kernel/snippets/video
    kernel/snippets/weight
    kernel/snippets/wordstat
    kernel/tarc/docdescr
    kernel/tarc/iface
    kernel/tarc/markup_zones
    kernel/url_tools
    kernel/web_factors_info
    kernel/word_hyphenator
    library/cpp/charset
    library/cpp/codecs
    library/cpp/containers/comptrie
    library/cpp/containers/comptrie/loader
    library/cpp/containers/dense_hash
    library/cpp/deprecated/split
    library/cpp/eventlog
    library/cpp/html/pcdata
    library/cpp/json
    library/cpp/json/writer
    library/cpp/langmask
    library/cpp/langmask/serialization
    library/cpp/langs
    library/cpp/lcs
    library/cpp/scheme
    library/cpp/stopwords
    library/cpp/streams/bzip2
    library/cpp/string_utils/base64
    library/cpp/string_utils/quote
    library/cpp/string_utils/url
    library/cpp/telfinder
    library/cpp/token
    library/cpp/tokenizer
    library/cpp/unicode/punycode
    library/cpp/wordpos
    search/idl
    util/draft
)

SRCS(
    basesnip.cpp
    basesnip_impl.cpp
    basesnip_viewers.cpp
    default_snippetizer.cpp
    hilite_messer.cpp
    raw.cpp
    words_messer.cpp
    shuffle_words.cpp
    pseudo_rand.cpp
)

END()
