# vim: ft=dockerfile
#
FROM ubuntu:focal

# Required system packages
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update \
    && apt-get install -y \
        wget unzip build-essential \
        libpcre3-dev libssl-dev liblzma-dev liblz4-dev \
        devscripts debhelper \
        autoconf autotools-dev bison flex libevent-dev libexpat1-dev \
        libtool python-all-dev swig

RUN mkdir -p /build/src
WORKDIR /build
COPY debian /build/src/debian

WORKDIR /build/src

RUN debuild -us -uc
RUN mkdir -p /build/artifacts
RUN find /build -maxdepth 1 -type f|xargs -n1 -I _ cp -v _ /build/artifacts/
