.PHONY: generate clean

mkfile_path := $(abspath $(lastword $(MAKEFILE_LIST)))
dir := $(dir $(mkfile_path))

generate-swagger:
	$(dir)scripts/swagger_gen.sh

clean-swagger:
	$(dir)/scripts/swagger_clean.sh
