OWNER(g:mdb)

RECURSE(
    backstage
    backup
    billing
    bootstrap
    cli
    clickhouse
    cms
    datacloud
    dataproc-agent
    dataproc-infra-tests
    dataproc-manager
    dataproc-ui-proxy
    dataproc-utils
    dbaas_infra_tests/python-protobuf
    dbaas-internal-api-image
    dbaas_metadb
    dbaas_python_common
    dbaas_worker
    dbm
    deploy
    deploydb
    gpsync
    graphene
    grpc-ping
    e2e-tests
    idm_service
    image-releaser
    images
    infratests
    internal
    katan
    kafka_agent
    kafka_authorizer
    lazy_trim
    logs-api
    mdb-blackbox-sso
    mdb-cli
    mdb-config-salt
    mdb-config-salt-baremetal
    mdb-disklock
    mdb-dns
    mdb-event-producer
    mdb-health
    mdb-pillar-config
    mdb-pillar-secrets
    mdb-internal-api
    mdb-maintenance
    mdb-my-toolkit
    mdb-pgcheck
    mdb-porto-agent
    mdb-reaper
    mdb-salt-sync
    mdb-search-producer
    mdb-secrets
    mdb-selfdns-client-plugins
    mdb-vpc
    mlock
    mlockdb
    mysync
    packages
    pg
    pgsync
    recipes
    release
    salt
    salt-tests
    sandbox
    scripts/pillar_generators
    scripts/pg_upgrade_non_dbaas
    scripts/s3_resetup
    tools
    ui
    unified-agent
    yazk-flock
)
