GRANT USAGE ON SCHEMA deploy TO deploy_api;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA deploy TO deploy_api;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA deploy TO deploy_api;
GRANT USAGE ON SCHEMA code TO deploy_api;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA code TO deploy_api;
GRANT SELECT ON TABLE public.schema_version TO deploy_api;
GRANT CONNECT ON DATABASE deploydb TO deploy_api;
