GRANT CONNECT ON DATABASE deploydb TO mdb_ui;
GRANT USAGE ON SCHEMA deploy TO mdb_ui;
GRANT SELECT, UPDATE, DELETE ON ALL TABLES IN SCHEMA deploy TO mdb_ui;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA deploy TO mdb_ui;
GRANT USAGE ON SCHEMA code TO mdb_ui;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA code TO mdb_ui;
