#! /bin/bash

set -xe

[ -d debian/venv ] || virtualenv3 --always-copy debian/venv
. debian/venv/bin/activate
pip3 install -r requirements.txt
python3 setup.py install --old-and-unmanageable
deactivate
virtualenv3 --relocatable debian/venv
rm -fv debian/venv/bin/python*
rm -fv debian/venv/local/bin/python*
