@dependent-scenarios
Feature: Internal API MySQL Single lifecycle

  Background: Wait until internal api is ready
    Given Internal API is up and running
    And actual MetaDB version
    And actual DeployDB version
    And Deploy API is up and running
    And Fake DBM is up and running
    And s3 is up and running
    And Mlock api is up and running
    And Secrets api is up and running
    And we are working with single_instance MySQL cluster

  Scenario: MySQL single instance creation works
    When we try to create cluster "test_mysql"
    Then response should have status 200
    And generated task is finished within "15 minutes"
    And cluster "test_mysql" is up and running
    And all hosts in mysql "test_mysql" are online
    And s3 has bucket for cluster
    And initial backup task is done
    And cluster has no pending changes

  Scenario: MySQL single instance task reject works
    Given cluster "test_mysql" is up and running
    When we lock cluster
    When we attempt to modify cluster "test_mysql" with following parameters
    """
    configSpec:
      mysqlConfig_5_7:
        maxConnections: 30
        innodbBufferPoolSize: 536870912
        longQueryTime: 1.5
        generalLog: ON
        maxAllowedPacket: 2097152
    """
    Then response should have status 200
    And generated task is failed within "3 minutes"
    When we unlock cluster
    Then cluster has no pending changes

  Scenario: Execute maintenance task for MySQL
    Given cluster "test_mysql" is up and running
    When we create maintenance task for MySQL cluster "test_mysql"
    """
    restart: false
    """
    Then generated task is finished within "15 minutes"
    And cluster "test_mysql" is up and running
    When we create maintenance task for MySQL cluster "test_mysql"
    """
    restart: true
    """
    Then generated task is finished within "15 minutes"
    And cluster "test_mysql" is up and running

  Scenario: Add MySQL host to single instance cluster
    Given cluster "test_mysql" is up and running
    When we attempt to add host in "test_mysql"
    """
    hostSpecs:
      - zoneId: myt
    """
    Then response should have status 200
    And generated task is finished within "15 minutes"
    And all hosts in mysql "test_mysql" are online
    And cluster "test_mysql" is up and running
    And cluster has no pending changes

  Scenario: Remove MySQL single instance
    Given cluster "test_mysql" is up and running
    When we attempt to remove cluster "test_mysql"
    Then response should have status 200
    And generated task is finished within "5 minutes"
    And in worker_queue exists "mysql_cluster_delete_metadata" task
    And this task is done
    And autogenerated shard was deleted from Solomon
    And we are unable to find cluster "test_mysql"

  Scenario: MySQL case insensetive cluster creation works
    When we try to create cluster "test_mysql_lowercase" with following config overrides
    """
    {
        "configSpec": {
            "mysqlConfig_5_7": {
                    "lowerCaseTableNames": 1
            }
        }
    }

    """
    Then response should have status 200
    And generated task is finished within "15 minutes"
    And all hosts in mysql "test_mysql_lowercase" are online
    And cluster "test_mysql_lowercase" is up and running
    And s3 has bucket for cluster
    And cluster has no pending changes

  Scenario: MySQL add database to lowercase cluster works
    Given cluster "test_mysql_lowercase" is up and running
    When we attempt to add database in "test_mysql_lowercase"
    """
    databaseSpec:
      name: TESTDB
    """
    Then response should have status 200
    And generated task is finished within "3 minutes"
    When we attempt to grant permission to user "another_test_user" in "test_mysql_lowercase"
    """
    permission:
      databaseName: testdb
      roles: ['ALL_PRIVILEGES', 'SELECT']
    """
    Then response should have status 200
    And generated task is finished within "3 minutes"
    And cluster has no pending changes
    Then following SQL request on master in "test_mysql_lowercase" succeeds
    """
    show databases like 'TESTDB';
    """
    And query result is like
    """
    - Database (TESTDB): 'testdb'
    """

  Scenario: MySQL remove database from lowercase cluster works
    Given cluster "test_mysql_lowercase" is up and running
    When we attempt to remove database "TESTDB" in cluster
    Then response should have status 200
    And generated task is finished within "3 minutes"
    Then following SQL request on master in "test_mysql_lowercase" succeeds
    """
    show databases like 'TESTDB';
    """
    And query result is empty
