FROM cr.yandex/yc-internal/base:2019-11-11T16-17

MAINTAINER https://wiki.yandex-team.ru/devtools/yandex-jdk/

RUN apt-get install --force-yes -y libapr1 libapr1-dev yandex-openjdk11=11.0.5-tzdata2019b
