#include "factor_names.h"

// autogenerated code
#include <kernel/begemot_query_rt_factors_info/factors_gen.cpp>

#include <kernel/generated_factors_info/simple_factors_info.h>

namespace NBegemotQueryRtFactors {

    // This function is declared in code-generated header factors_gen.h
    TAutoPtr<IFactorsInfo> GetFactorsInfoIf(size_t begin, size_t end) {
        Y_ASSERT(begin <= end);
        Y_ASSERT(end <= N_FACTOR_COUNT);
        return new TWebFactorsInfo<TFactorInfo>(begin, end, NBegemotQueryRtFactors::GetFactorsInfo());
    }

}  // namespace NBegemotQueryRtFactors
