CREATE TABLE %(table_name)s
(
    
    account_name String,
    -- active_grant_ids String,
    -- active_grants Int64,
    -- ad_block Int64,
    -- age String,
    -- all String,
    -- architect String,
    -- architect_actual String,
    -- area String,
    -- ba_currency String,
    -- ba_name String,
    -- ba_payment_cycle_type String,
    -- ba_payment_cycle_type_actual String,
    ba_person_type String,
    ba_person_type_actual String,
    ba_state String,
    ba_state_actual String,
    ba_type String,
    ba_type_actual String,
    ba_usage_status String,
    ba_usage_status_actual String,
    -- balance Float64,
    -- balance_actual Float64,
    -- balance_long_name String,
    -- balance_name String,
    billing_account_id String,
    -- billing_record_pricing_unit String,
    -- billing_record_usage_unit String,
    -- block_reason String,
    -- board_segment String,
    -- board_segment_actual String,
    -- br_cost Float64,
    -- br_cost_rub Float64,
    -- br_cost_rub_vat Float64,
    -- br_credit Float64,
    -- br_credit_cud Float64,
    -- br_credit_cud_rub Float64,
    -- br_credit_cud_rub_vat Float64,
    -- br_credit_disabled Float64,
    -- br_credit_disabled_rub Float64,
    -- br_credit_disabled_rub_vat Float64,
    -- br_credit_grant Float64,
    -- br_credit_grant_rub Float64,
    -- br_credit_grant_rub_vat Float64,
    -- br_credit_rub Float64,
    -- br_credit_rub_vat Float64,
    -- br_credit_service Float64,
    -- br_credit_service_rub Float64,
    -- br_credit_service_rub_vat Float64,
    -- br_credit_trial Float64,
    -- br_credit_trial_rub Float64,
    -- br_credit_trial_rub_vat Float64,
    -- br_credit_volume_incentive Float64,
    -- br_credit_volume_incentive_rub Float64,
    -- br_credit_volume_incentive_rub_vat Float64,
    -- br_pricing_quantity Float64,
    -- br_total Float64,
    -- br_var_reward Float64,
    -- br_var_reward_rub Float64,
    -- br_var_reward_rub_vat Float64,
    -- channel String,
    -- city String,
    -- client_ip String,
    cloud_id String,
    -- cloud_name String,
    -- cloud_status String,
    -- core_fraction String,
    -- core_fraction_number Float64,
    -- core_type String,
    -- cores String,
    -- cores_number Float64,
    -- country String,
    crm_account_architect String,
    crm_account_architect_current String,
    crm_account_bus_dev String,
    crm_account_bus_dev_current String,
    crm_account_name String,
    crm_account_owner String,
    crm_account_owner_current String,
    crm_account_partner_manager String,
    crm_account_partner_manager_current String,
    crm_account_sales String,
    crm_account_sales_current String,
    crm_account_segment String,
    crm_account_segment_current String,
    crm_account_tags String,
    -- database String,
    -- device_model String,
    -- device_type String,
    -- duration Int64,
    -- email String,
    event String,
    event_time DateTime,
    first_ba_created_datetime String,
    -- first_first_paid_consumption_datetime String,
    -- first_first_trial_consumption_datetime String,
    -- first_name String,
    -- general_interests String,
    -- grant_amount Float64,
    -- grant_amounts String,
    -- grant_end_times String,
    -- grant_source_ids String,
    -- grant_sources String,
    -- grant_start_times String,
    -- hits Int64,
    -- income Int64,
    -- interests String,
    -- is_bounce Int64,
    -- is_committed Float64,
    -- is_corporate_card Int64,
    is_fraud Int64,
    -- is_iot Int64,
    -- is_iot_actual Int64,
    -- is_isv Int64,
    -- is_isv_actual Int64,
    -- is_reserve String,
    -- is_robot String,
    -- is_var String,
    -- is_var_actual String,
    -- is_verified String,
    -- is_verified_actual String,
    -- last_name String,
    -- login String,
    -- mail_billing Int64,
    -- mail_event Int64,
    -- mail_feature Int64,
    -- mail_info Int64,
    -- mail_promo Int64,
    -- mail_tech Int64,
    -- mail_testing Int64,
    marketing_touched_events_count UInt64,
    marketing_touched_events_list String,
    -- master_account_id String,
    -- metrika_last_sign_touch_channel String,
    -- metrika_last_sign_touch_channel_marketing_influenced String,
    -- metrika_last_sign_touch_trafic_source String,
    -- metrika_last_sign_touch_utm_campaign String,
    -- metrika_last_sign_touch_utm_content String,
    -- metrika_last_sign_touch_utm_medium String,
    -- metrika_last_sign_touch_utm_source String,
    -- metrika_last_sign_touch_utm_term String,
    -- mk8s_relevant Float64,
    -- mobile_phone_vendor Int64,
    -- os String,
    -- page_views Int64,
    -- phone String,
    -- platform String,
    -- potential String,
    -- potential_actual String,
    -- preemptible String,
    -- puid String,
    -- ram String,
    -- ram_number Float64,
    -- real_consumption Float64,
    real_consumption_vat Float64,
    -- referer String,
    -- remote_ip String,
    -- resolution_depth Int64,
    -- resolution_height Int64,
    -- resolution_width Int64,
    sales_name String,
    -- sales_name_actual String,
    -- search_phrase String,
    segment String,
    segment_actual String,
    service_group String,
    service_id String,
    service_long_name String,
    service_name String,
    -- session_start_time String,
    -- sex String,
    sku_id String,
    sku_lazy Int64,
    sku_name String,
    -- start_url String,
    subservice_name String,
    -- total String,
    -- total_visits Int64,
    -- trial_consumption Float64,
    trial_consumption_vat Float64 ,
    -- unblock_reason String,
    -- usd_rur_quote Float64,
    -- user_settings_email String,
    -- utm_campaign String,
    -- utm_content String,
    -- utm_medium String,
    -- utm_source String,
    -- utm_term String
    -- vm_origin String,
    -- window_client_height Int64
    marketing_attribution_event_id UInt64,
    marketing_attribution_event_type String,
    marketing_attribution_event_time UInt64,
    marketing_attribution_channel String,
    marketing_attribution_channel_marketing_influenced String,
    marketing_attribution_utm_campaign String,
    marketing_attribution_utm_source String,
    marketing_attribution_utm_medium String,
    marketing_attribution_utm_term String,
    marketing_attribution_counter_id_serial UInt64,
    marketing_attribution_event_first_weight Float64,
    marketing_attribution_event_last_weight Float64,
    marketing_attribution_event_uniform_weight Float64,
    marketing_attribution_event_u_shape_weight Float64,
    marketing_attribution_event_exp_7d_half_life_time_decay_weight Float64
    
)
ENGINE = ReplicatedMergeTree('/clickhouse/tables/{shard}/%(table_name)s', '{replica}')
ORDER BY(event_time) PARTITION BY toYYYYMM(event_time)
