CREATE TABLE %(table_name)s
(
    date DateTime,
    billing_account_id String,
    ba_curr_state String,
    ba_curr_state_extended String,
    cloud_id String,
    service1 String,
    service2 String,
    service3 String,
    service4 String,
    sku String,
    pricing_unit String,
    quantity_cum_day Float64,
    cost_cum_day Float64,
    credit_cum_day Float64,
    paid_consumption_cum_day Float64,
    cost_minus_vat_cum_day Float64,
    credit_minus_vat_cum_day Float64,
    paid_consumption_minus_vat_cum_day Float64,
    quantity_cum Float64,
    cost_cum Float64,
    credit_cum Float64,
    paid_consumption_cum Float64,
    cost_minus_vat_cum Float64,
    credit_minus_vat_cum Float64,
    paid_consumption_minus_vat_cum Float64,
    quantity_cum_week Float64,
    cost_cum_week Float64,
    credit_cum_week Float64,
    paid_consumption_cum_week Float64,
    cost_minus_vat_cum_week Float64,
    credit_minus_vat_cum_week Float64,
    paid_consumption_minus_vat_cum_week Float64,
    quantity_cum_month Float64,
    cost_cum_month Float64,
    credit_cum_month Float64,
    paid_consumption_cum_month Float64,
    cost_minus_vat_cum_month Float64,
    credit_minus_vat_cum_month Float64,
    paid_consumption_minus_vat_cum_month Float64,
    quantity_cum_quarter Float64,
    cost_cum_quarter Float64,
    credit_cum_quarter Float64,
    paid_consumption_cum_quarter Float64,
    cost_minus_vat_cum_quarter Float64,
    credit_minus_vat_cum_quarter Float64,
    paid_consumption_minus_vat_cum_quarter Float64,
    usage_status String,
    offer_amount Float64,
    client_name String,
    source String,
    source2 String,
    segment String,
    sales_person String,
    idc_industry String

)
ENGINE = ReplicatedMergeTree('/clickhouse/tables/{shard}/%(table_name)s', '{replica}')
ORDER BY(date, billing_account_id, cloud_id, sku) PARTITION BY toYYYYMM(date)
