CREATE TABLE %(table_name)s
(
    lead_id Nullable(String),
    event_time DateTime,
    event Nullable(String),
    lead_state Nullable(String),
    ba_payment_cycle_type Nullable(String),
    ba_person_type Nullable(String),
    ba_state Nullable(String),
    ba_usage_status Nullable(String),
    billing_account_id Nullable(String),
    block_reason Nullable(String),
    call_description Nullable(String),
    call_id Nullable(String),
    call_name Nullable(String),
    call_parent_type Nullable(String),
    call_status Nullable(String),
    call_tag Nullable(String),
    channel Nullable(String),
    cloud_status Nullable(String),
    lead_email Nullable(String),
    lead_phone Nullable(String),
    lead_source Nullable(String),
    lead_source_description Nullable(String),
    paid_comsumption_cloud_ai Nullable(Float64),
    paid_comsumption_cloud_network Nullable(Float64),
    paid_comsumption_compute Nullable(Float64),
    paid_comsumption_mdb Nullable(Float64),
    paid_comsumption_nlb Nullable(Float64),
    paid_comsumption_storage Nullable(Float64),
    paid_comsumption_total Nullable(Float64),
    sales_name Nullable(String),
    segment Nullable(String),
    trial_comsumption_cloud_ai Nullable(Float64),
    trial_comsumption_cloud_network Nullable(Float64),
    trial_comsumption_compute Nullable(Float64),
    trial_comsumption_mdb Nullable(Float64),
    trial_comsumption_nlb Nullable(Float64),
    trial_comsumption_storage Nullable(Float64),
    trial_comsumption_total Nullable(Float64),
    puid Nullable(String),
    account_name Nullable(String)
    
)
ENGINE = ReplicatedMergeTree('/clickhouse/tables/{shard}/%(table_name)s', '{replica}')
ORDER BY(event_time) PARTITION BY toYYYYMM(event_time)