CREATE TABLE %(table_name)s
(
    ba_state Nullable(String),
    ba_type Nullable(String),
    balance_name Nullable(String),
    billing_account_id Nullable(String),
    cloud_id Nullable(String),
    email Nullable(String),
    first_name Nullable(String),
    is_real_consumption Nullable(Int32),
    is_real_consumption_next_period Nullable(Int32),
    is_real_payment Nullable(Int32),
    is_real_payment_next_period Nullable(Int32),
    is_trial_consumption Nullable(Int32),
    is_trial_consumption_next_period Nullable(Int32),
    last_name Nullable(String),
    phone Nullable(String),
    product Nullable(String),
    promocode_client_type Nullable(String),
    promocode_source Nullable(String),
    promocode_type Nullable(String),
    puid Nullable(String),
    real_consumption Nullable(Float64),
    real_consumption_client_type Nullable(String),
    real_consumption_cum Nullable(Float64),
    real_consumption_delta Nullable(Float64),
    real_consumption_next_period Nullable(Float64),
    real_payment Nullable(Float64),
    real_payment_client_type Nullable(String),
    real_payment_cum Nullable(Float64),
    real_payment_delta Nullable(Float64),
    real_payment_next_period Nullable(Float64),
    segment Nullable(String),
    trial_consumption Nullable(Float64),
    trial_consumption_client_type Nullable(String),
    trial_consumption_cum Nullable(Float64),
    trial_consumption_delta Nullable(Float64),
    trial_consumption_next_period Nullable(Float64),
    week Date,
    week_delta Int32,
    week_next Date,
    first_ba_created_datetime Nullable(DateTime),
    first_ba_became_paid_datetime Nullable(DateTime),
    first_cloud_created_datetime Nullable(DateTime),
    first_first_paid_consumption_datetime Nullable(DateTime),
    first_first_trial_consumption_datetime Nullable(DateTime),
    first_visit_datetime Nullable(DateTime),
    promocode_client_name Nullable(String),
    crm_client_name Nullable(String),
    sales Nullable(String),
    ba_usage_status Nullable(String),
    ba_person_type Nullable(String),
    block_reason Nullable(String)
    
)
ENGINE = ReplicatedMergeTree('/clickhouse/tables/{shard}/%(table_name)s', '{replica}')
ORDER BY(week,week_next, week_delta) PARTITION BY toYYYYMM(week)