CREATE TABLE %(table_name)s
(
    unit String,
    type String,
    ba_person_type String,
    preemptible UInt64,
    platform_id String,
    block_reason String,
    public_fips UInt64,
    ba_state String,
    t DateTime,
    paid_status String,
    ba_usage_status String,
    segment String,
    start DateTime,
    cores UInt64,
    product_ids String,
    ba_name String,
    sockets UInt64,
    version String,
    schema String,
    source_id String,
    cloud_id String,
    finish DateTime,
    ba_type String,
    core_fraction UInt64,
    potential String,
    channel String,
    folder_id String,
    billing_account_id String,
    is_fraud Int64,
    d Date,
    resource_id String,
    memory UInt64,
    sales_name String,
    architect String
)
ENGINE = ReplicatedMergeTree('/clickhouse/tables/{shard}/%(table_name)s', '{replica}')
ORDER BY(resource_id,start) PARTITION BY toYYYYMM(t)
