#!/bin/sh
# preinst script for config-monitoring-common
set -e

if dpkg-maintscript-helper supports rm_conffile 2>/dev/null; then
  dpkg-maintscript-helper rm_conffile /etc/monrun/conf.d/opened_rotated_logs.conf 1.0-63 -- "$@"
fi

exit 0
