#!/usr/bin/env python
# -*-coding: utf-8 -*-
# vim: sw=4 ts=4 expandtab ai

import introspect


def main():
    args = introspect.parse_args()

    services_to_check = [(name, introspect.SUPPORTED_SERVICES[name]) for name in args.checks]
    for name, port in services_to_check:
        # CLOUD-3100: do not report services we ignore
        if introspect.is_ignored(name, args.ignores):
            continue
        proc_status = introspect.get_procstatus(args.host, port, args.test)
        introspect.print_for_human(name, proc_status, args.ignores)


if __name__ == '__main__':
    main()
