Vagrant.configure("2") do |config|
  ## Choose base box
  config.vm.box = "ubuntu/trusty64"

  ## mount your salt states to '/srv/salt' dir
  config.vm.synced_folder "../platform-base/salt_base/", "/srv/salt/"

  ## install salt package and dependencies
  config.vm.provision :salt do |salt|
    salt.masterless = true
    salt.no_minion = false
    salt.run_highstate = false
  end

  config.vm.provision "shell" do |s|
    ## Set your salt states to test as  last args,
    # s.inline = "salt-call -l debug --local state.sls <state file names without '.sls'>"

    # for example
    s.inline = "salt-call -l debug --local state.sls grpcurl"
  end
end
