# This file is generated by
# https://bb.yandex-team.ru/projects/CLOUD/repos/cloud-go/browse/tools/cmd/syncapi
# in Teamcity Task
# https://teamcity.yandex-team.ru/buildConfiguration/Cloud_Api_ApiSync

OWNER(g:cloud-api g:mdb)
PROTO_LIBRARY()

PROTO_NAMESPACE(GLOBAL cloud/bitbucket/private-api)
PY_NAMESPACE(yandex.cloud.priv.mdb.postgresql.v1)

GRPC()
SRCS(
    alert.proto
    alert_group.proto
    backup.proto
    backup_service.proto
    cluster.proto
    cluster_service.proto
    database.proto
    database_service.proto
    maintenance.proto
    operation_service.proto
    perf_diag.proto
    perf_diag_service.proto
    resource_preset.proto
    resource_preset_service.proto
    user.proto
    user_service.proto
)

USE_COMMON_GOOGLE_APIS(
    api/annotations
    rpc/code
    rpc/errdetails
    rpc/status
    type/timeofday
    type/dayofweek
)

IF (GO_PROTO)
    PEERDIR(
        cloud/bitbucket/common-api/yandex/cloud/api
        cloud/bitbucket/common-api/yandex/cloud/api/tools
        cloud/bitbucket/private-api/yandex/cloud/priv
        cloud/bitbucket/private-api/yandex/cloud/priv/mdb/postgresql/v1/config
        cloud/bitbucket/private-api/yandex/cloud/priv/operation
    )
ELSE()
    PEERDIR(
        cloud/bitbucket/common-api/yandex/cloud/api
        cloud/bitbucket/common-api/yandex/cloud/api/tools
        cloud/bitbucket/private-api/yandex/cloud/priv
        cloud/bitbucket/private-api/yandex/cloud/priv/mdb/postgresql/v1/config
        cloud/bitbucket/private-api/yandex/cloud/priv/operation
    )
ENDIF()
END()

