#!/bin/bash
master=$(curl -s "https://slb.yandex-team.ru/api/v1/rs/?service=cvs.yandex-team.ru" | jq -r '.data[] | (select(.alive==true)) | .fqdn' | grep net | sed 's/\ *"//g' | uniq)
#master=`curl -s -I http://cvs.yandex-team.ru | grep X-CVS-Server | cut -f2 -d: | tr -d "[:space:]"`
[ -z $master ] && exit 1
echo "$master"
