#!/bin/bash

# removing old symlink for conf: 
rm /etc/zookeeper/conf

# creating new symlink for conf: 
ln -s /etc/zookeeper/conf_afisha /etc/zookeeper/conf

# creating symlink for myid: 
cp /etc/zookeeper/conf_afisha/myid.$(hostname -f) /etc/zookeeper/conf_afisha/myid

# diverting files: 
dpkg-divert --package config-corba-zookeeper --add /etc/zookeeper/conf_afisha/myid
dpkg-divert --package config-corba-zookeeper --add /etc/zookeeper/conf
