#!/bin/bash

# removing divertions: 
dpkg-divert --remove /etc/zookeeper/conf
dpkg-divert --remove /etc/zookeeper/conf_afisha/myid

#removing hand-made files: 
rm /etc/zookeeper/conf
rm /etc/zookeeper/conf_afisha/myid

# creating old symlink:
ln -s /etc/zookeeper/conf_example /etc/zookeeper/conf

