#pragma once

#define NON_WORD_PREFIX                       "##"
#define NON_WORD_PREFIX_LEN                   2

#define YDX_DOC_LEN_KEY  NON_WORD_PREFIX      "_DOC_LENS"
#define YDX_TITLE_LEN_KEY  NON_WORD_PREFIX    "_TITLE_LENS"
#define YDX_HEADING_LEN_KEY  NON_WORD_PREFIX  "_HEADING_LENS"
#define YDX_NORM_LEN_KEY  NON_WORD_PREFIX     "_NORMAL_TEXT_LENS"
#define YDX_LOW_LEN_KEY NON_WORD_PREFIX       "_LOW_TEXT_LENS"

#define YDX_DOC_IDF_SUM_KEY  NON_WORD_PREFIX      "_DOC_IDF_SUM"
#define YDX_TITLE_IDF_SUM_KEY  NON_WORD_PREFIX    "_TITLE_IDF_SUM"
#define YDX_HEADING_IDF_SUM_KEY  NON_WORD_PREFIX  "_HEADING_IDF_SUM"
#define YDX_NORM_IDF_SUM_KEY  NON_WORD_PREFIX     "_NORMAL_TEXT_IDF_SUM"
#define YDX_LOW_IDF_SUM_KEY NON_WORD_PREFIX       "_LOW_TEXT_IDF_SUM"

#define YDX_DOC_SIZE_KEY NON_WORD_PREFIX      "_DOC_SIZE"
#define YDX_MAX_FREQ_KEY NON_WORD_PREFIX      "_MAX_FREQ"
#define YDX_NOSPAM_FREQ_KEY NON_WORD_PREFIX   "_UNOPT_FREQ"
#define YDX_NKEYWORD_POS_KEY NON_WORD_PREFIX  "_KW_FREQ"

#define YDX_FAKE_KEY                          "####_FAKE"

#define YDX_INDEX_DATE                        "idate"
#define FDATE_ATTR_PREFIX                     "date"
