config_mf_skus = {
    "names_all_sku_sgps": [
        "Infrastructure",
        "Data Storage and Analytics",
        "Marketplace",
        "Support",
        "Cloud Native",
        "ML and AI",
        "Adjustments",
        "Tracker"
    ],
    "names_all_sku_srvs": [
        "compute",
        "cloud_network",
        "storage",
        "mdb",
        "marketplace",
        "support",
        "cloud_ai",
        "nlb",
        "cr",
        "serverless",
        "kms",
        "mk8s",
        "ydb",
        "ymq",
        "monitoring",
        "api_gateway",
        "iot",
        "adjustments",
        "tracker",
        "datalens",
        "dns"
    ],
    "names_mf_sku_sbsrvs": [
        "nbs_hdd",
        "fips",
        "cpu",
        "ram",
        "egress_inet",
        "ingress_inet",
        "used_space",
        "nbs_ssd",
        "storage",
        "postgres",
        "snapshot",
        "get",
        "put",
        "windows",
        "mysql",
        "head",
        "standard",
        "mongo",
        "clickhouse",
        "speech",
        "image",
        "delete",
        "redis",
        "nlb"
    ]
}
