#!/bin/sh
exec 2>&1

/Berkanavt/skynet/bin/gosky || true
/skynet/python/bin/python -sBtt /skynet/startup/up.py autostart || true

while [ 1 ]
do
    /Berkanavt/skynet/bin/gosky || true
    /skynet/startup/up.py autostart || true
    /usr/local/bin/skyctl autoinit  || true
    sleep 600
done
