enum Kind based on "path/to/file.proto":Path.Inside.Proto {
    Railway,
    Metro,
    Other
}

struct Address based on "search/address.proto":Address {
    struct Component based on "search/address.proto":Component {
        enum Kind based on "search/kind.proto":Kind {
            Country,
            Region,
            Province,
            Area,
            Locality,
            District,
            Street,
            House,

            Route,
            Station,
            MetroStation,
            RailwayStation,

            Vegetation,
            Hydro,
            Airport,
            Other
        }

        string name;
        vector<Kind> kind;
        dictionary<string, Component> someMap;
    }

    string formattedAddress;
    optional string postalCode;
    optional string countryCode;
    vector<Component> components;
}
