{{>DOCS}}YRT_EXPORT @interface {{TYPE_NAME}} {{#IS_CATEGORY}}({{CATEGORY}}){{/IS_CATEGORY}}{{#HAS_PARENT}}: {{#PARENT}}{{NAME}}{{/PARENT}}{{/HAS_PARENT}}{{#ITEM}}{{#METHOD}}

{{>METHOD}}{{/METHOD}}{{#PROPERTY}}

+ ({{#OPTIONAL}}nullable {{/OPTIONAL}}{{#NON_OPTIONAL}}nonnull {{/NON_OPTIONAL}}{{PROPERTY_TYPE}}){{#BOOL}}is{{PROPERTY_NAME:x-cap}}{{/BOOL}}{{#NOT_BOOL}}{{PROPERTY_NAME}}{{/NOT_BOOL}};{{#NOT_INTERFACE}}{{#NOT_READONLY}}
+ (void)set{{PROPERTY_NAME:x-cap}}:({{PROPERTY_TYPE}}){{PROPERTY_NAME}};{{/NOT_READONLY}}{{/NOT_INTERFACE}}{{/PROPERTY}}{{/ITEM}}

@end
