build-rpm:
	rpmbuild \
		--define "_defined_release `git rev-parse --short HEAD`" \
		--define "_defined_build_number `git rev-list HEAD --count`" \
		-bb yamail-gpsync.spec
	rm -rf INSTALLED_FILES build/ dist/ gpsync.egg-info/

clean:
	find . -name "*.pyc" -exec rm -rf {} \;
	find . -name "*.pyo" -exec rm -rf {} \;
	rm -rf INSTALLED_FILES build/ dist/ noarch/ gpsync.egg-info/

rpm: clean build-rpm
