#! /bin/bash

FIX_COUNT=$(timetail -n 900 -t syslog /var/log/default-route-fixer.log | grep -c flush)

if [ $FIX_COUNT -gt 0 ]; then
    echo "2;$FIX_COUNT neighbour flushes in the last 15 minutes"
else
    echo "0;ok"
fi
