#include "factor_names.h"

#include <kernel/generated_factors_info/simple_factors_info.h>

// autogenerated code
#include <kernel/alice/device_state_factors_info/factors_gen.cpp>

namespace NAliceDeviceState {

    // This function is declared in code-generated header factors_gen.h
    TAutoPtr<IFactorsInfo> GetFactorsInfoIf(const size_t begin, const size_t end) {
        Y_ASSERT(begin <= end);
        Y_ASSERT(end <= N_FACTOR_COUNT);
        return new TWebFactorsInfo<TFactorInfo>{begin, end, NAliceDeviceState::GetFactorsInfo()};
    }

}
