#!/bin/bash

export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
export LANGUAGE=en_US.UTF-8

exec 2>&1

if [ ! -f /var/tmp/mr_proper ]; then
  echo -n '0; Ok' > /var/tmp/mr_proper
fi

while :; do
if [[ `date +%H` == "02" ]]; then
    flock -w150 /var/lock/mr_proper -c '/usr/bin/mr_proper.py -l /dev/stdout --root-dc RTC --sv runit'
    sleep 3700;
else
    sleep 1800;
fi
done

