#!/bin/sh

### BEGIN INIT INFO
# Provides:             media-graphite-sender
# Required-Start:       $network
# Required-Stop:        
# Default-Start:        2 3 4 5
# Default-Stop:         0 1 6
# Short-Description:    forward metrics to graphite
### END INIT INFO

exec service media-graphite-sender "$1"
