{{#EXCLUDE}}/// @cond EXCLUDE
{{/EXCLUDE}}{{>DOCS}}{{#IS_NOT_STATIC}}virtual {{/IS_NOT_STATIC}}{{#IS_STATIC}}YANDEX_EXPORT {{/IS_STATIC}}{{RESULT_TYPE}} {{FUNCTION_NAME}}({{#PARAM}}
    {{#CONST_PARAM}}const {{/CONST_PARAM}}{{PARAM_TYPE}}{{#REF_PARAM}}&{{/REF_PARAM}} {{PARAM_NAME}}{{#DEFAULT_VALUE}} ={{VALUE}}{{/DEFAULT_VALUE}}{{#PARAM_separator}},{{/PARAM_separator}}{{/PARAM}}){{#IS_NOT_STATIC}}{{#CONST_METHOD}} const{{/CONST_METHOD}} = 0{{/IS_NOT_STATIC}};{{#EXCLUDE}}
/// @endcond{{/EXCLUDE}}