{{#EXCLUDE}}/// @cond EXCLUDE
{{/EXCLUDE}}{{#ITEM}}{{#METHOD}}{{>METHOD}}{{/METHOD}}{{#PROPERTY}}{{>PROPERTY_DOCS}}{{#INTERFACE}}YANDEX_EXPORT {{PROPERTY_TYPE}} {{PROPERTY_NAME}}();{{/INTERFACE}}{{#NOT_INTERFACE}}YANDEX_EXPORT {{#NOT_LISTENER}}{{#NOT_GEN}}{{#NOT_POD}}const {{/NOT_POD}}{{/NOT_GEN}}{{/NOT_LISTENER}}{{PROPERTY_TYPE}}{{#NOT_GEN}}{{#NOT_POD}}&{{/NOT_POD}}{{/NOT_GEN}} {{PROPERTY_NAME}}();{{#NOT_READONLY}}
YANDEX_EXPORT void set{{PROPERTY_NAME:x-cap}}({{#NOT_LISTENER}}{{#NOT_POD}}const {{/NOT_POD}}{{/NOT_LISTENER}}{{PROPERTY_TYPE}}{{#NOT_POD}}&{{/NOT_POD}} {{PROPERTY_NAME}});{{/NOT_READONLY}}{{/NOT_INTERFACE}}{{/PROPERTY}}{{#ITEM_separator}}

{{/ITEM_separator}}{{/ITEM}}{{#EXCLUDE}}
/// @endcond{{/EXCLUDE}}