# -*- coding: utf-8 -*-
"""
DBaaS Internal API PostgreSQL globals
"""

MY_CLUSTER_TYPE = 'postgresql_cluster'
USER_OBJ = 'users'
DATABASE_OBJ = 'databases'
RESTART_DEFAULTS = ['max_connections', 'shared_buffers']
DBNAME_WILDCARD = '*'
DEFAULT_CONN_LIMIT = 50
DEFAULT_SYS_CONN_LIMIT = 5
EDITION_1C = '1c'
DEFAULT_MAX_WAL_FRAC = 0.1
DEFAULT_MIN_WAL_FRAC = 0.05
DEFAULT_FRAC_DISK_SIZE_WAL_LIMIT = 0.5
DEFAULT_MIN_WAL_SIZE_IN_MEGABYTE = 64
DEFAULT_MAX_REPLICATION_SLOTS = 20
DEFAULT_MAX_WAL_SENDERS = 20
DEFAULT_MAX_LOGICAL_REPLICATION_WORKERS = 4
DEFAULT_MAX_WORKER_PROCESSES = 8
MAX_DEFAULT_MAINTENANCE_WORK_MEM_GB = 1
MAINTENANCE_WORK_MEM_STEP_MB = 64
ALLOW_DEPRECATED_VERSIONS_FEATURE_FLAG = 'MDB_PG_ALLOW_DEPRECATED_VERSIONS'
