# This file is generated by
# https://bb.yandex-team.ru/projects/CLOUD/repos/cloud-go/browse/tools/cmd/syncapi
# in Teamcity Task
# https://teamcity.yandex-team.ru/buildConfiguration/Cloud_Api_ApiSync

OWNER(g:cloud-api)
PROTO_LIBRARY()

PROTO_NAMESPACE(GLOBAL cloud/bitbucket/private-api)
PY_NAMESPACE(yandex.cloud.priv.cic.v1.inner.service)

GRPC()
SRCS(
    debug.proto
    peering.proto
    private_connection.proto
    private_connection_service.proto
    public_connection.proto
    public_connection_service.proto
    trunk_connection.proto
    trunk_connection_service.proto
)

USE_COMMON_GOOGLE_APIS(
    api/annotations
    rpc/code
    rpc/errdetails
    rpc/status
    type/timeofday
    type/dayofweek
)

IF (GO_PROTO)
    PEERDIR(
        cloud/bitbucket/common-api/yandex/cloud/api
        cloud/bitbucket/private-api/yandex/cloud/priv
        cloud/bitbucket/private-api/yandex/cloud/priv/cic/v1/inner/inventory
        cloud/bitbucket/private-api/yandex/cloud/priv/operation
    )
ELSE()
    PEERDIR(
        cloud/bitbucket/common-api/yandex/cloud/api
        cloud/bitbucket/private-api/yandex/cloud/priv
        cloud/bitbucket/private-api/yandex/cloud/priv/cic/v1/inner/inventory
        cloud/bitbucket/private-api/yandex/cloud/priv/operation
    )
ENDIF()
END()

