// Code generated by "stringer -type=AuthType -linecomment -output enums_string.go"; DO NOT EDIT.

package cfgtypes

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[DefaultAuthType-0]
	_ = x[NoAuthType-1]
	_ = x[IAMMetaAuthType-2]
	_ = x[TVMAuthType-3]
	_ = x[JWTAuthType-4]
	_ = x[TeamJWTAuthType-5]
	_ = x[StaticTokenAuthType-6]
	_ = x[maxAuthType-7]
}

const _AuthType_name = "_defaultnoauthiam-metadatatvmjwtteam-jwtstatic_max"

var _AuthType_index = [...]uint8{0, 8, 14, 26, 29, 32, 40, 46, 50}

func (i AuthType) String() string {
	if i >= AuthType(len(_AuthType_index)-1) {
		return "AuthType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _AuthType_name[_AuthType_index[i]:_AuthType_index[i+1]]
}
