#!/bin/bash
exec 2>&1
sleep 1

if [ ! -f /var/tmp/nginx_conf_ok ]
then
    sleep 3
    mkdir /var/lib/nginx 2>/dev/null || true
    mkdir /etc/yandex-certs/ 2>/dev/null || true
    cp -p /place/db/iss3/instances/*/mds.yandex.net.pem/mds.yandex.net.pem /etc/yandex-certs/mds.yandex.net.pem
    cp -p /place/db/iss3/instances/*/mds.yandex.net.key/mds.yandex.net.key /etc/yandex-certs/mds.yandex.net.key
    chmod 400 /etc/yandex-certs/mds.yandex.net.pem 
    chmod 400 /etc/yandex-certs/mds.yandex.net.key
    mkdir /root/nginx_conf/
    cp -v /place/db/iss3/instances/*/nginx.tar.xz/nginx.tar.xz /root/nginx_conf/
    mv -v /etc/nginx /etc/nginx_builded_state
    OCWD=$(pwd)
    cd  /root/nginx_conf/
    tar -xJf ./nginx.tar.xz
    mv -v ./nginx /etc/
    cd $OCWD
    echo 'set $tikaite_config_version 0-52;' > /etc/tikaite-config.version
    echo 'set $tikaite_version 1.0-10;' > /etc/tikaite.version
    touch /var/tmp/nginx_conf_ok
fi
if [ ! -f /root/nginx_conf/nginx.tar.xz ]; then
    rm /var/tmp/nginx_conf_ok
    exit 3
fi
if [ ! -f /etc/yandex-certs/mds.yandex.net.pem ]; then
    cp /place/db/iss3/instances/*/mds.yandex.net.pem/mds.yandex.net.pem /etc/yandex-certs/mds.yandex.net.pem
    cp /place/db/iss3/instances/*/mds.yandex.net.key/mds.yandex.net.key /etc/yandex-certs/mds.yandex.net.key
    chmod 400 /etc/yandex-certs/mds.yandex.net.pem
    chmod 400 /etc/yandex-certs/mds.yandex.net.key
fi
if [ ! -f /etc/yandex-certs/mds.yandex.net.key ]; then
    cp /place/db/iss3/instances/*/mds.yandex.net.pem/mds.yandex.net.pem /etc/yandex-certs/mds.yandex.net.pem
    cp /place/db/iss3/instances/*/mds.yandex.net.key/mds.yandex.net.key /etc/yandex-certs/mds.yandex.net.key
    chmod 400 /etc/yandex-certs/mds.yandex.net.pem
    chmod 400 /etc/yandex-certs/mds.yandex.net.key
fi

chmod 777 /var/run/loggiver/loggiver.sock

exec /usr/sbin/nginx -c /etc/nginx/nginx.conf -g "daemon off;"

