#! /usr/bin/env python3

from monmongo.ShardDistribution import ShardDistribution
import argparse
from urllib.parse import quote


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('url', type=str, help='URL to connect to', nargs='?')
    args = ap.parse_args()

    # detect url
    url = args.url
    if not url:
        with open('/etc/mongo-monitor.conf') as f:
            login = f.readline().strip()
            password = f.readline().strip()
        url = 'mongodb://{}:{}@localhost:27017/admin'.format(quote(login), quote(password))

    ShardDistribution().run(url)


if __name__ == '__main__':
    main()
