#!/bin/sh
set -e

case "$1" in
    configure)
        if [ -d /run/systemd ]; then
            systemctl daemon-reload
            systemctl start mdb-deploy-agent.service
            systemctl enable mdb-deploy-agent.service
        fi

        ;;

    abort-upgrade|abort-remove|abort-deconfigure)
        ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
        ;;
esac

exit 0
