#!/bin/sh
set -e

case "$1" in
    remove|deconfigure)
        if [ -d /run/systemd ]; then
            systemctl stop mdb-deploy-agent.service || true
            systemctl disable mdb-deploy-agent.service || true
        fi

        ;;

    failed-upgrade|upgrade)
        ;;

    *)
        echo "prerm called with unknown argument \`$1'" >&2
        exit 1
        ;;
esac

exit 0
