#!/bin/sh
set -e

# need for arcadia
#DEBHELPER#

# clean images
systemctl stop yc-snapshot
for CONTAINER_ID in $(docker ps -qa -f label=a.yandex-team.ru/cloud/compute/snapshot/qemu); do
    docker rm --force $CONTAINER_ID
done
docker rmi --force snapshot_qemu_nbd
