#!/bin/sh
exec 2>&1

sleep 5

FQDN=$(hostname -f)

if (( ${#FQDN} < 3 ))
then
  exit 191
fi

if [ ! -h /var/log/spacemimic ]
then
  mv /var/log/spacemimic /var/log/spacemimic.tmp.$(date +%s)
  if [ ! -d /place/db/www/logs/$FQDN/spacemimic/ ]
  then
    mkdir -p /place/db/www/logs/$FQDN/spacemimic/
  fi
  ln -sf /place/db/www/logs/$FQDN/spacemimic /var/log/
fi

exec /usr/bin/spacemimic --config=/etc/elliptics/spacemimic.conf --port=11000 --workers=5

