RECURSE(
    billing_accounts
    crm_account_roles
    crm_account_roles_audit
    crm_accounts
    crm_accounts_audit
    crm_accounts_contacts
    crm_accounts_opportunities
    crm_calls
    crm_calls_audit
    crm_contacts
    crm_contacts_audit
    crm_dimensions
    crm_email_address_bean_relations
    crm_email_addresses
    crm_leads
    crm_leads_audit
    crm_leads_billing_accounts
    crm_notes
    crm_opportunities
    crm_opportunities_audit
    crm_opportunities_contacts
    crm_opportunity_resource_lines
    crm_opportunity_resources
    crm_plans
    crm_plans_audit
    crm_product_categories
    crm_product_templates
    crm_product_templates_audit
    crm_revenue_line_items_audit
    crm_segments
    crm_tags
    crm_tasks
    crm_tasks_audit
    crm_team_sets_teams
    crm_teams
    crm_users
    dimension_bean_relations
    tag_bean_relations
)
