#!/bin/bash

export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
export LANGUAGE=en_US.UTF-8

mkdir /var/run/cocaine
exec 2>&1
ulimit -c unlimited
sleep 30
while [ ! -f /var/tmp/cocaine_conf_ok ]
do
    sleep 30
done
while [ `cocaine-tool i | wc -l` -le 1 ]
do
    sleep 10
done
DC=$(/usr/local/bin/get_qloud_data.py dc)
sed -i "s/__DC__/$DC/g" /etc/cocaine/orca.yaml
if [ $? != 0 ]
then
    echo "ERROR: cant change __DC__ in cocaine-orca config"
    exit 1
fi
sleep 10
exec /usr/bin/cocaine-orca

