{
 "title": "Cloud Architects",
 "time": { "from": "now-90d", "to": "now+8d" },
 "templating": {
  "list": [
   { "name": "consumption_type", "query": "trial, paid" },
   {
    "name": "architect",
    "query": "SELECT DISTINCT architect FROM cloud_analytics.consumption_daily_cube where architect not in  ('no_architect', '')"
   },
   {
    "name": "billing_account_id",
    "query": "SELECT DISTINCT billing_account_id FROM cloud_analytics.consumption_daily_cube WHERE has([$architect], architect)=1  ORDER BY billing_account_id"
   },
   {
    "name": "service",
    "label": "Service",
    "query": "SELECT distinct service_name FROM cloud_analytics.consumption_daily_cube WHERE service_name !=''"
   },
   {
    "name": "aggr_period",
    "query": "day,week,month,quarter,rolling_7days,rolling_14days,rolling_28days"
   },
   {
    "name": "period1",
    "label": "period_start_date",
    "query": "SELECT toDateTime(concat('$period1_date', ' 00:00:00'))"
   },
   {
    "name": "period1_date",
    "label": "period_start_date",
    "query": "SELECT DISTINCT toDate(multiIf('$aggr_period' = 'week', toMonday(date), '$aggr_period' = 'month', toStartOfMonth(date), '$aggr_period' = 'quarter', toStartOfQuarter(date), date)) FROM cloud_analytics.consumption_daily_cube"
   },
   {
    "name": "prev_period",
    "query": "SELECT multiIf('$aggr_period'='week', addWeeks(toDateTime('$period1'),-1), '$aggr_period'='month', addMonths(toDateTime('$period1'),-1), '$aggr_period'='quarter', addQuarters(toDateTime('$period1'),-1), addDays(toDateTime('$period1'),if('$aggr_period'='rolling_7days',-7,if('$aggr_period'='rolling_14days',-14,if('$aggr_period'='rolling_28days',-28,-1)))))"
   },
   {
    "name": "period1_end",
    "query": "SELECT multiIf('$aggr_period'='week', addWeeks(toDateTime('$period1'),1), '$aggr_period'='month', addMonths(toDateTime('$period1'),1), '$aggr_period'='quarter', addQuarters(toDateTime('$period1'),1),addDays(toDateTime('$period1'),if( '$aggr_period'='rolling_7days',7,if( '$aggr_period'='rolling_14days',14, if( '$aggr_period'='rolling_28days',28,1)))))"
   },
   {
    "name": "period1_end_date",
    "query": "SELECT addDays(toDate('$period1_end'), -1)"
   },
   { "name": "prev_period_date", "query": "SELECT toDate('$prev_period')" },
   {
    "name": "prev_period_end_date",
    "query": "SELECT addDays(toDate('$period1_date'),-1)"
   },
   { "name": "data_source", "query": "consumption_daily_cube" }
  ]
 },
 "panels": [
  { "title": "Информация о дашборде", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Дата и время последнего обновления",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT metadata_modification_time FROM system.tables \nWHERE name = '$data_source'\nAND database = 'cloud_analytics'",
     "rawQuery": "SELECT metadata_modification_time FROM system.tables  WHERE name = 'consumption_daily_cube' AND database = 'cloud_analytics'",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Обратная связь",
   "type": "text",
   "gridPos": { "h": 2, "w": 19, "x": 5, "y": 1 },
   "content": "\n## Если у Вас что-то не работает или Вам не хватает функциональности, пожалуйста, [дайте нам знать](https://forms.yandex-team.ru/surveys/21421/).\n\n\n"
  },
  { "title": "Потребление", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "Revenue Dynamics: Breakdown by Clients",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT  reverse(replaceAll(toFixedString(reverse(toString(rowNumberInAllBlocks() + 1)), 3), '\\0', '0')) N,\n        last_architect Architect,\n        billing_account_id BA,\n        last_client_name \"Компания\", \n        sumIf(sum_cost, date>='$prev_period' AND date<'$period1') as \"$prev_period_date to $prev_period_end_date\",\n        sumIf(sum_cost, date>='$period1' AND date<'$period1_end') as \"$period1_date to $period1_end_date\",\n        \"$period1_date to $period1_end_date\" - \"$prev_period_date to $prev_period_end_date\" as growth,\n        \"$period1_date to $period1_end_date\"/\"$prev_period_date to $prev_period_end_date\" -1 as growth_pct\nFROM( \n  SELECT\n    billing_account_id,\n    last_architect,\n    date,\n    last_client_name,\n    sum(cons_sum) as sum_cost\n  FROM cloud_analytics.consumption_daily_cube\n  WHERE (has ([$billing_account_id], billing_account_id) = 1 OR $billing_account_id = 'All')\n  AND has([$consumption_type], cons_type) = 1\n  AND has([$service], service_name) = 1\n  AND has([$architect], last_architect) = 1\n  GROUP BY last_architect, last_client_name,  billing_account_id, date\n)\nGROUP BY last_architect, last_client_name,  billing_account_id\n\nUNION All\n\nSELECT  'z.Total' N,\n        'z.Total' Architect,\n        'z.Total' BA,\n        'z.Total' \"Компания\", \n        sumIf(sum_cost, date>='$prev_period' AND date<'$period1') as prev_period,\n        sumIf(sum_cost, date>='$period1' AND date<'$period1_end') as period,\n        period - prev_period as prev_week_growth,\n        period/prev_period -1 as growth_pct\nFROM( \n  SELECT\n    date,\n    cons_sum as sum_cost\n  FROM cloud_analytics.consumption_daily_cube\n  WHERE (has ([$billing_account_id], billing_account_id) = 1 OR $billing_account_id = 'All')\n  AND has([$consumption_type], cons_type) = 1\n  AND has([$service], service_name) = 1\n  AND has([$architect], last_architect) = 1\n  \n)",
     "rawQuery": "SELECT  reverse(replaceAll(toFixedString(reverse(toString(rowNumberInAllBlocks() + 1)), 3), '\\0', '0')) N,         last_architect Architect,         billing_account_id BA,         last_client_name \"Компания\",          sumIf(sum_cost, date>='2019-05-01 00:00:00' AND date<'2019-06-01 00:00:00') as \"2019-05-01 to 2019-05-31\",         sumIf(sum_cost, date>='2019-06-01 00:00:00' AND date<'2019-07-01 00:00:00') as \"2019-06-01 to 2019-06-30\",         \"2019-06-01 to 2019-06-30\" - \"2019-05-01 to 2019-05-31\" as growth,         \"2019-06-01 to 2019-06-30\"/\"2019-05-01 to 2019-05-31\" -1 as growth_pct FROM(    SELECT     billing_account_id,     last_architect,     date,     last_client_name,     sum(cons_sum) as sum_cost   FROM cloud_analytics.consumption_daily_cube   WHERE (has (['All'], billing_account_id) = 1 OR 'All' = 'All')   AND has(['paid'], cons_type) = 1   AND has(['ai','compute','cr','mdb','network','nlb','storage','ymq'], service_name) = 1   AND has(['nrkk','vetkasov','vsgrab'], last_architect) = 1   GROUP BY last_architect, last_client_name,  billing_account_id, date ) GROUP BY last_architect, last_client_name,  billing_account_id  UNION All  SELECT  'z.Total' N,         'z.Total' Architect,         'z.Total' BA,         'z.Total' \"Компания\",          sumIf(sum_cost, date>='2019-05-01 00:00:00' AND date<'2019-06-01 00:00:00') as prev_period,         sumIf(sum_cost, date>='2019-06-01 00:00:00' AND date<'2019-07-01 00:00:00') as period,         period - prev_period as prev_week_growth,         period/prev_period -1 as growth_pct FROM(    SELECT     date,     cons_sum as sum_cost   FROM cloud_analytics.consumption_daily_cube   WHERE (has (['All'], billing_account_id) = 1 OR 'All' = 'All')   AND has(['paid'], cons_type) = 1   AND has(['ai','compute','cr','mdb','network','nlb','storage','ymq'], service_name) = 1   AND has(['nrkk','vetkasov','vsgrab'], last_architect) = 1    )",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Total Revenue",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "database": "cloud_analytics",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT \ndate, sum_cost\nFROM(\nSELECT \ntoInt32(date) * 1000 as date,\nsum(sum_cost) as sum_cost\nFROM (\n\n    SELECT multiIf('$aggr_period' = 'day', date, \n                   '$aggr_period' = 'week', toMonday(date),\n                   '$aggr_period' = 'month', toStartOfMonth(date), \n                   '$aggr_period' = 'quarter', toStartOfQuarter(date),\n                   date) AS date,\n         sum(cons_sum) as sum_cost\n    FROM cloud_analytics.consumption_daily_cube\n    WHERE (has ([$billing_account_id], billing_account_id) = 1 OR $billing_account_id = 'All')\n  AND has([$consumption_type], cons_type) = 1\n  AND has([$service], service_name) = 1\n  AND has([$architect], architect) = 1\n    GROUP BY date\n    ORDER BY date\n)\nGROUP BY date\nORDER BY date DESC\nLIMIT 0,1000\n)\nORDER BY date",
     "rawQuery": "SELECT  date, sum_cost FROM( SELECT  toInt32(date) * 1000 as date, sum(sum_cost) as sum_cost FROM (      SELECT multiIf('month' = 'day', date,                     'month' = 'week', toMonday(date),                    'month' = 'month', toStartOfMonth(date),                     'month' = 'quarter', toStartOfQuarter(date),                    date) AS date,          sum(cons_sum) as sum_cost     FROM cloud_analytics.consumption_daily_cube     WHERE (has (['All'], billing_account_id) = 1 OR 'All' = 'All')   AND has(['paid'], cons_type) = 1   AND has(['ai','compute','cr','mdb','network','nlb','storage','ymq'], service_name) = 1   AND has(['nrkk','vetkasov','vsgrab'], architect) = 1     GROUP BY date     ORDER BY date ) GROUP BY date ORDER BY date DESC LIMIT 0,1000 ) ORDER BY date",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Revenue Breakdown by Product",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "\nSELECT \ntoInt32(now()) * 1000 as date,\narrayMap(x->(if(x.1='zother','other',x.1),x.2),arraySort(x->x.1,groupArray((service_name_, sum_cost)))) as sum_cost\nFROM (\n    \n\n    SELECT\n          if(service_name in ('compute', 'mdb', 'ai', 'storage', 'network'), service_name, 'zother') as service_name_, \n         sumIf(cons_sum, date>='$period1' AND date<'$period1_end') as sum_cost\n    FROM cloud_analytics.consumption_daily_cube\n    WHERE (has ([$billing_account_id], billing_account_id) = 1 OR $billing_account_id = 'All')\n  AND has([$consumption_type], cons_type) = 1\n  AND has([$service], service_name) = 1\n  AND has([$architect], architect) = 1\n    GROUP BY service_name\n\n    \n)\n\n\n    \n    ",
     "rawQuery": "SELECT  toInt32(now()) * 1000 as date, arrayMap(x->(if(x.1='zother','other',x.1),x.2),arraySort(x->x.1,groupArray((service_name_, sum_cost)))) as sum_cost FROM (           SELECT           if(service_name in ('compute', 'mdb', 'ai', 'storage', 'network'), service_name, 'zother') as service_name_,           sumIf(cons_sum, date>='2019-06-01 00:00:00' AND date<'2019-07-01 00:00:00') as sum_cost     FROM cloud_analytics.consumption_daily_cube     WHERE (has (['All'], billing_account_id) = 1 OR 'All' = 'All')   AND has(['paid'], cons_type) = 1   AND has(['ai','compute','cr','mdb','network','nlb','storage','ymq'], service_name) = 1   AND has(['nrkk','vetkasov','vsgrab'], architect) = 1     GROUP BY service_name       )",
     "round": "0s"
    }
   ]
  }
 ]
}