{
 "title": "Cloud Consumption Research",
 "time": { "from": "now-90d", "to": "now+1d" },
 "templating": {
  "list": [
   { "name": "data_source", "query": "consumption_daily_v2_1" },
   {
    "name": "consumption_type",
    "query": "SELECT DISTINCT cons_type FROM cloud_analytics.consumption_daily_v2_1"
   },
   {
    "name": "segment",
    "query": "SELECT DISTINCT segment FROM cloud_analytics.consumption_daily_v2_1"
   },
   {
    "name": "billing_account_id",
    "query": "SELECT DISTINCT billing_account_id FROM cloud_analytics.consumption_daily_v2_1"
   },
   {
    "name": "size",
    "query": "SELECT DISTINCT size FROM cloud_analytics.consumption_daily_v2_1"
   },
   {
    "name": "person_type",
    "query": "SELECT DISTINCT person_type FROM cloud_analytics.consumption_daily_v2_1"
   },
   {
    "name": "channel",
    "query": "SELECT DISTINCT channel from cloud_analytics.consumption_daily"
   },
   {
    "name": "service_name",
    "query": "SELECT DISTINCT service_name FROM cloud_analytics.consumption_daily_v2_1"
   },
   {
    "name": "usage_status",
    "label": "Usage Status",
    "query": "SELECT DISTINCT usage_status FROM cloud_analytics.consumption_daily_v2_1"
   },
   {
    "name": "state",
    "query": "SELECT DISTINCT state FROM cloud_analytics.consumption_daily_v2_1"
   },
   {
    "name": "block_reason",
    "query": "SELECT DISTINCT block_reason FROM cloud_analytics.consumption_daily_v2_1 "
   },
   {
    "name": "core_fraction",
    "query": "SELECT DISTINCT core_fraction FROM cloud_analytics.consumption_daily_v2_1"
   },
   {
    "name": "preemptible",
    "query": "SELECT DISTINCT preemptible FROM cloud_analytics.consumption_daily_v2_1"
   },
   {
    "name": "platform",
    "query": "SELECT DISTINCT platform FROM cloud_analytics.consumption_daily_v2_1"
   },
   {
    "name": "database",
    "query": "SELECT DISTINCT database FROM cloud_analytics.consumption_daily_v2_1"
   },
   {
    "name": "aggr_period",
    "query": "day,week,month,quarter,rolling_7days,rolling_14days,rolling_28days"
   },
   {
    "name": "dimension1",
    "label": "Graph 1",
    "query": "total,cons_type,service_name,subservice_name,segment,channel,size,usage_status,state,last_state,block_reason,last_block_reason,platform,core_fraction,preemptible,database,billing_account_id,client_name"
   },
   {
    "name": "dimension2",
    "label": "Graph 2",
    "query": "total,cons_type,service_name,subservice_name,segment,channel,size,usage_status,state,last_state,block_reason,last_block_reason,platform,core_fraction,preemptible,database,billing_account_id,client_name"
   },
   {
    "name": "dimension3",
    "label": "Graph 3",
    "query": "total,cons_type,service_name,subservice_name,segment,channel,size,usage_status,state,last_state,block_reason,last_block_reason,platform,core_fraction,preemptible,database,billing_account_id,client_name"
   },
   {
    "name": "dimension4",
    "label": "Graph 4",
    "query": "total,cons_type,service_name,subservice_name,segment,channel,size,usage_status,state,last_state,block_reason,last_block_reason,platform,core_fraction,preemptible,database,billing_account_id,client_name"
   },
   {
    "name": "dimension5",
    "label": "Graph 5",
    "query": "total,cons_type,service_name,subservice_name,segment,channel,size,usage_status,state,last_state,block_reason,last_block_reason,platform,core_fraction,preemptible,database,billing_account_id,client_name"
   },
   {
    "name": "dimension6",
    "label": "Graph 6",
    "query": "total,cons_type,service_name,subservice_name,segment,channel,size,usage_status,state,last_state,block_reason,last_block_reason,platform,core_fraction,preemptible,database,billing_account_id,client_name"
   }
  ]
 },
 "panels": [
  { "title": "Информация о дашборде", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Дата и время последнего обновления",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT metadata_modification_time FROM system.tables \nWHERE name = 'consumption_daily_v2_1'\nAND database = 'cloud_analytics'",
     "rawQuery": "SELECT metadata_modification_time FROM system.tables  WHERE name = 'consumption_daily_v2_1' AND database = 'cloud_analytics'",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Обратная связь",
   "type": "text",
   "gridPos": { "h": 2, "w": 19, "x": 5, "y": 1 },
   "content": "\n## Если у Вас что-то не работает или Вам не хватает функциональности, пожалуйста, [дайте нам знать](https://forms.yandex-team.ru/surveys/21421/).\n\n\n"
  },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "1.Consumption by $dimension1",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "database": "cloud_analytics",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT \ntoInt32(date) * 1000 as date,\ngroupArray( (product, sum_cost))\nFROM (\n\n    SELECT multiIf('$aggr_period' = 'day', date, \n                   '$aggr_period' = 'week', toMonday(date),\n                   '$aggr_period' = 'month', toStartOfMonth(date), \n                   '$aggr_period' = 'year', toStartOfYear(date),\n                   date) AS date, \n           $dimension1 as product,\n          sum(cons_sum) as sum_cost\n    FROM cloud_analytics.$data_source\n    WHERE has([$usage_status], usage_status)=1\n    AND has([$consumption_type], cons_type) = 1\n    AND has([$service_name], service_name)=1\n    AND (has([$billing_account_id], billing_account_id) = 1 OR $billing_account_id = 'All')\n    AND has([$segment], segment)=1\n    AND has([$person_type], person_type)=1\n    AND has([$channel], channel)=1\n    AND has([$state], last_state)=1\n    AND has([$block_reason], last_block_reason)=1\n    AND has([$size], size)=1\n    AND has([$core_fraction], core_fraction)=1\n    AND has([$preemptible], preemptible)=1\n    AND has([$platform], platform)=1\n    AND has([$database], database)=1\n    GROUP BY date, product\n    ORDER BY date, product\n)\nGROUP BY date\nORDER BY date",
     "rawQuery": "SELECT  toInt32(date) * 1000 as date, groupArray( (product, sum_cost)) FROM (      SELECT multiIf('week' = 'day', date,                     'week' = 'week', toMonday(date),                    'week' = 'month', toStartOfMonth(date),                     'week' = 'year', toStartOfYear(date),                    date) AS date,             total as product,           sum(cons_sum) as sum_cost     FROM cloud_analytics.consumption_daily_v2_1     WHERE has(['trial','paid','disabled'], usage_status)=1     AND has(['trial','paid'], cons_type) = 1     AND has(['compute','mdb','network','storage','ai','nlb','cr','ymq'], service_name)=1     AND (has(['All'], billing_account_id) = 1 OR 'All' = 'All')     AND has(['','csm','enterprise','isv','isv_large','isv_ml','unmanaged','var'], segment)=1     AND has(['company','','individual','switzerland_nonresident_company'], person_type)=1     AND has(['Perfomance','Unknown','Direct','Referrals','Yandex Portal','Organic Search','Sales','Social','Emailing','unknown','Other'], channel)=1     AND has(['','active','inactive','new','payment_not_confirmed','payment_required','suspended'], last_state)=1     AND has(['','Unlocked','antifraud','debt','manual','mining','threshold','trial_expired','unbound_card'], last_block_reason)=1     AND has(['small','micro','unknown','medium','large'], size)=1     AND has(['','5','10','20','50','100'], core_fraction)=1     AND has(['','preemptible'], preemptible)=1     AND has(['','v2','v1'], platform)=1     AND has(['','pg','clickhouse','mysql','mongo','redis','ms_sql'], database)=1     GROUP BY date, product     ORDER BY date, product ) GROUP BY date ORDER BY date",
     "round": "0s"
    }
   ]
  },
  {
   "title": "2.Consumption by $dimension2",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "database": "cloud_analytics",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT \ntoInt32(date) * 1000 as date,\ngroupArray( (product, sum_cost))\nFROM (\n\n    SELECT multiIf('$aggr_period' = 'day', date, \n                   '$aggr_period' = 'week', toMonday(date),\n                   '$aggr_period' = 'month', toStartOfMonth(date), \n                   '$aggr_period' = 'year', toStartOfYear(date),\n                   date) AS date, \n           $dimension2 as product,\n          sum(cons_sum) as sum_cost\n    FROM cloud_analytics.$data_source\n    WHERE has([$usage_status], usage_status)=1\n    AND has([$consumption_type], cons_type) = 1\n    AND has([$service_name], service_name)=1\n    AND (has([$billing_account_id], billing_account_id) = 1 OR $billing_account_id = 'All')\n    AND has([$segment], segment)=1\n    AND has([$person_type], person_type)=1\n    AND has([$channel], channel)=1\n    AND has([$state], last_state)=1\n    AND has([$block_reason], last_block_reason)=1\n    AND has([$size], size)=1\n    AND has([$core_fraction], core_fraction)=1\n    AND has([$preemptible], preemptible)=1\n    AND has([$platform], platform)=1\n    AND has([$database], database)=1\n    GROUP BY date, product\n    ORDER BY date, product\n)\nGROUP BY date\nORDER BY date",
     "rawQuery": "SELECT  toInt32(date) * 1000 as date, groupArray( (product, sum_cost)) FROM (      SELECT multiIf('week' = 'day', date,                     'week' = 'week', toMonday(date),                    'week' = 'month', toStartOfMonth(date),                     'week' = 'year', toStartOfYear(date),                    date) AS date,             total as product,           sum(cons_sum) as sum_cost     FROM cloud_analytics.consumption_daily_v2_1     WHERE has(['trial','paid','disabled'], usage_status)=1     AND has(['trial','paid'], cons_type) = 1     AND has(['compute','mdb','network','storage','ai','nlb','cr','ymq'], service_name)=1     AND (has(['All'], billing_account_id) = 1 OR 'All' = 'All')     AND has(['','csm','enterprise','isv','isv_large','isv_ml','unmanaged','var'], segment)=1     AND has(['company','','individual','switzerland_nonresident_company'], person_type)=1     AND has(['Perfomance','Unknown','Direct','Referrals','Yandex Portal','Organic Search','Sales','Social','Emailing','unknown','Other'], channel)=1     AND has(['','active','inactive','new','payment_not_confirmed','payment_required','suspended'], last_state)=1     AND has(['','Unlocked','antifraud','debt','manual','mining','threshold','trial_expired','unbound_card'], last_block_reason)=1     AND has(['small','micro','unknown','medium','large'], size)=1     AND has(['','5','10','20','50','100'], core_fraction)=1     AND has(['','preemptible'], preemptible)=1     AND has(['','v2','v1'], platform)=1     AND has(['','pg','clickhouse','mysql','mongo','redis','ms_sql'], database)=1     GROUP BY date, product     ORDER BY date, product ) GROUP BY date ORDER BY date",
     "round": "0s"
    }
   ]
  },
  {
   "title": "3.Consumption by $dimension3",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "database": "cloud_analytics",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT \ntoInt32(date) * 1000 as date,\ngroupArray( (product, sum_cost))\nFROM (\n\n    SELECT multiIf('$aggr_period' = 'day', date, \n                   '$aggr_period' = 'week', toMonday(date),\n                   '$aggr_period' = 'month', toStartOfMonth(date), \n                   '$aggr_period' = 'year', toStartOfYear(date),\n                   date) AS date, \n           $dimension3 as product,\n          sum(cons_sum) as sum_cost\n    FROM cloud_analytics.$data_source\n    WHERE has([$usage_status], usage_status)=1\n    AND has([$consumption_type], cons_type) = 1\n    AND has([$service_name], service_name)=1\n    AND (has([$billing_account_id], billing_account_id) = 1 OR $billing_account_id = 'All')\n    AND has([$segment], segment)=1\n    AND has([$person_type], person_type)=1\n    AND has([$channel], channel)=1\n    AND has([$state], last_state)=1\n    AND has([$block_reason], last_block_reason)=1\n    AND has([$size], size)=1\n    AND has([$core_fraction], core_fraction)=1\n    AND has([$preemptible], preemptible)=1\n    AND has([$platform], platform)=1\n    AND has([$database], database)=1\n    GROUP BY date, product\n    ORDER BY date, product\n)\nGROUP BY date\nORDER BY date",
     "rawQuery": "SELECT  toInt32(date) * 1000 as date, groupArray( (product, sum_cost)) FROM (      SELECT multiIf('week' = 'day', date,                     'week' = 'week', toMonday(date),                    'week' = 'month', toStartOfMonth(date),                     'week' = 'year', toStartOfYear(date),                    date) AS date,             total as product,           sum(cons_sum) as sum_cost     FROM cloud_analytics.consumption_daily_v2_1     WHERE has(['trial','paid','disabled'], usage_status)=1     AND has(['trial','paid'], cons_type) = 1     AND has(['compute','mdb','network','storage','ai','nlb','cr','ymq'], service_name)=1     AND (has(['All'], billing_account_id) = 1 OR 'All' = 'All')     AND has(['','csm','enterprise','isv','isv_large','isv_ml','unmanaged','var'], segment)=1     AND has(['company','','individual','switzerland_nonresident_company'], person_type)=1     AND has(['Perfomance','Unknown','Direct','Referrals','Yandex Portal','Organic Search','Sales','Social','Emailing','unknown','Other'], channel)=1     AND has(['','active','inactive','new','payment_not_confirmed','payment_required','suspended'], last_state)=1     AND has(['','Unlocked','antifraud','debt','manual','mining','threshold','trial_expired','unbound_card'], last_block_reason)=1     AND has(['small','micro','unknown','medium','large'], size)=1     AND has(['','5','10','20','50','100'], core_fraction)=1     AND has(['','preemptible'], preemptible)=1     AND has(['','v2','v1'], platform)=1     AND has(['','pg','clickhouse','mysql','mongo','redis','ms_sql'], database)=1     GROUP BY date, product     ORDER BY date, product ) GROUP BY date ORDER BY date",
     "round": "0s"
    }
   ]
  },
  {
   "title": "4.Consumption by $dimension4",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "database": "cloud_analytics",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT \ntoInt32(date) * 1000 as date,\ngroupArray( (product, sum_cost))\nFROM (\n\n    SELECT multiIf('$aggr_period' = 'day', date, \n                   '$aggr_period' = 'week', toMonday(date),\n                   '$aggr_period' = 'month', toStartOfMonth(date), \n                   '$aggr_period' = 'year', toStartOfYear(date),\n                   date) AS date, \n           $dimension4 as product,\n          sum(cons_sum) as sum_cost\n    FROM cloud_analytics.$data_source\n    WHERE has([$usage_status], usage_status)=1\n    AND has([$consumption_type], cons_type) = 1\n    AND has([$service_name], service_name)=1\n    AND (has([$billing_account_id], billing_account_id) = 1 OR $billing_account_id = 'All')\n    AND has([$segment], segment)=1\n    AND has([$person_type], person_type)=1\n    AND has([$channel], channel)=1\n    AND has([$state], last_state)=1\n    AND has([$block_reason], last_block_reason)=1\n    AND has([$size], size)=1\n    AND has([$core_fraction], core_fraction)=1\n    AND has([$preemptible], preemptible)=1\n    AND has([$platform], platform)=1\n    AND has([$database], database)=1\n    GROUP BY date, product\n    ORDER BY date, product\n)\nGROUP BY date\nORDER BY date",
     "rawQuery": "SELECT  toInt32(date) * 1000 as date, groupArray( (product, sum_cost)) FROM (      SELECT multiIf('week' = 'day', date,                     'week' = 'week', toMonday(date),                    'week' = 'month', toStartOfMonth(date),                     'week' = 'year', toStartOfYear(date),                    date) AS date,             total as product,           sum(cons_sum) as sum_cost     FROM cloud_analytics.consumption_daily_v2_1     WHERE has(['trial','paid','disabled'], usage_status)=1     AND has(['trial','paid'], cons_type) = 1     AND has(['compute','mdb','network','storage','ai','nlb','cr','ymq'], service_name)=1     AND (has(['All'], billing_account_id) = 1 OR 'All' = 'All')     AND has(['','csm','enterprise','isv','isv_large','isv_ml','unmanaged','var'], segment)=1     AND has(['company','','individual','switzerland_nonresident_company'], person_type)=1     AND has(['Perfomance','Unknown','Direct','Referrals','Yandex Portal','Organic Search','Sales','Social','Emailing','unknown','Other'], channel)=1     AND has(['','active','inactive','new','payment_not_confirmed','payment_required','suspended'], last_state)=1     AND has(['','Unlocked','antifraud','debt','manual','mining','threshold','trial_expired','unbound_card'], last_block_reason)=1     AND has(['small','micro','unknown','medium','large'], size)=1     AND has(['','5','10','20','50','100'], core_fraction)=1     AND has(['','preemptible'], preemptible)=1     AND has(['','v2','v1'], platform)=1     AND has(['','pg','clickhouse','mysql','mongo','redis','ms_sql'], database)=1     GROUP BY date, product     ORDER BY date, product ) GROUP BY date ORDER BY date",
     "round": "0s"
    }
   ]
  },
  {
   "title": "5.Consumption by $dimension5",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "database": "cloud_analytics",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT \ntoInt32(date) * 1000 as date,\ngroupArray( (product, sum_cost))\nFROM (\n\n    SELECT multiIf('$aggr_period' = 'day', date, \n                   '$aggr_period' = 'week', toMonday(date),\n                   '$aggr_period' = 'month', toStartOfMonth(date), \n                   '$aggr_period' = 'year', toStartOfYear(date),\n                   date) AS date, \n           $dimension5 as product,\n          sum(cons_sum) as sum_cost\n    FROM cloud_analytics.$data_source\n    WHERE has([$usage_status], usage_status)=1\n    AND has([$consumption_type], cons_type) = 1\n    AND has([$service_name], service_name)=1\n    AND (has([$billing_account_id], billing_account_id) = 1 OR $billing_account_id = 'All')\n    AND has([$segment], segment)=1\n    AND has([$person_type], person_type)=1\n    AND has([$channel], channel)=1\n    AND has([$state], last_state)=1\n    AND has([$block_reason], last_block_reason)=1\n    AND has([$size], size)=1\n    AND has([$core_fraction], core_fraction)=1\n    AND has([$preemptible], preemptible)=1\n    AND has([$platform], platform)=1\n    AND has([$database], database)=1\n    GROUP BY date, product\n    ORDER BY date, product\n)\nGROUP BY date\nORDER BY date",
     "rawQuery": "SELECT  toInt32(date) * 1000 as date, groupArray( (product, sum_cost)) FROM (      SELECT multiIf('week' = 'day', date,                     'week' = 'week', toMonday(date),                    'week' = 'month', toStartOfMonth(date),                     'week' = 'year', toStartOfYear(date),                    date) AS date,             total as product,           sum(cons_sum) as sum_cost     FROM cloud_analytics.consumption_daily_v2_1     WHERE has(['trial','paid','disabled'], usage_status)=1     AND has(['trial','paid'], cons_type) = 1     AND has(['compute','mdb','network','storage','ai','nlb','cr','ymq'], service_name)=1     AND (has(['All'], billing_account_id) = 1 OR 'All' = 'All')     AND has(['','csm','enterprise','isv','isv_large','isv_ml','unmanaged','var'], segment)=1     AND has(['company','','individual','switzerland_nonresident_company'], person_type)=1     AND has(['Perfomance','Unknown','Direct','Referrals','Yandex Portal','Organic Search','Sales','Social','Emailing','unknown','Other'], channel)=1     AND has(['','active','inactive','new','payment_not_confirmed','payment_required','suspended'], last_state)=1     AND has(['','Unlocked','antifraud','debt','manual','mining','threshold','trial_expired','unbound_card'], last_block_reason)=1     AND has(['small','micro','unknown','medium','large'], size)=1     AND has(['','5','10','20','50','100'], core_fraction)=1     AND has(['','preemptible'], preemptible)=1     AND has(['','v2','v1'], platform)=1     AND has(['','pg','clickhouse','mysql','mongo','redis','ms_sql'], database)=1     GROUP BY date, product     ORDER BY date, product ) GROUP BY date ORDER BY date",
     "round": "0s"
    }
   ]
  },
  {
   "title": "6.Consumption by $dimension6",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "database": "cloud_analytics",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT \ntoInt32(date) * 1000 as date,\ngroupArray( (product, sum_cost))\nFROM (\n\n    SELECT multiIf('$aggr_period' = 'day', date, \n                   '$aggr_period' = 'week', toMonday(date),\n                   '$aggr_period' = 'month', toStartOfMonth(date), \n                   '$aggr_period' = 'year', toStartOfYear(date),\n                   date) AS date, \n           $dimension6 as product,\n          sum(cons_sum) as sum_cost\n    FROM cloud_analytics.$data_source\n    WHERE has([$usage_status], usage_status)=1\n    AND has([$consumption_type], cons_type) = 1\n    AND has([$service_name], service_name)=1\n    AND (has([$billing_account_id], billing_account_id) = 1 OR $billing_account_id = 'All')\n    AND has([$segment], segment)=1\n    AND has([$person_type], person_type)=1\n    AND has([$channel], channel)=1\n    AND has([$state], last_state)=1\n    AND has([$block_reason], last_block_reason)=1\n    AND has([$size], size)=1\n    AND has([$core_fraction], core_fraction)=1\n    AND has([$preemptible], preemptible)=1\n    AND has([$platform], platform)=1\n    AND has([$database], database)=1\n    GROUP BY date, product\n    ORDER BY date, product\n)\nGROUP BY date\nORDER BY date",
     "rawQuery": "SELECT  toInt32(date) * 1000 as date, groupArray( (product, sum_cost)) FROM (      SELECT multiIf('week' = 'day', date,                     'week' = 'week', toMonday(date),                    'week' = 'month', toStartOfMonth(date),                     'week' = 'year', toStartOfYear(date),                    date) AS date,             total as product,           sum(cons_sum) as sum_cost     FROM cloud_analytics.consumption_daily_v2_1     WHERE has(['trial','paid','disabled'], usage_status)=1     AND has(['trial','paid'], cons_type) = 1     AND has(['compute','mdb','network','storage','ai','nlb','cr','ymq'], service_name)=1     AND (has(['All'], billing_account_id) = 1 OR 'All' = 'All')     AND has(['','csm','enterprise','isv','isv_large','isv_ml','unmanaged','var'], segment)=1     AND has(['company','','individual','switzerland_nonresident_company'], person_type)=1     AND has(['Perfomance','Unknown','Direct','Referrals','Yandex Portal','Organic Search','Sales','Social','Emailing','unknown','Other'], channel)=1     AND has(['','active','inactive','new','payment_not_confirmed','payment_required','suspended'], last_state)=1     AND has(['','Unlocked','antifraud','debt','manual','mining','threshold','trial_expired','unbound_card'], last_block_reason)=1     AND has(['small','micro','unknown','medium','large'], size)=1     AND has(['','5','10','20','50','100'], core_fraction)=1     AND has(['','preemptible'], preemptible)=1     AND has(['','v2','v1'], platform)=1     AND has(['','pg','clickhouse','mysql','mongo','redis','ms_sql'], database)=1     GROUP BY date, product     ORDER BY date, product ) GROUP BY date ORDER BY date",
     "round": "0s"
    }
   ]
  }
 ]
}