{
 "title": "(Alpha) Cohorts Dynamics (Consumption)",
 "time": { "from": "now-90d", "to": "now+1d" },
 "templating": {
  "list": [
   {
    "name": "cohort",
    "query": "total,week,month,segment,ba_curr_state_extended,sales_person,channel,person_type"
   },
   {
    "name": "type",
    "query": "real,pct_to_cloud,pct_to_ba,pct_to_prev"
   },
   {
    "name": "month",
    "query": "SELECT DISTINCT month from cloud_analytics.funnel_events"
   },
   {
    "name": "segment",
    "query": "SELECT DISTINCT segment from cloud_analytics.funnel_events"
   },
   {
    "name": "ba_curr_state",
    "query": "SELECT DISTINCT ba_curr_state_extended from cloud_analytics.funnel_events"
   },
   {
    "name": "channel",
    "query": "SELECT DISTINCT channel FROM cloud_analytics.funnel_events"
   },
   {
    "name": "person_type",
    "query": "SELECT DISTINCT person_type FROM cloud_analytics.funnel_events"
   }
  ]
 },
 "panels": [
  { "title": "Важно", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Дата и время последнего обновления",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT metadata_modification_time FROM system.tables \nWHERE name = 'funnel_events'\nAND database = 'cloud_analytics'",
     "rawQuery": "SELECT metadata_modification_time FROM system.tables  WHERE name = 'funnel_events' AND database = 'cloud_analytics'",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Обратная связь",
   "type": "text",
   "gridPos": { "h": 2, "w": 19, "x": 5, "y": 1 },
   "content": "\n## Если у Вас что-то не работает или Вам не хватает функциональности, пожалуйста, [дайте нам знать](https://forms.yandex-team.ru/surveys/21421/).\n\n\n"
  },
  {
   "title": "Disclaimer",
   "type": "text",
   "gridPos": { "h": 9, "w": 18, "x": 0, "y": 3 },
   "content": "Динамика численности когорт, дошедших до определенной стадии воронки. Шаг - одна неделя. Воронка простраивается по passport_uid'у.\n\nСтадии (события) воронки:\n  * Cloud Created - владелец данного passport_uid'а зашел в консоль и создал облако;\n  * BA Created - владелец данного passport_uid'а создал платежный аккаунт;\n  * First Consumption - владелец данного passport_uid'а начал потребление;\n  * Active Consumption - владелец данного passport_uid'а считается активным, если на неделе t он хотя бы в один день потребил 10 рублей и более;\n  * First Paid Consumption - владелец данного passport_uid'а начал платное потребление;\n  * Active Paid Consumption - владелец данного passport_uid'а считается активным, если на неделе t он хотя бы в один день потребил платно 10 рублей и более.\n\nМожно выбирать следующие тэги в качестве когорт:\n  * total - фиктивная когорта, включает в себя всех пользователей\n  * week/month - неделя/месяц регистрации в Облаке;\n  * segment/ba_curr_state_extended/sales_person/channel - сегмент/статус биллинга/сейлз/канал привлечения для данного пользователя;\n\nМожно выбрать тип отображения:\n  * real - кол-во пользователей, достигших определенной стадии воронки\n  * pct_to_cloud - процент пользователей достигших определенной стадии воронки от кол-ва пользователей, зарегистрировашихся в Облаке\n  * pct_to_ba - процент пользователей достигших определенной стадии воронки от кол-ва пользователей, создавших BA в Облаке\n  * pct_to_prev - процент пользователей, достигших определенной стадии воронек от кол-ва пользователей, достигших предыдущего шага. \n  Последовательность следующая: Cloud Created, BA Created/Cloud Created, First Consumption/BA Created, Active Consumption/First Consumption, First Paid Consumption/First Consumption, Active Paid Consumption/First Paid Consumption\n\nТакже можно фильтровать данные по месяцу регистрации в Облаке (month), сегменту (segment), статусу биллинга (ba_curr_state_extended) и каналу привлечения (channel)"
  },
  { "title": "Cohorts Dynamics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Cloud Created",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\nt, groupArray(($cohort, cloud_created))\nFROM (\n  SELECT \n    toInt64(t)*1000 as t,\n    $cohort,\n    sum(cloud_created) as cloud_created\n  FROM\n    cloud_analytics.funnel_grouped\n  WHERE\n    has([$month], month ) = 1\n    AND has([$segment], segment ) = 1\n    AND has([$ba_curr_state], ba_curr_state_extended ) = 1\n    AND has([$channel], channel) = 1\n    AND has([$person_type], person_type) = 1\n  GROUP BY\n    t, \n    $cohort\n)\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT t, groupArray((week, cloud_created)) FROM (   SELECT      toInt64(t)*1000 as t,     week,     sum(cloud_created) as cloud_created   FROM     cloud_analytics.funnel_grouped   WHERE     has(['2019-03','2019-02','2019-01'], month ) = 1     AND has(['enterprise','isv','mass','yandex'], segment ) = 1     AND has(['active','not_created','payment_not_confirmed','payment_required'], ba_curr_state_extended ) = 1     AND has(['Direct','Emailing','Organic Search','Other','Perfomance','Referrals','Sales','Social','Unknown','Yandex Portal','organic'], channel) = 1     AND has(['not_created','individual','company','switzerland_nonresident_company','other'], person_type) = 1   GROUP BY     t,      week ) GROUP BY t ORDER BY t",
     "round": "0s"
    }
   ]
  },
  {
   "title": "BA Created",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\nt, groupArray(($cohort, ba_created))\nFROM (\n  SELECT \n    toInt64(t)*1000 as t,\n    $cohort,\n    multiIf('$type' = 'real', toFloat64(sum(ba_created)), \n            '$type' = 'pct_to_cloud', sum(ba_created)/sum(cloud_created)*100, \n            '$type' = 'pct_to_ba', toFloat64(sum(ba_created)),\n            sum(ba_created)/sum(cloud_created)*100)  as ba_created\n  FROM\n    cloud_analytics.funnel_grouped\n  WHERE\n    has([$month], month ) = 1\n    AND has([$segment], segment ) = 1\n    AND has([$ba_curr_state], ba_curr_state_extended ) = 1\n    AND has([$channel], channel) = 1\n    AND has([$person_type], person_type) = 1\n  GROUP BY\n    t, \n    $cohort\n)\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT t, groupArray((week, ba_created)) FROM (   SELECT      toInt64(t)*1000 as t,     week,     multiIf('real' = 'real', toFloat64(sum(ba_created)),              'real' = 'pct_to_cloud', sum(ba_created)/sum(cloud_created)*100,              'real' = 'pct_to_ba', toFloat64(sum(ba_created)),             sum(ba_created)/sum(cloud_created)*100)  as ba_created   FROM     cloud_analytics.funnel_grouped   WHERE     has(['2019-03','2019-02','2019-01'], month ) = 1     AND has(['enterprise','isv','mass','yandex'], segment ) = 1     AND has(['active','not_created','payment_not_confirmed','payment_required'], ba_curr_state_extended ) = 1     AND has(['Direct','Emailing','Organic Search','Other','Perfomance','Referrals','Sales','Social','Unknown','Yandex Portal','organic'], channel) = 1     AND has(['not_created','individual','company','switzerland_nonresident_company','other'], person_type) = 1   GROUP BY     t,      week ) GROUP BY t ORDER BY t",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Total Trial Consumption",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\nt, groupArray(($cohort, ba_first_consumption))\nFROM (\n  SELECT \n    toInt64(t)*1000 as t,\n    $cohort,\n    multiIf('$type' = 'real', toFloat64(sum(total_trial_consumption)), \n            '$type' = 'pct_to_cloud', sum(ba_first_consumption)/sum(cloud_created)*100, \n            '$type' = 'pct_to_ba', sum(ba_first_consumption)/sum(ba_created)*100,\n            sum(ba_first_consumption)/sum(ba_created)*100)  as ba_first_consumption\n  FROM\n    cloud_analytics.funnel_grouped_consumption\n  WHERE\n    has([$month], month ) = 1\n    AND has([$segment], segment ) = 1\n    AND has([$ba_curr_state], ba_curr_state_extended ) = 1\n    AND has([$channel], channel) = 1\n    AND has([$person_type], person_type) = 1\n  GROUP BY\n    t, \n    $cohort\n)\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT t, groupArray((week, ba_first_consumption)) FROM (   SELECT      toInt64(t)*1000 as t,     week,     multiIf('real' = 'real', toFloat64(sum(total_trial_consumption)),              'real' = 'pct_to_cloud', sum(ba_first_consumption)/sum(cloud_created)*100,              'real' = 'pct_to_ba', sum(ba_first_consumption)/sum(ba_created)*100,             sum(ba_first_consumption)/sum(ba_created)*100)  as ba_first_consumption   FROM     cloud_analytics.funnel_grouped_consumption   WHERE     has(['2019-03','2019-02','2019-01'], month ) = 1     AND has(['enterprise','isv','mass','yandex'], segment ) = 1     AND has(['active','not_created','payment_not_confirmed','payment_required'], ba_curr_state_extended ) = 1     AND has(['Direct','Emailing','Organic Search','Other','Perfomance','Referrals','Sales','Social','Unknown','Yandex Portal','organic'], channel) = 1     AND has(['not_created','individual','company','switzerland_nonresident_company','other'], person_type) = 1   GROUP BY     t,      week ) GROUP BY t ORDER BY t",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Active Trial Consumption",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\nt, groupArray(($cohort, ba_consumed_last_7days))\nFROM (\n  SELECT \n    toInt64(t)*1000 as t,\n    $cohort,\n    multiIf('$type' = 'real', toFloat64(sum(active_trial_consumption)), \n            '$type' = 'pct_to_cloud', sum(ba_consumed_last_7days)/sum(cloud_created)*100, \n            '$type' = 'pct_to_ba', sum(ba_consumed_last_7days)/sum(ba_created)*100,\n            sum(ba_consumed_last_7days)/sum(ba_first_consumption)*100)  as ba_consumed_last_7days\n  FROM\n    cloud_analytics.funnel_grouped_consumption\n  WHERE\n    has([$month], month ) = 1\n    AND has([$segment], segment ) = 1\n    AND has([$ba_curr_state], ba_curr_state_extended ) = 1\n    AND has([$channel], channel) = 1\n    AND has([$person_type], person_type) = 1\n  GROUP BY\n    t, \n    $cohort\n)\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT t, groupArray((week, ba_consumed_last_7days)) FROM (   SELECT      toInt64(t)*1000 as t,     week,     multiIf('real' = 'real', toFloat64(sum(active_trial_consumption)),              'real' = 'pct_to_cloud', sum(ba_consumed_last_7days)/sum(cloud_created)*100,              'real' = 'pct_to_ba', sum(ba_consumed_last_7days)/sum(ba_created)*100,             sum(ba_consumed_last_7days)/sum(ba_first_consumption)*100)  as ba_consumed_last_7days   FROM     cloud_analytics.funnel_grouped_consumption   WHERE     has(['2019-03','2019-02','2019-01'], month ) = 1     AND has(['enterprise','isv','mass','yandex'], segment ) = 1     AND has(['active','not_created','payment_not_confirmed','payment_required'], ba_curr_state_extended ) = 1     AND has(['Direct','Emailing','Organic Search','Other','Perfomance','Referrals','Sales','Social','Unknown','Yandex Portal','organic'], channel) = 1     AND has(['not_created','individual','company','switzerland_nonresident_company','other'], person_type) = 1   GROUP BY     t,      week ) GROUP BY t ORDER BY t",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Total Paid Consumption",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\nt, groupArray(($cohort, ba_first_paid_consumption))\nFROM (\n  SELECT \n    toInt64(t)*1000 as t,\n    $cohort,\n    multiIf('$type' = 'real', toFloat64(sum(total_paid_consumption)), \n            '$type' = 'pct_to_cloud', sum(ba_first_paid_consumption)/sum(cloud_created)*100, \n            '$type' = 'pct_to_ba', sum(ba_first_paid_consumption)/sum(ba_created)*100,\n            sum(ba_first_paid_consumption)/sum(ba_first_consumption)*100) as ba_first_paid_consumption\n  FROM\n    cloud_analytics.funnel_grouped_consumption\n  WHERE\n    has([$month], month ) = 1\n    AND has([$segment], segment ) = 1\n    AND has([$ba_curr_state], ba_curr_state_extended ) = 1\n    AND has([$channel], channel) = 1\n    AND has([$person_type], person_type) = 1\n  GROUP BY\n    t, \n    $cohort\n)\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT t, groupArray((week, ba_first_paid_consumption)) FROM (   SELECT      toInt64(t)*1000 as t,     week,     multiIf('real' = 'real', toFloat64(sum(total_paid_consumption)),              'real' = 'pct_to_cloud', sum(ba_first_paid_consumption)/sum(cloud_created)*100,              'real' = 'pct_to_ba', sum(ba_first_paid_consumption)/sum(ba_created)*100,             sum(ba_first_paid_consumption)/sum(ba_first_consumption)*100) as ba_first_paid_consumption   FROM     cloud_analytics.funnel_grouped_consumption   WHERE     has(['2019-03','2019-02','2019-01'], month ) = 1     AND has(['enterprise','isv','mass','yandex'], segment ) = 1     AND has(['active','not_created','payment_not_confirmed','payment_required'], ba_curr_state_extended ) = 1     AND has(['Direct','Emailing','Organic Search','Other','Perfomance','Referrals','Sales','Social','Unknown','Yandex Portal','organic'], channel) = 1     AND has(['not_created','individual','company','switzerland_nonresident_company','other'], person_type) = 1   GROUP BY     t,      week ) GROUP BY t ORDER BY t",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Active Paid Consumption",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\nt, groupArray(($cohort, ba_consumed_paid_last_7days))\nFROM (\n  SELECT \n    toInt64(t)*1000 as t,\n    $cohort,\n    multiIf('$type' = 'real', toFloat64(sum(active_paid_consumption)), \n            '$type' = 'pct_to_cloud', sum(ba_consumed_paid_last_7days)/sum(cloud_created)*100, \n            '$type' = 'pct_to_ba',sum(ba_consumed_paid_last_7days)/sum(ba_created)*100,\n            sum(ba_consumed_paid_last_7days)/sum(ba_first_paid_consumption)*100)  as ba_consumed_paid_last_7days\n  FROM\n    cloud_analytics.funnel_grouped_consumption\n  WHERE\n    has([$month], month ) = 1\n    AND has([$segment], segment ) = 1\n    AND has([$ba_curr_state], ba_curr_state_extended ) = 1\n    AND has([$channel], channel) = 1\n    AND has([$person_type], person_type) = 1\n  GROUP BY\n    t, \n    $cohort\n)\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT t, groupArray((week, ba_consumed_paid_last_7days)) FROM (   SELECT      toInt64(t)*1000 as t,     week,     multiIf('real' = 'real', toFloat64(sum(active_paid_consumption)),              'real' = 'pct_to_cloud', sum(ba_consumed_paid_last_7days)/sum(cloud_created)*100,              'real' = 'pct_to_ba',sum(ba_consumed_paid_last_7days)/sum(ba_created)*100,             sum(ba_consumed_paid_last_7days)/sum(ba_first_paid_consumption)*100)  as ba_consumed_paid_last_7days   FROM     cloud_analytics.funnel_grouped_consumption   WHERE     has(['2019-03','2019-02','2019-01'], month ) = 1     AND has(['enterprise','isv','mass','yandex'], segment ) = 1     AND has(['active','not_created','payment_not_confirmed','payment_required'], ba_curr_state_extended ) = 1     AND has(['Direct','Emailing','Organic Search','Other','Perfomance','Referrals','Sales','Social','Unknown','Yandex Portal','organic'], channel) = 1     AND has(['not_created','individual','company','switzerland_nonresident_company','other'], person_type) = 1   GROUP BY     t,      week ) GROUP BY t ORDER BY t",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Total Consumption",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\nt, groupArray(($cohort, ba_first_consumption))\nFROM (\n  SELECT \n    toInt64(t)*1000 as t,\n    $cohort,\n    multiIf('$type' = 'real', toFloat64(sum(total_consumption)), \n            '$type' = 'pct_to_cloud', sum(ba_first_consumption)/sum(cloud_created)*100, \n            '$type' = 'pct_to_ba', sum(ba_first_consumption)/sum(ba_created)*100,\n            sum(ba_first_consumption)/sum(ba_created)*100)  as ba_first_consumption\n  FROM\n    cloud_analytics.funnel_grouped_consumption\n  WHERE\n    has([$month], month ) = 1\n    AND has([$segment], segment ) = 1\n    AND has([$ba_curr_state], ba_curr_state_extended ) = 1\n    AND has([$channel], channel) = 1\n    AND has([$person_type], person_type) = 1\n  GROUP BY\n    t, \n    $cohort\n)\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT t, groupArray((week, ba_first_consumption)) FROM (   SELECT      toInt64(t)*1000 as t,     week,     multiIf('real' = 'real', toFloat64(sum(total_consumption)),              'real' = 'pct_to_cloud', sum(ba_first_consumption)/sum(cloud_created)*100,              'real' = 'pct_to_ba', sum(ba_first_consumption)/sum(ba_created)*100,             sum(ba_first_consumption)/sum(ba_created)*100)  as ba_first_consumption   FROM     cloud_analytics.funnel_grouped_consumption   WHERE     has(['2019-03','2019-02','2019-01'], month ) = 1     AND has(['enterprise','isv','mass','yandex'], segment ) = 1     AND has(['active','not_created','payment_not_confirmed','payment_required'], ba_curr_state_extended ) = 1     AND has(['Direct','Emailing','Organic Search','Other','Perfomance','Referrals','Sales','Social','Unknown','Yandex Portal','organic'], channel) = 1     AND has(['not_created','individual','company','switzerland_nonresident_company','other'], person_type) = 1   GROUP BY     t,      week ) GROUP BY t ORDER BY t",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Active Consumption",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\nt, groupArray(($cohort, ba_consumed_paid_last_7days))\nFROM (\n  SELECT \n    toInt64(t)*1000 as t,\n    $cohort,\n    multiIf('$type' = 'real', toFloat64(sum(active_consumption)), \n            '$type' = 'pct_to_cloud', sum(ba_consumed_paid_last_7days)/sum(cloud_created)*100, \n            '$type' = 'pct_to_ba',sum(ba_consumed_paid_last_7days)/sum(ba_created)*100,\n            sum(ba_consumed_paid_last_7days)/sum(ba_first_paid_consumption)*100)  as ba_consumed_paid_last_7days\n  FROM\n    cloud_analytics.funnel_grouped_consumption\n  WHERE\n    has([$month], month ) = 1\n    AND has([$segment], segment ) = 1\n    AND has([$ba_curr_state], ba_curr_state_extended ) = 1\n    AND has([$channel], channel) = 1\n    AND has([$person_type], person_type) = 1\n  GROUP BY\n    t, \n    $cohort\n)\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT t, groupArray((week, ba_consumed_paid_last_7days)) FROM (   SELECT      toInt64(t)*1000 as t,     week,     multiIf('real' = 'real', toFloat64(sum(active_consumption)),              'real' = 'pct_to_cloud', sum(ba_consumed_paid_last_7days)/sum(cloud_created)*100,              'real' = 'pct_to_ba',sum(ba_consumed_paid_last_7days)/sum(ba_created)*100,             sum(ba_consumed_paid_last_7days)/sum(ba_first_paid_consumption)*100)  as ba_consumed_paid_last_7days   FROM     cloud_analytics.funnel_grouped_consumption   WHERE     has(['2019-03','2019-02','2019-01'], month ) = 1     AND has(['enterprise','isv','mass','yandex'], segment ) = 1     AND has(['active','not_created','payment_not_confirmed','payment_required'], ba_curr_state_extended ) = 1     AND has(['Direct','Emailing','Organic Search','Other','Perfomance','Referrals','Sales','Social','Unknown','Yandex Portal','organic'], channel) = 1     AND has(['not_created','individual','company','switzerland_nonresident_company','other'], person_type) = 1   GROUP BY     t,      week ) GROUP BY t ORDER BY t",
     "round": "0s"
    }
   ]
  }
 ]
}