{
 "title": "SMB cloud lead report",
 "time": { "from": "now-30d", "to": "now+1d" },
 "templating": {
  "list": [
   { "name": "aggr_period", "label": "Aggr Periods", "query": "day, week, month, year" },
   {
    "name": "fraud_status",
    "label": "Fraud Status",
    "query": "SELECT distinct multiIf(ba_state IN ('active', 'payment_required') OR block_reason = 'trial_expired', 'Not Fraud','Fraud') FROM cloud_analytics_testing.crm_lead_cube_test WHERE ba_state IS NOT NULL"
   },
   {
    "name": "ba_usage_status",
    "label": "BA Usage Status",
    "query": "SELECT DISTINCT ba_usage_status FROM cloud_analytics_testing.crm_lead_cube_test"
   },
   {
    "name": "ba_person_type",
    "label": "Person Type",
    "query": "SELECT DISTINCT ba_person_type FROM cloud_analytics_testing.crm_lead_cube_test"
   },
   {
    "name": "lead_source",
    "label": "Lead Source",
    "query": "SELECT DISTINCT lead_source FROM cloud_analytics_testing.crm_lead_cube_test"
   },
   {
    "name": "call_status",
    "label": "Call Status",
    "query": "SELECT DISTINCT multiIf(call_status LIKE 'reachible%' OR call_status LIKE '%,reachible%', 'reachible', 'unreachible')  FROM cloud_analytics_testing.crm_lead_cube_test WHERE event = 'call'"
   },
   {
    "name": "sales_name",
    "label": "Sales",
    "query": "SELECT DISTINCT sales_name FROM cloud_analytics_testing.crm_lead_cube_test"
   },
   {
    "name": "funnel_values",
    "label": "Funnel View",
    "query": "absolute,step_to_step,step_to_first_step"
   },
   {
    "name": "data_updated",
    "query": "SELECT metadata_modification_time FROM system.tables  WHERE name = 'crm_lead_cube_test' AND database = 'cloud_analytics_testing'"
   }
  ]
 },
 "panels": [
  { "type": "text", "gridPos": { "h": 3, "w": 12, "x": 0, "y": 0 }, "content": "# Alfa Version" },
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "content": "## Если у Вас что-то не работает или Вам не хватает функциональности, пожалуйста, [дайте нам знать](https://forms.yandex-team.ru/surveys/21421/)."
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 3 },
   "content": "# Data Updated At $data_updated"
  },
  {
   "title": "New Leads By Source",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT \ntoInt32(date) * 1000 as date,\ngroupArray((lead_source, sum_cost))\nFROM (\n\n    SELECT multiIf('$aggr_period' = 'day', toDateTime(toDate(event_time)), \n                   '$aggr_period' = 'week', toMonday(toDateTime(toDate(event_time))),\n                   '$aggr_period' = 'month', toStartOfMonth(toDateTime(toDate(event_time))), \n                   '$aggr_period' = 'year', toStartOfYear(toDateTime(toDate(event_time))),\n                   toDateTime(toDate(event_time))) AS date, \n                   lead_source,\n         COUNT(*) as sum_cost\n    FROM cloud_analytics_testing.crm_lead_cube_test\n    WHERE \n      event = 'lead_changed_status'\n      AND lead_state IN ('New')\n      AND event_time >= toDate('2018-12-01')\n      AND has([$fraud_status], multiIf(ba_state IN ('active', 'payment_required') OR block_reason = 'trial_expired', 'Not Fraud','Fraud'))=1\n      AND has([$ba_usage_status], ba_usage_status)=1\n      AND has([$ba_person_type], ba_person_type)=1\n      AND has([$lead_source], lead_source)=1\n      AND has([$call_status], multiIf(call_status LIKE 'reachible%' OR call_status LIKE '%,reachible%', 'reachible', 'unreachible')  )=1\n      AND has([$sales_name], sales_name  )=1\n    GROUP BY date, lead_source\n    ORDER BY date, lead_source\n)\nGROUP BY date\nORDER BY date",
     "rawQuery": "SELECT  toInt32(date) * 1000 as date, groupArray((lead_source, sum_cost)) FROM (      SELECT multiIf('week' = 'day', toDateTime(toDate(event_time)),                     'week' = 'week', toMonday(toDateTime(toDate(event_time))),                    'week' = 'month', toStartOfMonth(toDateTime(toDate(event_time))),                     'week' = 'year', toStartOfYear(toDateTime(toDate(event_time))),                    toDateTime(toDate(event_time))) AS date,                     lead_source,          COUNT(*) as sum_cost     FROM cloud_analytics_testing.crm_lead_cube_test     WHERE        event = 'lead_changed_status'       AND lead_state IN ('New')       AND event_time >= toDate('2018-12-01')       AND has(['Fraud','Not Fraud'], multiIf(ba_state IN ('active', 'payment_required') OR block_reason = 'trial_expired', 'Not Fraud','Fraud'))=1       AND has(['unknown','paid','trial','disabled','service'], ba_usage_status)=1       AND has(['unknown','company','individual'], ba_person_type)=1       AND has(['unknown','request','sales','marketo','consult_request'], lead_source)=1       AND has(['reachible','unreachible'], multiIf(call_status LIKE 'reachible%' OR call_status LIKE '%,reachible%', 'reachible', 'unreachible')  )=1       AND has(['anbalu','unknown','dmtroe','gingerkote','timag','moiseeva-m','glebmarkevich','asribny','ebelobrova','annvy','andreigusev'], sales_name  )=1     GROUP BY date, lead_source     ORDER BY date, lead_source ) GROUP BY date ORDER BY date",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Days Since Last Changes",
   "type": "michaeldmoore-multistat-panel",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    multiIf( toDate(NOW()) - toDate(event_time) > 30, 31, toDate(NOW()) - toDate(event_time) ) as days,\n    COUNT(*) as leads\nFROM (\n    SELECT\n        lead_id,\n        block_reason,\n        ba_state,\n        ba_usage_status,\n        ba_person_type,\n        lead_source,\n        sales_name,\n        groupArray(event_time)[1] as event_time,\n        groupArray(lead_state)[1] as lead_state\n    FROM (\n        SELECT\n            t0.*\n        FROM(\n            SELECT\n                *\n            FROM cloud_analytics_testing.crm_lead_cube_test\n            WHERE lead_state NOT IN ('Recycled', 'Converted')\n        ) as t0\n        ANY LEFT JOIN (\n            SELECT\n                DISTINCT lead_id\n            FROM cloud_analytics_testing.crm_lead_cube_test\n            WHERE lead_state IN ('Recycled', 'Converted')\n        ) as t1\n        ON t0.lead_id = t1.lead_id\n        WHERE\n            t1.lead_id IS NULL\n        ORDER BY\n            lead_id,\n            event_time DESC\n    )\n    GROUP BY\n        lead_id,\n        block_reason,\n        ba_state,\n        ba_usage_status,\n        ba_person_type,\n        lead_source,\n        sales_name\n)\nGROUP BY\n    days\nORDER BY\n    days",
     "rawQuery": "SELECT     multiIf( toDate(NOW()) - toDate(event_time) > 30, 31, toDate(NOW()) - toDate(event_time) ) as days,     COUNT(*) as leads FROM (     SELECT         lead_id,         block_reason,         ba_state,         ba_usage_status,         ba_person_type,         lead_source,         sales_name,         groupArray(event_time)[1] as event_time,         groupArray(lead_state)[1] as lead_state     FROM (         SELECT             t0.*         FROM(             SELECT                 *             FROM cloud_analytics_testing.crm_lead_cube_test             WHERE lead_state NOT IN ('Recycled', 'Converted')         ) as t0         ANY LEFT JOIN (             SELECT                 DISTINCT lead_id             FROM cloud_analytics_testing.crm_lead_cube_test             WHERE lead_state IN ('Recycled', 'Converted')         ) as t1         ON t0.lead_id = t1.lead_id         WHERE             t1.lead_id IS NULL         ORDER BY             lead_id,             event_time DESC     )     GROUP BY         lead_id,         block_reason,         ba_state,         ba_usage_status,         ba_person_type,         lead_source,         sales_name ) GROUP BY     days ORDER BY     days",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Leads States",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT \ntoInt32(date) * 1000 as date,\ngroupArray((lead_state, sum_cost))\nFROM (\n\n    SELECT multiIf('$aggr_period' = 'day', toDateTime(toDate(event_time)), \n                   '$aggr_period' = 'week', toMonday(toDateTime(toDate(event_time))),\n                   '$aggr_period' = 'month', toStartOfMonth(toDateTime(toDate(event_time))), \n                   '$aggr_period' = 'year', toStartOfYear(toDateTime(toDate(event_time))),\n                   toDateTime(toDate(event_time))) AS date, \n                   lead_state,\n         COUNT(*) as sum_cost\n    FROM cloud_analytics_testing.crm_lead_cube_test\n    WHERE \n      event = 'lead_changed_status'\n      AND lead_state NOT IN ('call', 'New', 'Recycled')\n      AND event_time >= toDate('2018-12-01')\n      AND has([$fraud_status], multiIf(ba_state IN ('active', 'payment_required') OR block_reason = 'trial_expired', 'Not Fraud','Fraud'))=1\n      AND has([$ba_usage_status], ba_usage_status)=1\n      AND has([$ba_person_type], ba_person_type)=1\n      AND has([$lead_source], lead_source)=1\n      AND has([$call_status], multiIf(call_status LIKE 'reachible%' OR call_status LIKE '%,reachible%', 'reachible', 'unreachible')  )=1\n      AND has([$sales_name], sales_name  )=1\n    GROUP BY date, lead_state\n    ORDER BY date, lead_state\n)\nGROUP BY date\nORDER BY date",
     "rawQuery": "SELECT  toInt32(date) * 1000 as date, groupArray((lead_state, sum_cost)) FROM (      SELECT multiIf('week' = 'day', toDateTime(toDate(event_time)),                     'week' = 'week', toMonday(toDateTime(toDate(event_time))),                    'week' = 'month', toStartOfMonth(toDateTime(toDate(event_time))),                     'week' = 'year', toStartOfYear(toDateTime(toDate(event_time))),                    toDateTime(toDate(event_time))) AS date,                     lead_state,          COUNT(*) as sum_cost     FROM cloud_analytics_testing.crm_lead_cube_test     WHERE        event = 'lead_changed_status'       AND lead_state NOT IN ('call', 'New', 'Recycled')       AND event_time >= toDate('2018-12-01')       AND has(['Fraud','Not Fraud'], multiIf(ba_state IN ('active', 'payment_required') OR block_reason = 'trial_expired', 'Not Fraud','Fraud'))=1       AND has(['unknown','paid','trial','disabled','service'], ba_usage_status)=1       AND has(['unknown','company','individual'], ba_person_type)=1       AND has(['unknown','request','sales','marketo','consult_request'], lead_source)=1       AND has(['reachible','unreachible'], multiIf(call_status LIKE 'reachible%' OR call_status LIKE '%,reachible%', 'reachible', 'unreachible')  )=1       AND has(['anbalu','unknown','dmtroe','gingerkote','timag','moiseeva-m','glebmarkevich','asribny','ebelobrova','annvy','andreigusev'], sales_name  )=1     GROUP BY date, lead_state     ORDER BY date, lead_state ) GROUP BY date ORDER BY date",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Current Lead's States",
   "type": "table",
   "gridPos": { "h": 19, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    multiIf(\n      '$aggr_period' = 'day', toString(toDate(event_time)),\n      '$aggr_period' = 'week', toString(toMonday(toDate(event_time))),\n      '$aggr_period' = 'month', toString(toStartOfMonth(toDate(event_time))),\n      '$aggr_period' = 'year', toString(toStartOfYear(toDate(event_time))),\n      toString(toDate(event_time))\n    ) AS period,\n    COUNT(DISTINCT lead_id) as \"Total Leads\",\n    countIf(current_state = 'New') as \"New\",\n    countIf(current_state = 'Assigned') as \"To TeleSales\",\n    countIf(current_state = 'In Process') as \"In Process\",\n    countIf(current_state = 'Recycled') as \"Disqualified\",\n    countIf(current_state = 'Converted') as \"Ready To Pay\"\nFROM(\n    SELECT\n        t0.lead_id,\n        t0.event_time,\n        t0.block_reason,\n        t0.ba_state,\n        t0.ba_usage_status,\n        t0.ba_person_type,\n        t0.lead_source,\n        t0.sales_name,\n        t1.current_state\n    FROM (\n        SELECT\n            lead_id,\n            event_time,\n            block_reason,\n            ba_state,\n            ba_usage_status,\n            ba_person_type,\n            lead_source,\n            sales_name\n        FROM cloud_analytics_testing.crm_lead_cube_test\n        WHERE lead_state = 'New'\n    ) as t0\n    ANY LEFT JOIN(\n        SELECT\n            lead_id,\n            groupArray(lead_state)[1] as current_state\n        FROM (SELECT * FROM cloud_analytics_testing.crm_lead_cube_test WHERE lead_state IN ('New', 'Assigned', 'In Process', 'Recycled', 'Converted') ORDER BY event_time DESC)\n        GROUP BY\n            lead_id\n    ) as t1\n    ON t0.lead_id = t1.lead_id\n)\nWHERE\n    event_time >= toDate('2018-11-01')\n    AND has([$fraud_status], multiIf(ba_state IN ('active', 'payment_required') OR block_reason = 'trial_expired', 'Not Fraud','Fraud'))=1\n    AND has([$ba_usage_status], ba_usage_status)=1\n    AND has([$ba_person_type], ba_person_type)=1\n    AND has([$lead_source], lead_source)=1\n    AND has([$sales_name], sales_name  )=1\nGROUP BY\n    period\nORDER BY\n    period DESC\n\nUNION ALL\n\nSELECT\n    toString('Total') AS period,\n    COUNT(DISTINCT lead_id) as \"Total Leads\",\n    countIf(current_state = 'New') as \"New\",\n    countIf(current_state = 'Assigned') as \"To TeleSales\",\n    countIf(current_state = 'In Process') as \"In Process\",\n    countIf(current_state = 'Recycled') as \"Disqualified\",\n    countIf(current_state = 'Converted') as \"Ready To Pay\"\nFROM(\n    SELECT\n        t0.lead_id,\n        t0.event_time,\n        t0.block_reason,\n        t0.ba_state,\n        t0.ba_usage_status,\n        t0.ba_person_type,\n        t0.lead_source,\n        t0.sales_name,\n        t1.current_state\n    FROM (\n        SELECT\n            lead_id,\n            event_time,\n            block_reason,\n            ba_state,\n            ba_usage_status,\n            ba_person_type,\n            lead_source,\n            sales_name\n        FROM cloud_analytics_testing.crm_lead_cube_test\n        WHERE lead_state = 'New'\n    ) as t0\n    ANY LEFT JOIN(\n        SELECT\n            lead_id,\n            groupArray(lead_state)[1] as current_state\n        FROM (SELECT * FROM cloud_analytics_testing.crm_lead_cube_test WHERE lead_state IN ('New', 'Assigned', 'In Process', 'Recycled', 'Converted') ORDER BY event_time DESC)\n        GROUP BY\n            lead_id\n    ) as t1\n    ON t0.lead_id = t1.lead_id\n)\nWHERE\n    event_time >= toDate('2018-11-01')\n    AND has([$fraud_status], multiIf(ba_state IN ('active', 'payment_required') OR block_reason = 'trial_expired', 'Not Fraud','Fraud'))=1\n    AND has([$ba_usage_status], ba_usage_status)=1\n    AND has([$ba_person_type], ba_person_type)=1\n    AND has([$lead_source], lead_source)=1\n    AND has([$sales_name], sales_name  )=1\nGROUP BY\n    period",
     "rawQuery": "SELECT     multiIf(       'week' = 'day', toString(toDate(event_time)),       'week' = 'week', toString(toMonday(toDate(event_time))),       'week' = 'month', toString(toStartOfMonth(toDate(event_time))),       'week' = 'year', toString(toStartOfYear(toDate(event_time))),       toString(toDate(event_time))     ) AS period,     COUNT(DISTINCT lead_id) as \"Total Leads\",     countIf(current_state = 'New') as \"New\",     countIf(current_state = 'Assigned') as \"To TeleSales\",     countIf(current_state = 'In Process') as \"In Process\",     countIf(current_state = 'Recycled') as \"Disqualified\",     countIf(current_state = 'Converted') as \"Ready To Pay\" FROM(     SELECT         t0.lead_id,         t0.event_time,         t0.block_reason,         t0.ba_state,         t0.ba_usage_status,         t0.ba_person_type,         t0.lead_source,         t0.sales_name,         t1.current_state     FROM (         SELECT             lead_id,             event_time,             block_reason,             ba_state,             ba_usage_status,             ba_person_type,             lead_source,             sales_name         FROM cloud_analytics_testing.crm_lead_cube_test         WHERE lead_state = 'New'     ) as t0     ANY LEFT JOIN(         SELECT             lead_id,             groupArray(lead_state)[1] as current_state         FROM (SELECT * FROM cloud_analytics_testing.crm_lead_cube_test WHERE lead_state IN ('New', 'Assigned', 'In Process', 'Recycled', 'Converted') ORDER BY event_time DESC)         GROUP BY             lead_id     ) as t1     ON t0.lead_id = t1.lead_id ) WHERE     event_time >= toDate('2018-11-01')     AND has(['Fraud','Not Fraud'], multiIf(ba_state IN ('active', 'payment_required') OR block_reason = 'trial_expired', 'Not Fraud','Fraud'))=1     AND has(['unknown','paid','trial','disabled','service'], ba_usage_status)=1     AND has(['unknown','company','individual'], ba_person_type)=1     AND has(['unknown','request','sales','marketo','consult_request'], lead_source)=1     AND has(['anbalu','unknown','dmtroe','gingerkote','timag','moiseeva-m','glebmarkevich','asribny','ebelobrova','annvy','andreigusev'], sales_name  )=1 GROUP BY     period ORDER BY     period DESC  UNION ALL  SELECT     toString('Total') AS period,     COUNT(DISTINCT lead_id) as \"Total Leads\",     countIf(current_state = 'New') as \"New\",     countIf(current_state = 'Assigned') as \"To TeleSales\",     countIf(current_state = 'In Process') as \"In Process\",     countIf(current_state = 'Recycled') as \"Disqualified\",     countIf(current_state = 'Converted') as \"Ready To Pay\" FROM(     SELECT         t0.lead_id,         t0.event_time,         t0.block_reason,         t0.ba_state,         t0.ba_usage_status,         t0.ba_person_type,         t0.lead_source,         t0.sales_name,         t1.current_state     FROM (         SELECT             lead_id,             event_time,             block_reason,             ba_state,             ba_usage_status,             ba_person_type,             lead_source,             sales_name         FROM cloud_analytics_testing.crm_lead_cube_test         WHERE lead_state = 'New'     ) as t0     ANY LEFT JOIN(         SELECT             lead_id,             groupArray(lead_state)[1] as current_state         FROM (SELECT * FROM cloud_analytics_testing.crm_lead_cube_test WHERE lead_state IN ('New', 'Assigned', 'In Process', 'Recycled', 'Converted') ORDER BY event_time DESC)         GROUP BY             lead_id     ) as t1     ON t0.lead_id = t1.lead_id ) WHERE     event_time >= toDate('2018-11-01')     AND has(['Fraud','Not Fraud'], multiIf(ba_state IN ('active', 'payment_required') OR block_reason = 'trial_expired', 'Not Fraud','Fraud'))=1     AND has(['unknown','paid','trial','disabled','service'], ba_usage_status)=1     AND has(['unknown','company','individual'], ba_person_type)=1     AND has(['unknown','request','sales','marketo','consult_request'], lead_source)=1     AND has(['anbalu','unknown','dmtroe','gingerkote','timag','moiseeva-m','glebmarkevich','asribny','ebelobrova','annvy','andreigusev'], sales_name  )=1 GROUP BY     period",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Lead Funnel",
   "type": "table",
   "gridPos": { "h": 19, "w": 24, "x": 0, "y": 40 },
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    multiIf(\n      '$aggr_period' = 'day', toDate(time),\n      '$aggr_period' = 'week', toMonday(toDate(time)),\n      '$aggr_period' = 'month', toStartOfMonth(toDate(time)),\n      '$aggr_period' = 'year', toStartOfYear(toDate(time)),\n      toDate(time)\n    ) AS date,\n    SUM(new) as \"New\",\n    multiIf(\n      '$funnel_values' = 'absolute', SUM(new_assigned)/1.0,\n      '$funnel_values' = 'step_to_step', ROUND(SUM(new_assigned)/SUM(new)/1.0, 2),\n      ROUND(SUM(new_assigned)/SUM(new)/1.0, 2)\n    ) as \"To Tele Sales\",\n    multiIf(\n      '$funnel_values' = 'absolute', SUM(assigned_inprocess)/1.0,\n      '$funnel_values' = 'step_to_step', ROUND(SUM(assigned_inprocess)/SUM(new_assigned)/1.0, 2),\n      ROUND(SUM(assigned_inprocess)/SUM(new)/1.0, 2)\n    ) as \"In Process\",\n    \n    multiIf(\n      '$funnel_values' = 'absolute', SUM(inprocess_recycled)/1.0,\n      '$funnel_values' = 'step_to_step', ROUND(SUM(inprocess_recycled)/SUM(assigned_inprocess)/1.0, 2),\n      ROUND(SUM(inprocess_recycled)/SUM(new)/1.0, 2)\n    ) as \"Disqualified\",\n    \n    multiIf(\n      '$funnel_values' = 'absolute', SUM(inprocess_converted)/1.0,\n      '$funnel_values' = 'step_to_step', ROUND(SUM(inprocess_converted)/SUM(assigned_inprocess)/1.0, 2),\n      ROUND(SUM(inprocess_converted)/SUM(new)/1.0, 2)\n    ) as \"Ready To Pay\",\n    \n    multiIf(\n      '$funnel_values' = 'absolute', SUM(converted_paid_consumption)/1.0,\n      '$funnel_values' = 'step_to_step', ROUND(SUM(converted_paid_consumption)/SUM(inprocess_converted)/1.0, 2),\n      ROUND(SUM(converted_paid_consumption)/SUM(new)/1.0, 2)\n    ) as \"First Paid Consumption\",\n    ROUND(SUM(arraySum(multiIf(converted_paid_consumption = 1, paid_consumption_totals, [0]))), 0) as \"Total Paid Consumption,RUR\"\nFROM\n    cloud_analytics_testing.lead_funnel\nWHERE\n    time >= toDate('2018-11-01')\n    AND has([$fraud_status], multiIf(ba_state IN ('active', 'payment_required') OR block_reason = 'trial_expired', 'Not Fraud','Fraud'))=1\n    AND has([$ba_usage_status], ba_usage_status)=1\n    AND has([$ba_person_type], ba_person_type)=1\n    AND has([$lead_source], lead_source)=1\n    AND has([$sales_name], sales_name  )=1\nGROUP BY\n    date\nORDER BY\n    date DESC",
     "rawQuery": "SELECT     multiIf(       'week' = 'day', toDate(time),       'week' = 'week', toMonday(toDate(time)),       'week' = 'month', toStartOfMonth(toDate(time)),       'week' = 'year', toStartOfYear(toDate(time)),       toDate(time)     ) AS date,     SUM(new) as \"New\",     multiIf(       'absolute' = 'absolute', SUM(new_assigned)/1.0,       'absolute' = 'step_to_step', ROUND(SUM(new_assigned)/SUM(new)/1.0, 2),       ROUND(SUM(new_assigned)/SUM(new)/1.0, 2)     ) as \"To Tele Sales\",     multiIf(       'absolute' = 'absolute', SUM(assigned_inprocess)/1.0,       'absolute' = 'step_to_step', ROUND(SUM(assigned_inprocess)/SUM(new_assigned)/1.0, 2),       ROUND(SUM(assigned_inprocess)/SUM(new)/1.0, 2)     ) as \"In Process\",          multiIf(       'absolute' = 'absolute', SUM(inprocess_recycled)/1.0,       'absolute' = 'step_to_step', ROUND(SUM(inprocess_recycled)/SUM(assigned_inprocess)/1.0, 2),       ROUND(SUM(inprocess_recycled)/SUM(new)/1.0, 2)     ) as \"Disqualified\",          multiIf(       'absolute' = 'absolute', SUM(inprocess_converted)/1.0,       'absolute' = 'step_to_step', ROUND(SUM(inprocess_converted)/SUM(assigned_inprocess)/1.0, 2),       ROUND(SUM(inprocess_converted)/SUM(new)/1.0, 2)     ) as \"Ready To Pay\",          multiIf(       'absolute' = 'absolute', SUM(converted_paid_consumption)/1.0,       'absolute' = 'step_to_step', ROUND(SUM(converted_paid_consumption)/SUM(inprocess_converted)/1.0, 2),       ROUND(SUM(converted_paid_consumption)/SUM(new)/1.0, 2)     ) as \"First Paid Consumption\",     ROUND(SUM(arraySum(multiIf(converted_paid_consumption = 1, paid_consumption_totals, [0]))), 0) as \"Total Paid Consumption,RUR\" FROM     cloud_analytics_testing.lead_funnel WHERE     time >= toDate('2018-11-01')     AND has(['Fraud','Not Fraud'], multiIf(ba_state IN ('active', 'payment_required') OR block_reason = 'trial_expired', 'Not Fraud','Fraud'))=1     AND has(['unknown','paid','trial','disabled','service'], ba_usage_status)=1     AND has(['unknown','company','individual'], ba_person_type)=1     AND has(['unknown','request','sales','marketo','consult_request'], lead_source)=1     AND has(['anbalu','unknown','dmtroe','gingerkote','timag','moiseeva-m','glebmarkevich','asribny','ebelobrova','annvy','andreigusev'], sales_name  )=1 GROUP BY     date ORDER BY     date DESC",
     "round": "0s"
    }
   ]
  }
 ]
}