{
 "title": "SMB call efficiency report",
 "time": { "from": "now-90d", "to": "now-1d" },
 "templating": {
  "list": [
   { "name": "aggr_period", "label": "Aggr Periods", "query": "day, week, month, year" },
   {
    "name": "ba_usage_status",
    "label": "BA Usage Status",
    "query": "SELECT DISTINCT ba_usage_status FROM cloud_analytics_testing.crm_lead_cube_test"
   },
   {
    "name": "ba_person_type",
    "label": "Person Type",
    "query": "SELECT DISTINCT ba_person_type FROM cloud_analytics_testing.crm_lead_cube_test"
   },
   {
    "name": "lead_source",
    "label": "Lead Source",
    "query": "SELECT DISTINCT lead_source FROM cloud_analytics_testing.crm_lead_cube_test"
   },
   {
    "name": "call_status",
    "label": "Call Status",
    "query": "SELECT DISTINCT multiIf(call_status LIKE 'reachible%' OR call_status LIKE '%,reachible%', 'reachible', 'unreachible')  FROM cloud_analytics_testing.crm_lead_cube_test WHERE event = 'call'"
   },
   {
    "name": "sales_name",
    "label": "Sales",
    "query": "SELECT DISTINCT sales_name FROM cloud_analytics_testing.crm_lead_cube_test"
   },
   {
    "name": "funnel_values",
    "label": "Funnel View",
    "query": "absolute,step_to_step,step_to_first_step"
   },
   {
    "name": "data_updated",
    "query": "SELECT metadata_modification_time FROM system.tables  WHERE name = 'crm_lead_cube_test' AND database = 'cloud_analytics_testing'"
   }
  ]
 },
 "panels": [
  { "type": "text", "gridPos": { "h": 3, "w": 12, "x": 0, "y": 0 }, "content": "# Alfa Version" },
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "content": "## Если у Вас что-то не работает или Вам не хватает функциональности, пожалуйста, [дайте нам знать](https://forms.yandex-team.ru/surveys/21421/)."
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 3 },
   "content": "# Data Updated At $data_updated"
  },
  {
   "title": "Calls",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT \ntoInt32(date) * 1000 as date,\nSUM(sum_cost) as calls\nFROM (\n\n    SELECT multiIf('$aggr_period' = 'day', toDateTime(toDate(event_time)), \n                   '$aggr_period' = 'week', toMonday(toDateTime(toDate(event_time))),\n                   '$aggr_period' = 'month', toStartOfMonth(toDateTime(toDate(event_time))), \n                   '$aggr_period' = 'year', toStartOfYear(toDateTime(toDate(event_time))),\n                   toDateTime(toDate(event_time))) AS date, \n         COUNT(*) as sum_cost\n    FROM cloud_analytics_testing.crm_lead_cube_test\n    WHERE event = 'call'\n    AND sales_name IN ('dmtroe', 'anbalu', 'la-n')\n    AND has([$ba_usage_status], ba_usage_status)=1\n    AND has([$ba_person_type], ba_person_type)=1\n    AND has([$lead_source], lead_source)=1\n    AND has([$call_status], multiIf(call_status LIKE 'reachible%' OR call_status LIKE '%,reachible%', 'reachible', 'unreachible')  )=1\n    AND has([$sales_name], sales_name  )=1\n    GROUP BY date\n    ORDER BY date\n)\nGROUP BY date\nORDER BY date",
     "rawQuery": "SELECT  toInt32(date) * 1000 as date, SUM(sum_cost) as calls FROM (      SELECT multiIf('week' = 'day', toDateTime(toDate(event_time)),                     'week' = 'week', toMonday(toDateTime(toDate(event_time))),                    'week' = 'month', toStartOfMonth(toDateTime(toDate(event_time))),                     'week' = 'year', toStartOfYear(toDateTime(toDate(event_time))),                    toDateTime(toDate(event_time))) AS date,           COUNT(*) as sum_cost     FROM cloud_analytics_testing.crm_lead_cube_test     WHERE event = 'call'     AND sales_name IN ('dmtroe', 'anbalu', 'la-n')     AND has(['unknown','paid','trial','disabled','service'], ba_usage_status)=1     AND has(['individual','company','unknown'], ba_person_type)=1     AND has(['sales','request','marketo','unknown','consult_request'], lead_source)=1     AND has(['reachible','unreachible'], multiIf(call_status LIKE 'reachible%' OR call_status LIKE '%,reachible%', 'reachible', 'unreachible')  )=1     AND has(['unknown','dmtroe','anbalu','gingerkote','moiseeva-m','timag','asribny','ebelobrova','glebmarkevich','andreigusev','annvy'], sales_name  )=1     GROUP BY date     ORDER BY date ) GROUP BY date ORDER BY date",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Calls By Sales Person",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT \ntoInt32(date) * 1000 as date,\ngroupArray( (sales_name, sum_cost))\nFROM (\n\n    SELECT multiIf('$aggr_period' = 'day', toDateTime(toDate(event_time)), \n                   '$aggr_period' = 'week', toMonday(toDateTime(toDate(event_time))),\n                   '$aggr_period' = 'month', toStartOfMonth(toDateTime(toDate(event_time))), \n                   '$aggr_period' = 'year', toStartOfYear(toDateTime(toDate(event_time))),\n                   toDateTime(toDate(event_time))) AS date, \n           sales_name as sales_name,\n         COUNT(*) as sum_cost\n    FROM cloud_analytics_testing.crm_lead_cube_test\n    WHERE event = 'call'\n    AND sales_name IN ('dmtroe', 'anbalu', 'la-n')\n    AND has([$ba_usage_status], ba_usage_status)=1\n    AND has([$ba_person_type], ba_person_type)=1\n    AND has([$lead_source], lead_source)=1\n    AND has([$call_status], multiIf(call_status LIKE 'reachible%' OR call_status LIKE '%,reachible%', 'reachible', 'unreachible')  )=1\n    AND has([$sales_name], sales_name  )=1\n    GROUP BY date, sales_name\n    ORDER BY date, sales_name\n)\nGROUP BY date\nORDER BY date",
     "rawQuery": "SELECT  toInt32(date) * 1000 as date, groupArray( (sales_name, sum_cost)) FROM (      SELECT multiIf('week' = 'day', toDateTime(toDate(event_time)),                     'week' = 'week', toMonday(toDateTime(toDate(event_time))),                    'week' = 'month', toStartOfMonth(toDateTime(toDate(event_time))),                     'week' = 'year', toStartOfYear(toDateTime(toDate(event_time))),                    toDateTime(toDate(event_time))) AS date,             sales_name as sales_name,          COUNT(*) as sum_cost     FROM cloud_analytics_testing.crm_lead_cube_test     WHERE event = 'call'     AND sales_name IN ('dmtroe', 'anbalu', 'la-n')     AND has(['unknown','paid','trial','disabled','service'], ba_usage_status)=1     AND has(['individual','company','unknown'], ba_person_type)=1     AND has(['sales','request','marketo','unknown','consult_request'], lead_source)=1     AND has(['reachible','unreachible'], multiIf(call_status LIKE 'reachible%' OR call_status LIKE '%,reachible%', 'reachible', 'unreachible')  )=1     AND has(['unknown','dmtroe','anbalu','gingerkote','moiseeva-m','timag','asribny','ebelobrova','glebmarkevich','andreigusev','annvy'], sales_name  )=1     GROUP BY date, sales_name     ORDER BY date, sales_name ) GROUP BY date ORDER BY date",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Доля Недозвонов",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT \ntoInt32(date) * 1000 as date,\nSUM(reachible) / SUM(sum_cost) as \"unreachible_share\"\nFROM (\n\n    SELECT multiIf('$aggr_period' = 'day', toDateTime(toDate(event_time)), \n                   '$aggr_period' = 'week', toMonday(toDateTime(toDate(event_time))),\n                   '$aggr_period' = 'month', toStartOfMonth(toDateTime(toDate(event_time))), \n                   '$aggr_period' = 'year', toStartOfYear(toDateTime(toDate(event_time))),\n                   toDateTime(toDate(event_time))) AS date, \n         COUNT(*) as sum_cost, \n         countIf(multiIf(call_status LIKE 'unreachible%', 'unreachible', 'reachible') = 'unreachible') as reachible\n    FROM cloud_analytics_testing.crm_lead_cube_test\n    WHERE event = 'call'\n    AND sales_name IN ('dmtroe', 'anbalu', 'la-n')\n    AND has([$ba_usage_status], ba_usage_status)=1\n    AND has([$ba_person_type], ba_person_type)=1\n    AND has([$lead_source], lead_source)=1\n    AND has([$call_status], multiIf(call_status LIKE 'reachible%' OR call_status LIKE '%,reachible%', 'reachible', 'unreachible')  )=1\n    AND has([$sales_name], sales_name  )=1\n    GROUP BY date\n    ORDER BY date\n)\nGROUP BY date\nORDER BY date",
     "rawQuery": "SELECT  toInt32(date) * 1000 as date, SUM(reachible) / SUM(sum_cost) as \"unreachible_share\" FROM (      SELECT multiIf('week' = 'day', toDateTime(toDate(event_time)),                     'week' = 'week', toMonday(toDateTime(toDate(event_time))),                    'week' = 'month', toStartOfMonth(toDateTime(toDate(event_time))),                     'week' = 'year', toStartOfYear(toDateTime(toDate(event_time))),                    toDateTime(toDate(event_time))) AS date,           COUNT(*) as sum_cost,           countIf(multiIf(call_status LIKE 'unreachible%', 'unreachible', 'reachible') = 'unreachible') as reachible     FROM cloud_analytics_testing.crm_lead_cube_test     WHERE event = 'call'     AND sales_name IN ('dmtroe', 'anbalu', 'la-n')     AND has(['unknown','paid','trial','disabled','service'], ba_usage_status)=1     AND has(['individual','company','unknown'], ba_person_type)=1     AND has(['sales','request','marketo','unknown','consult_request'], lead_source)=1     AND has(['reachible','unreachible'], multiIf(call_status LIKE 'reachible%' OR call_status LIKE '%,reachible%', 'reachible', 'unreachible')  )=1     AND has(['unknown','dmtroe','anbalu','gingerkote','moiseeva-m','timag','asribny','ebelobrova','glebmarkevich','andreigusev','annvy'], sales_name  )=1     GROUP BY date     ORDER BY date ) GROUP BY date ORDER BY date",
     "round": "0s"
    }
   ]
  },
  {
   "title": "CR: Call >> Ready To Pay",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    toInt32(date) * 1000 as date,\n    groupArray((sales_name, \"CR:Call >> Ready To Pay\"))\nFROM(\n    SELECT\n        multiIf(\n            '$aggr_period' = 'day', toDateTime(toDate(event_time)), \n            '$aggr_period' = 'week', toMonday(toDateTime(toDate(event_time))),\n            '$aggr_period' = 'month', toStartOfMonth(toDateTime(toDate(event_time))), \n            '$aggr_period' = 'year', toStartOfYear(toDateTime(toDate(event_time))),\n            toDateTime(toDate(event_time))\n        ) AS date,\n        sales_name,\n        SUM(converted)/COUNT(*) as \"CR:Call >> Ready To Pay\"\n    FROM(\n        SELECT\n            lead_id,\n            lead_state,\n            sales_name,\n            lead_source,\n            ba_person_type,\n            ba_usage_status,\n            event_times as event_time,\n            call_statuses as call_status,\n            is_mins as converted\n        FROM(\n            SELECT\n                lead_id,\n                lead_state,\n                sales_name,\n                lead_source,\n                ba_person_type,\n                ba_usage_status,\n                groupArray(event_time) as event_times,\n                groupArray(call_status) as call_statuses,\n                arraySort(groupArray(time_diff))[1] as min_time_diff,\n                arrayMap(x,y -> x = min_time_diff AND y = 1, groupArray(time_diff), groupArray(converted)) as is_mins\n            FROM(\n                SELECT\n                    DISTINCT\n                    t0.lead_id,\n                    t0.sales_name,\n                    t0.lead_source,\n                    t0.ba_person_type,\n                    t0.ba_usage_status,\n                    t0.call_id,\n                    t0.lead_state,\n                    t0.call_status,\n                    t0.event_time,\n                    t1.converted_time,\n                    t1.converted,\n                    abs(t1.converted_time - t0.event_time) as time_diff\n                FROM(\n                    SELECT\n                        *\n                    FROM cloud_analytics_testing.crm_lead_cube_test\n                    WHERE lead_state IN ('call') \n                ) as t0\n                ANY LEFT JOIN (\n                    SELECT\n                        lead_id,\n                        1 as converted,\n                        event_time as converted_time\n                    FROM cloud_analytics_testing.crm_lead_cube_test\n                    WHERE lead_state IN ('Converted')\n                ) as t1\n                ON t0.lead_id = t1.lead_id\n                ORDER BY\n                    lead_id,\n                    event_time\n            )\n            GROUP BY\n                lead_id,\n                lead_state,\n                sales_name,\n                lead_source,\n                ba_person_type,\n                ba_usage_status\n        )\n        ARRAY JOIN event_times, call_statuses, is_mins\n    )\n    WHERE\n      has([$ba_usage_status], ba_usage_status)=1\n      AND has([$ba_person_type], ba_person_type)=1\n      AND has([$lead_source], lead_source)=1\n      AND has([$call_status], multiIf(call_status LIKE 'reachible%' OR call_status LIKE '%,reachible%', 'reachible', 'unreachible')  )=1\n      AND has([$sales_name], sales_name  )=1\n      AND sales_name IN ('dmtroe', 'anbalu', 'la-n')\n      AND multiIf(call_status LIKE 'reachible%' OR call_status LIKE '%,reachible%', 'reachible', 'unreachible') = 'reachible'\n    GROUP BY\n        date,\n        sales_name\n    ORDER BY\n        date,\n        sales_name\n)\nGROUP BY\n    date\nORDER BY \n    date",
     "rawQuery": "SELECT     toInt32(date) * 1000 as date,     groupArray((sales_name, \"CR:Call >> Ready To Pay\")) FROM(     SELECT         multiIf(             'week' = 'day', toDateTime(toDate(event_time)),              'week' = 'week', toMonday(toDateTime(toDate(event_time))),             'week' = 'month', toStartOfMonth(toDateTime(toDate(event_time))),              'week' = 'year', toStartOfYear(toDateTime(toDate(event_time))),             toDateTime(toDate(event_time))         ) AS date,         sales_name,         SUM(converted)/COUNT(*) as \"CR:Call >> Ready To Pay\"     FROM(         SELECT             lead_id,             lead_state,             sales_name,             lead_source,             ba_person_type,             ba_usage_status,             event_times as event_time,             call_statuses as call_status,             is_mins as converted         FROM(             SELECT                 lead_id,                 lead_state,                 sales_name,                 lead_source,                 ba_person_type,                 ba_usage_status,                 groupArray(event_time) as event_times,                 groupArray(call_status) as call_statuses,                 arraySort(groupArray(time_diff))[1] as min_time_diff,                 arrayMap(x,y -> x = min_time_diff AND y = 1, groupArray(time_diff), groupArray(converted)) as is_mins             FROM(                 SELECT                     DISTINCT                     t0.lead_id,                     t0.sales_name,                     t0.lead_source,                     t0.ba_person_type,                     t0.ba_usage_status,                     t0.call_id,                     t0.lead_state,                     t0.call_status,                     t0.event_time,                     t1.converted_time,                     t1.converted,                     abs(t1.converted_time - t0.event_time) as time_diff                 FROM(                     SELECT                         *                     FROM cloud_analytics_testing.crm_lead_cube_test                     WHERE lead_state IN ('call')                  ) as t0                 ANY LEFT JOIN (                     SELECT                         lead_id,                         1 as converted,                         event_time as converted_time                     FROM cloud_analytics_testing.crm_lead_cube_test                     WHERE lead_state IN ('Converted')                 ) as t1                 ON t0.lead_id = t1.lead_id                 ORDER BY                     lead_id,                     event_time             )             GROUP BY                 lead_id,                 lead_state,                 sales_name,                 lead_source,                 ba_person_type,                 ba_usage_status         )         ARRAY JOIN event_times, call_statuses, is_mins     )     WHERE       has(['unknown','paid','trial','disabled','service'], ba_usage_status)=1       AND has(['individual','company','unknown'], ba_person_type)=1       AND has(['sales','request','marketo','unknown','consult_request'], lead_source)=1       AND has(['reachible','unreachible'], multiIf(call_status LIKE 'reachible%' OR call_status LIKE '%,reachible%', 'reachible', 'unreachible')  )=1       AND has(['unknown','dmtroe','anbalu','gingerkote','moiseeva-m','timag','asribny','ebelobrova','glebmarkevich','andreigusev','annvy'], sales_name  )=1       AND sales_name IN ('dmtroe', 'anbalu', 'la-n')       AND multiIf(call_status LIKE 'reachible%' OR call_status LIKE '%,reachible%', 'reachible', 'unreachible') = 'reachible'     GROUP BY         date,         sales_name     ORDER BY         date,         sales_name ) GROUP BY     date ORDER BY      date",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Leads Stats",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT \ntoInt32(date) * 1000 as date,\ngroupArray((lead_state, sum_cost))\nFROM (\n\n    SELECT multiIf('$aggr_period' = 'day', toDateTime(toDate(event_time)), \n                   '$aggr_period' = 'week', toMonday(toDateTime(toDate(event_time))),\n                   '$aggr_period' = 'month', toStartOfMonth(toDateTime(toDate(event_time))), \n                   '$aggr_period' = 'year', toStartOfYear(toDateTime(toDate(event_time))),\n                   toDateTime(toDate(event_time))) AS date, \n                   lead_state,\n         COUNT(*) as sum_cost\n    FROM cloud_analytics_testing.crm_lead_cube_test\n    WHERE \n      event = 'lead_changed_status'\n      AND lead_state NOT IN ('call', 'New')\n      AND event_time >= toDate('2018-12-01')\n      AND has([$ba_usage_status], ba_usage_status)=1\n      AND has([$ba_person_type], ba_person_type)=1\n      AND has([$lead_source], lead_source)=1\n      AND has([$call_status], multiIf(call_status LIKE 'reachible%' OR call_status LIKE '%,reachible%', 'reachible', 'unreachible')  )=1\n      AND has([$sales_name], sales_name  )=1\n    GROUP BY date, lead_state\n    ORDER BY date, lead_state\n)\nGROUP BY date\nORDER BY date",
     "rawQuery": "SELECT  toInt32(date) * 1000 as date, groupArray((lead_state, sum_cost)) FROM (      SELECT multiIf('week' = 'day', toDateTime(toDate(event_time)),                     'week' = 'week', toMonday(toDateTime(toDate(event_time))),                    'week' = 'month', toStartOfMonth(toDateTime(toDate(event_time))),                     'week' = 'year', toStartOfYear(toDateTime(toDate(event_time))),                    toDateTime(toDate(event_time))) AS date,                     lead_state,          COUNT(*) as sum_cost     FROM cloud_analytics_testing.crm_lead_cube_test     WHERE        event = 'lead_changed_status'       AND lead_state NOT IN ('call', 'New')       AND event_time >= toDate('2018-12-01')       AND has(['unknown','paid','trial','disabled','service'], ba_usage_status)=1       AND has(['individual','company','unknown'], ba_person_type)=1       AND has(['sales','request','marketo','unknown','consult_request'], lead_source)=1       AND has(['reachible','unreachible'], multiIf(call_status LIKE 'reachible%' OR call_status LIKE '%,reachible%', 'reachible', 'unreachible')  )=1       AND has(['unknown','dmtroe','anbalu','gingerkote','moiseeva-m','timag','asribny','ebelobrova','glebmarkevich','andreigusev','annvy'], sales_name  )=1     GROUP BY date, lead_state     ORDER BY date, lead_state ) GROUP BY date ORDER BY date",
     "round": "0s"
    }
   ]
  },
  {
   "title": "CR: Ready To Pay >> First Paid Consumption",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    toInt32(date) * 1000 as date,\n    groupArray((sales_name, first_paid))\nFROM(\n    SELECT\n        multiIf(\n            '$aggr_period' = 'day', toDateTime(toDate(event_time)), \n            '$aggr_period' = 'week', toMonday(toDateTime(toDate(event_time))),\n            '$aggr_period' = 'month', toStartOfMonth(toDateTime(toDate(event_time))), \n            '$aggr_period' = 'year', toStartOfYear(toDateTime(toDate(event_time))),\n            toDateTime(toDate(event_time))\n        ) AS date,\n        sales_name,\n        SUM(first_paid)/COUNT(*) as first_paid\n    FROM(\n        SELECT\n            DISTINCT\n            t0.lead_id,\n            t0.sales_name,\n            t0.lead_source,\n            t0.ba_person_type,\n            t0.ba_usage_status,\n            t0.lead_state,\n            t0.call_status,\n            t0.event_time,\n            t1.converted_time,\n            multiIf(t1.converted_time >= t0.event_time, 1, 0) as first_paid\n        FROM(\n            SELECT\n                *\n            FROM cloud_analytics_testing.crm_lead_cube_test\n            WHERE lead_state IN ('Converted') \n        ) as t0\n        ANY LEFT JOIN (\n            SELECT\n                lead_id,\n                1 as converted,\n                event_time as converted_time\n            FROM cloud_analytics_testing.crm_lead_cube_test\n            WHERE lead_state IN ('first_paid_consumption')\n        ) as t1\n        ON t0.lead_id = t1.lead_id\n    )\n    WHERE\n      has([$ba_usage_status], ba_usage_status)=1\n      AND has([$ba_person_type], ba_person_type)=1\n      AND has([$lead_source], lead_source)=1\n      AND has([$call_status], multiIf(call_status LIKE 'reachible%' OR call_status LIKE '%,reachible%', 'reachible', 'unreachible')  )=1\n      AND has([$sales_name], sales_name  )=1\n      AND sales_name IN ('dmtroe', 'anbalu', 'la-n')\n    GROUP BY\n        date,\n        sales_name\n    ORDER BY\n        date,\n        sales_name\n)\nGROUP BY\n    date\nORDER BY \n    date",
     "rawQuery": "SELECT     toInt32(date) * 1000 as date,     groupArray((sales_name, first_paid)) FROM(     SELECT         multiIf(             'week' = 'day', toDateTime(toDate(event_time)),              'week' = 'week', toMonday(toDateTime(toDate(event_time))),             'week' = 'month', toStartOfMonth(toDateTime(toDate(event_time))),              'week' = 'year', toStartOfYear(toDateTime(toDate(event_time))),             toDateTime(toDate(event_time))         ) AS date,         sales_name,         SUM(first_paid)/COUNT(*) as first_paid     FROM(         SELECT             DISTINCT             t0.lead_id,             t0.sales_name,             t0.lead_source,             t0.ba_person_type,             t0.ba_usage_status,             t0.lead_state,             t0.call_status,             t0.event_time,             t1.converted_time,             multiIf(t1.converted_time >= t0.event_time, 1, 0) as first_paid         FROM(             SELECT                 *             FROM cloud_analytics_testing.crm_lead_cube_test             WHERE lead_state IN ('Converted')          ) as t0         ANY LEFT JOIN (             SELECT                 lead_id,                 1 as converted,                 event_time as converted_time             FROM cloud_analytics_testing.crm_lead_cube_test             WHERE lead_state IN ('first_paid_consumption')         ) as t1         ON t0.lead_id = t1.lead_id     )     WHERE       has(['unknown','paid','trial','disabled','service'], ba_usage_status)=1       AND has(['individual','company','unknown'], ba_person_type)=1       AND has(['sales','request','marketo','unknown','consult_request'], lead_source)=1       AND has(['reachible','unreachible'], multiIf(call_status LIKE 'reachible%' OR call_status LIKE '%,reachible%', 'reachible', 'unreachible')  )=1       AND has(['unknown','dmtroe','anbalu','gingerkote','moiseeva-m','timag','asribny','ebelobrova','glebmarkevich','andreigusev','annvy'], sales_name  )=1       AND sales_name IN ('dmtroe', 'anbalu', 'la-n')     GROUP BY         date,         sales_name     ORDER BY         date,         sales_name ) GROUP BY     date ORDER BY      date",
     "round": "0s"
    }
   ]
  },
  {
   "title": "CR: Disqualified >> First Paid Consumption",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n    toInt32(date) * 1000 as date,\n    groupArray((sales_name, first_paid))\nFROM(\n    SELECT\n        multiIf(\n            '$aggr_period' = 'day', toDateTime(toDate(event_time)), \n            '$aggr_period' = 'week', toMonday(toDateTime(toDate(event_time))),\n            '$aggr_period' = 'month', toStartOfMonth(toDateTime(toDate(event_time))), \n            '$aggr_period' = 'year', toStartOfYear(toDateTime(toDate(event_time))),\n            toDateTime(toDate(event_time))\n        ) AS date,\n        sales_name,\n        SUM(first_paid)/COUNT(*) as first_paid\n    FROM(\n        SELECT\n            DISTINCT\n            t0.lead_id,\n            t0.sales_name,\n            t0.lead_source,\n            t0.ba_person_type,\n            t0.ba_usage_status,\n            t0.lead_state,\n            t0.call_status,\n            t0.event_time,\n            t1.converted_time,\n            multiIf(t1.converted_time >= t0.event_time, 1, 0) as first_paid\n        FROM(\n            SELECT\n                *\n            FROM cloud_analytics_testing.crm_lead_cube_test\n            WHERE lead_state IN ('Recycled') \n        ) as t0\n        ANY LEFT JOIN (\n            SELECT\n                lead_id,\n                1 as converted,\n                event_time as converted_time\n            FROM cloud_analytics_testing.crm_lead_cube_test\n            WHERE lead_state IN ('first_paid_consumption')\n        ) as t1\n        ON t0.lead_id = t1.lead_id\n        WHERE\n          event_time <= converted_time OR converted_time = toDateTime('0000-00-00 00:00:00')\n    )\n    WHERE\n      has([$ba_usage_status], ba_usage_status)=1\n      AND has([$ba_person_type], ba_person_type)=1\n      AND has([$lead_source], lead_source)=1\n      AND has([$call_status], multiIf(call_status LIKE 'reachible%' OR call_status LIKE '%,reachible%', 'reachible', 'unreachible')  )=1\n      AND has([$sales_name], sales_name  )=1\n      AND sales_name IN ('dmtroe', 'anbalu', 'la-n')\n    GROUP BY\n        date,\n        sales_name\n    ORDER BY\n        date,\n        sales_name\n)\nGROUP BY\n    date\nORDER BY \n    date",
     "rawQuery": "SELECT     toInt32(date) * 1000 as date,     groupArray((sales_name, first_paid)) FROM(     SELECT         multiIf(             'week' = 'day', toDateTime(toDate(event_time)),              'week' = 'week', toMonday(toDateTime(toDate(event_time))),             'week' = 'month', toStartOfMonth(toDateTime(toDate(event_time))),              'week' = 'year', toStartOfYear(toDateTime(toDate(event_time))),             toDateTime(toDate(event_time))         ) AS date,         sales_name,         SUM(first_paid)/COUNT(*) as first_paid     FROM(         SELECT             DISTINCT             t0.lead_id,             t0.sales_name,             t0.lead_source,             t0.ba_person_type,             t0.ba_usage_status,             t0.lead_state,             t0.call_status,             t0.event_time,             t1.converted_time,             multiIf(t1.converted_time >= t0.event_time, 1, 0) as first_paid         FROM(             SELECT                 *             FROM cloud_analytics_testing.crm_lead_cube_test             WHERE lead_state IN ('Recycled')          ) as t0         ANY LEFT JOIN (             SELECT                 lead_id,                 1 as converted,                 event_time as converted_time             FROM cloud_analytics_testing.crm_lead_cube_test             WHERE lead_state IN ('first_paid_consumption')         ) as t1         ON t0.lead_id = t1.lead_id         WHERE           event_time <= converted_time OR converted_time = toDateTime('0000-00-00 00:00:00')     )     WHERE       has(['unknown','paid','trial','disabled','service'], ba_usage_status)=1       AND has(['individual','company','unknown'], ba_person_type)=1       AND has(['sales','request','marketo','unknown','consult_request'], lead_source)=1       AND has(['reachible','unreachible'], multiIf(call_status LIKE 'reachible%' OR call_status LIKE '%,reachible%', 'reachible', 'unreachible')  )=1       AND has(['unknown','dmtroe','anbalu','gingerkote','moiseeva-m','timag','asribny','ebelobrova','glebmarkevich','andreigusev','annvy'], sales_name  )=1       AND sales_name IN ('dmtroe', 'anbalu', 'la-n')     GROUP BY         date,         sales_name     ORDER BY         date,         sales_name ) GROUP BY     date ORDER BY      date",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Доля Недозвонов по ТелеСейлзам",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT \ntoInt32(date) * 1000 as date,\ngroupArray((sales_name, reachible / sum_cost))\nFROM (\n\n    SELECT multiIf('$aggr_period' = 'day', toDateTime(toDate(event_time)), \n                   '$aggr_period' = 'week', toMonday(toDateTime(toDate(event_time))),\n                   '$aggr_period' = 'month', toStartOfMonth(toDateTime(toDate(event_time))), \n                   '$aggr_period' = 'year', toStartOfYear(toDateTime(toDate(event_time))),\n                   toDateTime(toDate(event_time))) AS date, \n        sales_name,\n         COUNT(*) as sum_cost,\n         countIf(multiIf(call_status LIKE 'unreachible%', 'unreachible', 'reachible') = 'unreachible') as reachible\n    FROM cloud_analytics_testing.crm_lead_cube_test\n    WHERE event = 'call'\n    AND sales_name IN ('dmtroe', 'anbalu', 'la-n')\n    AND has([$ba_usage_status], ba_usage_status)=1\n    AND has([$ba_person_type], ba_person_type)=1\n    AND has([$lead_source], lead_source)=1\n    AND has([$call_status], multiIf(call_status LIKE 'reachible%' OR call_status LIKE '%,reachible%', 'reachible', 'unreachible')  )=1\n    AND has([$sales_name], sales_name  )=1\n    GROUP BY date,sales_name\n    ORDER BY date,sales_name\n)\nGROUP BY date\nORDER BY date",
     "rawQuery": "SELECT  toInt32(date) * 1000 as date, groupArray((sales_name, reachible / sum_cost)) FROM (      SELECT multiIf('week' = 'day', toDateTime(toDate(event_time)),                     'week' = 'week', toMonday(toDateTime(toDate(event_time))),                    'week' = 'month', toStartOfMonth(toDateTime(toDate(event_time))),                     'week' = 'year', toStartOfYear(toDateTime(toDate(event_time))),                    toDateTime(toDate(event_time))) AS date,          sales_name,          COUNT(*) as sum_cost,          countIf(multiIf(call_status LIKE 'unreachible%', 'unreachible', 'reachible') = 'unreachible') as reachible     FROM cloud_analytics_testing.crm_lead_cube_test     WHERE event = 'call'     AND sales_name IN ('dmtroe', 'anbalu', 'la-n')     AND has(['unknown','paid','trial','disabled','service'], ba_usage_status)=1     AND has(['individual','company','unknown'], ba_person_type)=1     AND has(['sales','request','marketo','unknown','consult_request'], lead_source)=1     AND has(['reachible','unreachible'], multiIf(call_status LIKE 'reachible%' OR call_status LIKE '%,reachible%', 'reachible', 'unreachible')  )=1     AND has(['unknown','dmtroe','anbalu','gingerkote','moiseeva-m','timag','asribny','ebelobrova','glebmarkevich','andreigusev','annvy'], sales_name  )=1     GROUP BY date,sales_name     ORDER BY date,sales_name ) GROUP BY date ORDER BY date",
     "round": "0s"
    }
   ]
  }
 ]
}