{
 "title": "Support Tasks",
 "time": { "from": "now-90d", "to": "now-1d" },
 "templating": {
  "list": [
   { "name": "aggr_period", "label": "Aggr Period", "query": "day, week, month, year" },
   {
    "name": "in_time_response",
    "label": "Was Response In Time?",
    "query": "SELECT DISTINCT in_time_response FROM  cloud_analytics.support_tasks"
   },
   {
    "name": "task_type",
    "query": "SELECT DISTINCT task_type FROM cloud_analytics.support_tasks"
   },
   {
    "name": "response_time_group",
    "query": "SELECT DISTINCT response_time_group FROM  cloud_analytics.support_tasks"
   },
   {
    "name": "data_updated",
    "query": "SELECT metadata_modification_time FROM system.tables  WHERE name = 'support_tasks' AND database = 'cloud_analytics'"
   }
  ]
 },
 "panels": [
  { "type": "text", "gridPos": { "h": 3, "w": 12, "x": 0, "y": 0 }, "content": "# Alfa Version" },
  {
   "type": "text",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 0 },
   "content": "## Если у Вас что-то не работает или Вам не хватает функциональности, пожалуйста, [дайте нам знать](https://forms.yandex-team.ru/surveys/21421/)."
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 3 },
   "content": "# Data Updated At $data_updated"
  },
  {
   "title": "Support Tasks",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT \ntoInt32(date) * 1000 as date,\nSUM(tasks) as tasks\nFROM (\n\n    SELECT multiIf('$aggr_period' = 'day', toDateTime(toDate(task_time)), \n                   '$aggr_period' = 'week', toMonday(toDateTime(toDate(task_time))),\n                   '$aggr_period' = 'month', toStartOfMonth(toDateTime(toDate(task_time))), \n                   '$aggr_period' = 'year', toStartOfYear(toDateTime(toDate(task_time))),\n                   toDateTime(toDate(task_time))) AS date, \n         COUNT(*) as tasks\n    FROM cloud_analytics.support_tasks\n    WHERE\n      has([$task_type], task_type)=1\n      AND has([$response_time_group], response_time_group)=1\n      AND has([$in_time_response], in_time_response)=1\n    GROUP BY date\n    ORDER BY date\n)\nGROUP BY date\nORDER BY date",
     "rawQuery": "SELECT  toInt32(date) * 1000 as date, SUM(tasks) as tasks FROM (      SELECT multiIf('week' = 'day', toDateTime(toDate(task_time)),                     'week' = 'week', toMonday(toDateTime(toDate(task_time))),                    'week' = 'month', toStartOfMonth(toDateTime(toDate(task_time))),                     'week' = 'year', toStartOfYear(toDateTime(toDate(task_time))),                    toDateTime(toDate(task_time))) AS date,           COUNT(*) as tasks     FROM cloud_analytics.support_tasks     WHERE       has(['question','incident','task','improvement','problem'], task_type)=1       AND has(['1-2 hour','less then 1 hour','3-4 hour','5-8 hour','9-24 hour','25+ hour'], response_time_group)=1       AND has(['in_time','out_of_time'], in_time_response)=1     GROUP BY date     ORDER BY date ) GROUP BY date ORDER BY date",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Support Tasks By SLA",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT \ntoInt32(date) * 1000 as date,\ngroupArray((in_time_response, tasks) )\nFROM (\n\n    SELECT multiIf('$aggr_period' = 'day', toDateTime(toDate(task_time)), \n                   '$aggr_period' = 'week', toMonday(toDateTime(toDate(task_time))),\n                   '$aggr_period' = 'month', toStartOfMonth(toDateTime(toDate(task_time))), \n                   '$aggr_period' = 'year', toStartOfYear(toDateTime(toDate(task_time))),\n                   toDateTime(toDate(task_time))) AS date, \n          in_time_response,\n         COUNT(*) as tasks\n    FROM cloud_analytics.support_tasks\n    WHERE\n      has([$task_type], task_type)=1\n      AND has([$response_time_group], response_time_group)=1\n      AND has([$in_time_response], in_time_response)=1\n    GROUP BY date,in_time_response\n    ORDER BY date,in_time_response\n)\nGROUP BY date\nORDER BY date",
     "rawQuery": "SELECT  toInt32(date) * 1000 as date, groupArray((in_time_response, tasks) ) FROM (      SELECT multiIf('week' = 'day', toDateTime(toDate(task_time)),                     'week' = 'week', toMonday(toDateTime(toDate(task_time))),                    'week' = 'month', toStartOfMonth(toDateTime(toDate(task_time))),                     'week' = 'year', toStartOfYear(toDateTime(toDate(task_time))),                    toDateTime(toDate(task_time))) AS date,            in_time_response,          COUNT(*) as tasks     FROM cloud_analytics.support_tasks     WHERE       has(['question','incident','task','improvement','problem'], task_type)=1       AND has(['1-2 hour','less then 1 hour','3-4 hour','5-8 hour','9-24 hour','25+ hour'], response_time_group)=1       AND has(['in_time','out_of_time'], in_time_response)=1     GROUP BY date,in_time_response     ORDER BY date,in_time_response ) GROUP BY date ORDER BY date",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Support Tasks By Hours To Response",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT \ntoInt32(date) * 1000 as date,\ngroupArray((response_time_group, tasks) )\nFROM (\n\n    SELECT multiIf('$aggr_period' = 'day', toDateTime(toDate(task_time)), \n                   '$aggr_period' = 'week', toMonday(toDateTime(toDate(task_time))),\n                   '$aggr_period' = 'month', toStartOfMonth(toDateTime(toDate(task_time))), \n                   '$aggr_period' = 'year', toStartOfYear(toDateTime(toDate(task_time))),\n                   toDateTime(toDate(task_time))) AS date, \n          response_time_group,\n         COUNT(*) as tasks\n    FROM cloud_analytics.support_tasks\n    WHERE\n      has([$task_type], task_type)=1\n      AND has([$response_time_group], response_time_group)=1\n      AND has([$in_time_response], in_time_response)=1\n    GROUP BY date,response_time_group\n    ORDER BY date,response_time_group\n)\nGROUP BY date\nORDER BY date",
     "rawQuery": "SELECT  toInt32(date) * 1000 as date, groupArray((response_time_group, tasks) ) FROM (      SELECT multiIf('week' = 'day', toDateTime(toDate(task_time)),                     'week' = 'week', toMonday(toDateTime(toDate(task_time))),                    'week' = 'month', toStartOfMonth(toDateTime(toDate(task_time))),                     'week' = 'year', toStartOfYear(toDateTime(toDate(task_time))),                    toDateTime(toDate(task_time))) AS date,            response_time_group,          COUNT(*) as tasks     FROM cloud_analytics.support_tasks     WHERE       has(['question','incident','task','improvement','problem'], task_type)=1       AND has(['1-2 hour','less then 1 hour','3-4 hour','5-8 hour','9-24 hour','25+ hour'], response_time_group)=1       AND has(['in_time','out_of_time'], in_time_response)=1     GROUP BY date,response_time_group     ORDER BY date,response_time_group ) GROUP BY date ORDER BY date",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Support Tasks By Type",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT \ntoInt32(date) * 1000 as date,\ngroupArray((task_type, tasks) )\nFROM (\n\n    SELECT multiIf('$aggr_period' = 'day', toDateTime(toDate(task_time)), \n                   '$aggr_period' = 'week', toMonday(toDateTime(toDate(task_time))),\n                   '$aggr_period' = 'month', toStartOfMonth(toDateTime(toDate(task_time))), \n                   '$aggr_period' = 'year', toStartOfYear(toDateTime(toDate(task_time))),\n                   toDateTime(toDate(task_time))) AS date, \n          task_type,\n         COUNT(*) as tasks\n    FROM cloud_analytics.support_tasks\n    WHERE\n      has([$task_type], task_type)=1\n      AND has([$response_time_group], response_time_group)=1\n      AND has([$in_time_response], in_time_response)=1\n    GROUP BY date,task_type\n    ORDER BY date,task_type\n)\nGROUP BY date\nORDER BY date",
     "rawQuery": "SELECT  toInt32(date) * 1000 as date, groupArray((task_type, tasks) ) FROM (      SELECT multiIf('week' = 'day', toDateTime(toDate(task_time)),                     'week' = 'week', toMonday(toDateTime(toDate(task_time))),                    'week' = 'month', toStartOfMonth(toDateTime(toDate(task_time))),                     'week' = 'year', toStartOfYear(toDateTime(toDate(task_time))),                    toDateTime(toDate(task_time))) AS date,            task_type,          COUNT(*) as tasks     FROM cloud_analytics.support_tasks     WHERE       has(['question','incident','task','improvement','problem'], task_type)=1       AND has(['1-2 hour','less then 1 hour','3-4 hour','5-8 hour','9-24 hour','25+ hour'], response_time_group)=1       AND has(['in_time','out_of_time'], in_time_response)=1     GROUP BY date,task_type     ORDER BY date,task_type ) GROUP BY date ORDER BY date",
     "round": "0s"
    }
   ]
  }
 ]
}