{
 "title": "(Beta) VAR Dashboard v2",
 "time": { "from": "now-90d", "to": "now+7d" },
 "templating": {
  "list": [
   {
    "name": "data_source",
    "query": "consumption_daily_v2_1,consumption_daily_cube"
   },
   { "name": "consumption_type", "query": "trial, paid" },
   {
    "name": "billing_account_id",
    "query": "SELECT DISTINCT billing_account_id FROM cloud_analytics.$data_source WHERE  has(['var'], segment) = 1 AND has([$sales_name], sales_name)=1 ORDER BY billing_account_id"
   },
   {
    "name": "sales_name",
    "query": "SELECT distinct sales_name FROM cloud_analytics.$data_source WHERE master_account_id != ''"
   },
   {
    "name": "service",
    "label": "Service",
    "query": "SELECT distinct service_name FROM cloud_analytics.$data_source WHERE has(['var'], segment) = 1"
   },
   { "name": "aggr_period", "query": "day,week,month,quarter" },
   {
    "name": "period1",
    "label": "period_start_date",
    "query": "SELECT toDateTime(concat('$period1_date', ' 00:00:00'))"
   },
   {
    "name": "period1_date",
    "label": "period_start_date",
    "query": "SELECT DISTINCT toDate(multiIf('$aggr_period' = 'week', toMonday(date), '$aggr_period' = 'month', toStartOfMonth(date), '$aggr_period' = 'quarter', toStartOfQuarter(date), date)) FROM cloud_analytics.$data_source WHERE has([$sales_name], sales_name) = 1"
   },
   {
    "name": "prev_period",
    "query": "SELECT multiIf('$aggr_period'='week', addWeeks(toDateTime('$period1'),-1), '$aggr_period'='month', addMonths(toDateTime('$period1'),-1), '$aggr_period'='quarter', addQuarters(toDateTime('$period1'),-1), addDays(toDateTime('$period1'),-1))"
   },
   {
    "name": "period1_end",
    "query": "SELECT multiIf('$aggr_period'='week', addWeeks(toDateTime('$period1'),1), '$aggr_period'='month', addMonths(toDateTime('$period1'),1), '$aggr_period'='quarter', addQuarters(toDateTime('$period1'),1),addDays(toDateTime('$period1'),1))"
   },
   {
    "name": "period1_end_date",
    "query": "SELECT addDays(toDate('$period1_end'), -1)"
   },
   { "name": "prev_period_date", "query": "SELECT toDate('$prev_period')" },
   {
    "name": "prev_period_end_date",
    "query": "SELECT addDays(toDate('$period1_date'),-1)"
   },
   { "name": "segment", "query": "'var'" }
  ]
 },
 "panels": [
  { "title": "Информация о дашборде", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Последнее обновление",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT metadata_modification_time FROM system.tables \nWHERE name = '$data_source'\nAND database = 'cloud_analytics'",
     "rawQuery": "SELECT metadata_modification_time FROM system.tables  WHERE name = 'consumption_daily_v2_1' AND database = 'cloud_analytics'",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Обратная связь",
   "type": "text",
   "gridPos": { "h": 2, "w": 19, "x": 4, "y": 1 },
   "content": "\n## Если у Вас что-то не работает или Вам не хватает функциональности, пожалуйста, [дайте нам знать](https://forms.yandex-team.ru/surveys/21421/).\n\n\n"
  },
  { "title": "Потребление", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "Revenue Dynamics: Breakdown by Clients",
   "type": "table",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT \n  reverse(replaceAll(toFixedString(reverse(toString(rowNumberInAllBlocks() + 1)), 5), '\\0', '0')) N,\n  master_account_id,\n  master_account_name,\n  billing_account_id BA,\n  client_name \"Компания\",\n  sum_prev_period as \"$prev_period_date to $prev_period_end_date\",\n  sum_this_period as \"$period1_date to $period1_end_date\",\n  \"$period1_date to $period1_end_date\" - \"$prev_period_date to $prev_period_end_date\" as growth,\n  \"$period1_date to $period1_end_date\"/\"$prev_period_date to $prev_period_end_date\" -1 as growth_pct\nFROM (\nSELECT  master_account_id,\n        billing_account_id,\n        client_name, \n        sumIf(sum_cost, date>='$prev_period' AND date<'$period1') as sum_prev_period ,\n        sumIf(sum_cost, date>='$period1' AND date<'$period1_end') as sum_this_period\n        \nFROM( \n  SELECT\n    master_account_id,\n    billing_account_id,\n    date,\n    client_name,\n    sum(cons_sum) as sum_cost\n  FROM cloud_analytics.$data_source\n  WHERE (has ([$billing_account_id], billing_account_id) = 1 OR $billing_account_id = 'All')\n  AND has([$consumption_type], cons_type) = 1\n  AND master_account_id not in  ('dn2muumiel12ud28m476', 'dn2q97qq6iant0n4l061', '')\n  AND has([$sales_name], sales_name) = 1\n  AND has([$service], service_name) = 1\n  GROUP BY master_account_id, client_name,  billing_account_id, date\n)\nGROUP BY master_account_id, client_name,  billing_account_id\n) as a \nANY INNER JOIN (\n  SELECT DISTINCT billing_account_id as master_account_id, client_name as master_account_name\n  FROM cloud_analytics.$data_source\n  ) as b \nUSING master_account_id\n\nUNION All\n\nSELECT  'z.Total' \"N\", \n        'z.Total' \"Master Account\",  \n        'z.Total' \"Master Account Name\",  \n        'z.Total' BA,\n        'z.Total' \"Компания\", \n        sumIf(sum_cost, date>='$prev_period' AND date<'$period1') as prev_period,\n        sumIf(sum_cost, date>='$period1' AND date<'$period1_end') as period,\n        period - prev_period as prev_week_growth,\n        period/prev_period -1 as growth_pct\nFROM( \n  SELECT\n    billing_account_id,\n    date,\n    client_name,\n    sum(cons_sum) as sum_cost\n  FROM cloud_analytics.$data_source\n  WHERE (has ([$billing_account_id], billing_account_id) = 1 OR $billing_account_id = 'All')\n  AND has([$consumption_type], cons_type) = 1\n  AND master_account_id not in  ('dn2muumiel12ud28m476', 'dn2q97qq6iant0n4l061', '')\n  AND has([$sales_name], sales_name) = 1\n  AND has([$service], service_name) = 1\n  AND master_account_id != ''\n  GROUP BY client_name,  billing_account_id, date\n)\n",
     "rawQuery": "SELECT    reverse(replaceAll(toFixedString(reverse(toString(rowNumberInAllBlocks() + 1)), 5), '\\0', '0')) N,   master_account_id,   master_account_name,   billing_account_id BA,   client_name \"Компания\",   sum_prev_period as \"2019-06-17 to 2019-06-23\",   sum_this_period as \"2019-06-24 to 2019-06-30\",   \"2019-06-24 to 2019-06-30\" - \"2019-06-17 to 2019-06-23\" as growth,   \"2019-06-24 to 2019-06-30\"/\"2019-06-17 to 2019-06-23\" -1 as growth_pct FROM ( SELECT  master_account_id,         billing_account_id,         client_name,          sumIf(sum_cost, date>='2019-06-17 00:00:00' AND date<'2019-06-24 00:00:00') as sum_prev_period ,         sumIf(sum_cost, date>='2019-06-24 00:00:00' AND date<'2019-07-01 00:00:00') as sum_this_period          FROM(    SELECT     master_account_id,     billing_account_id,     date,     client_name,     sum(cons_sum) as sum_cost   FROM cloud_analytics.consumption_daily_v2_1   WHERE (has (['All'], billing_account_id) = 1 OR 'All' = 'All')   AND has(['paid'], cons_type) = 1   AND master_account_id not in  ('dn2muumiel12ud28m476', 'dn2q97qq6iant0n4l061', '')   AND has(['admin','timag','unmanaged','victorbutenko','voytko'], sales_name) = 1   AND has(['compute','network','storage','ai','mdb'], service_name) = 1   GROUP BY master_account_id, client_name,  billing_account_id, date ) GROUP BY master_account_id, client_name,  billing_account_id ) as a  ANY INNER JOIN (   SELECT DISTINCT billing_account_id as master_account_id, client_name as master_account_name   FROM cloud_analytics.consumption_daily_v2_1   ) as b  USING master_account_id  UNION All  SELECT  'z.Total' \"N\",          'z.Total' \"Master Account\",           'z.Total' \"Master Account Name\",           'z.Total' BA,         'z.Total' \"Компания\",          sumIf(sum_cost, date>='2019-06-17 00:00:00' AND date<'2019-06-24 00:00:00') as prev_period,         sumIf(sum_cost, date>='2019-06-24 00:00:00' AND date<'2019-07-01 00:00:00') as period,         period - prev_period as prev_week_growth,         period/prev_period -1 as growth_pct FROM(    SELECT     billing_account_id,     date,     client_name,     sum(cons_sum) as sum_cost   FROM cloud_analytics.consumption_daily_v2_1   WHERE (has (['All'], billing_account_id) = 1 OR 'All' = 'All')   AND has(['paid'], cons_type) = 1   AND master_account_id not in  ('dn2muumiel12ud28m476', 'dn2q97qq6iant0n4l061', '')   AND has(['admin','timag','unmanaged','victorbutenko','voytko'], sales_name) = 1   AND has(['compute','network','storage','ai','mdb'], service_name) = 1   AND master_account_id != ''   GROUP BY client_name,  billing_account_id, date )",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Total Revenue",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "database": "cloud_analytics",
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT \ntoInt32(date) * 1000 as date,\nsum(sum_cost) as sum_cost\nFROM (\n\n    SELECT multiIf('$aggr_period' = 'day', date, \n                   '$aggr_period' = 'week', toMonday(date),\n                   '$aggr_period' = 'month', toStartOfMonth(date), \n                   '$aggr_period' = 'quarter', toStartOfQuarter(date),\n                   date) AS date,\n         sum(cons_sum) as sum_cost\n    FROM cloud_analytics.$data_source\n    WHERE (has ([$billing_account_id], billing_account_id) = 1 OR $billing_account_id = 'All')\n  AND master_account_id not in  ('dn2muumiel12ud28m476', 'dn2q97qq6iant0n4l061', '')\n  AND has([$consumption_type], cons_type) = 1\n  AND has([$sales_name], sales_name) = 1\n  AND has([$service], service_name) = 1\n  AND master_account_id != ''\n    GROUP BY date\n    ORDER BY date\n)\nGROUP BY date\nORDER BY date",
     "rawQuery": "SELECT  toInt32(date) * 1000 as date, sum(sum_cost) as sum_cost FROM (      SELECT multiIf('week' = 'day', date,                     'week' = 'week', toMonday(date),                    'week' = 'month', toStartOfMonth(date),                     'week' = 'quarter', toStartOfQuarter(date),                    date) AS date,          sum(cons_sum) as sum_cost     FROM cloud_analytics.consumption_daily_v2_1     WHERE (has (['All'], billing_account_id) = 1 OR 'All' = 'All')   AND master_account_id not in  ('dn2muumiel12ud28m476', 'dn2q97qq6iant0n4l061', '')   AND has(['paid'], cons_type) = 1   AND has(['admin','timag','unmanaged','victorbutenko','voytko'], sales_name) = 1   AND has(['compute','network','storage','ai','mdb'], service_name) = 1   AND master_account_id != ''     GROUP BY date     ORDER BY date ) GROUP BY date ORDER BY date",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Revenue Breakdown by Product",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "\nSELECT \ntoInt32(now()) * 1000 as date,\narrayMap(x->(if(x.1='zother','other',x.1),x.2),arraySort(x->x.1,groupArray((service_name_, sum_cost)))) as sum_cost\nFROM (\n    \n\n    SELECT\n          if(service_name in ('compute', 'mdb', 'ai', 'storage', 'network'), service_name, 'zother') as service_name_, \n         sum(cons_sum) as sum_cost\n    FROM cloud_analytics.$data_source\n    WHERE (has ([$billing_account_id], billing_account_id) = 1 OR $billing_account_id = 'All')\n  AND master_account_id not in  ('dn2muumiel12ud28m476', 'dn2q97qq6iant0n4l061', '')\n  AND has([$consumption_type], cons_type) = 1\n  AND has([$sales_name], sales_name) = 1\n  AND has([$service], service_name) = 1\n  AND master_account_id != ''\n  AND date >= '$period1'and date < '$period1_end'\n    GROUP BY service_name_\n    \n    \n\n      \n    \n)\n\n\n\n    \n    ",
     "rawQuery": "SELECT  toInt32(now()) * 1000 as date, arrayMap(x->(if(x.1='zother','other',x.1),x.2),arraySort(x->x.1,groupArray((service_name_, sum_cost)))) as sum_cost FROM (           SELECT           if(service_name in ('compute', 'mdb', 'ai', 'storage', 'network'), service_name, 'zother') as service_name_,           sum(cons_sum) as sum_cost     FROM cloud_analytics.consumption_daily_v2_1     WHERE (has (['All'], billing_account_id) = 1 OR 'All' = 'All')   AND master_account_id not in  ('dn2muumiel12ud28m476', 'dn2q97qq6iant0n4l061', '')   AND has(['paid'], cons_type) = 1   AND has(['admin','timag','unmanaged','victorbutenko','voytko'], sales_name) = 1   AND has(['compute','network','storage','ai','mdb'], service_name) = 1   AND master_account_id != ''   AND date >= '2019-06-24 00:00:00'and date < '2019-07-01 00:00:00'     GROUP BY service_name_                        )",
     "round": "0s"
    }
   ]
  },
  { "title": "Заявки и первое потребление", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Заявки VAR",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n  toInt64(toDateTime(created_at_week)) * 1000 as date_,\n  arraySort(x->x.1, groupArray((status, req_count)))\nFROM (\n  \n  SELECT \n    toMonday(created_at) as created_at_week,\n    multiIf(status='approved', status, status='declined', status, 'in_work') as status,\n    count(id) as req_count\n  FROM (\n    SELECT *\n    FROM cloud_analytics.var_isv_requests\n    ORDER BY status\n    )\n  WHERE id like '%CLOUDVAR%' and status != 'archived'\n  GROUP BY\n    created_at_week, \n    status\n)\nGROUP BY date_\nORDER BY date_\n",
     "rawQuery": "SELECT   toInt64(toDateTime(created_at_week)) * 1000 as date_,   arraySort(x->x.1, groupArray((status, req_count))) FROM (      SELECT      toMonday(created_at) as created_at_week,     multiIf(status='approved', status, status='declined', status, 'in_work') as status,     count(id) as req_count   FROM (     SELECT *     FROM cloud_analytics.var_isv_requests     ORDER BY status     )   WHERE id like '%CLOUDVAR%' and status != 'archived'   GROUP BY     created_at_week,      status ) GROUP BY date_ ORDER BY date_",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Заявки VAR",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\ntoUInt32(toDateTime(created_at_week)) * 1000 as t,\narraySort(x->x.1, groupArray((status, req_count)))\nFROM(\nSELECT\nstatus,\ncreated_at_week,\nreq_count\nFROM\n(\n\nSELECT\nstatus,\ngroupArray(created_at_week) as created_at_week,\narrayCumSum(groupArray(req_count)) as req_count\nFROM(\n\nSELECT\n  b.created_at_week as created_at_week,\n  b.status as status,\n  req_count\nFROM\n  (\n    SELECT\n      toMonday(created_at) as created_at_week,\n      multiIf(\n        status = 'approved',\n        status,\n        status = 'declined',\n        status,\n        'in_work'\n      ) as status,\n      count(id) as req_count\n    FROM\n      (\n        SELECT\n          *\n        FROM\n          cloud_analytics.var_isv_requests\n        ORDER BY\n          status\n      )\n    WHERE\n      id like '%CLOUDVAR%'\n      and status != 'archived'\n    GROUP BY\n      created_at_week,\n      status\n  ) as a FULL\n  JOIN (\n    SELECT\n      created_at_week,\n      status\n    FROM\n      (\n        SELECT\n          created_at_week,\n          status\n        FROM\n          (\n            SELECT\n              groupUniqArray(toMonday(created_at)) as created_at_week,\n              array('approved', 'declined', 'in_work') as status\n            FROM\n              cloud_analytics.var_isv_requests\n          ) ARRAY\n          JOIN status\n      ) ARRAY\n      JOIN created_at_week\n  ) as b ON (a.created_at_week = b.created_at_week)\n  AND (a.status = b.status)\nORDER BY\n  status,\n  created_at_week\n) \nGROUP BY status\n)\nARRAY JOIN created_at_week, req_count\n)\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT toUInt32(toDateTime(created_at_week)) * 1000 as t, arraySort(x->x.1, groupArray((status, req_count))) FROM( SELECT status, created_at_week, req_count FROM (  SELECT status, groupArray(created_at_week) as created_at_week, arrayCumSum(groupArray(req_count)) as req_count FROM(  SELECT   b.created_at_week as created_at_week,   b.status as status,   req_count FROM   (     SELECT       toMonday(created_at) as created_at_week,       multiIf(         status = 'approved',         status,         status = 'declined',         status,         'in_work'       ) as status,       count(id) as req_count     FROM       (         SELECT           *         FROM           cloud_analytics.var_isv_requests         ORDER BY           status       )     WHERE       id like '%CLOUDVAR%'       and status != 'archived'     GROUP BY       created_at_week,       status   ) as a FULL   JOIN (     SELECT       created_at_week,       status     FROM       (         SELECT           created_at_week,           status         FROM           (             SELECT               groupUniqArray(toMonday(created_at)) as created_at_week,               array('approved', 'declined', 'in_work') as status             FROM               cloud_analytics.var_isv_requests           ) ARRAY           JOIN status       ) ARRAY       JOIN created_at_week   ) as b ON (a.created_at_week = b.created_at_week)   AND (a.status = b.status) ORDER BY   status,   created_at_week )  GROUP BY status ) ARRAY JOIN created_at_week, req_count ) GROUP BY t ORDER BY t",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Первое потребление",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT t,  arrayReverseSort(groupArray((type, ba_count)))\nFROM(\nSELECT\n    toUInt32(toDateTime(week))*1000 as t,\n    type,\n    count(billing_account_id) as ba_count\nFROM (\n    SELECT\n      'dummy' as billing_account_id,\n       toMonday(toDate('2018-09-01')) as week,\n      'paid' as type\n    \n    UNION ALL\n    \n    SELECT\n        billing_account_id,\n        toMonday(min(date)) as week,\n        'paid' as type\n    FROM\n        cloud_analytics.$data_source\n    WHERE \n      segment='var' \n      AND cons_type='paid'\n      AND usage_status != 'service'\n      AND has([$sales_name], sales_name) = 1\n  AND has([$service], service_name) = 1\n    GROUP BY\n        billing_account_id\n        \n    UNION ALL\n    \n    SELECT\n        billing_account_id,\n        toMonday(min(date)) as week,\n        'trial' as type\n    FROM\n        cloud_analytics.$data_source\n    WHERE \n      segment='var' \n      AND cons_type='trial'\n      AND usage_status != 'service'\n      AND has([$sales_name], sales_name) = 1\n    GROUP BY\n        billing_account_id\n)\nGROUP BY \n    t, type\n)\nGROUP BY t\nORDER BY t",
     "rawQuery": "SELECT t,  arrayReverseSort(groupArray((type, ba_count))) FROM( SELECT     toUInt32(toDateTime(week))*1000 as t,     type,     count(billing_account_id) as ba_count FROM (     SELECT       'dummy' as billing_account_id,        toMonday(toDate('2018-09-01')) as week,       'paid' as type          UNION ALL          SELECT         billing_account_id,         toMonday(min(date)) as week,         'paid' as type     FROM         cloud_analytics.consumption_daily_v2_1     WHERE        segment='var'        AND cons_type='paid'       AND usage_status != 'service'       AND has(['admin','timag','unmanaged','victorbutenko','voytko'], sales_name) = 1   AND has(['compute','network','storage','ai','mdb'], service_name) = 1     GROUP BY         billing_account_id              UNION ALL          SELECT         billing_account_id,         toMonday(min(date)) as week,         'trial' as type     FROM         cloud_analytics.consumption_daily_v2_1     WHERE        segment='var'        AND cons_type='trial'       AND usage_status != 'service'       AND has(['admin','timag','unmanaged','victorbutenko','voytko'], sales_name) = 1     GROUP BY         billing_account_id ) GROUP BY      t, type ) GROUP BY t ORDER BY t",
     "round": "0s"
    }
   ]
  },
  {
   "title": "Первое потребление",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dateTimeType": "DATETIME",
     "formattedQuery": "SELECT $timeSeries as t, count() FROM $table WHERE $timeFilter GROUP BY t ORDER BY t",
     "query": "SELECT\n  t,\n  arrayReverseSort( groupArray((type, ba_count)))\nFROM\n  (\n    SELECT\n      type,\n      t,\n      ba_count\n    FROM\n      (\n        SELECT\n          type,\n          groupArray(toUInt32(toDateTime(week)) * 1000) as t,\n          arrayCumSum(groupArray(ba_count)) as ba_count\n        FROM\n          (\n            SELECT\n              b.week as week,\n              b.type as type,\n              ba_count\n            FROM(\n                SELECT\n                  week,\n                  type,\n                  count(billing_account_id) as ba_count\n                FROM\n                  (\n                    SELECT\n                      billing_account_id,\n                      toMonday(min(date)) as week,\n                      'trial' as type\n                    FROM\n                      cloud_analytics.$data_source\n                    WHERE\n                      segment='var' \n                      AND cons_type='trial' \n                      AND usage_status != 'service'\n                      AND has([$sales_name], sales_name) = 1\n                    GROUP BY\n                      billing_account_id\n                    UNION ALL\n                    SELECT\n                      billing_account_id,\n                      toMonday(min(date)) as week,\n                      'paid' as type\n                    FROM\n                      cloud_analytics.$data_source\n                    WHERE\n                      segment = 'var'\n                      AND cons_type = 'paid'\n                      AND usage_status != 'service'\n                      AND has([$sales_name], sales_name) = 1\n                    GROUP BY\n                      billing_account_id\n                  )\n                GROUP BY\n                  week,\n                  type\n              ) as a FULL\n              JOIN (\n                SELECT\n                  week,\n                  type\n                FROM\n                  (\n                    SELECT\n                      week,\n                      type\n                    FROM\n                      (\n                        SELECT\n                          groupUniqArray(toMonday(date)) as week,\n                          array('trial', 'paid') as type\n                        FROM\n                          cloud_analytics.$data_source\n                      ) ARRAY\n                      JOIN type\n                  ) ARRAY\n                  JOIN week\n              ) as b ON ((a.week = b.week)\n              AND (a.type = b.type))\n              ORDER BY\n                  type,\n                  week\n          )\n        GROUP BY\n          type\n      ) ARRAY\n      JOIN t,\n      ba_count\n  )\nGROUP BY\n  t\nORDER BY\n  t\n",
     "rawQuery": "SELECT   t,   arrayReverseSort( groupArray((type, ba_count))) FROM   (     SELECT       type,       t,       ba_count     FROM       (         SELECT           type,           groupArray(toUInt32(toDateTime(week)) * 1000) as t,           arrayCumSum(groupArray(ba_count)) as ba_count         FROM           (             SELECT               b.week as week,               b.type as type,               ba_count             FROM(                 SELECT                   week,                   type,                   count(billing_account_id) as ba_count                 FROM                   (                     SELECT                       billing_account_id,                       toMonday(min(date)) as week,                       'trial' as type                     FROM                       cloud_analytics.consumption_daily_v2_1                     WHERE                       segment='var'                        AND cons_type='trial'                        AND usage_status != 'service'                       AND has(['admin','timag','unmanaged','victorbutenko','voytko'], sales_name) = 1                     GROUP BY                       billing_account_id                     UNION ALL                     SELECT                       billing_account_id,                       toMonday(min(date)) as week,                       'paid' as type                     FROM                       cloud_analytics.consumption_daily_v2_1                     WHERE                       segment = 'var'                       AND cons_type = 'paid'                       AND usage_status != 'service'                       AND has(['admin','timag','unmanaged','victorbutenko','voytko'], sales_name) = 1                     GROUP BY                       billing_account_id                   )                 GROUP BY                   week,                   type               ) as a FULL               JOIN (                 SELECT                   week,                   type                 FROM                   (                     SELECT                       week,                       type                     FROM                       (                         SELECT                           groupUniqArray(toMonday(date)) as week,                           array('trial', 'paid') as type                         FROM                           cloud_analytics.consumption_daily_v2_1                       ) ARRAY                       JOIN type                   ) ARRAY                   JOIN week               ) as b ON ((a.week = b.week)               AND (a.type = b.type))               ORDER BY                   type,                   week           )         GROUP BY           type       ) ARRAY       JOIN t,       ba_count   ) GROUP BY   t ORDER BY   t",
     "round": "0s"
    }
   ]
  }
 ]
}