#!/usr/bin/env bash

init_docker.sh || exit 1

docker run -v /var/loadtest:/var/loadtest -v /etc/yc-iot/tank/:/etc/yc-iot/tank/ -v $SSH_AUTH_SOCK:/ssh-agent -e LOGIN=${USER} -e SSH_AUTH_SOCK=/ssh-agent --net host -it --entrypoint /bin/bash cr.yandex/crp7nvlkttssi7kapoho/iot/tank:{{ tank_application_version}}
