#!/bin/bash

if [[ "${USER}" != 'root' ]]; then
    echo You should run this script as root
    exit 1
fi

PIPER_CONTAINER=`docker ps --filter='name=k8s_piper_yc-billing-piper-pod-' -q`
if [[ -z "$PIPER_CONTAINER" ]]; then
    echo Piper container does not started
    exit 2
fi

case "$1" in
    inspect) docker inspect $PIPER_CONTAINER ;;
    restart) docker restart $PIPER_CONTAINER ;;
    kill) docker kill $PIPER_CONTAINER ;;
    shell) docker exec -it $PIPER_CONTAINER bash ;;
    stats) curl http://localhost:9741/$2; echo ;;
    profile) curl http://localhost:9741/debug/pprof/$2 ;;
    status) echo ok ;;
    "") echo You should specify command ;;
    *) echo Unknown command "$1" && exit 127 ;;
esac
