package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.BuildType
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a buildType with id = 'Nbs_Cleanup_Prod_TemporaryResources'
in the project with id = 'Nbs_Cleanup_Prod', and delete the patch script.
*/
create(RelativeId("Nbs_Cleanup_Prod"), BuildType({
    templates(RelativeId("Nbs_Cleanup_YcCleanup"))
    id("Nbs_Cleanup_Prod_TemporaryResources")
    name = "Temporary resources"
    description = "Remove stale temporary entities"
    paused = true

    params {
        param("env.INSTANCE_REGEX", """^"tmpinstance-[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}"${'$'}""")
        param("env.DISK_REGEX", """^"tmpdisk-[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}"${'$'}""")
        param("env.IMAGE_REGEX", """^"tmpimage-[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}"${'$'}""")
        param("env.SNAPSHOT_REGEX", """^"tmpsnapshot-[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}"${'$'}""")
    }
}))

