package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.BuildType
import jetbrains.buildServer.configs.kotlin.v2019_2.buildFeatures.XmlReport
import jetbrains.buildServer.configs.kotlin.v2019_2.buildFeatures.xmlReport
import jetbrains.buildServer.configs.kotlin.v2019_2.triggers.schedule
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a buildType with id = 'Nbs_LocalTests_Stable224_LocalLoadTestsNoAgentBuilds_LocalLoadTestsReleaseMemorySanitizer'
in the project with id = 'Nbs_LocalTests_Stable224_LocalLoadTestsNoAgentBuilds', and delete the patch script.
*/
create(RelativeId("Nbs_LocalTests_Stable224_LocalLoadTestsNoAgentBuilds"), BuildType({
    templates(RelativeId("Nbs_YcNbsCiRunYaMakeAgentless"))
    id("Nbs_LocalTests_Stable224_LocalLoadTestsNoAgentBuilds_LocalLoadTestsReleaseMemorySanitizer")
    name = "Local Load Tests (release, memory sanitizer)"

    params {
        param("sandbox.config_path", "%configs_dir%/runner/nbs/local_tests/%branch_name%/load_tests/memory_sanitizer.yaml")
    }

    triggers {
        schedule {
            id = "TRIGGER_1461"
            schedulingPolicy = daily {
                hour = 3
            }
            triggerBuild = always()
            withPendingChangesOnly = false
        }
    }

    features {
        xmlReport {
            id = "BUILD_EXT_2942"
            reportType = XmlReport.XmlReportType.JUNIT
            rules = "%output_dir%/**/junit_report.xml"
            verbose = true
        }
    }
}))

