package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.BuildType
import jetbrains.buildServer.configs.kotlin.v2019_2.buildFeatures.notifications
import jetbrains.buildServer.configs.kotlin.v2019_2.triggers.schedule
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a buildType with id = 'Nbs_FioPerformanceTests_ProdNoAgentBuilds_FioPerformanceTestsOverlayBuilds_FioPerformanceTestsOverlay2'
in the project with id = 'Nbs_FioPerformanceTests_ProdNoAgentBuilds_FioPerformanceTestsOverlayBuilds', and delete the patch script.
*/
create(RelativeId("Nbs_FioPerformanceTests_ProdNoAgentBuilds_FioPerformanceTestsOverlayBuilds"), BuildType({
    templates(RelativeId("Nbs_YcNbsCiFioPerformanceTestSuite"))
    id("Nbs_FioPerformanceTests_ProdNoAgentBuilds_FioPerformanceTestsOverlayBuilds_FioPerformanceTestsOverlay2")
    name = "Fio Performance Tests (overlay #2)"
    description = "Instance: 1; Disks: 2; Disk sizes (GiB): [320, 325]"
    paused = true

    triggers {
        schedule {
            id = "TRIGGER_1461"
            enabled = false
            schedulingPolicy = daily {
                hour = 11
            }
            branchFilter = ""
            triggerBuild = always()
            withPendingChangesOnly = false
        }
    }

    features {
        notifications {
            id = "BUILD_EXT_3120"
            notifierSettings = emailNotifier {
                email = "vlad-serikov@yandex-team.ru"
            }
            buildFailedToStart = true
            buildFailed = true
            firstBuildErrorOccurs = true
        }
    }
}))

