package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.BuildType
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a buildType with id = 'Nfs_LocalTests_Stable224_LoadTests_LoadTestsRelwithdebinfo'
in the project with id = 'Nfs_LocalTests_Stable224_LoadTests', and delete the patch script.
*/
create(RelativeId("Nfs_LocalTests_Stable224_LoadTests"), BuildType({
    templates(RelativeId("Nfs_YcNbsCiRunYaMake"))
    id("Nfs_LocalTests_Stable224_LoadTests_LoadTestsRelwithdebinfo")
    name = "Load Tests (relwithdebinfo)"
    paused = true

    params {
        param("env.TEST_TARGETS", "cloud/filestore/ci/loadtests ")
        param("env.BUILD_TYPE", "relwithdebinfo")
    }
}))

