# Generated by Django 3.2.9 on 2022-04-24 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('s_keeper', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='queue_filter',
            name='filter',
        ),
        migrations.AddField(
            model_name='queue_filter',
            name='crew_danger_limit',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='queue_filter',
            name='crew_warning_limit',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='queue_filter',
            name='oldschool',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='queue_filter',
            name='tickets_danger_limit',
            field=models.SmallIntegerField(default=25),
        ),
        migrations.AddField(
            model_name='queue_filter',
            name='tickets_warning_limit',
            field=models.SmallIntegerField(default=15),
        ),
        migrations.AddField(
            model_name='queue_filter',
            name='ts_in_progress',
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AddField(
            model_name='queue_filter',
            name='ts_open',
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AddField(
            model_name='queue_filter',
            name='ts_sla_failed',
            field=models.CharField(blank=True, max_length=1024),
        ),
    ]
