# Generated by Django 3.2.9 on 2022-04-24 18:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('s_keeper', '0004_auto_20220424_1817'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='queue_filter',
            name='id',
        ),
        migrations.AddField(
            model_name='queue_filter',
            name='q_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
