# Generated by Django 3.2.9 on 2022-04-25 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('s_keeper', '0007_auto_20220425_0615'),
    ]

    operations = [
        migrations.AddField(
            model_name='support_unit',
            name='rank',
            field=models.PositiveIntegerField(default=3),
        ),
    ]
