# Generated by Django 3.2.9 on 2022-04-25 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('s_keeper', '0008_support_unit_rank'),
    ]

    operations = [
        migrations.CreateModel(
            name='RanksDict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Шеф', max_length=64)),
            ],
        ),
        migrations.AlterField(
            model_name='support_unit',
            name='rank',
            field=models.PositiveIntegerField(default=4),
        ),
    ]
