# Generated by Django 3.2.9 on 2022-04-29 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('s_keeper', '0010_queue_filter_assignees'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='queue_filter',
            name='assignees',
        ),
        migrations.AddField(
            model_name='queue_filter',
            name='assignees',
            field=models.ManyToManyField(to='s_keeper.Support_Unit'),
        ),
    ]
