# Generated by Django 3.2.9 on 2022-05-16 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('s_keeper', '0014_queue_filter_last_supervisor'),
    ]

    operations = [
        migrations.AddField(
            model_name='support_unit',
            name='is_staff',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
