PRAGMA Library("datetime.sql");
PRAGMA Library("helpers.sql");

IMPORT `datetime` SYMBOLS $get_datetime, $get_timestamp_from_days;
IMPORT `helpers` SYMBOLS $get_md5;

$src_table = {{ param["source_table_path"]->quote() }};
$dst_table = {{ input1->table_quote() }};
$pii_dst_table = {{ param["pii_destination_path"] -> quote() }};

$toString = ($data) -> (CAST($data AS String));
$decode_utf8 = ($data) -> (nvl(cast(String::Base64StrictDecode($data) as Utf8),$data));

$get_timestamp = ($ts) -> (CAST($ts AS TimeStamp));
$from_utc_ts_to_msk_dt = ($ts) -> (DateTime::MakeDatetime(DateTime::Update(AddTimeZone($ts, "Europe/Moscow"), "GMT"  as Timezone)));

$result = (
    SELECT
        $toString(`account_type`)                                                               AS account_type,
        $toString(`acl_team_set_id`)                                                            AS acl_crm_team_set_id,
        `annual_revenue`                                                                        AS annual_revenue,
        $toString(`assigned_user_id`)                                                           AS assigned_user_id,
        $toString(`assigned_user_id_second`)                                                    AS assigned_user_id_second,
        `assigned_user_second_share`                                                            AS assigned_user_second_share,
        `assigned_user_share`                                                                   AS assigned_user_share,
        `ba_base_rate`                                                                          AS ba_base_rate,
        $toString(`ba_currency_id`)                                                             AS ba_currency_id,
        `balance_id`                                                                            AS crm_balance_id,
        $toString(`billing_address_city`)                                                       AS billing_address_city,
        $toString(`billing_address_country`)                                                    AS billing_address_country,
        $toString(`billing_address_postalcode`)                                                 AS billing_address_postalcode,
        $toString(`billing_address_state`)                                                      AS billing_address_state,
        $toString(`billing_address_street`)                                                     AS billing_address_street,
        $toString(`billing_counterparty_id`)                                                    AS billing_counterparty_id,
        $toString(`block_reason`)                                                               AS block_reason,
        $toString(`campaign_id`)                                                                AS crm_campaign_id,
        `cloud_budget`                                                                          AS cloud_budget,
        CAST(`cloudboost_account` AS bool)                                                      AS cloudboost_account,
        $toString(`consumption_type`)                                                           AS consumption_type,
        $toString($decode_utf8(`country_directory`))                                            AS country_directory,
        $toString(`country_name_phone_alternate`)                                               AS country_name_phone_alternate,
        $toString(`country_name_phone_office`)                                                  AS country_name_phone_office,
        CAST(`country_verified_phone_alternate` AS bool)                                        AS country_verified_phone_alternate,
        CAST(`country_verified_phone_office`  AS bool)                                          AS country_verified_phone_office,
        $toString(`created_by`)                                                                 AS created_by,
        $toString(`currency_id`)                                                                AS crm_currency_id,
        $toString(`customer_interest_level`)                                                    AS customer_interest_level,
        $get_timestamp(`date_entered`)                                                          AS date_entered_ts,
        $from_utc_ts_to_msk_dt($get_timestamp(`date_entered`))                                  AS date_entered_dttm_local,
        $get_timestamp(`date_modified`)                                                         AS date_modified_ts,
        $from_utc_ts_to_msk_dt($get_timestamp(`date_modified`))                                 AS date_modified_dttm_local,
        CAST(`deleted` AS bool)                                                                 AS deleted,
        $toString($decode_utf8(`description`))                                                  AS crm_account_description,
        $toString(`display_status`)                                                             AS display_status,
        $toString(`dri_workflow_template_id`)                                                   AS dri_workflow_template_id,
        $toString(`duns_num`)                                                                   AS duns_num,
        $toString(`employees`)                                                                  AS employees,
        $toString(`facebook`)                                                                   AS facebook,
        $toString(`first_name`)                                                                 AS first_name,
        `first_trial_consumption_date`                                                          AS first_trial_consumption_date,
        $toString(`full_name`)                                                                  AS full_name,
        $toString(`googleplus`)                                                                 AS googleplus,
        $toString(`id`)                                                                         AS crm_account_id,
        $toString($decode_utf8(`industry`))                                                     AS industry,
        $toString(`inn`                  )                                                      AS inn,
        $toString(`internal_ent_segment`)                                                       AS internal_ent_segment,
        $toString(`kpp`      )                                                                  AS kpp,
        $toString(`last_name`)                                                                  AS last_name,
        `linked_total_billing_accounts`                                                         AS linked_total_billing_accounts,
        `linked_total_contacts`                                                                 AS linked_total_contacts,
        `linked_total_leads`                                                                    AS linked_total_leads,
        `linked_total_notes`                                                                    AS linked_total_notes,
        `linked_total_opportunities`                                                            AS linked_total_opportunities,
        `linked_total_tasks`                                                                    AS linked_total_tasks,
        $toString(`main_ba_id`)                                                                 AS main_ba_id,
        $toString(`modified_user_id`)                                                           AS modified_user_id,
        $toString(`name`)                                                                       AS crm_account_name,
        CAST(`old_format_dimensions` AS bool)                                                   AS old_format_dimensions,
        $toString(`org_type`)                                                                   AS org_type,
        $toString(`ownership`)                                                                  AS ownership,
        `paid_consumption`                                                                      AS paid_consumption,
        $toString(`parent_id`)                                                                  AS parent_id,
        $toString(`person_type`)                                                                AS person_type,
        $toString(`phone_alternate`)                                                            AS phone_alternate,
        $toString(`phone_fax`)                                                                  AS phone_fax,
        $toString(`phone_office`)                                                               AS phone_office,
        $toString(`rating`)                                                                     AS rating,
        CAST(`second_owner`  AS bool)                                                           AS second_owner,
        $toString(`segment`)                                                                    AS segment,
        $toString(`segment_ba`)                                                                 AS segment_ba,
        $toString(`segment_id`)                                                                 AS crm_segment_id,
        CAST(`segment_manually` AS bool)                                                        AS segment_manually,
        $toString(`service_rang`)                                                               AS service_rang,
        $toString(`shipping_address_city`)                                                      AS shipping_address_city,
        $toString(`shipping_address_country`)                                                   AS shipping_address_country,
        $toString(`shipping_address_postalcode`)                                                AS shipping_address_postalcode,
        $toString(`shipping_address_state` )                                                    AS shipping_address_state,
        $toString(`shipping_address_street`)                                                    AS shipping_address_street,
        $toString(`sic_code`)                                                                   AS sic_code,
        $toString($decode_utf8(`sub_industry`))                                                 AS sub_industry,
        $toString(`team_id`)                                                                    AS crm_team_id,
        $toString(`team_set_id`)                                                                AS crm_team_set_id,
        $toString(`ticker_symbol`)                                                              AS ticker_symbol,
        $toString(`timezone`)                                                                   AS timezone,
        `trial_consumption`                                                                     AS trial_consumption,
        $toString(`twitter`)                                                                    AS twitter,
        $toString(`website`)                                                                    AS website
    FROM $src_table
);

/* Save result in ODS */
INSERT INTO $dst_table WITH TRUNCATE
SELECT 
    account_type                                                                   AS account_type,
    acl_crm_team_set_id                                                            AS acl_crm_team_set_id,
    annual_revenue                                                                 AS annual_revenue,
    assigned_user_id                                                               AS assigned_user_id,
    assigned_user_id_second                                                        AS assigned_user_id_second,
    assigned_user_second_share                                                     AS assigned_user_second_share,
    assigned_user_share                                                            AS assigned_user_share,
    ba_base_rate                                                                   AS ba_base_rate,
    ba_currency_id                                                                 AS ba_currency_id,
    crm_balance_id                                                                 AS crm_balance_id,
    billing_address_city                                                           AS billing_address_city,
    $get_md5(billing_address_country)                                              AS billing_address_country_hash,
    $get_md5(billing_address_postalcode)                                           AS billing_address_postalcode_hash,
    $get_md5(billing_address_state)                                                AS billing_address_state_hash,
    $get_md5(billing_address_street)                                               AS billing_address_street_hash,
    billing_counterparty_id                                                        AS billing_counterparty_id,
    block_reason                                                                   AS block_reason,
    crm_campaign_id                                                                AS crm_campaign_id,
    cloud_budget                                                                   AS cloud_budget,
    cloudboost_account                                                             AS cloudboost_account,
    consumption_type                                                               AS consumption_type,
    country_directory                                                              AS country_directory,
    country_name_phone_alternate                                                   AS country_name_phone_alternate,
    country_name_phone_office                                                      AS country_name_phone_office,
    country_verified_phone_alternate                                               AS country_verified_phone_alternate,
    country_verified_phone_office                                                  AS country_verified_phone_office,
    created_by                                                                     AS created_by,
    crm_currency_id                                                                AS crm_currency_id,
    customer_interest_level                                                        AS customer_interest_level,
    date_entered_ts                                                                as date_entered_ts,
    date_entered_dttm_local                                                        as date_entered_dttm_local,
    date_modified_ts                                                               as date_modified_ts,
    date_modified_dttm_local                                                       as date_modified_dttm_local,
    deleted                                                                        AS deleted,
    $get_md5(crm_account_description)                                              AS crm_account_description_hash,
    display_status                                                                 AS display_status,
    dri_workflow_template_id                                                       AS dri_workflow_template_id,
    duns_num                                                                       AS duns_num,
    employees                                                                      AS employees,
    $get_md5(facebook)                                                             AS facebook_hash,
    $get_md5(first_name)                                                           AS first_name_hash,
    first_trial_consumption_date                                                   AS first_trial_consumption_date,
    full_name                                                                      AS full_name,
    $get_md5(googleplus)                                                           AS googleplus_hash,
    crm_account_id                                                                 AS crm_account_id,
    industry                                                                       AS industry,
    inn                                                                            AS inn,
    internal_ent_segment                                                           AS internal_ent_segment,
    kpp                                                                            AS kpp,
    $get_md5(last_name)                                                            AS last_name_hash,
    linked_total_billing_accounts                                                  AS linked_total_billing_accounts,
    linked_total_contacts                                                          AS linked_total_contacts,
    linked_total_leads                                                             AS linked_total_leads,
    linked_total_notes                                                             AS linked_total_notes,
    linked_total_opportunities                                                     AS linked_total_opportunities,
    linked_total_tasks                                                             AS linked_total_tasks,
    main_ba_id                                                                     AS main_ba_id,
    modified_user_id                                                               AS modified_user_id,
    crm_account_name                                                               AS crm_account_name,
    old_format_dimensions                                                          AS old_format_dimensions,
    org_type                                                                       AS org_type,
    ownership                                                                      AS ownership,
    paid_consumption                                                               AS paid_consumption,
    parent_id                                                                      AS parent_id,
    person_type                                                                    AS person_type,
    $get_md5(phone_alternate)                                                      AS phone_alternate_hash,
    $get_md5(phone_fax)                                                            AS phone_fax_hash,
    $get_md5(phone_office)                                                         AS phone_office_hash,
    rating                                                                         AS rating,
    second_owner                                                                   AS second_owner,
    segment                                                                        AS segment,
    segment_ba                                                                     AS segment_ba,
    crm_segment_id                                                                 AS crm_segment_id,
    segment_manually                                                               AS segment_manually,
    service_rang                                                                   AS service_rang,
    shipping_address_city                                                          AS shipping_address_city,
    $get_md5(shipping_address_country)                                             AS shipping_address_country_hash,
    $get_md5(shipping_address_postalcode)                                          AS shipping_address_postalcode_hash,
    $get_md5(shipping_address_state)                                               AS shipping_address_state_hash,
    $get_md5(shipping_address_street)                                              AS shipping_address_street_hash,
    sic_code                                                                       AS sic_code,
    sub_industry                                                                   AS sub_industry,
    crm_team_id                                                                    AS crm_team_id,
    crm_team_set_id                                                                AS crm_team_set_id,
    ticker_symbol                                                                  AS ticker_symbol,
    timezone                                                                       AS timezone,
    trial_consumption                                                              AS trial_consumption,
    $get_md5(twitter)                                                              AS twitter_hash,
    website                                                                        AS website
FROM $result
ORDER BY `crm_account_id`;


/* Save result in ODS PII*/
INSERT INTO $pii_dst_table WITH TRUNCATE
SELECT 
    crm_account_id                                                                 AS crm_account_id,
    crm_account_description                                                        AS crm_account_description,
    billing_address_country                                                        AS billing_address_country,
    billing_address_postalcode                                                     AS billing_address_postalcode,
    billing_address_state                                                          AS billing_address_state,
    billing_address_street                                                         AS billing_address_street,
    facebook                                                                       AS facebook,
    first_name                                                                     AS first_name,
    googleplus                                                                     AS googleplus,
    last_name                                                                      AS last_name,
    phone_alternate                                                                AS phone_alternate,
    phone_fax                                                                      AS phone_fax,
    phone_office                                                                   AS phone_office,
    shipping_address_country                                                       AS shipping_address_country,
    shipping_address_postalcode                                                    AS shipping_address_postalcode,
    shipping_address_state                                                         AS shipping_address_state,
    shipping_address_street                                                        AS shipping_address_street,
    twitter                                                                        AS twitter
FROM $result
ORDER BY `crm_account_id`;
