#!/bin/bash

log="/var/log/cocaine-core/cocaine-tskv.log"

timetail -n 10860 -t tskv ${log} | fgrep "stage=convert" | fgrep "dst_format=preview" | grep -c "status=\"ok\"" | sed 's/^/preview_ok\ /' || echo "preview_ok"
timetail -n 10860 -t tskv ${log} | fgrep "stage=convert" | fgrep "dst_format=preview" | grep -v -c "status=\"ok\"" | sed 's/^/preview_error\ /' || echo "preview_error"
