#!/bin/bash

export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
export LANGUAGE=en_US.UTF-8

exec 2>&1
ulimit -c unlimited
sleep 3
#while [ ! -f /var/tmp/pushclient_ok ]
#do
#    sleep 15
#done
#sleep 5
export LD_PRELOAD=/usr/lib/x86_64-linux-gnu/libjemalloc.so.1
sleep 1
if [ -d /var/run/cocaine ]; then
  rm -rf /var/run/cocaine/*
else
  mkdir -p /var/run/cocaine
fi

if [ ! -f /root/.pgpass ]
then
    mv /place/db/iss3/instances/*/psql-cocaine-testing/pgpass /root/.pgpass
fi

if grep -q ___tvm_92_client_secret___ /etc/cocaine/cocaine.conf
then
    TVMSECRET=$(cat /place/db/iss3/instances/*/cocaine.tvm.key/tvm.92)
    sed -i "s/___tvm_92_client_secret___/$TVMSECRET/" /etc/cocaine/cocaine.conf
fi

if [ ! -f /etc/cocaine/.cocaine/tools.yml ]
then
    mkdir /etc/cocaine/.cocaine/ 2>/dev/null || true
    mv /place/db/iss3/instances/*/cocaine-tool.conf/tools.yml /etc/cocaine/.cocaine/tools.yml
fi

exec /usr/bin/cocaine-runtime --configuration /etc/cocaine/cocaine.conf

