CURRENT_API_VERSION = "v1"
PREVIOUS_INTERNAL_API_VERSION = "v1"
CURRENT_INTERNAL_API_VERSION = "v2"
CURRENT_API_PREFIX = "/" + CURRENT_API_VERSION
CURRENT_INTERNAL_API_PREFIX = "/" + CURRENT_INTERNAL_API_VERSION
PREVIOUS_INTERNAL_API_PREFIX = "/" + PREVIOUS_INTERNAL_API_VERSION
