

generate-migration:
	ya make -tt -F 'features.metadb_sql.Migrations produce same DDL as metadb.sql::Generate migration with code/ changes'
	cp test-results/py3test/testing_out_stuff/V*__generated.sql ../migrations/
