#!/usr/bin/env bash

synnorm=quality/global_search/synnorm

quality/global_search/tools/syngrexp/syngrexp --for-gazetteer $synnorm/test_graph $synnorm/test_synsets test.gzt
dict/gazetteer/compiler/gztcompiler --force -I quality/global_search/synnorm test.gzt
base64 <test.gzt.bin >test.base64
