#!/bin/bash
exec 2>&1
if [ ! -f /var/tmp/nginx_conf_ok ]
then
    sed -i 's/www-data/root/g' /etc/nginx/nginx-default.conf
    sed -i 's/\/var\/log\/nginx\/[a-z]\{5,6\}\.log/\/proc\/self\/fd\/1/' /etc/nginx/nginx-default.conf
    touch /var/tmp/nginx_conf_ok
fi
mkdir /var/lib/nginx
exec /usr/sbin/nginx -c /etc/nginx/nginx-default.conf -g "daemon off;"

