#! /bin/bash

set -e

[ -d debian/venv ] || virtualenv3 --always-copy debian/venv
. debian/venv/bin/activate
debian/venv/bin/pip3 install setuptools
python3 setup.py install --prefix=debian/venv
deactivate
virtualenv3 --relocatable debian/venv
rm -fv debian/venv/bin/python*
rm -fv debian/venv/local/bin/python*
