"""
ClickHouse operations description
"""

from ...core.types import ResponseType
from ...utils.operations import EMPTY_RESPONSE as _EMPTY
from ...utils.operations import (
    OperationHandle,
    annotation_maker,
    describe_operations,
    modify_database_event_details,
    modify_database_metadata,
    modify_format_schema_event_details,
    modify_reschedule_maintenance_metadata,
    modify_reschedule_maintenance_event_details,
    modify_format_schema_metadata,
    modify_hosts_event_details,
    modify_hosts_metadata,
    modify_ml_model_event_details,
    modify_ml_model_metadata,
    modify_shard_event_details,
    modify_shard_group_event_details,
    modify_shard_group_metadata,
    modify_shard_metadata,
    modify_user_event_details,
    modify_user_metadata,
    move_event_details,
    move_metadata,
    restore_event_details,
    restore_metadata,
)
from .constants import MY_CLUSTER_TYPE
from .traits import ClickhouseOperations

__a = annotation_maker('yandex.cloud.mdb.clickhouse.v1')
__et = annotation_maker('yandex.cloud.events.mdb.clickhouse')
_CLUSTER = (ResponseType.cluster, __a('Cluster'))
_SHARD = (ResponseType.shard, __a('Shard'))
_BACKUP = (ResponseType.backup, __a('Backup'))
_DATABASE = (ResponseType.database, __a('Database'))
_USER = (ResponseType.user, __a('User'))
_ML_MODEL = (ResponseType.ml_model, __a('MlModel'))
_FORMAT_SCHEMA = (ResponseType.format_schema, __a('FormatSchema'))
_SHARD_GROUP = (ResponseType.shard_group, __a('ShardGroup'))

describe_operations(
    cluster_type=MY_CLUSTER_TYPE,
    operation_types=ClickhouseOperations,
    handles={
        ClickhouseOperations.create: OperationHandle(
            description='Create ClickHouse cluster',
            response=_CLUSTER,
            metadata_annotation=__a('CreateClusterMetadata'),
            event_type=__et('CreateCluster'),
        ),
        ClickhouseOperations.modify: OperationHandle(
            'Modify ClickHouse cluster',
            response=_CLUSTER,
            metadata_annotation=__a('UpdateClusterMetadata'),
            event_type=__et('UpdateCluster'),
        ),
        ClickhouseOperations.metadata: OperationHandle(
            'Update ClickHouse cluster metadata',
            response=_CLUSTER,
            metadata_annotation=__a('UpdateClusterMetadata'),
            event_type=__et('UpdateCluster'),
        ),
        ClickhouseOperations.start: OperationHandle(
            'Start ClickHouse cluster',
            response=_CLUSTER,
            metadata_annotation=__a('StartClusterMetadata'),
            event_type=__et('StartCluster'),
        ),
        ClickhouseOperations.stop: OperationHandle(
            'Stop ClickHouse cluster',
            response=_CLUSTER,
            metadata_annotation=__a('StopClusterMetadata'),
            event_type=__et('StopCluster'),
        ),
        ClickhouseOperations.move: OperationHandle(
            'Move ClickHouse cluster',
            response=_CLUSTER,
            metadata=move_metadata,
            event_details=move_event_details,
            metadata_annotation=__a('MoveClusterMetadata'),
            event_type=__et('MoveCluster'),
        ),
        ClickhouseOperations.delete: OperationHandle(
            'Delete ClickHouse cluster',
            response=_EMPTY,
            metadata_annotation=__a('DeleteClusterMetadata'),
            event_type=__et('DeleteCluster'),
        ),
        ClickhouseOperations.add_zookeeper: OperationHandle(
            'Add ZooKeeper to ClickHouse cluster',
            response=_CLUSTER,
            metadata_annotation=__a('AddClusterZookeeperMetadata'),
            event_type=__et('AddClusterZookeeper'),
        ),
        ClickhouseOperations.add_dictionary: OperationHandle(
            'Add external dictionary in ClickHouse cluster',
            response=_CLUSTER,
            metadata_annotation=__a('CreateClusterExternalDictionaryMetadata'),
            event_type=__et('CreateClusterExternalDictionary'),
        ),
        ClickhouseOperations.update_dictionary: OperationHandle(
            'Update external dictionary in ClickHouse cluster',
            response=_CLUSTER,
            metadata_annotation=__a('UpdateClusterExternalDictionaryMetadata'),
            event_type=__et('UpdateClusterExternalDictionary'),
        ),
        ClickhouseOperations.delete_dictionary: OperationHandle(
            'Delete external dictionary in ClickHouse cluster',
            response=_CLUSTER,
            metadata_annotation=__a('DeleteClusterExternalDictionaryMetadata'),
            event_type=__et('DeleteClusterExternalDictionary'),
        ),
        ClickhouseOperations.restore: OperationHandle(
            'Create new ClickHouse cluster from the backup',
            response=_CLUSTER,
            metadata_annotation=__a('RestoreClusterMetadata'),
            event_type=__et('RestoreCluster'),
            metadata=restore_metadata,
            event_details=restore_event_details,
        ),
        ClickhouseOperations.backup: OperationHandle(
            'Create a backup for ClickHouse cluster',
            response=_BACKUP,
            metadata_annotation=__a('BackupClusterMetadata'),
            event_type=__et('BackupCluster'),
        ),
        ClickhouseOperations.host_create: OperationHandle(
            'Add hosts to ClickHouse cluster',
            response=_EMPTY,
            metadata_annotation=__a('AddClusterHostsMetadata'),
            event_type=__et('AddClusterHosts'),
            metadata=modify_hosts_metadata,
            event_details=modify_hosts_event_details,
        ),
        ClickhouseOperations.host_delete: OperationHandle(
            'Delete hosts from ClickHouse cluster',
            response=_EMPTY,
            metadata_annotation=__a('DeleteClusterHostsMetadata'),
            event_type=__et('DeleteClusterHosts'),
            metadata=modify_hosts_metadata,
            event_details=modify_hosts_event_details,
        ),
        ClickhouseOperations.shard_create: OperationHandle(
            'Add shard to ClickHouse cluster',
            response=_SHARD,
            metadata_annotation=__a('AddClusterShardMetadata'),
            event_type=__et('AddClusterShard'),
            metadata=modify_shard_metadata,
            event_details=modify_shard_event_details,
        ),
        ClickhouseOperations.shard_modify: OperationHandle(
            'Modify ClickHouse shard',
            response=_SHARD,
            metadata_annotation=__a('UpdateClusterShardMetadata'),
            event_type=__et('UpdateClusterShard'),
            metadata=modify_shard_metadata,
            event_details=modify_shard_event_details,
        ),
        ClickhouseOperations.shard_delete: OperationHandle(
            'Delete shard from ClickHouse cluster',
            response=_EMPTY,
            metadata_annotation=__a('DeleteClusterShardMetadata'),
            event_type=__et('DeleteClusterShard'),
            metadata=modify_shard_metadata,
            event_details=modify_shard_event_details,
        ),
        ClickhouseOperations.database_add: OperationHandle(
            'Add database to ClickHouse cluster',
            response=_DATABASE,
            metadata=modify_database_metadata,
            event_details=modify_database_event_details,
            metadata_annotation=__a('CreateDatabaseMetadata'),
            event_type=__et('CreateDatabase'),
        ),
        ClickhouseOperations.database_delete: OperationHandle(
            'Delete database from ClickHouse cluster',
            response=_EMPTY,
            metadata=modify_database_metadata,
            event_details=modify_database_event_details,
            metadata_annotation=__a('DeleteDatabaseMetadata'),
            event_type=__et('DeleteDatabase'),
        ),
        ClickhouseOperations.user_create: OperationHandle(
            'Create user in ClickHouse cluster',
            response=_USER,
            metadata=modify_user_metadata,
            event_details=modify_user_event_details,
            metadata_annotation=__a('CreateUserMetadata'),
            event_type=__et('CreateUser'),
        ),
        ClickhouseOperations.user_modify: OperationHandle(
            'Modify user in ClickHouse cluster',
            response=_USER,
            metadata=modify_user_metadata,
            event_details=modify_user_event_details,
            metadata_annotation=__a('UpdateUserMetadata'),
            event_type=__et('UpdateUser'),
        ),
        ClickhouseOperations.user_delete: OperationHandle(
            'Delete user in ClickHouse cluster',
            response=_EMPTY,
            metadata=modify_user_metadata,
            event_details=modify_user_event_details,
            metadata_annotation=__a('DeleteUserMetadata'),
            event_type=__et('DeleteUser'),
        ),
        ClickhouseOperations.grant_permission: OperationHandle(
            'Grant permission to user in ClickHouse cluster',
            response=_USER,
            metadata=modify_user_metadata,
            event_details=modify_user_event_details,
            metadata_annotation=__a('GrantUserPermissionMetadata'),
            event_type=__et('GrantUserPermission'),
        ),
        ClickhouseOperations.revoke_permission: OperationHandle(
            'Revoke permission from user in ClickHouse cluster',
            response=_USER,
            metadata=modify_user_metadata,
            event_details=modify_user_event_details,
            metadata_annotation=__a('RevokeUserPermissionMetadata'),
            event_type=__et('RevokeUserPermission'),
        ),
        ClickhouseOperations.model_create: OperationHandle(
            'Add ML model in ClickHouse cluster',
            response=_ML_MODEL,
            metadata=modify_ml_model_metadata,
            event_details=modify_ml_model_event_details,
            metadata_annotation=__a('CreateMlModelMetadata'),
            event_type=__et('CreateMlModel'),
        ),
        ClickhouseOperations.model_modify: OperationHandle(
            'Modify ML model in ClickHouse cluster',
            response=_ML_MODEL,
            metadata=modify_ml_model_metadata,
            event_details=modify_ml_model_event_details,
            metadata_annotation=__a('UpdateMlModelMetadata'),
            event_type=__et('UpdateMlModel'),
        ),
        ClickhouseOperations.model_delete: OperationHandle(
            'Delete ML model in ClickHouse cluster',
            response=_EMPTY,
            metadata=modify_ml_model_metadata,
            event_details=modify_ml_model_event_details,
            metadata_annotation=__a('DeleteMlModelMetadata'),
            event_type=__et('DeleteMlModel'),
        ),
        ClickhouseOperations.format_schema_create: OperationHandle(
            'Add format schema in ClickHouse cluster',
            response=_FORMAT_SCHEMA,
            metadata=modify_format_schema_metadata,
            event_details=modify_format_schema_event_details,
            metadata_annotation=__a('CreateFormatSchemaMetadata'),
            event_type=__et('CreateFormatSchema'),
        ),
        ClickhouseOperations.format_schema_modify: OperationHandle(
            'Modify format schema in ClickHouse cluster',
            response=_FORMAT_SCHEMA,
            metadata=modify_format_schema_metadata,
            event_details=modify_format_schema_event_details,
            metadata_annotation=__a('UpdateFormatSchemaMetadata'),
            event_type=__et('UpdateFormatSchema'),
        ),
        ClickhouseOperations.format_schema_delete: OperationHandle(
            'Delete format schema in ClickHouse cluster',
            response=_EMPTY,
            metadata=modify_format_schema_metadata,
            event_details=modify_format_schema_event_details,
            metadata_annotation=__a('DeleteFormatSchemaMetadata'),
            event_type=__et('DeleteFormatSchema'),
        ),
        ClickhouseOperations.maintenance_reschedule: OperationHandle(
            'Reschedule maintenance in ClickHouse cluster',
            response=_CLUSTER,
            metadata=modify_reschedule_maintenance_metadata,
            metadata_annotation=__a('RescheduleMaintenanceMetadata'),
            event_type=__et('RescheduleMaintenance'),
            event_details=modify_reschedule_maintenance_event_details,
        ),
        ClickhouseOperations.shard_group_create: OperationHandle(
            'Add shard group in ClickHouse cluster',
            response=_SHARD_GROUP,
            metadata=modify_shard_group_metadata,
            event_details=modify_shard_group_event_details,
            metadata_annotation=__a('CreateClusterShardGroupMetadata'),
            event_type=__et('CreateShardGroup'),
        ),
        ClickhouseOperations.shard_group_modify: OperationHandle(
            'Update shard group in ClickHouse cluster',
            response=_SHARD_GROUP,
            metadata=modify_shard_group_metadata,
            event_details=modify_shard_group_event_details,
            metadata_annotation=__a('UpdateClusterShardGroupMetadata'),
            event_type=__et('UpdateShardGroup'),
        ),
        ClickhouseOperations.shard_group_delete: OperationHandle(
            'Delete shard group in ClickHouse cluster',
            response=_EMPTY,
            metadata=modify_shard_group_metadata,
            event_details=modify_shard_group_event_details,
            metadata_annotation=__a('DeleteClusterShardGroupMetadata'),
            event_type=__et('DeleteShardGroup'),
        ),
        ClickhouseOperations.host_modify: OperationHandle(
            'Update hosts in ClickHouse cluster',
            response=_CLUSTER,
            metadata=modify_hosts_metadata,
            event_details=modify_hosts_event_details,
            metadata_annotation=__a('UpdateClusterHostsMetadata'),
            event_type=__et('UpdateClusterHosts'),
        ),
    },
)
