import "type_test2/type_test2.idl";

enum Kind1 {
    F,
    G
}

struct Address1 {
    struct Component1 {
        enum Kind1_1 {
            C,
            D
        }

        options struct Address1 {
            int field;
        }

        int field;
    }

    int field;
}
