#!/usr/bin/env bash

# should not call "airflow version" here: metadata db may be not initialized
# trying to read version from file because "pip3 show/list" command takes more than 1 sec sometimes
AIRFLOW_VERSION="2"
if [ -f /etc/airflow/version.txt ]
then
    AIRFLOW_VERSION=`cat /etc/airflow/version.txt`
else
    AIRFLOW_VERSION=$(pip3 show apache-airflow | grep -i version | cut -d' ' -f2)
fi

echo ""
echo "Welcome to Yandex.Cloud Apache Airflow version $AIRFLOW_VERSION image."
echo ""
echo "Main configuration file is: /etc/airflow/airflow.cfg"
echo "LocalExecutor is being used by default"
echo "Logs are stored in: /var/log/airflow/"
echo "DAGs should be placed to: /home/airflow/dags/"
echo "Airflow scheduler and webserver are run as systemd units: airflow-scheduler.service, airflow-webserver.service"
echo "Airflow metadata db is run as local PostgreSQL daemon 127.0.0.1:5432 (user=airflow,password=airflow,dbname=airflow)"
echo "Airflow webserver is listening on: http://0.0.0.0:80/"
INSTANCE_ID=`curl --silent -H "Metadata-Flavor: Google" "http://169.254.169.254/computeMetadata/v1/instance/id"`
echo "Web authentication is enabled. Default username=test_admin,password=$INSTANCE_ID"
echo ""
echo "Full documentation: https://cloud.yandex.ru/marketplace/products/f2e9ae0bm5h1ltispt7c"
echo ""
