#!/bin/sh

case $1 in
    configure)

	[ -f /etc/logrotate.d/syslog-full ] && rm -f /etc/logrotate.d/syslog-full

    ;;
	abort-upgrade|abort-remove|abort-deconfigure)
    ;;

   	*)
       	echo "postinst called with unknown argument \`$1'" >&2
    ;;

esac
exit 0
