#!/bin/bash

if [ $1 = "install" ] || [ $1 = "upgrade" -a $2 = "0.6" ]; then
            dpkg-divert --add --rename --package yandex-media-common-lxd-setip  \
                        --divert /etc/yandex-hbf-agent/yandex-hbf-agent.conf.lxd-orig /etc/yandex-hbf-agent/yandex-hbf-agent.conf
fi
