OWNER(g:cpp-contrib)

RECURSE(
    address_extractor
    address_filter
    alice
    attributes
    banner_query_normalize
    begemot_model_factors_info
    begemot_query_factors_info
    begemot_query_factors_info/proto
    begemot_query_factors_info/ut
    begemot_query_rt_factors_info
    begemot_query_rt_l2_factors_info
    bert
    bert/tests
    blender
    blogs
    bundle
    bundle/ut
    catboost
    catboost/tests
    calc_module
    catfilter
    catfilter/ut
    click_sim
    click_sim/ut
    common_proxy
    common_server
    cluster
    cluster_machine
    country_data
    country_data/enum
    country_data/enum/protos
    country_data/enum/ut
    daemon
    dater
    dater/ut
    decapitalizer
    decapitalizer/ut
    doc_heap
    doc_remap
    doc_remap/ut
    doc_url_index
    docindexer
    docindexer/ut
    doom
    drawrichtree
    dssm_applier
    dssm_applier/embeddings_transfer/ut
    dssm_applier/nn_applier
    dssm_applier/nn_applier/test
    dssm_applier/nn_applier/lib/optimized_multiply_add/tests
    dssm_applier/nn_applier/lib/optimized_multiply_add/bench
    dssm_applier/nn_applier/lib
    dssm_applier/nn_applier/lib/ut
    dssm_applier/decompression/ut
    dssm_applier/utils/ut
    dssm_applier/optimized_model/bench
    dssm_applier/optimized_model/run_bench
    dssm_applier/optimized_model/test
    dups
    dups/banned_info/ut
    dups/tools
    embeddings_info/lib
    embeddings_info/lib/ut
    embeddings_info/proto
    embeddings_info/ut
    erfcreator
    erfcreator/ut
    ethos
    extended_mx_calcer
    extended_mx_calcer/calcers/ut
    extended_mx_calcer/tools
    externalrelev
    factor_slices
    factor_slices/ut
    factor_storage
    factor_storage/ut
    factor_storage/ut
    factors_codegen
    factors_info
    factors_info/all_slices_infos
    factors_selector
    factors_util
    factqueries
    facts
    fast_user_factors
    feature_pool
    feature_pool/ut
    features_remap
    features_remap/ut
    fill_factors_codegen
    fio
    fio_extractor
    fio_extractor/remorph
    formula_storage
    formula_storage/ut
    gazetteer
    gazetteer/common/ut
    gazetteer/config/ut
    gazetteer/proto
    gazetteer/protoparser
    gazetteer/richtree
    gazetteer/richtree/ut
    gazetteer/ut
    generated_factors_info
    geo
    geo/canonical_data/files/geodata_tree_ling
    geo/tests
    geo/ut
    geodb
    geodb/default
    geodb/default/ut
    geodb/protos
    geodb/translocal
    geodb/translocal/protos
    geodb/translocal/ut
    geodb/ut
    geograph
    geourl
    groupattrs
    groupattrs/ut
    gsk_model
    herf_hash/ut
    hosts
    httpsearchclient
    httpsearchclient/ut
    idx_ops
    idx_ops/ut
    idx_proto
    idx_proto/cpp
    idx_proto/cpp/ut
    images_nn_over_dssm_doc_features
    index_generation
    index_mapping
    indexann
    indexann_data
    indexann/protos
    indexdoc
    indexdoc/entry_protos
    indexer
    indexuser_types
    inflectorlib
    inflectorlib/pluralize/tool
    inflectorlib/pluralize/ut
    is_holiday
    itditp
    itditp_user_history_factors_info
    iznanka
    langregion
    lang_distr
    lemmas_merger
    lemmer
    lemmer/alpha/tests
    lemmer/alpha/ut
    lemmer/benchmark
    lemmer/core/ut
    lemmer/new_engine/ut
    lemmer/performance_test
    lemmer/superlemmer
    lemmer/superlemmer/builder
    lemmer/superlemmer/test
    lemmer/superlemmer/ut
    lemmer/tests
    lemmer/ut
    lingboost
    lingboost/enum_map_benchmark
    lingboost/ut
    m2n
    m2n/ut
    mango
    matrixnet
    matrixnet/perftest
    matrixnet/perftest/metrics
    matrixnet/ut
    miniapp
    mirrors
    mlock_limiter
    multilanguage_hosts
    multilanguage_hosts/ut
    multipart_archive
    multipart_archive/common/ut
    multipart_archive/part_impl/ut
    multipart_archive/ut
    ngrams
    nn
    nn_ops
    nn_ops/protos
    nn_ops/ut
    normalize_by_lemmas
    normalize_by_lemmas/tests
    normalize_by_lemmas/ut
    oldrobottxt
    parallel_mx_calcer
    porno
    porno/enums
    porno/proto
    porno/ut
    proto_codegen
    proto_fuzz
    proto_fuzz/ut
    prs_log
    prs_log/ut
    public_suffixes
    public_suffixes/ut
    pure_lib
    qeflexindex
    qeflexindex/ut
    qtree
    queries
    querydata
    queryfactors
    random_log_factors
    random_log_factors/ut
    random_log_parse
    random_log_parse/ut
    ranking_feature_pool
    ranking_feature_pool/ut
    recshell
    relev_locale
    relev_locale/tools
    relev_locale/ut
    relevfml
    relevfml/ut
    relevgeo
    relevstatic
    remap
    remap/ut
    remorph
    reqbundle
    reqbundle/tests
    reqbundle/ut
    reqbundle_iterator
    reqbundle_iterator/ut
    reqerror
    reqerror/ut
    reqid
    reqid/ut
    saas_trie/codec_bench
    saas_trie/ut
    saas_trie/search_bench
    search_daemon_iface
    search_query
    search_query/bench
    search_query/ut
    search_query/ut_canonize
    search_zone
    searchlog
    searchlog/ut
    segmentator
    segnumerator
    segnumerator/ut
    segutils
    segutils_dater
    seinfo
    seinfo/ut
    semanet
    sent_lens
    sent_lens/generate-test-output
    sent_lens/generate-trie
    sent_lens/ut
    server/protos
    shard_conf
    shard_conf/ut
    signurl
    signurl/ut
    social
    social/ut
    streams
    stringmatch_tracker
    stringmatch_tracker/matchers/ut
    stringmatch_tracker/ut
    struct_codegen
    surf_word_stats
    synnorm
    synnorm/ut
    synnorm/standalone
    synnorm/standalone/ut
    synsets
    tarc
    text_machine
    text_machine/parts/common/ut
    text_machine/tools
    text_machine/ut
    title_ranges
    title_ranges/test_title_ranges
    title_ranges/ut
    titlefeatures
    totalban
    totalban/ut
    translate
    translate/source
    translate/ut
    translit
    translit/ut
    tr_over_reqbundle_iterator
    trie_common
    turbo
    u_tracker
    ugc
    uri
    url
    url/ut
    url_sequences
    url_text_analyzer
    url_text_analyzer/ut
    url_tools
    url_tools/ut
    url_translit_similarity
    url_translit_similarity/console_test
    url_translit_similarity/data
    urlid
    urlid/ut
    urlnorm
    urlnorm/ut
    user_history/ut
    user_history/lib/ut
    vector_machine
    vector_machine/ut
    voice_text
    voice_text/bin
    voice_text/ut
    walrus
    walrus/ut
    web_factors_info
    web_factors_info/all_web_slices_checks
    web_factors_info/ut
    web_production_formula_features_factors_info
    web_relev_artifacts
    web_relev_artifacts/ut
    web_itditp_factors_info
    web_itditp_static_features_factors_info
    web_itditp_recommender_factors_info
    web_l1_factors_info
    web_l2_factors_info
    web_l3_mxnet_factors_info
    web_meta_factors_info/ut
    web_meta_pers_factors_info
    web_new_l1_factors_info
    web_rtmodels_factors_info
    weighted_sequence_features
    weighted_sequence_features/ut
    xmlreq
    xmlreq/ut
    xpathmarker
    xref
    yacatalog
    yacatalog/ut
    yawklib
    ydo
    word_hyphenator
    word_hyphenator/ut
    word_hyphenator/trie_generator
    key_inv_processor
    knn_service
    knn_service/ut
    yellowness_factors
    keyinv/hitlist/memory
    keyinv/hitlist
    keyinv/invkeypos
    keyinv/indexfile
    keyinv/hitlist/ut
    keyinv/invkeypos/ut
    keyinv/indexfile/ut
    classify_results
    classify_results/ut
    segmentator/structs
    snippets
)

IF (NOT SANITIZER_TYPE)
    RECURSE(
        dssm_applier/optimized_model/run_test # sanitizer somehow affects result of floating point operations
    )
ENDIF()

IF (NOT OS_WINDOWS)
    RECURSE(
        server
        server/examples
        querydata/ut
        index_mapping/ut
    )
ENDIF()

IF (LINUX)
    RECURSE(p0f)
ENDIF()
