from collections import OrderedDict
from io import StringIO
from typing import NamedTuple

from ruamel import yaml

yaml.RoundTripRepresenter.add_representer(OrderedDict, yaml.RoundTripRepresenter.represent_dict)


class Config(NamedTuple):
    file_path: str
    content: str


def load_file(file_path: str) -> str:
    with open(file_path, 'r') as file:
        return file.read()


def load_yaml_file(file_path: str) -> dict:
    with open(file_path, 'r') as f:
        return yaml.load(f, Loader=yaml.RoundTripLoader)


def dump_yaml(value: dict, generation_notice=False) -> str:
    if not generation_notice:
        return yaml.dump(value, Dumper=yaml.RoundTripDumper, width=120)

    buffer = StringIO()
    buffer.write('# Generated by "make generate" from cloud/mdb/clickhouse/versions\n')
    yaml.dump(value, stream=buffer, Dumper=yaml.RoundTripDumper, width=120)
    return buffer.getvalue()
