#! /bin/bash

. /lib/lsb/init-functions

DAEMON="push-client-cocaine-logs"
DAEMON_BASE="statbox"
DAEMON_BIN="/usr/bin/push-client"
DAEMON_NAME="push-client-cocaine-logs"
DAEMON_OPTS="-f -w"
DAEMON_CONF="/etc/yandex/push-client-cocaine-logs.yaml"

if [ ! -x $DAEMON_BIN ]
then
	exit 0
fi

for conf in $DAEMON_CONF
do
	DAEMON_OPTS="$DAEMON_OPTS -c $conf "
done

ulimit -c unlimited

case "$1" in
  start)
    log_begin_msg "Starting ${DAEMON_NAME}..."
    test -d /var/run/$DAEMON_BASE || mkdir -p /var/run/$DAEMON_BASE

    if start-stop-daemon --quiet --stop --signal 0 --pidfile /var/run/$DAEMON_BASE/$DAEMON.pid 2>/dev/null 1>/dev/null; then
      log_failure_msg "${DAEMON_NAME} already running"
    else
      start-stop-daemon -c statbox --start -bmp /var/run/$DAEMON_BASE/$DAEMON.pid --exec ${DAEMON_BIN} -- ${DAEMON_OPTS}
      log_end_msg $?
    fi

    log_end_msg $?
  ;;

  stop)
    log_begin_msg "Stopping ${DAEMON_NAME}..."
    start-stop-daemon --quiet --retry=TERM/10/KILL/5 --stop --pidfile /var/run/$DAEMON_BASE/$DAEMON.pid 1>/dev/null 2>&1
    log_end_msg $?
    rm -f /var/run/$DAEMON_BASE/$DAEMON.pid 2>/dev/null
  ;;

  reload)
   log_begin_msg "Reloading ${DAEMON_NAME}..."
   start-stop-daemon --quiet --stop --signal 1 --pidfile /var/run/$DAEMON_BASE/$DAEMON.pid 
   log_end_msg $?
  ;;

  restart)
    log_begin_msg "Restarting ${DAEMON_NAME}..."
    $0 stop
    sleep 1
    $0 start
  ;;

*)
  log_success_msg "Usage $0 {start|stop|reload|restart}"
  exit 1

esac

exit 0

