# -*- coding: utf-8 -*-
"""
DBaaS Internal API MySQL globals
"""

MY_CLUSTER_TYPE = 'mysql_cluster'
RESTART_DEFAULTS = ['innodb_buffer_pool_size']

INTERNAL_USERS = ['admin', 'monitor', 'root', 'repl', 'mysql.session', 'mysql.sys']
SYSTEM_DATABASES = ['mysql', 'sys', 'information_schema', 'performance_schema']
PRIVILEGES = [
    'ALTER',
    'ALTER ROUTINE',
    'CREATE',
    'CREATE ROUTINE',
    'CREATE TEMPORARY TABLES',
    'CREATE VIEW',
    'DELETE',
    'DROP',
    'EVENT',
    'EXECUTE',
    'INDEX',
    'INSERT',
    'LOCK TABLES',
    'SELECT',
    'SHOW VIEW',
    'TRIGGER',
    'UPDATE',
    'REFERENCES',
]

GLOBAL_PRIVILEGES = [
    'REPLICATION CLIENT',
    'REPLICATION SLAVE',
    'PROCESS',
]

SPECIAL_GLOBAL_PRIVILEGES = [
    'RELOAD',
    'FLUSH_TABLES',
]

ALL_PRIVILEGES = 'ALL PRIVILEGES'
VALID_ROLES = [ALL_PRIVILEGES] + PRIVILEGES
DEFAULT_ROLES = [ALL_PRIVILEGES]
DEFAULT_SERVICES = ['mysql']
GLOBAL_VALID_ROLES_API_ENUM = [p.replace(' ', '_') for p in GLOBAL_PRIVILEGES]
VALID_ROLES_API_ENUM = [p.replace(' ', '_') for p in VALID_ROLES]

SQL_MODES_5_7 = [
    "ALLOW_INVALID_DATES",
    "ANSI_QUOTES",
    "ERROR_FOR_DIVISION_BY_ZERO",
    "HIGH_NOT_PRECEDENCE",
    "IGNORE_SPACE",
    "NO_AUTO_CREATE_USER",
    "NO_AUTO_VALUE_ON_ZERO",
    "NO_BACKSLASH_ESCAPES",
    "NO_DIR_IN_CREATE",
    "NO_ENGINE_SUBSTITUTION",
    "NO_UNSIGNED_SUBTRACTION",
    "NO_ZERO_DATE",
    "NO_ZERO_IN_DATE",
    "NO_FIELD_OPTIONS",
    "NO_KEY_OPTIONS",
    "NO_TABLE_OPTIONS",
    "ONLY_FULL_GROUP_BY",
    "PAD_CHAR_TO_FULL_LENGTH",
    "PIPES_AS_CONCAT",
    "REAL_AS_FLOAT",
    "STRICT_ALL_TABLES",
    "STRICT_TRANS_TABLES",
    "ANSI",
    "TRADITIONAL",
    "DB2",
    "MAXDB",
    "MSSQL",
    "MYSQL323",
    "MYSQL40",
    "ORACLE",
    "POSTGRESQL",
]

SQL_MODES_8_0 = [
    "ALLOW_INVALID_DATES",
    "ANSI_QUOTES",
    "ERROR_FOR_DIVISION_BY_ZERO",
    "HIGH_NOT_PRECEDENCE",
    "IGNORE_SPACE",
    "NO_AUTO_VALUE_ON_ZERO",
    "NO_BACKSLASH_ESCAPES",
    "NO_DIR_IN_CREATE",
    "NO_ENGINE_SUBSTITUTION",
    "NO_UNSIGNED_SUBTRACTION",
    "NO_ZERO_DATE",
    "NO_ZERO_IN_DATE",
    "ONLY_FULL_GROUP_BY",
    "PAD_CHAR_TO_FULL_LENGTH",
    "PIPES_AS_CONCAT",
    "REAL_AS_FLOAT",
    "STRICT_ALL_TABLES",
    "STRICT_TRANS_TABLES",
    "TIME_TRUNCATE_FRACTIONAL",
    "ANSI",
    "TRADITIONAL",
]

DEFAULT_AUTH_PLUGIN_5_7 = "mysql_native_password"
DEFAULT_AUTH_PLUGIN_8_0 = "caching_sha2_password"

AUTH_PLUGINS_5_7 = [
    "mysql_native_password",
    "sha256_password",
]

AUTH_PLUGINS_8_0 = [
    "mysql_native_password",
    "caching_sha2_password",
    "sha256_password",
]

UPPER_AUTH_PLUGINS_8_0_ENUM = [e.upper() for e in AUTH_PLUGINS_8_0]
UPPER_AUTH_PLUGINS_5_7_ENUM = [e.upper() for e in AUTH_PLUGINS_5_7]

MYSQL_BINLOGS_APPLY_RATE = 1024**3  # 1 Mb/s per core

USER_LIMITS = [
    "max_questions_per_hour",
    "max_updates_per_hour",
    "max_connections_per_hour",
    "max_user_connections",
]

CHARSET_5_7 = [
    'big5',
    'dec8',
    'cp850',
    'hp8',
    'koi8r',
    'latin1',
    'latin2',
    'swe7',
    'ascii',
    'ujis',
    'sjis',
    'hebrew',
    'tis620',
    'euckr',
    'koi8u',
    'gb2312',
    'greek',
    'cp1250',
    'gbk',
    'latin5',
    'armscii8',
    'utf8',
    'ucs2',
    'cp866',
    'keybcs2',
    'macce',
    'macroman',
    'cp852',
    'latin7',
    'utf8mb4',
    'cp1251',
    'utf16',
    'utf16le',
    'cp1256',
    'cp1257',
    'utf32',
    'binary',
    'geostd8',
    'cp932',
    'eucjpms',
    'gb18030',
]

COLLATION_5_7 = [
    'big5_chinese_ci',
    'big5_bin',
    'dec8_swedish_ci',
    'dec8_bin',
    'cp850_general_ci',
    'cp850_bin',
    'hp8_english_ci',
    'hp8_bin',
    'koi8r_general_ci',
    'koi8r_bin',
    'latin1_german1_ci',
    'latin1_swedish_ci',
    'latin1_danish_ci',
    'latin1_german2_ci',
    'latin1_bin',
    'latin1_general_ci',
    'latin1_general_cs',
    'latin1_spanish_ci',
    'latin2_czech_cs',
    'latin2_general_ci',
    'latin2_hungarian_ci',
    'latin2_croatian_ci',
    'latin2_bin',
    'swe7_swedish_ci',
    'swe7_bin',
    'ascii_general_ci',
    'ascii_bin',
    'ujis_japanese_ci',
    'ujis_bin',
    'sjis_japanese_ci',
    'sjis_bin',
    'hebrew_general_ci',
    'hebrew_bin',
    'tis620_thai_ci',
    'tis620_bin',
    'euckr_korean_ci',
    'euckr_bin',
    'koi8u_general_ci',
    'koi8u_bin',
    'gb2312_chinese_ci',
    'gb2312_bin',
    'greek_general_ci',
    'greek_bin',
    'cp1250_general_ci',
    'cp1250_czech_cs',
    'cp1250_croatian_ci',
    'cp1250_bin',
    'cp1250_polish_ci',
    'gbk_chinese_ci',
    'gbk_bin',
    'latin5_turkish_ci',
    'latin5_bin',
    'armscii8_general_ci',
    'armscii8_bin',
    'utf8_general_ci',
    'utf8_bin',
    'utf8_unicode_ci',
    'utf8_icelandic_ci',
    'utf8_latvian_ci',
    'utf8_romanian_ci',
    'utf8_slovenian_ci',
    'utf8_polish_ci',
    'utf8_estonian_ci',
    'utf8_spanish_ci',
    'utf8_swedish_ci',
    'utf8_turkish_ci',
    'utf8_czech_ci',
    'utf8_danish_ci',
    'utf8_lithuanian_ci',
    'utf8_slovak_ci',
    'utf8_spanish2_ci',
    'utf8_roman_ci',
    'utf8_persian_ci',
    'utf8_esperanto_ci',
    'utf8_hungarian_ci',
    'utf8_sinhala_ci',
    'utf8_german2_ci',
    'utf8_croatian_ci',
    'utf8_unicode_520_ci',
    'utf8_vietnamese_ci',
    'utf8_general_mysql500_ci',
    'ucs2_general_ci',
    'ucs2_bin',
    'ucs2_unicode_ci',
    'ucs2_icelandic_ci',
    'ucs2_latvian_ci',
    'ucs2_romanian_ci',
    'ucs2_slovenian_ci',
    'ucs2_polish_ci',
    'ucs2_estonian_ci',
    'ucs2_spanish_ci',
    'ucs2_swedish_ci',
    'ucs2_turkish_ci',
    'ucs2_czech_ci',
    'ucs2_danish_ci',
    'ucs2_lithuanian_ci',
    'ucs2_slovak_ci',
    'ucs2_spanish2_ci',
    'ucs2_roman_ci',
    'ucs2_persian_ci',
    'ucs2_esperanto_ci',
    'ucs2_hungarian_ci',
    'ucs2_sinhala_ci',
    'ucs2_german2_ci',
    'ucs2_croatian_ci',
    'ucs2_unicode_520_ci',
    'ucs2_vietnamese_ci',
    'ucs2_general_mysql500_ci',
    'cp866_general_ci',
    'cp866_bin',
    'keybcs2_general_ci',
    'keybcs2_bin',
    'macce_general_ci',
    'macce_bin',
    'macroman_general_ci',
    'macroman_bin',
    'cp852_general_ci',
    'cp852_bin',
    'latin7_estonian_cs',
    'latin7_general_ci',
    'latin7_general_cs',
    'latin7_bin',
    'utf8mb4_general_ci',
    'utf8mb4_bin',
    'utf8mb4_unicode_ci',
    'utf8mb4_icelandic_ci',
    'utf8mb4_latvian_ci',
    'utf8mb4_romanian_ci',
    'utf8mb4_slovenian_ci',
    'utf8mb4_polish_ci',
    'utf8mb4_estonian_ci',
    'utf8mb4_spanish_ci',
    'utf8mb4_swedish_ci',
    'utf8mb4_turkish_ci',
    'utf8mb4_czech_ci',
    'utf8mb4_danish_ci',
    'utf8mb4_lithuanian_ci',
    'utf8mb4_slovak_ci',
    'utf8mb4_spanish2_ci',
    'utf8mb4_roman_ci',
    'utf8mb4_persian_ci',
    'utf8mb4_esperanto_ci',
    'utf8mb4_hungarian_ci',
    'utf8mb4_sinhala_ci',
    'utf8mb4_german2_ci',
    'utf8mb4_croatian_ci',
    'utf8mb4_unicode_520_ci',
    'utf8mb4_vietnamese_ci',
    'cp1251_bulgarian_ci',
    'cp1251_ukrainian_ci',
    'cp1251_bin',
    'cp1251_general_ci',
    'cp1251_general_cs',
    'utf16_general_ci',
    'utf16_bin',
    'utf16_unicode_ci',
    'utf16_icelandic_ci',
    'utf16_latvian_ci',
    'utf16_romanian_ci',
    'utf16_slovenian_ci',
    'utf16_polish_ci',
    'utf16_estonian_ci',
    'utf16_spanish_ci',
    'utf16_swedish_ci',
    'utf16_turkish_ci',
    'utf16_czech_ci',
    'utf16_danish_ci',
    'utf16_lithuanian_ci',
    'utf16_slovak_ci',
    'utf16_spanish2_ci',
    'utf16_roman_ci',
    'utf16_persian_ci',
    'utf16_esperanto_ci',
    'utf16_hungarian_ci',
    'utf16_sinhala_ci',
    'utf16_german2_ci',
    'utf16_croatian_ci',
    'utf16_unicode_520_ci',
    'utf16_vietnamese_ci',
    'utf16le_general_ci',
    'utf16le_bin',
    'cp1256_general_ci',
    'cp1256_bin',
    'cp1257_lithuanian_ci',
    'cp1257_bin',
    'cp1257_general_ci',
    'utf32_general_ci',
    'utf32_bin',
    'utf32_unicode_ci',
    'utf32_icelandic_ci',
    'utf32_latvian_ci',
    'utf32_romanian_ci',
    'utf32_slovenian_ci',
    'utf32_polish_ci',
    'utf32_estonian_ci',
    'utf32_spanish_ci',
    'utf32_swedish_ci',
    'utf32_turkish_ci',
    'utf32_czech_ci',
    'utf32_danish_ci',
    'utf32_lithuanian_ci',
    'utf32_slovak_ci',
    'utf32_spanish2_ci',
    'utf32_roman_ci',
    'utf32_persian_ci',
    'utf32_esperanto_ci',
    'utf32_hungarian_ci',
    'utf32_sinhala_ci',
    'utf32_german2_ci',
    'utf32_croatian_ci',
    'utf32_unicode_520_ci',
    'utf32_vietnamese_ci',
    'binary',
    'geostd8_general_ci',
    'geostd8_bin',
    'cp932_japanese_ci',
    'cp932_bin',
    'eucjpms_japanese_ci',
    'eucjpms_bin',
    'gb18030_chinese_ci',
    'gb18030_bin',
    'gb18030_unicode_520_ci',
]

DEFAULT_CHARSET_5_7 = 'latin1'

DEFAULT_COLLATION_5_7 = 'latin1_swedish_ci'

CHARSET_8_0 = [
    'armscii8',
    'ascii',
    'big5',
    'binary',
    'cp1250',
    'cp1251',
    'cp1256',
    'cp1257',
    'cp850',
    'cp852',
    'cp866',
    'cp932',
    'dec8',
    'eucjpms',
    'euckr',
    'gb18030',
    'gb2312',
    'gbk',
    'geostd8',
    'greek',
    'hebrew',
    'hp8',
    'keybcs2',
    'koi8r',
    'koi8u',
    'latin1',
    'latin2',
    'latin5',
    'latin7',
    'macce',
    'macroman',
    'sjis',
    'swe7',
    'tis620',
    'ucs2',
    'ujis',
    'utf16',
    'utf16le',
    'utf32',
    'utf8',
    'utf8mb4',
]

COLLATION_8_0 = [
    'armscii8_bin',
    'armscii8_general_ci',
    'ascii_bin',
    'ascii_general_ci',
    'big5_bin',
    'big5_chinese_ci',
    'binary',
    'cp1250_bin',
    'cp1250_croatian_ci',
    'cp1250_czech_cs',
    'cp1250_general_ci',
    'cp1250_polish_ci',
    'cp1251_bin',
    'cp1251_bulgarian_ci',
    'cp1251_general_ci',
    'cp1251_general_cs',
    'cp1251_ukrainian_ci',
    'cp1256_bin',
    'cp1256_general_ci',
    'cp1257_bin',
    'cp1257_general_ci',
    'cp1257_lithuanian_ci',
    'cp850_bin',
    'cp850_general_ci',
    'cp852_bin',
    'cp852_general_ci',
    'cp866_bin',
    'cp866_general_ci',
    'cp932_bin',
    'cp932_japanese_ci',
    'dec8_bin',
    'dec8_swedish_ci',
    'eucjpms_bin',
    'eucjpms_japanese_ci',
    'euckr_bin',
    'euckr_korean_ci',
    'gb18030_bin',
    'gb18030_chinese_ci',
    'gb18030_unicode_520_ci',
    'gb2312_bin',
    'gb2312_chinese_ci',
    'gbk_bin',
    'gbk_chinese_ci',
    'geostd8_bin',
    'geostd8_general_ci',
    'greek_bin',
    'greek_general_ci',
    'hebrew_bin',
    'hebrew_general_ci',
    'hp8_bin',
    'hp8_english_ci',
    'keybcs2_bin',
    'keybcs2_general_ci',
    'koi8r_bin',
    'koi8r_general_ci',
    'koi8u_bin',
    'koi8u_general_ci',
    'latin1_bin',
    'latin1_danish_ci',
    'latin1_general_ci',
    'latin1_general_cs',
    'latin1_german1_ci',
    'latin1_german2_ci',
    'latin1_spanish_ci',
    'latin1_swedish_ci',
    'latin2_bin',
    'latin2_croatian_ci',
    'latin2_czech_cs',
    'latin2_general_ci',
    'latin2_hungarian_ci',
    'latin5_bin',
    'latin5_turkish_ci',
    'latin7_bin',
    'latin7_estonian_cs',
    'latin7_general_ci',
    'latin7_general_cs',
    'macce_bin',
    'macce_general_ci',
    'macroman_bin',
    'macroman_general_ci',
    'sjis_bin',
    'sjis_japanese_ci',
    'swe7_bin',
    'swe7_swedish_ci',
    'tis620_bin',
    'tis620_thai_ci',
    'ucs2_bin',
    'ucs2_croatian_ci',
    'ucs2_czech_ci',
    'ucs2_danish_ci',
    'ucs2_esperanto_ci',
    'ucs2_estonian_ci',
    'ucs2_general_ci',
    'ucs2_general_mysql500_ci',
    'ucs2_german2_ci',
    'ucs2_hungarian_ci',
    'ucs2_icelandic_ci',
    'ucs2_latvian_ci',
    'ucs2_lithuanian_ci',
    'ucs2_persian_ci',
    'ucs2_polish_ci',
    'ucs2_romanian_ci',
    'ucs2_roman_ci',
    'ucs2_sinhala_ci',
    'ucs2_slovak_ci',
    'ucs2_slovenian_ci',
    'ucs2_spanish2_ci',
    'ucs2_spanish_ci',
    'ucs2_swedish_ci',
    'ucs2_turkish_ci',
    'ucs2_unicode_520_ci',
    'ucs2_unicode_ci',
    'ucs2_vietnamese_ci',
    'ujis_bin',
    'ujis_japanese_ci',
    'utf16le_bin',
    'utf16le_general_ci',
    'utf16_bin',
    'utf16_croatian_ci',
    'utf16_czech_ci',
    'utf16_danish_ci',
    'utf16_esperanto_ci',
    'utf16_estonian_ci',
    'utf16_general_ci',
    'utf16_german2_ci',
    'utf16_hungarian_ci',
    'utf16_icelandic_ci',
    'utf16_latvian_ci',
    'utf16_lithuanian_ci',
    'utf16_persian_ci',
    'utf16_polish_ci',
    'utf16_romanian_ci',
    'utf16_roman_ci',
    'utf16_sinhala_ci',
    'utf16_slovak_ci',
    'utf16_slovenian_ci',
    'utf16_spanish2_ci',
    'utf16_spanish_ci',
    'utf16_swedish_ci',
    'utf16_turkish_ci',
    'utf16_unicode_520_ci',
    'utf16_unicode_ci',
    'utf16_vietnamese_ci',
    'utf32_bin',
    'utf32_croatian_ci',
    'utf32_czech_ci',
    'utf32_danish_ci',
    'utf32_esperanto_ci',
    'utf32_estonian_ci',
    'utf32_general_ci',
    'utf32_german2_ci',
    'utf32_hungarian_ci',
    'utf32_icelandic_ci',
    'utf32_latvian_ci',
    'utf32_lithuanian_ci',
    'utf32_persian_ci',
    'utf32_polish_ci',
    'utf32_romanian_ci',
    'utf32_roman_ci',
    'utf32_sinhala_ci',
    'utf32_slovak_ci',
    'utf32_slovenian_ci',
    'utf32_spanish2_ci',
    'utf32_spanish_ci',
    'utf32_swedish_ci',
    'utf32_turkish_ci',
    'utf32_unicode_520_ci',
    'utf32_unicode_ci',
    'utf32_vietnamese_ci',
    'utf8mb4_0900_ai_ci',
    'utf8mb4_0900_as_ci',
    'utf8mb4_0900_as_cs',
    'utf8mb4_0900_bin',
    'utf8mb4_bin',
    'utf8mb4_croatian_ci',
    'utf8mb4_cs_0900_ai_ci',
    'utf8mb4_cs_0900_as_cs',
    'utf8mb4_czech_ci',
    'utf8mb4_danish_ci',
    'utf8mb4_da_0900_ai_ci',
    'utf8mb4_da_0900_as_cs',
    'utf8mb4_de_pb_0900_ai_ci',
    'utf8mb4_de_pb_0900_as_cs',
    'utf8mb4_eo_0900_ai_ci',
    'utf8mb4_eo_0900_as_cs',
    'utf8mb4_esperanto_ci',
    'utf8mb4_estonian_ci',
    'utf8mb4_es_0900_ai_ci',
    'utf8mb4_es_0900_as_cs',
    'utf8mb4_es_trad_0900_ai_ci',
    'utf8mb4_es_trad_0900_as_cs',
    'utf8mb4_et_0900_ai_ci',
    'utf8mb4_et_0900_as_cs',
    'utf8mb4_general_ci',
    'utf8mb4_german2_ci',
    'utf8mb4_hr_0900_ai_ci',
    'utf8mb4_hr_0900_as_cs',
    'utf8mb4_hungarian_ci',
    'utf8mb4_hu_0900_ai_ci',
    'utf8mb4_hu_0900_as_cs',
    'utf8mb4_icelandic_ci',
    'utf8mb4_is_0900_ai_ci',
    'utf8mb4_is_0900_as_cs',
    'utf8mb4_ja_0900_as_cs',
    'utf8mb4_ja_0900_as_cs_ks',
    'utf8mb4_latvian_ci',
    'utf8mb4_la_0900_ai_ci',
    'utf8mb4_la_0900_as_cs',
    'utf8mb4_lithuanian_ci',
    'utf8mb4_lt_0900_ai_ci',
    'utf8mb4_lt_0900_as_cs',
    'utf8mb4_lv_0900_ai_ci',
    'utf8mb4_lv_0900_as_cs',
    'utf8mb4_persian_ci',
    'utf8mb4_pl_0900_ai_ci',
    'utf8mb4_pl_0900_as_cs',
    'utf8mb4_polish_ci',
    'utf8mb4_romanian_ci',
    'utf8mb4_roman_ci',
    'utf8mb4_ro_0900_ai_ci',
    'utf8mb4_ro_0900_as_cs',
    'utf8mb4_ru_0900_ai_ci',
    'utf8mb4_ru_0900_as_cs',
    'utf8mb4_sinhala_ci',
    'utf8mb4_sk_0900_ai_ci',
    'utf8mb4_sk_0900_as_cs',
    'utf8mb4_slovak_ci',
    'utf8mb4_slovenian_ci',
    'utf8mb4_sl_0900_ai_ci',
    'utf8mb4_sl_0900_as_cs',
    'utf8mb4_spanish2_ci',
    'utf8mb4_spanish_ci',
    'utf8mb4_sv_0900_ai_ci',
    'utf8mb4_sv_0900_as_cs',
    'utf8mb4_swedish_ci',
    'utf8mb4_tr_0900_ai_ci',
    'utf8mb4_tr_0900_as_cs',
    'utf8mb4_turkish_ci',
    'utf8mb4_unicode_520_ci',
    'utf8mb4_unicode_ci',
    'utf8mb4_vietnamese_ci',
    'utf8mb4_vi_0900_ai_ci',
    'utf8mb4_vi_0900_as_cs',
    'utf8mb4_zh_0900_as_cs',
    'utf8_bin',
    'utf8_croatian_ci',
    'utf8_czech_ci',
    'utf8_danish_ci',
    'utf8_esperanto_ci',
    'utf8_estonian_ci',
    'utf8_general_ci',
    'utf8_general_mysql500_ci',
    'utf8_german2_ci',
    'utf8_hungarian_ci',
    'utf8_icelandic_ci',
    'utf8_latvian_ci',
    'utf8_lithuanian_ci',
    'utf8_persian_ci',
    'utf8_polish_ci',
    'utf8_romanian_ci',
    'utf8_roman_ci',
    'utf8_sinhala_ci',
    'utf8_slovak_ci',
    'utf8_slovenian_ci',
    'utf8_spanish2_ci',
    'utf8_spanish_ci',
    'utf8_swedish_ci',
    'utf8_tolower_ci',
    'utf8_turkish_ci',
    'utf8_unicode_520_ci',
    'utf8_unicode_ci',
    'utf8_vietnamese_ci',
]

DEFAULT_CHARSET_8_0 = 'utf8mb4'

DEFAULT_COLLATION_8_0 = 'utf8mb4_0900_ai_ci'

TRANSACTION_ISOLATION = [
    'READ-COMMITTED',
    'REPEATABLE-READ',
    'SERIALIZABLE',
]

TRANSACTION_ISOLATION_ENUM = [t.replace('-', '_') for t in TRANSACTION_ISOLATION]

BINLOG_ROW_IMAGE_ENUM = [
    'FULL',
    'MINIMAL',
    'NOBLOB',
]

SLAVE_PARALLEL_TYPE_ENUM = [
    'DATABASE',
    'LOGICAL_CLOCK',
]

BINLOG_TRANSACTION_DEPENDENCY_TRACKING_ENUM = [
    'COMMIT_ORDER',
    'WRITESET',
    'WRITESET_SESSION',
]

LOG_SLOW_RATE_TYPE_ENUM = [
    'SESSION',
    'QUERY',
]

LOG_SLOW_FILTER_ENUM = [
    'FULL_SCAN',
    'FULL_JOIN',
    'TMP_TABLE',
    'TMP_TABLE_ON_DISK',
    'FILESORT',
    'FILESORT_ON_DISK',
]

INNODB_PAGE_SIZES = [
    4096,
    8192,
    16384,
    32768,
    65536,
]

DEFAULT_INNODB_PAGE_SIZE = 16384
