LIBRARY()

OWNER(
    sankear
    g:base
)

SRCS(
    standard_models_storage.h
)

RESOURCE(
    models/standard_io_model_panther_key_io_model_v1 standard_io_model_panther_key_io_model_v1
    models/standard_io_model_panther_hit_io_model_v1 standard_io_model_panther_hit_io_model_v1

    models/standard_io_model_attributes_hit_io_model_v1 standard_io_model_attributes_hit_io_model_v1
    models/standard_io_model_attributes_key_io_model_v1 standard_io_model_attributes_key_io_model_v1

    models/standard_io_model_double_panther_key_io_model_v1 standard_io_model_double_panther_key_io_model_v1
    models/standard_io_model_double_panther_hit_io_model_v1 standard_io_model_double_panther_hit_io_model_v1

    models/standard_io_model_ann_data_hit_io_model_v1 standard_io_model_ann_data_hit_io_model_v1

    models/standard_io_model_ann_key_io_model_v1 standard_io_model_ann_key_io_model_v1
    models/standard_io_model_ann_hit_io_model_v1 standard_io_model_ann_hit_io_model_v1

    models/standard_io_model_ann_sorted_multi_keys_key_io_model_v1 standard_io_model_ann_sorted_multi_keys_key_io_model_v1
    models/standard_io_model_ann_sorted_multi_keys_hit_io_model_v1 standard_io_model_ann_sorted_multi_keys_hit_io_model_v1

    models/standard_io_model_counts_key_io_model_v1 standard_io_model_counts_key_io_model_v1
    models/standard_io_model_counts_hit_io_model_v1 standard_io_model_counts_hit_io_model_v1

    models/standard_io_model_portion_counts_key_io_model_v1 standard_io_model_portion_counts_key_io_model_v1
    models/standard_io_model_portion_counts_hit_io_model_v1 standard_io_model_portion_counts_hit_io_model_v1

    models/standard_io_model_portion_attributes_key_io_model_v1 standard_io_model_portion_attributes_key_io_model_v1
    models/standard_io_model_portion_attributes_hit_io_model_v1 standard_io_model_portion_attributes_hit_io_model_v1

    models/standard_io_model_omni_dssm_log_dwell_time_bigrams_embedding_io_model_v1 standard_io_model_omni_dssm_log_dwell_time_bigrams_embedding_io_model_v1
    models/standard_io_model_omni_ann_reg_stats_io_model_v1 standard_io_model_omni_ann_reg_stats_io_model_v1
    models/standard_io_model_omni_dssm_aggregated_ann_reg_embedding_io_model_v1 standard_io_model_omni_dssm_aggregated_ann_reg_embedding_io_model_v1
    models/standard_io_model_omni_dssm_ann_ctr_compressed_embedding_io_model_v1 standard_io_model_omni_dssm_ann_ctr_compressed_embedding_io_model_v1
    models/standard_io_model_omni_dssm_ann_xf_dt_show_one_compressed_embedding_io_model_v1 standard_io_model_omni_dssm_ann_xf_dt_show_one_compressed_embedding_io_model_v1
    models/standard_io_model_omni_dssm_ann_xf_dt_show_one_se_compressed_embedding_io_model_v1 standard_io_model_omni_dssm_ann_xf_dt_show_one_se_compressed_embedding_io_model_v1
    models/standard_io_model_omni_dssm_ann_xf_dt_show_weight_compressed_embedding1_io_model_v1 standard_io_model_omni_dssm_ann_xf_dt_show_weight_compressed_embedding1_io_model_v1
    models/standard_io_model_omni_dssm_ann_xf_dt_show_weight_compressed_embedding2_io_model_v1 standard_io_model_omni_dssm_ann_xf_dt_show_weight_compressed_embedding2_io_model_v1
    models/standard_io_model_omni_dssm_ann_xf_dt_show_weight_compressed_embedding3_io_model_v1 standard_io_model_omni_dssm_ann_xf_dt_show_weight_compressed_embedding3_io_model_v1
    models/standard_io_model_omni_dssm_ann_xf_dt_show_weight_compressed_embedding4_io_model_v1 standard_io_model_omni_dssm_ann_xf_dt_show_weight_compressed_embedding4_io_model_v1
    models/standard_io_model_omni_dssm_ann_xf_dt_show_weight_compressed_embedding5_io_model_v1 standard_io_model_omni_dssm_ann_xf_dt_show_weight_compressed_embedding5_io_model_v1
    models/standard_io_model_omni_dssm_concatenated_ann_reg_embedding_io_model_v1 standard_io_model_omni_dssm_concatenated_ann_reg_embedding_io_model_v1
    models/standard_io_model_omni_dssm_embedding_io_model_v1 standard_io_model_omni_dssm_embedding_io_model_v1
    models/standard_io_model_omni_dssm_main_content_keywords_embedding_io_model_v1 standard_io_model_omni_dssm_main_content_keywords_embedding_io_model_v1
    models/standard_io_model_omni_title_io_model_v1 standard_io_model_omni_title_io_model_v1
    models/standard_io_model_omni_url_io_model_v1 standard_io_model_omni_url_io_model_v1

    models/standard_io_model_portion_panther_key_io_model_v1 standard_io_model_portion_panther_key_io_model_v1
    models/standard_io_model_portion_panther_hit_io_model_v1 standard_io_model_portion_panther_hit_io_model_v1

    models/standard_io_model_click_sim_io_model_v1 standard_io_model_click_sim_io_model_v1

    models/standard_io_model_doc_portion_key_io_model_v1 standard_io_model_doc_portion_key_io_model_v1
    models/standard_io_model_doc_portion_hit_io_model_v1 standard_io_model_doc_portion_hit_io_model_v1

    models/standard_io_model_erf_io_model_v1 standard_io_model_erf_io_model_v1

    models/standard_io_model_regherf_io_model_v1 standard_io_model_regherf_io_model_v1

    models/standard_io_model_host_erf_io_model_v1 standard_io_model_host_erf_io_model_v1

    models/standard_io_model_regerf_io_model_v1 standard_io_model_regerf_io_model_v1

    models/standard_io_model_ann_sent_hit_io_model_v1 standard_io_model_ann_sent_hit_io_model_v1
    models/standard_io_model_factor_ann_sent_hit_io_model_v1 standard_io_model_factor_ann_sent_hit_io_model_v1
    models/standard_io_model_link_ann_sent_hit_io_model_v1 standard_io_model_link_ann_sent_hit_io_model_v1
    models/standard_io_model_sent_hit_io_model_v1 standard_io_model_sent_hit_io_model_v1
    models/standard_io_model_doc_attrs_hit_io_model_v1 standard_io_model_doc_attrs_hit_io_model_v1
    models/standard_io_model_doc_attrs64_hit_io_model_v1 standard_io_model_doc_attrs64_hit_io_model_v1
    models/standard_io_model_name_to_categ_domain_model_v1 standard_io_model_name_to_categ_domain_model_v1
    models/standard_io_model_name_to_categ_host_model_v1 standard_io_model_name_to_categ_host_model_v1

    models/standard_io_model_panther_ngrams_hash_model_v1 standard_io_model_panther_ngrams_hash_model_v1
    models/standard_io_model_panther_ngrams_hit_model_v1 standard_io_model_panther_ngrams_hit_model_v1

    models/standard_io_model_img_ann_sorted_multi_keys_key_io_model_v1 standard_io_model_img_ann_sorted_multi_keys_key_io_model_v1
    models/standard_io_model_img_ann_sorted_multi_keys_hit_io_model_v1 standard_io_model_img_ann_sorted_multi_keys_hit_io_model_v1

    models/standard_io_model_inverted_index_panther_hash_model_v1 standard_io_model_inverted_index_panther_hash_model_v1
    models/standard_io_model_inverted_index_panther_hit_model_v1 standard_io_model_inverted_index_panther_hit_model_v1

    models/standard_io_model_keyinv_lemmas_remappings_io_model_v1 standard_io_model_keyinv_lemmas_remappings_io_model_v1
    models/standard_io_model_keyinv_forms_remappings_io_model_v1 standard_io_model_keyinv_forms_remappings_io_model_v1
    models/standard_io_model_keyinv_hit_io_model_v1 standard_io_model_keyinv_hit_io_model_v1
    models/standard_io_model_keyinv_hit_io_model_v2 standard_io_model_keyinv_hit_io_model_v2

    models/standard_io_model_erasure_locations_model_v1 standard_io_model_erasure_locations_model_v1
)

PEERDIR(
    library/cpp/offroad/codec
    library/cpp/resource
    kernel/doom/standard_models
)

END()
