debian/steam-site.settings.development.py   /usr/share/pyshared/steam/conf
debian/steam-site.settings.testing.py       /usr/share/pyshared/steam/conf
debian/steam-site.settings.prestable.py     /usr/share/pyshared/steam/conf
debian/steam-site.settings.production.py    /usr/share/pyshared/steam/conf
debian/steam-site.settings.stress.py        /usr/share/pyshared/steam/conf
site/steam/etc/ubic/steam-gunicorn                 /etc/ubic/service/steam
site/steam/etc/ubic/steam-celery                   /etc/ubic/service/steam
site/steam/etc/ubic/steam-celery-serp              /etc/ubic/service/steam
