enum SimpleEnum {
    ONE,
    // @internal
    TWO,
    THREE
}

// @internal
struct SimpleStruct {
    int reserved;
    double value;
}

struct SecondStruct {
    SimpleStruct s;
    SimpleEnum se;
}

// @internal
struct ThirdStruct {
   // @internal
   double value;
}

interface I {
    ThirdStruct method();
}
