# This file is generated by
# https://bb.yandex-team.ru/projects/CLOUD/repos/cloud-go/browse/tools/cmd/syncapi
# in Teamcity Task
# https://teamcity.yandex-team.ru/buildConfiguration/Cloud_Api_ApiSync

OWNER(g:cloud-api)
PROTO_LIBRARY()

PROTO_NAMESPACE(GLOBAL cloud/bitbucket/private-api)
PY_NAMESPACE(yandex.cloud.priv.marketplace.licenseserver.v1.license.partners)

GRPC()
SRCS(
    template_service.proto
    template_version_service.proto
)

USE_COMMON_GOOGLE_APIS(
    api/annotations
    rpc/code
    rpc/errdetails
    rpc/status
    type/timeofday
    type/dayofweek
)

IF (GO_PROTO)
    PEERDIR(
        cloud/bitbucket/common-api/yandex/cloud/api
        cloud/bitbucket/private-api/yandex/cloud/priv
        cloud/bitbucket/private-api/yandex/cloud/priv/marketplace/licenseserver/v1/license
        cloud/bitbucket/private-api/yandex/cloud/priv/operation
    )
ELSE()
    PEERDIR(
        cloud/bitbucket/common-api/yandex/cloud/api
        cloud/bitbucket/private-api/yandex/cloud/priv
        cloud/bitbucket/private-api/yandex/cloud/priv/marketplace/licenseserver/v1/license
        cloud/bitbucket/private-api/yandex/cloud/priv/operation
    )
ENDIF()
END()

