PY3_LIBRARY(yc_common)

OWNER(zasimov-a)

PEERDIR(
    contrib/python/colorlog
    contrib/python/humanize
    contrib/python/iso8601
    contrib/python/jsonschema
    contrib/python/prometheus-client
    contrib/python/requests
    contrib/python/responses
    contrib/python/simplejson
    contrib/python/schematics
    contrib/python/PyYAML
    contrib/python/regex
    contrib/python/toml
    contrib/python/requests-oauthlib
    contrib/python/oauthlib
    contrib/python/Flask
    contrib/python/aiohttp
    contrib/python/gunicorn  # for aiohttp
    contrib/python/pytest

    contrib/libs/grpc/src/python/grpcio

    ydb/public/sdk/python
    kikimr/public/sdk/python/iam

    devtools/experimental/cloud/x-contrib/tasklocals

    cloud/gauthling/auth_token_python/lib
    cloud/gauthling/yc_auth/lib
    cloud/gauthling/yc_requests/lib

    cloud/bitbucket/private-api/yandex/cloud/priv/access
    cloud/bitbucket/private-api/yandex/cloud/priv/ai/config/v1
    cloud/bitbucket/private-api/yandex/cloud/priv/ai/language/v1
    cloud/bitbucket/private-api/yandex/cloud/priv/ai/platform/v1
    cloud/bitbucket/private-api/yandex/cloud/priv/ai/stt/v2
    cloud/bitbucket/private-api/yandex/cloud/priv/ai/translate/v2
    cloud/bitbucket/private-api/yandex/cloud/priv/ai/vision/v1
    cloud/bitbucket/private-api/yandex/cloud/priv/billing/v1/private
    cloud/bitbucket/private-api/yandex/cloud/priv/billing/v1
    cloud/bitbucket/private-api/yandex/cloud/priv/certificatemanager/v1/console
    cloud/bitbucket/private-api/yandex/cloud/priv/certificatemanager/v1
    cloud/bitbucket/private-api/yandex/cloud/priv/compute/v1
    cloud/bitbucket/private-api/yandex/cloud/priv/containerregistry/v1/console
    cloud/bitbucket/private-api/yandex/cloud/priv/containerregistry/v1
    cloud/bitbucket/private-api/yandex/cloud/priv/dataproc/manager/v1
    cloud/bitbucket/private-api/yandex/cloud/priv/dataproc/v1
    cloud/bitbucket/private-api/yandex/cloud/priv/dns/v1/inner
    cloud/bitbucket/private-api/yandex/cloud/priv/dns/v1
    cloud/bitbucket/private-api/yandex/cloud/priv/example/v1alpha
    cloud/bitbucket/private-api/yandex/cloud/priv/healthcheck/v1alpha/inner
    cloud/bitbucket/private-api/yandex/cloud/priv/healthcheck/v1alpha
    cloud/bitbucket/private-api/yandex/cloud/priv/iam/v1/awscompatibility
    cloud/bitbucket/private-api/yandex/cloud/priv/iam/v1/console
    cloud/bitbucket/private-api/yandex/cloud/priv/iam/v1/saml
    cloud/bitbucket/private-api/yandex/cloud/priv/iam/v1/token
    cloud/bitbucket/private-api/yandex/cloud/priv/iam/v1/transitional
    cloud/bitbucket/private-api/yandex/cloud/priv/iam/v1
    cloud/bitbucket/private-api/yandex/cloud/priv/infra/tpmagent/v1
    cloud/bitbucket/private-api/yandex/cloud/priv/iot/devices/v1/inner
    cloud/bitbucket/private-api/yandex/cloud/priv/iot/devices/v1
    cloud/bitbucket/private-api/yandex/cloud/priv/k8s/v1/console
    cloud/bitbucket/private-api/yandex/cloud/priv/k8s/v1/inner
    cloud/bitbucket/private-api/yandex/cloud/priv/k8s/v1
    cloud/bitbucket/private-api/yandex/cloud/priv/kms/v1/console
    cloud/bitbucket/private-api/yandex/cloud/priv/kms/v1
    cloud/bitbucket/private-api/yandex/cloud/priv/loadbalancer/v1/console
    cloud/bitbucket/private-api/yandex/cloud/priv/loadbalancer/v1/inner
    cloud/bitbucket/private-api/yandex/cloud/priv/loadbalancer/v1
    cloud/bitbucket/private-api/yandex/cloud/priv/loadbalancer/v1alpha/console
    cloud/bitbucket/private-api/yandex/cloud/priv/loadbalancer/v1alpha/inner
    cloud/bitbucket/private-api/yandex/cloud/priv/loadbalancer/v1alpha
    cloud/bitbucket/private-api/yandex/cloud/priv/locator/v1
    cloud/bitbucket/private-api/yandex/cloud/priv/logs/v1/inner
    cloud/bitbucket/private-api/yandex/cloud/priv/logs/v1
    cloud/bitbucket/private-api/yandex/cloud/priv/marketplace/v1/license
    cloud/bitbucket/private-api/yandex/cloud/priv/marketplace/v1/metering
    cloud/bitbucket/private-api/yandex/cloud/priv/marketplace/v1alpha1/console
    cloud/bitbucket/private-api/yandex/cloud/priv/marketplace/v1alpha1/private
    cloud/bitbucket/private-api/yandex/cloud/priv/marketplace/v1alpha1
    cloud/bitbucket/private-api/yandex/cloud/priv/mdb/clickhouse/v1/config
    cloud/bitbucket/private-api/yandex/cloud/priv/mdb/clickhouse/v1/console
    cloud/bitbucket/private-api/yandex/cloud/priv/mdb/clickhouse/v1
    cloud/bitbucket/private-api/yandex/cloud/priv/mdb/elasticsearch/v1/config
    cloud/bitbucket/private-api/yandex/cloud/priv/mdb/elasticsearch/v1
    cloud/bitbucket/private-api/yandex/cloud/priv/mdb/kafka/v1
    cloud/bitbucket/private-api/yandex/cloud/priv/mdb/mongodb/v1/config
    cloud/bitbucket/private-api/yandex/cloud/priv/mdb/mongodb/v1/console
    cloud/bitbucket/private-api/yandex/cloud/priv/mdb/mongodb/v1
    cloud/bitbucket/private-api/yandex/cloud/priv/mdb/mysql/v1/config
    cloud/bitbucket/private-api/yandex/cloud/priv/mdb/mysql/v1/console
    cloud/bitbucket/private-api/yandex/cloud/priv/mdb/mysql/v1
    cloud/bitbucket/private-api/yandex/cloud/priv/mdb/mysql/v1alpha/config
    cloud/bitbucket/private-api/yandex/cloud/priv/mdb/mysql/v1alpha/console
    cloud/bitbucket/private-api/yandex/cloud/priv/mdb/mysql/v1alpha
    cloud/bitbucket/private-api/yandex/cloud/priv/mdb/postgresql/v1/config
    cloud/bitbucket/private-api/yandex/cloud/priv/mdb/postgresql/v1/console
    cloud/bitbucket/private-api/yandex/cloud/priv/mdb/postgresql/v1
    cloud/bitbucket/private-api/yandex/cloud/priv/mdb/redis/v1/config
    cloud/bitbucket/private-api/yandex/cloud/priv/mdb/redis/v1/console
    cloud/bitbucket/private-api/yandex/cloud/priv/mdb/redis/v1
    cloud/bitbucket/private-api/yandex/cloud/priv/mdb/sqlserver/v1alpha/config
    cloud/bitbucket/private-api/yandex/cloud/priv/mdb/sqlserver/v1alpha/console
    cloud/bitbucket/private-api/yandex/cloud/priv/mdb/sqlserver/v1alpha
    cloud/bitbucket/private-api/yandex/cloud/priv/mdb/v1/console
    cloud/bitbucket/private-api/yandex/cloud/priv/mdb/v1/support
    cloud/bitbucket/private-api/yandex/cloud/priv/mdb/v1
    cloud/bitbucket/private-api/yandex/cloud/priv/mdb/v2
    cloud/bitbucket/private-api/yandex/cloud/priv/microcosm/fakecloud/v1
    cloud/bitbucket/private-api/yandex/cloud/priv/microcosm/instancegroup/v1/inner
    cloud/bitbucket/private-api/yandex/cloud/priv/microcosm/instancegroup/v1
    cloud/bitbucket/private-api/yandex/cloud/priv/monitoring/v2
    cloud/bitbucket/private-api/yandex/cloud/priv/oauth/v1
    cloud/bitbucket/private-api/yandex/cloud/priv/operation
    cloud/bitbucket/private-api/yandex/cloud/priv/platform/alb/v1/inner
    cloud/bitbucket/private-api/yandex/cloud/priv/platform/alb/v1
    cloud/bitbucket/private-api/yandex/cloud/priv/platform/jaegermeister/v1
    cloud/bitbucket/private-api/yandex/cloud/priv/quota
    cloud/bitbucket/private-api/yandex/cloud/priv/reference
    cloud/bitbucket/private-api/yandex/cloud/priv/resourcemanager/v1/console
    cloud/bitbucket/private-api/yandex/cloud/priv/resourcemanager/v1/transitional
    cloud/bitbucket/private-api/yandex/cloud/priv/resourcemanager/v1
    cloud/bitbucket/private-api/yandex/cloud/priv/serverless/apigateway/v1
    cloud/bitbucket/private-api/yandex/cloud/priv/serverless/functions/v1/inner
    cloud/bitbucket/private-api/yandex/cloud/priv/serverless/functions/v1
    cloud/bitbucket/private-api/yandex/cloud/priv/serverless/mdbproxy/v1
    cloud/bitbucket/private-api/yandex/cloud/priv/serverless/triggers/v1/inner
    cloud/bitbucket/private-api/yandex/cloud/priv/serverless/triggers/v1
    cloud/bitbucket/private-api/yandex/cloud/priv/servicecontrol/v1
    cloud/bitbucket/private-api/yandex/cloud/priv/storage/extension/v1
    cloud/bitbucket/private-api/yandex/cloud/priv/support/v1/console
    cloud/bitbucket/private-api/yandex/cloud/priv/support/v1/private
    cloud/bitbucket/private-api/yandex/cloud/priv/support/v1
    cloud/bitbucket/private-api/yandex/cloud/priv/vpc/v1/inner
    cloud/bitbucket/private-api/yandex/cloud/priv/vpc/v1
    cloud/bitbucket/private-api/yandex/cloud/priv
    cloud/bitbucket/private-api/yandex/cloud/priv/ydb/v1
)

IF (OS_LINUX)
    IF (OS_SDK != "ubuntu-12")
        PEERDIR(
            contrib/python/cysystemd
        )
    ENDIF()
ENDIF ()

PY_SRCS(
    TOP_LEVEL
    yc_common/api/__init__.py
    yc_common/api/authentication.py
    yc_common/api/authorization.py
    yc_common/api/authorization_v2.py
    yc_common/api/handling.py
    yc_common/api/middlewares/__init__.py
    yc_common/api/middlewares/aiohttp.py
    yc_common/api/middlewares/flask.py
    yc_common/api/request_context.py
    yc_common/arcadia/__init__.py
    yc_common/arcadia/fs.py
    yc_common/backoff.py
    yc_common/clients/__init__.py
    yc_common/clients/access_service.py
    yc_common/clients/api.py
    yc_common/clients/billing.py
    yc_common/clients/common.py
    yc_common/clients/compute.py
    yc_common/clients/compute_node.py
    yc_common/clients/compute_private.py
    yc_common/clients/compute_worker.py
    yc_common/clients/contrail/__init__.py
    yc_common/clients/contrail/client.py
    yc_common/clients/contrail/context.py
    yc_common/clients/contrail/exceptions.py
    yc_common/clients/contrail/resource.py
    yc_common/clients/contrail/schema/__init__.py
    yc_common/clients/contrail/schema/_v_1_10.py
    yc_common/clients/contrail/schema/_v_2_21.py
    yc_common/clients/contrail/schema/_v_3_0.py
    yc_common/clients/contrail/schema/_v_3_1.py
    yc_common/clients/contrail/schema/_v_3_2.py
    yc_common/clients/contrail/schema/exceptions.py
    yc_common/clients/contrail/schema/schema.py
    yc_common/clients/contrail/utils.py
    yc_common/clients/grpc/__init__.py
    yc_common/clients/grpc/base.py
    yc_common/clients/grpc/health_check.py
    yc_common/clients/grpc/load_balancer.py
    yc_common/clients/grpc/network.py
    yc_common/clients/grpc/target_group.py
    yc_common/clients/identity_private.py
    yc_common/clients/identity_private_v3.py
    yc_common/clients/identity_v2.py
    yc_common/clients/identity_v3.py
    yc_common/clients/infra.py
    yc_common/clients/instance_metadata.py
    yc_common/clients/juggler.py
    yc_common/clients/kikimr/__init__.py
    yc_common/clients/kikimr/client.py
    yc_common/clients/kikimr/config.py
    yc_common/clients/kikimr/exceptions.py
    yc_common/clients/kikimr/kikimr_types.py
    yc_common/clients/kikimr/metrics.py
    yc_common/clients/kikimr/sql.py
    yc_common/clients/kikimr/util.py
    yc_common/clients/l3manager.py
    yc_common/clients/marketplace_private.py
    yc_common/clients/models/__init__.py
    yc_common/clients/models/base.py
    yc_common/clients/models/billing/__init__.py
    yc_common/clients/models/billing/billing_account.py
    yc_common/clients/models/billing/cloud.py
    yc_common/clients/models/billing/contract.py
    yc_common/clients/models/billing/grant_policy.py
    yc_common/clients/models/billing/monetary_grant_offer.py
    yc_common/clients/models/billing/person.py
    yc_common/clients/models/billing/pricing.py
    yc_common/clients/models/billing/publisher_account.py
    yc_common/clients/models/billing/revenue_report.py
    yc_common/clients/models/billing/sku.py
    yc_common/clients/models/commitments.py
    yc_common/clients/models/console.py
    yc_common/clients/models/disks.py
    yc_common/clients/models/grpc/__init__.py
    yc_common/clients/models/grpc/common.py
    yc_common/clients/models/grpc/forwarding_group.py
    yc_common/clients/models/grpc/health_check_group.py
    yc_common/clients/models/images.py
    yc_common/clients/models/instances.py
    yc_common/clients/models/labels.py
    yc_common/clients/models/network_load_balancers.py
    yc_common/clients/models/networks.py
    yc_common/clients/models/operating_system.py
    yc_common/clients/models/operations.py
    yc_common/clients/models/placement_groups.py
    yc_common/clients/models/quotas.py
    yc_common/clients/models/snapshots.py
    yc_common/clients/models/solomon.py
    yc_common/clients/models/target_groups.py
    yc_common/clients/models/zones.py
    yc_common/clients/network/__init__.py
    yc_common/clients/network/billing.py
    yc_common/clients/network/client.py
    yc_common/clients/network/config.py
    yc_common/clients/network/loader.py
    yc_common/clients/network/models/__init__.py
    yc_common/clients/network/models/network_acl.py
    yc_common/clients/network/models/route_table.py
    yc_common/clients/network/models/virtual_network.py
    yc_common/clients/network/naming.py
    yc_common/clients/racktables.py
    yc_common/clients/sample.py
    yc_common/clients/scheduler.py
    yc_common/clients/snapshot.py
    yc_common/clients/teamcity.py
    yc_common/clients/tvm.py
    yc_common/config.py
    yc_common/constants.py
    yc_common/context.py
    yc_common/counting_generator.py
    yc_common/crypto.py
    yc_common/db_migration/__init__.py
    yc_common/db_migration/utils.py
    yc_common/exceptions.py
    yc_common/fields.py
    yc_common/formatting.py
    yc_common/grpc_metrics.py
    yc_common/ids.py
    yc_common/logging.py
    yc_common/metrics.py
    yc_common/misc.py
    yc_common/models.py
    yc_common/numeric_range_allocator.py
    yc_common/paging.py
    yc_common/resources.py
    yc_common/swagger_writer.py
    yc_common/system.py
    yc_common/test/__init__.py
    yc_common/test/core.py
    yc_common/throttler.py
    yc_common/tskv.py
    yc_common/unified_validation.py
    yc_common/validation.py
    yc_common/ya_clients/__init__.py
    yc_common/ya_clients/abc.py
    yc_common/ya_clients/cauth.py
    yc_common/ya_clients/common.py
    yc_common/ya_clients/exception.py
    yc_common/ya_clients/staff.py
)

RESOURCE(
    yc_common/test/test_resource.txt package_resources/yc_common/test/test_resource.txt
)

END()

RECURSE_FOR_TESTS(tests)
