#!/bin/sh
# This script is actually ran with /bin/sh -eu

_scenario() {
    INVI = marakasov-laptop:10001
    GLOB = marakasov-laptop:10001 cpu=1/3

    INVI start

    GLOB target1: start
    GLOB target2: start
    GLOB target3: start
    GLOB target4: start
    GLOB target5: start
    GLOB target6: start

    INVI end : target1 target2 target3 target4 target5 target6
}

echo "Args:" "$@"
echo "Date:" `date`
echo "Host:" `hostname`
echo " Sys:" `uname -a`
echo "Load:" `uptime`
echo "Cred:" `id`
env | sort | sed -e '1 s|^| Env: |; 2,$ s|^|      |'
echo "======================================================================"
echo "=== `date`: Running $1 on `hostname`"
echo "======================================================================"
sleep 1
true
echo "======================================================================"
echo "=== `date`: Finished $1 on `hostname`"
echo "======================================================================"
