export MDB_PROJECT_NAME=mdb-health
export MDB_PROJECT_CMD_PATH=cmd/${MDB_PROJECT_NAME}/${MDB_PROJECT_NAME}

include ../Makefile.defs

run:
	${MDB_PROJECT_CMD_PATH} --scheme=http --port=12345

.PHONY: run
