#!/bin/bash

exec 2>&1
while [ 1 ]
do
    while [ ! -f /var/tmp/cocaine-warmup_deny ]
    do
        sleep 15
    done
    sleep 60
    echo "check then cocaine-runtime is runing"
    while [ `/usr/local/bin/cocaine-depth.py | sed 's/1;\ error\ while\ connect\ to\ service\ node/2;pidor/g' | grep "^2;" | wc -l` -ne 0 ]
    do
        sleep 30
    done
    sleep 15
    echo "check then all apps is spooling"
    while [ `cocaine-tool i | grep spooling | wc -l` -ne 0 ]
    do
        sleep 30
    done
    rm -v /var/tmp/cocaine-warmup_deny
    /usr/local/bin/cocaine-warmup.py
    echo "open 10053 port"
    curl -XDELETE localhost:1/api/firewall/deny -d '{ "port": 10053 }'
    iptables -F INPUT 
    ip6tables -F INPUT
done

