GRANT USAGE ON SCHEMA s3 TO s3api;
GRANT ALL ON ALL SEQUENCES IN SCHEMA s3 TO s3api;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA s3 TO s3api;

GRANT USAGE ON SCHEMA v1_code TO s3api;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA v1_code TO s3api;

GRANT USAGE ON SCHEMA v1_impl TO s3api;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA v1_impl TO s3api;
