GRANT USAGE ON SCHEMA s3 TO s3maintain;
GRANT ALL ON ALL SEQUENCES IN SCHEMA s3 TO s3maintain;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA s3 TO s3maintain;

GRANT USAGE ON SCHEMA v1_code TO s3maintain;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA v1_code TO s3maintain;

GRANT USAGE ON SCHEMA v1_impl TO s3maintain;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA v1_impl TO s3maintain;
