PARAMS = {
    'TARGET_PAID_COND': 0.01,
    'MIN_CALIBR_PROBA': 0.001,
    'MAX_CALIBR_PROBA': 0.851,
    'PRED_PROBA_BRD': 0.02,
    'CONF_INTERVAL': 0.95,
    'DAYS_COMPANIES': 7,
    'DAYS_INDIVIDUAL': 14
}
