prod_model_colnames = [
    'billing_account_id',
    'billing_record_msk_date',
    'next_14d_cons',
    'sku_subservice_is_used_space',
    'prev_7d_cons',
    'billing_record_total_rub',
    'prev_30d_cons',
    'prev_1d_cons',
    'vm_cores_avg',
    'prev_45d_cons',
    'billing_record_credit_rub',
    'prev_21d_cons',
    'prev_14d_cons',
    'sku_group_is_Infrastructure',
    'prev_15d_grants',
    'sku_subservice_is_nbs_ssd',
    'sku_subservice_is_fips',
    'sku_subservice_is_snapshot',
    'sku_service_is_storage',
    'sku_subservice_is_ram',
    'sku_service_is_support',
    'prev_15d_cons',
    'sku_subservice_is_windows',
    'sku_group_is_Data_Storage_and_Analytics',
    'sku_service_is_marketplace',
    'sku_group_is_Support',
    'sku_service_is_mdb',
    'prev_14d_grants',
    # 'prev_1d_grants',
    # 'sku_service_is_compute',
    # 'sku_group_is_ML_and_AI',
    # 'sku_subservice_is_nbs_hdd',
    # 'sku_group_is_Marketplace',
    # 'vm_count',
    # 'sku_subservice_is_cpu',
    # 'sku_service_is_cloud_ai',
    # 'vm_age_days_min',
    # 'billing_record_cost_rub',
    # 'sku_subservice_name_is_other',
    # 'sku_service_is_cr',
    # 'days_from_created',
    # 'vm_age_days_sum',
    # 'vm_memory_sum',
    # 'prev_21d_grants',
    # 'vm_memory_avg',
    # 'sku_subservice_is_standard',
    # 'vm_cores_sum',
    # 'sku_service_is_nlb',
    # 'prev_7d_grants',
    # 'vm_age_days_max',
    # 'sku_subservice_is_postgres',
    # 'sku_subservice_is_clickhouse',
    # 'sku_service_is_cloud_network',
    # 'sku_service_is_kms',
    # 'vm_cores_max',
    # 'sku_service_is_mk8s',
    # 'vm_age_days_avg',
    # 'prev_45d_grants',
    # 'days_not_used',
    # 'sku_subservice_is_egress_inet',
    # 'vm_memory_min',
    # 'vm_cores_min',
    # 'sku_subservice_is_nlb',
    # 'sku_subservice_is_speech',
    # 'sku_service_is_iot',
    # 'vm_memory_max',
    # 'prev_30d_grants',
    # 'sku_subservice_is_get',
    # 'sku_service_is_monitoring',
    # 'sku_subservice_is_mysql',
    # 'billing_account_is_crm_account',
    # 'billing_account_person_type',
    # 'sku_subservice_is_put',
    # 'billing_account_state',
    # 'sku_subservice_is_storage'
]
