ARG fluent_bit_version=1.9.6
FROM \
    cr.yandex/crpj00snqdgtmd18j8uj/fluent/fluent-bit:${fluent_bit_version}

ARG fluent_bit_version
ARG storage_src=https://storage.cloud-preprod.yandex.net/fluentbit/ycp-logging.so

ADD ${storage_src} /fluent-bit/bin/ycp-logging.so
COPY fluent-bit.conf fluent-bit/etc/fluent-bit.conf

ENTRYPOINT ["/fluent-bit/bin/fluent-bit", "-e", "/fluent-bit/bin/ycp-logging.so"]
CMD ["-c", "/fluent-bit/etc/fluent-bit.conf"]
