# solution based on ideas https://github.com/9seconds/docker-vagrant

Vagrant.configure(2) do |config|
  config.vm.provider "docker" do |docker|
    docker.build_dir = "./docker/"
    docker.remains_running = true
    docker.has_ssh = true
  end

  ## mount your salt states to '/srv/salt' dir
  config.vm.synced_folder "./", "/srv/salt/"
  ####config.vm.synced_folder "./pillar_preprod/", "/srv/pillar/"

  ## install salt package and dependencies
  config.vm.provision :salt do |salt|
    salt.masterless = true
    salt.no_minion = false
    salt.run_highstate = false
  end

  config.vm.provision "shell" do |s|
    ## Set your salt states to test as  last args,
    # s.inline = "salt-call -l debug --local state.sls <state file names without '.sls'>"

    # for example
    s.inline = "salt-call -l debug --local state.sls sethostname"
  end
end


