OWNER(g:cloud-nbs)

RECURSE(
    local
    local-auth
    local-checkpoint
    local-discovery
    local-edgecase
    local-emergency
    local-encryption
    local-endpoints
    local-metrics
    local-mirror
    local-nemesis
    local-newfeatures
    local-nonrepl
    local-null
    local-overflow
    local-overlay
    local-endpoints-spdk
    local-throttling
    local-v2
)
