#!/bin/sh

usage()
{
    echo
    echo "signfile textfile"
    echo
    exit 1
}

if [ -z "$1" ]; then
    usage
else
    file=$1
fi

echo "DDD $file"

sudo gpg --default-key "Russian Fedora repository (Fedora - free)" --sign --digest-algo SHA256 --armor -t $file
sudo mv $file.asc $file
