Document: yandex-conf-repo-media-common-stable
Title: Debian yandex-conf-repo-media-common-stable Manual
Author: <insert document author here>
Abstract: This manual describes what yandex-conf-repo-media-common-stable is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/yandex-conf-repo-media-common-stable/yandex-conf-repo-media-common-stable.sgml.gz

Format: postscript
Files: /usr/share/doc/yandex-conf-repo-media-common-stable/yandex-conf-repo-media-common-stable.ps.gz

Format: text
Files: /usr/share/doc/yandex-conf-repo-media-common-stable/yandex-conf-repo-media-common-stable.text.gz

Format: HTML
Index: /usr/share/doc/yandex-conf-repo-media-common-stable/html/index.html
Files: /usr/share/doc/yandex-conf-repo-media-common-stable/html/*.html
