use hahn;

--`//home/cloud_analytics/cubes/acquisition_cube/cube_with_marketing_attribution`
DEFINE ACTION $cube_with_marketing_attribution($path) AS
    INSERT INTO $path WITH TRUNCATE 
    SELECT
        `cube`.`billing_account_id` as billing_account_id,
        `account_name`,
        -- `active_grant_ids`,
        -- `active_grants`,
        -- `ad_block`,
        -- `age`,
        -- `all`,
        -- `architect`,
        -- `architect_actual`,
        -- `area`,
        -- `ba_currency`,
        -- `ba_name`,
        -- `ba_payment_cycle_type`,
        -- `ba_payment_cycle_type_actual`,
        `ba_person_type`,
        `ba_person_type_actual`,
        `ba_state`,
        `ba_state_actual`,
        `ba_type`,
        `ba_type_actual`,
        `ba_usage_status`,
        `ba_usage_status_actual`,
        -- `balance`,
        -- `balance_actual`,
        -- `balance_long_name`,
        -- `balance_name`,
        -- `billing_record_pricing_unit`,
        -- `billing_record_usage_unit`,
        -- `block_reason`,
        -- `board_segment`,
        -- `board_segment_actual`,
        -- `br_cost`,
        -- `br_cost_rub`,
        -- `br_cost_rub_vat`,
        -- `br_credit`,
        -- `br_credit_cud`,
        -- `br_credit_cud_rub`,
        -- `br_credit_cud_rub_vat`,
        -- `br_credit_disabled`,
        -- `br_credit_disabled_rub`,
        -- `br_credit_disabled_rub_vat`,
        -- `br_credit_grant`,
        -- `br_credit_grant_rub`,
        -- `br_credit_grant_rub_vat`,
        -- `br_credit_rub`,
        -- `br_credit_rub_vat`,
        -- `br_credit_service`,
        -- `br_credit_service_rub`,
        -- `br_credit_service_rub_vat`,
        -- `br_credit_trial`,
        -- `br_credit_trial_rub`,
        -- `br_credit_trial_rub_vat`,
        -- `br_credit_volume_incentive`,
        -- `br_credit_volume_incentive_rub`,
        -- `br_credit_volume_incentive_rub_vat`,
        -- `br_pricing_quantity`,
        -- `br_total`,
        -- `br_var_reward`,
        -- `br_var_reward_rub`,
        -- `br_var_reward_rub_vat`,
        -- `city`,
        -- `client_ip`,
        `cloud_id`,
        -- `cloud_name`,
        -- `cloud_status`,
        -- `compute_core_fraction`,
        -- `compute_cores`,
        -- `compute_memory`,
        -- `compute_platform_id`,
        -- `compute_product_ids`,
        -- `compute_public_fips`,
        -- `compute_sockets`,
        -- `core_fraction`,
        -- `core_fraction_number`,
        -- `core_type`,
        -- `cores`,
        -- `cores_number`,
        -- `country`,
        `crm_account_architect`,
        `crm_account_architect_current`,
        `crm_account_bus_dev`,
        `crm_account_bus_dev_current`,
        `crm_account_name`,
        `crm_account_owner`,
        `crm_account_owner_current`,
        `crm_account_partner_manager`,
        `crm_account_partner_manager_current`,
        `crm_account_sales`,
        `crm_account_sales_current`,
        `crm_account_segment`,
        `crm_account_segment_current`,
        `crm_account_tags`,
        -- `database`,
        -- `device_model`,
        -- `device_type`,
        -- `duration`,
        -- `email`,
        `event`,
        `event_time`,
        `first_ba_created_datetime`,
        -- `first_first_paid_consumption_datetime`,
        -- `first_first_trial_consumption_datetime`,
        -- `first_name`,
        -- `general_interests`,
        -- `grant_amount`,
        -- `grant_amounts`,
        -- `grant_end_times`,
        -- `grant_source_ids`,
        -- `grant_sources`,
        -- `grant_start_times`,
        -- `hits`,
        -- `income`,
        -- `interests`,
        -- `is_bounce`,
        -- `is_committed`,
        -- `is_corporate_card`,
        `is_fraud`,
        -- `is_iot`,
        -- `is_iot_actual`,
        -- `is_isv`,
        -- `is_isv_actual`,
        -- `is_reserve`,
        -- `is_robot`,
        -- `is_var`,
        -- `is_var_actual`,
        -- `is_verified`,
        -- `is_verified_actual`,
        -- `last_name`,
        -- `login`,
        -- `mail_billing`,
        -- `mail_event`,
        -- `mail_feature`,
        -- `mail_info`,
        -- `mail_promo`,
        -- `mail_tech`,
        -- `mail_testing`,
        `marketing_touched_events_count`,
        `marketing_touched_events_list`,
        -- `master_account_id`,
        -- `mdb_cluster_id`,
        -- `mdb_cluster_type`,
        -- `mdb_compute_instance_id`,
        -- `mdb_core_fraction`,
        -- `mdb_cores`,
        -- `mdb_disk_size`,
        -- `mdb_disk_type_id`,
        -- `mdb_memory`,
        -- `mdb_online`,
        -- `mdb_platform_id`,
        -- `mdb_public_ip`,
        -- `mdb_resource_preset_id`,
        -- `mdb_roles`,
        -- `mdb_software_accelerated_network_cores`,
        -- `metrika_last_sign_touch_channel`,
        -- `metrika_last_sign_touch_channel_marketing_influenced`,
        -- `metrika_last_sign_touch_trafic_source`,
        -- `metrika_last_sign_touch_utm_campaign`,
        -- `metrika_last_sign_touch_utm_content`,
        -- `metrika_last_sign_touch_utm_medium`,
        -- `metrika_last_sign_touch_utm_source`,
        -- `metrika_last_sign_touch_utm_term`,
        -- `mk8s_relevant`,
        -- `mobile_phone_vendor`,
        -- `nbs_size`,
        -- `nbs_type`,
        -- `os`,
        -- `page_views`,
        -- `phone`,
        -- `platform`,
        -- `potential`,
        -- `potential_actual`,
        -- `preemptible`,
        -- `puid`,
        -- `ram`,
        -- `ram_number`,
        -- `real_consumption`,
        `real_consumption_vat`,
        -- `referer`,
        -- `remote_ip`,
        -- `resolution_depth`,
        -- `resolution_height`,
        -- `resolution_width`,
        `sales_name`,
        -- `sales_name_actual`,
        -- `search_phrase`,
        `segment`,
        `segment_actual`,
        `service_group`,
        `service_id`,
        `service_long_name`,
        `service_name`,
        `session_start_time`,
        -- `sex`,
        `sku_id`,
        `sku_lazy`,
        `sku_name`,
        -- `start_url`,
        `subservice_name`,
        -- `total`,
        -- `total_visits`,
        -- `trial_consumption`,
        `trial_consumption_vat`,
        -- `unblock_reason`,
        -- `usd_rur_quote`,
        -- `user_settings_email`,
        
        `vm_origin`,
        -- `window_client_height`
        
        coalesce(weights.marketing_attribution_event_id, 0) AS marketing_attribution_event_id,
        coalesce(weights.marketing_attribution_event_type, 'Unmatched') AS marketing_attribution_event_type,
        coalesce(weights.marketing_attribution_event_time, 0) AS marketing_attribution_event_time,
        coalesce(weights.marketing_attribution_channel, 'Unmatched') AS marketing_attribution_channel,
        coalesce(weights.marketing_attribution_channel_marketing_influenced, 'Unmatched') AS marketing_attribution_channel_marketing_influenced,
        coalesce(weights.marketing_attribution_utm_campaign, 'Unmatched') AS marketing_attribution_utm_campaign,
        coalesce(weights.marketing_attribution_utm_campaign_id, 'Unmatched') AS marketing_attribution_utm_campaign_id,
        coalesce(weights.marketing_attribution_utm_campaign_name, 'Unmatched') AS marketing_attribution_utm_campaign_name,
        coalesce(weights.marketing_attribution_utm_campaign_name_1, 'Unmatched') AS marketing_attribution_utm_campaign_name_1,
        coalesce(weights.marketing_attribution_utm_campaign_name_2, 'Unmatched') AS marketing_attribution_utm_campaign_name_2,
        coalesce(weights.marketing_attribution_utm_campaign_name_3, 'Unmatched') AS marketing_attribution_utm_campaign_name_3,
        coalesce(weights.marketing_attribution_utm_campaign_name_4, 'Unmatched') AS marketing_attribution_utm_campaign_name_4,
        coalesce(weights.marketing_attribution_utm_campaign_name_5, 'Unmatched') AS marketing_attribution_utm_campaign_name_5,
        coalesce(weights.marketing_attribution_utm_campaign_name_6, 'Unmatched') AS marketing_attribution_utm_campaign_name_6,
        coalesce(weights.marketing_attribution_utm_campaign_name_7, 'Unmatched') AS marketing_attribution_utm_campaign_name_7,
        coalesce(weights.marketing_attribution_utm_source, 'Unmatched') AS marketing_attribution_utm_source,
        coalesce(weights.marketing_attribution_utm_medium, 'Unmatched') AS marketing_attribution_utm_medium,
        coalesce(weights.marketing_attribution_utm_term, 'Unmatched') AS marketing_attribution_utm_term,
        -- coalesce(weights.marketing_attribution_counter_id_serial, 0) AS marketing_attribution_counter_id_serial,
        coalesce(weights.marketing_attribution_event_first_weight, 1.0) AS marketing_attribution_event_first_weight,
        coalesce(weights.marketing_attribution_event_last_weight, 1.0) AS marketing_attribution_event_last_weight,
        coalesce(weights.marketing_attribution_event_uniform_weight, 1.0) AS marketing_attribution_event_uniform_weight,
        coalesce(weights.marketing_attribution_event_u_shape_weight, 1.0) AS marketing_attribution_event_u_shape_weight,
        coalesce(weights.marketing_attribution_event_exp_7d_half_life_time_decay_weight, 1.0) AS marketing_attribution_event_exp_7d_half_life_time_decay_weight

    FROM `//home/cloud_analytics/cubes/acquisition_cube/cube` as `cube`
    LEFT JOIN `//home/cloud_analytics/marketing/attribution/attribution_flat` AS weights
    ON `cube`.billing_account_id = weights.billing_account_id
END DEFINE;

EXPORT $cube_with_marketing_attribution;
