#include <{{OWN_HEADER_INCLUDE_PATH}}>{{#IMPORT_SECTION}}
{{#IMPORT}}
#include {{IMPORT_PATH}}{{/IMPORT}}{{/IMPORT_SECTION}}
{{#NAMESPACE}}
namespace {{NAME}} {{{/NAMESPACE}}{{#CHILD}}

{{>CHILD}}{{/CHILD}}

{{#CLOSING_NAMESPACE}}} // namespace {{NAME}}{{#CLOSING_NAMESPACE_separator}}
{{/CLOSING_NAMESPACE_separator}}{{/CLOSING_NAMESPACE}}{{#GUID_REGISTRATION}}

REGISTER_GUID({{STRUCT_FULL_NAME}});
{{/GUID_REGISTRATION}}
