# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from yc_snapshot_client.snapshot_rpc import snapshot_python_pb2 as yc__snapshot__client_dot_snapshot__rpc_dot_snapshot__python__pb2


class SnapshotServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetMap = channel.unary_stream(
        '/snapshot_rpc.SnapshotService/GetMap',
        request_serializer=yc__snapshot__client_dot_snapshot__rpc_dot_snapshot__python__pb2.MapRequest.SerializeToString,
        response_deserializer=yc__snapshot__client_dot_snapshot__rpc_dot_snapshot__python__pb2.MapResponse.FromString,
        )
    self.Create = channel.unary_unary(
        '/snapshot_rpc.SnapshotService/Create',
        request_serializer=yc__snapshot__client_dot_snapshot__rpc_dot_snapshot__python__pb2.CreateRequest.SerializeToString,
        response_deserializer=yc__snapshot__client_dot_snapshot__rpc_dot_snapshot__python__pb2.CreateResponse.FromString,
        )
    self.Read = channel.unary_unary(
        '/snapshot_rpc.SnapshotService/Read',
        request_serializer=yc__snapshot__client_dot_snapshot__rpc_dot_snapshot__python__pb2.ReadRequest.SerializeToString,
        response_deserializer=yc__snapshot__client_dot_snapshot__rpc_dot_snapshot__python__pb2.ReadResponse.FromString,
        )
    self.Write = channel.unary_unary(
        '/snapshot_rpc.SnapshotService/Write',
        request_serializer=yc__snapshot__client_dot_snapshot__rpc_dot_snapshot__python__pb2.WriteRequest.SerializeToString,
        response_deserializer=yc__snapshot__client_dot_snapshot__rpc_dot_snapshot__python__pb2.Status.FromString,
        )
    self.Commit = channel.unary_unary(
        '/snapshot_rpc.SnapshotService/Commit',
        request_serializer=yc__snapshot__client_dot_snapshot__rpc_dot_snapshot__python__pb2.CommitRequest.SerializeToString,
        response_deserializer=yc__snapshot__client_dot_snapshot__rpc_dot_snapshot__python__pb2.Status.FromString,
        )
    self.Move = channel.unary_unary(
        '/snapshot_rpc.SnapshotService/Move',
        request_serializer=yc__snapshot__client_dot_snapshot__rpc_dot_snapshot__python__pb2.MoveRequest.SerializeToString,
        response_deserializer=yc__snapshot__client_dot_snapshot__rpc_dot_snapshot__python__pb2.Status.FromString,
        )
    self.Copy = channel.unary_unary(
        '/snapshot_rpc.SnapshotService/Copy',
        request_serializer=yc__snapshot__client_dot_snapshot__rpc_dot_snapshot__python__pb2.CopyRequest.SerializeToString,
        response_deserializer=yc__snapshot__client_dot_snapshot__rpc_dot_snapshot__python__pb2.CopyResponse.FromString,
        )
    self.GetTaskStatus = channel.unary_unary(
        '/snapshot_rpc.SnapshotService/GetTaskStatus',
        request_serializer=yc__snapshot__client_dot_snapshot__rpc_dot_snapshot__python__pb2.GetTaskStatusRequest.SerializeToString,
        response_deserializer=yc__snapshot__client_dot_snapshot__rpc_dot_snapshot__python__pb2.TaskStatus.FromString,
        )
    self.CancelTask = channel.unary_unary(
        '/snapshot_rpc.SnapshotService/CancelTask',
        request_serializer=yc__snapshot__client_dot_snapshot__rpc_dot_snapshot__python__pb2.CancelTaskRequest.SerializeToString,
        response_deserializer=yc__snapshot__client_dot_snapshot__rpc_dot_snapshot__python__pb2.Status.FromString,
        )
    self.DeleteTask = channel.unary_unary(
        '/snapshot_rpc.SnapshotService/DeleteTask',
        request_serializer=yc__snapshot__client_dot_snapshot__rpc_dot_snapshot__python__pb2.DeleteTaskRequest.SerializeToString,
        response_deserializer=yc__snapshot__client_dot_snapshot__rpc_dot_snapshot__python__pb2.Status.FromString,
        )
    self.ListChangedChildren = channel.unary_unary(
        '/snapshot_rpc.SnapshotService/ListChangedChildren',
        request_serializer=yc__snapshot__client_dot_snapshot__rpc_dot_snapshot__python__pb2.ChangedChildrenListRequest.SerializeToString,
        response_deserializer=yc__snapshot__client_dot_snapshot__rpc_dot_snapshot__python__pb2.ChangedChildrenList.FromString,
        )
    self.Ping = channel.unary_unary(
        '/snapshot_rpc.SnapshotService/Ping',
        request_serializer=yc__snapshot__client_dot_snapshot__rpc_dot_snapshot__python__pb2.Status.SerializeToString,
        response_deserializer=yc__snapshot__client_dot_snapshot__rpc_dot_snapshot__python__pb2.Status.FromString,
        )
    self.Delete = channel.unary_unary(
        '/snapshot_rpc.SnapshotService/Delete',
        request_serializer=yc__snapshot__client_dot_snapshot__rpc_dot_snapshot__python__pb2.DeleteRequest.SerializeToString,
        response_deserializer=yc__snapshot__client_dot_snapshot__rpc_dot_snapshot__python__pb2.Status.FromString,
        )
    self.List = channel.unary_unary(
        '/snapshot_rpc.SnapshotService/List',
        request_serializer=yc__snapshot__client_dot_snapshot__rpc_dot_snapshot__python__pb2.ListRequest.SerializeToString,
        response_deserializer=yc__snapshot__client_dot_snapshot__rpc_dot_snapshot__python__pb2.SnapshotList.FromString,
        )
    self.ListBases = channel.unary_unary(
        '/snapshot_rpc.SnapshotService/ListBases',
        request_serializer=yc__snapshot__client_dot_snapshot__rpc_dot_snapshot__python__pb2.BaseListRequest.SerializeToString,
        response_deserializer=yc__snapshot__client_dot_snapshot__rpc_dot_snapshot__python__pb2.SnapshotList.FromString,
        )
    self.Convert = channel.unary_unary(
        '/snapshot_rpc.SnapshotService/Convert',
        request_serializer=yc__snapshot__client_dot_snapshot__rpc_dot_snapshot__python__pb2.ConvertRequest.SerializeToString,
        response_deserializer=yc__snapshot__client_dot_snapshot__rpc_dot_snapshot__python__pb2.ConvertResponse.FromString,
        )
    self.Info = channel.unary_unary(
        '/snapshot_rpc.SnapshotService/Info',
        request_serializer=yc__snapshot__client_dot_snapshot__rpc_dot_snapshot__python__pb2.InfoRequest.SerializeToString,
        response_deserializer=yc__snapshot__client_dot_snapshot__rpc_dot_snapshot__python__pb2.SnapshotInfo.FromString,
        )
    self.Update = channel.unary_unary(
        '/snapshot_rpc.SnapshotService/Update',
        request_serializer=yc__snapshot__client_dot_snapshot__rpc_dot_snapshot__python__pb2.UpdateRequest.SerializeToString,
        response_deserializer=yc__snapshot__client_dot_snapshot__rpc_dot_snapshot__python__pb2.Status.FromString,
        )
    self.Verify = channel.unary_unary(
        '/snapshot_rpc.SnapshotService/Verify',
        request_serializer=yc__snapshot__client_dot_snapshot__rpc_dot_snapshot__python__pb2.VerifyRequest.SerializeToString,
        response_deserializer=yc__snapshot__client_dot_snapshot__rpc_dot_snapshot__python__pb2.VerifyReport.FromString,
        )


class SnapshotServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetMap(self, request, context):
    """Get snapshot chunk map.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Create(self, request, context):
    """Create snapshot.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Read(self, request, context):
    """Read snapshot chunk data.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Write(self, request, context):
    """Write snapshot chunk data.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Commit(self, request, context):
    """Finalize snapshot creation.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Move(self, request, context):
    """Move data from one place to another.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Copy(self, request, context):
    """Shallow-copy snapshot (copy references without copying data).
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def GetTaskStatus(self, request, context):
    """Get task status.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def CancelTask(self, request, context):
    """Cancel running task.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def DeleteTask(self, request, context):
    """Delete task to free resources.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ListChangedChildren(self, request, context):
    """List children changed due to snapshot removal.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Ping(self, request, context):
    """Healthcheck for balancer
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Delete(self, request, context):
    """Delete snapshot.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def List(self, request, context):
    """Get snapshot list by parameters.

    There are two modes of operation:
    1. (CURSOR) Neither "limit" nor "sort" is passed.
    You get a predefined number of snapshots.
    You also get "next_cursor", which can be passed to subsequent calls to get next part of data and a new cursor.

    NOTE: all query parameters must be passed as before, along with cursor

    Example:
    Request: GET /v1/projects/P1/snapshots?search_prefix=yyy
    Response: {"next_cursor":"ccc", "result": [...]}
    Request: GET /v1/projects/P1/snapshots?search_prefix=yyy&cursor=ccc

    2. (LIMIT) "limit" is specified. NOTE: "sort" requires "limit".
    You get up to "limit" snapshots sorted by "sort".
    If there are more snapshots matching the criteria then "has_more" is set to true.
    You can increase the limit for subsequent calls.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ListBases(self, request, context):
    """Get the list of base snapshots.

    Get the list of base and differential snapshots
    starting from direct predecessor.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Convert(self, request, context):
    """Import snapshot from S3.

    You can import a snapshot in different formats.
    Snapshot will be converted to our format.

    NOTE: This request only starts conversion process.
    You must check freshly created snapshot until its "state"."code"
    changes from "creating" to "ready" or "failed".
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Info(self, request, context):
    """Get snapshot properties.

    Get snapshot properties by id.
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Update(self, request, context):
    """Update specified fields in snapshot
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Verify(self, request, context):
    """Verify checksum for snapshot and chunks
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_SnapshotServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetMap': grpc.unary_stream_rpc_method_handler(
          servicer.GetMap,
          request_deserializer=yc__snapshot__client_dot_snapshot__rpc_dot_snapshot__python__pb2.MapRequest.FromString,
          response_serializer=yc__snapshot__client_dot_snapshot__rpc_dot_snapshot__python__pb2.MapResponse.SerializeToString,
      ),
      'Create': grpc.unary_unary_rpc_method_handler(
          servicer.Create,
          request_deserializer=yc__snapshot__client_dot_snapshot__rpc_dot_snapshot__python__pb2.CreateRequest.FromString,
          response_serializer=yc__snapshot__client_dot_snapshot__rpc_dot_snapshot__python__pb2.CreateResponse.SerializeToString,
      ),
      'Read': grpc.unary_unary_rpc_method_handler(
          servicer.Read,
          request_deserializer=yc__snapshot__client_dot_snapshot__rpc_dot_snapshot__python__pb2.ReadRequest.FromString,
          response_serializer=yc__snapshot__client_dot_snapshot__rpc_dot_snapshot__python__pb2.ReadResponse.SerializeToString,
      ),
      'Write': grpc.unary_unary_rpc_method_handler(
          servicer.Write,
          request_deserializer=yc__snapshot__client_dot_snapshot__rpc_dot_snapshot__python__pb2.WriteRequest.FromString,
          response_serializer=yc__snapshot__client_dot_snapshot__rpc_dot_snapshot__python__pb2.Status.SerializeToString,
      ),
      'Commit': grpc.unary_unary_rpc_method_handler(
          servicer.Commit,
          request_deserializer=yc__snapshot__client_dot_snapshot__rpc_dot_snapshot__python__pb2.CommitRequest.FromString,
          response_serializer=yc__snapshot__client_dot_snapshot__rpc_dot_snapshot__python__pb2.Status.SerializeToString,
      ),
      'Move': grpc.unary_unary_rpc_method_handler(
          servicer.Move,
          request_deserializer=yc__snapshot__client_dot_snapshot__rpc_dot_snapshot__python__pb2.MoveRequest.FromString,
          response_serializer=yc__snapshot__client_dot_snapshot__rpc_dot_snapshot__python__pb2.Status.SerializeToString,
      ),
      'Copy': grpc.unary_unary_rpc_method_handler(
          servicer.Copy,
          request_deserializer=yc__snapshot__client_dot_snapshot__rpc_dot_snapshot__python__pb2.CopyRequest.FromString,
          response_serializer=yc__snapshot__client_dot_snapshot__rpc_dot_snapshot__python__pb2.CopyResponse.SerializeToString,
      ),
      'GetTaskStatus': grpc.unary_unary_rpc_method_handler(
          servicer.GetTaskStatus,
          request_deserializer=yc__snapshot__client_dot_snapshot__rpc_dot_snapshot__python__pb2.GetTaskStatusRequest.FromString,
          response_serializer=yc__snapshot__client_dot_snapshot__rpc_dot_snapshot__python__pb2.TaskStatus.SerializeToString,
      ),
      'CancelTask': grpc.unary_unary_rpc_method_handler(
          servicer.CancelTask,
          request_deserializer=yc__snapshot__client_dot_snapshot__rpc_dot_snapshot__python__pb2.CancelTaskRequest.FromString,
          response_serializer=yc__snapshot__client_dot_snapshot__rpc_dot_snapshot__python__pb2.Status.SerializeToString,
      ),
      'DeleteTask': grpc.unary_unary_rpc_method_handler(
          servicer.DeleteTask,
          request_deserializer=yc__snapshot__client_dot_snapshot__rpc_dot_snapshot__python__pb2.DeleteTaskRequest.FromString,
          response_serializer=yc__snapshot__client_dot_snapshot__rpc_dot_snapshot__python__pb2.Status.SerializeToString,
      ),
      'ListChangedChildren': grpc.unary_unary_rpc_method_handler(
          servicer.ListChangedChildren,
          request_deserializer=yc__snapshot__client_dot_snapshot__rpc_dot_snapshot__python__pb2.ChangedChildrenListRequest.FromString,
          response_serializer=yc__snapshot__client_dot_snapshot__rpc_dot_snapshot__python__pb2.ChangedChildrenList.SerializeToString,
      ),
      'Ping': grpc.unary_unary_rpc_method_handler(
          servicer.Ping,
          request_deserializer=yc__snapshot__client_dot_snapshot__rpc_dot_snapshot__python__pb2.Status.FromString,
          response_serializer=yc__snapshot__client_dot_snapshot__rpc_dot_snapshot__python__pb2.Status.SerializeToString,
      ),
      'Delete': grpc.unary_unary_rpc_method_handler(
          servicer.Delete,
          request_deserializer=yc__snapshot__client_dot_snapshot__rpc_dot_snapshot__python__pb2.DeleteRequest.FromString,
          response_serializer=yc__snapshot__client_dot_snapshot__rpc_dot_snapshot__python__pb2.Status.SerializeToString,
      ),
      'List': grpc.unary_unary_rpc_method_handler(
          servicer.List,
          request_deserializer=yc__snapshot__client_dot_snapshot__rpc_dot_snapshot__python__pb2.ListRequest.FromString,
          response_serializer=yc__snapshot__client_dot_snapshot__rpc_dot_snapshot__python__pb2.SnapshotList.SerializeToString,
      ),
      'ListBases': grpc.unary_unary_rpc_method_handler(
          servicer.ListBases,
          request_deserializer=yc__snapshot__client_dot_snapshot__rpc_dot_snapshot__python__pb2.BaseListRequest.FromString,
          response_serializer=yc__snapshot__client_dot_snapshot__rpc_dot_snapshot__python__pb2.SnapshotList.SerializeToString,
      ),
      'Convert': grpc.unary_unary_rpc_method_handler(
          servicer.Convert,
          request_deserializer=yc__snapshot__client_dot_snapshot__rpc_dot_snapshot__python__pb2.ConvertRequest.FromString,
          response_serializer=yc__snapshot__client_dot_snapshot__rpc_dot_snapshot__python__pb2.ConvertResponse.SerializeToString,
      ),
      'Info': grpc.unary_unary_rpc_method_handler(
          servicer.Info,
          request_deserializer=yc__snapshot__client_dot_snapshot__rpc_dot_snapshot__python__pb2.InfoRequest.FromString,
          response_serializer=yc__snapshot__client_dot_snapshot__rpc_dot_snapshot__python__pb2.SnapshotInfo.SerializeToString,
      ),
      'Update': grpc.unary_unary_rpc_method_handler(
          servicer.Update,
          request_deserializer=yc__snapshot__client_dot_snapshot__rpc_dot_snapshot__python__pb2.UpdateRequest.FromString,
          response_serializer=yc__snapshot__client_dot_snapshot__rpc_dot_snapshot__python__pb2.Status.SerializeToString,
      ),
      'Verify': grpc.unary_unary_rpc_method_handler(
          servicer.Verify,
          request_deserializer=yc__snapshot__client_dot_snapshot__rpc_dot_snapshot__python__pb2.VerifyRequest.FromString,
          response_serializer=yc__snapshot__client_dot_snapshot__rpc_dot_snapshot__python__pb2.VerifyReport.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'snapshot_rpc.SnapshotService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
