Document: yandex-conf-repo-media-common-unstable
Title: Debian yandex-conf-repo-media-common-unstable Manual
Author: <insert document author here>
Abstract: This manual describes what yandex-conf-repo-media-common-unstable is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/yandex-conf-repo-media-common-unstable/yandex-conf-repo-media-common-unstable.sgml.gz

Format: postscript
Files: /usr/share/doc/yandex-conf-repo-media-common-unstable/yandex-conf-repo-media-common-unstable.ps.gz

Format: text
Files: /usr/share/doc/yandex-conf-repo-media-common-unstable/yandex-conf-repo-media-common-unstable.text.gz

Format: HTML
Index: /usr/share/doc/yandex-conf-repo-media-common-unstable/html/index.html
Files: /usr/share/doc/yandex-conf-repo-media-common-unstable/html/*.html
