blender_slices = {
    "BIATHLON": ["BIATHLON"],
    "COLLECTIONS_BOARD": ["COLLECTIONS_BOARD"],
    "CURRENCY_CONVERTER": ["CURRENCY_CONVERTER"],
    "DRUGS": ["DRUGS"],
    "EDA": ["EDA"],
    "ENTITY_SEARCH": ["ENTITY_SEARCH"],
    "GAMES": ["GAMES"],
    "GAMES_SINGLE": ["GAMES_SINGLE"],
    "GEOV": ["GEOV"],
    "NEWS_WIZARD": ["NEWS_WIZARD"],
    "PEOPLEWIZ": ["PEOPLEWIZ"],
    "RABOTA": ["RABOTA"],
    "SHINY_DISCOVERY": ["SHINY_DISCOVERY"],
    "STATIC_FACT": ["STATIC_FACT"],
    "TURBO_SNIPPET": ["TURBO_SNIPPET"],
    "TUTOR": ["TUTOR"],
    "TV_TRANSLATION": ["TV_TRANSLATION"],
    "UNISEARCH_APPLICATIONS": ["UNISEARCH_APPLICATIONS"],
    "UNISEARCH_EDUCATION": ["UNISEARCH_EDUCATION"],
    "UNISEARCH_MEDICINE": ["UNISEARCH_MEDICINE"],
    "UNISEARCH_VACANCIES": ["UNISEARCH_VACANCIES"],
    "UNITS_CONVERTER": ["UNITS_CONVERTER"],
    "VERTIS_GENERAL": ["VERTIS_GENERAL"],
    "VHS_WIZARD": ["VHS_WIZARD"],
    "VIDEOWIZ": ["VIDEOWIZ"],
    "WEB_GENERAL_ORG": ["WEB_GENERAL_ORG"],
    "WEB_Q": ["WEB_Q"],
    "WEB_QUESTION": ["WEB_QUESTION"],
    "WEB_WEATHER": ["WEB_WEATHER"],
    "WEB_ZNATOKI": ["WEB_ZNATOKI"],
    "WIZAUTO": ["WIZAUTO"],
    "WIZDISTRICT_GEO": ["WIZDISTRICT_GEO"],
    "WIZHEALTHENCYCLOPEDIA": ["WIZHEALTHENCYCLOPEDIA"],
    "WIZIMAGES": ["WIZIMAGES"],
    "WIZMAPS": ["WIZMAPS"],
    "WIZMARKET": ["WIZMARKET"],
    "WIZMUSIC": ["WIZMUSIC"],
    "WIZPROGRAMMING": ["WIZPROGRAMMING"],
    "WIZREALTY": ["WIZREALTY"],
    "WIZTRANSLATE": ["WIZTRANSLATE"],
    "WIZSTOCKS": ["WIZSTOCKS"],
    "WIZUSLUGI": ["WIZUSLUGI"],
    "WIZWEATHER": ["WIZWEATHER"],
    "WIZZNATOKIQUESTION": ["WIZZNATOKIQUESTION"],
    "YABS_PROXY_WIZ_EXP": ["YABS_PROXY_WIZ_EXP"],
    "YA_TALENTS": ["YA_TALENTS"],
    "Y_CONTENTGEN": ["Y_CONTENTGEN"],
    "Y_DISTRICT": ["Y_DISTRICT"],
    "Y_EDADEAL": ["Y_EDADEAL"],
    "Y_GAMES": ["Y_GAMES"],
    "Y_MAG_AUTO": ["Y_MAG_AUTO"],
    "Y_QUESTION": ["Y_QUESTION"],
    "Y_TALENTS": ["Y_TALENTS"],
    "Y_TUTOR": ["Y_TUTOR"],
    "Y_TUTOR_PDF": ["Y_TUTOR_PDF"],
    "Y_TUTOR_GDZ": ["Y_TUTOR_GDZ"],
    "Y_ZEN": ["Y_ZEN"],
    "ZEN": ["ZEN"],
    "Y_GENERAL": ["Y_GENERAL"],
    "Y_ZNATOKI": ["Y_ZNATOKI"],
    "ZNATOKI_MERGED": ["ZNATOKI_MERGED"],
    "ALL_DISTRICT": ["WIZDISTRICT_GEO", "Y_DISTRICT"],
    "ALL_ZNATOKI": ["WEB_QUESTION", "WEB_ZNATOKI", "WIZZNATOKIQUESTION", "Y_QUESTION", "Y_ZNATOKI", "ZNATOKI_MERGED",
                    "WEB_Q"],
    "ALL_TUTOR": ["TUTOR", "Y_TUTOR", "Y_TUTOR_GDZ", "Y_TUTOR_PDF"],
    "ALL_GAMES": ["GAMES", "GAMES_SINGLE", "Y_GAMES"],
    "ALL_GENERAL": ["VERTIS_GENERAL", "Y_GENERAL", "WEB_GENERAL_ORG"],
    "ALL_MUSHROOMS": ["BIATHLON", "EDA", "COLLECTIONS_BOARD", "GAMES", "GAMES_SINGLE", "TUTOR", "TV_TRANSLATION",
                      "VHS_WIZARD", "WEB_QUESTION", "WEB_ZNATOKI", "WIZZNATOKIQUESTION", "YABS_PROXY_WIZ_EXP",
                      "YA_TALENTS", "Y_DISTRICT", "Y_EDADEAL", "Y_GAMES", "Y_MAG_AUTO", "Y_QUESTION", "Y_TALENTS",
                      "Y_TUTOR", "Y_TUTOR_PDF", "Y_TUTOR_GDZ", "ZEN", "Y_ZEN", "Y_ZNATOKI", "ZNATOKI_MERGED", "WEB_Q",
                      "WIZDISTRICT_GEO", "VERTIS_GENERAL", "Y_GENERAL", "WEB_GENERAL_ORG"],
    "ALL_UNISEARCH": ["UNISEARCH_APPLICATIONS", "UNISEARCH_EDUCATION", "UNISEARCH_MEDICINE", "UNISEARCH_VACANCIES"],
}

blender_snippets = {
    "app_bno": ["app_bno_iphone_new", "app_bno_android_new", "app_bno_apad", "app_bno_ipad"],
    "bno": ["bno"],
    "image_snippet": ["image_snippet_one", "image_snippet_turbo", "image_snippet_exp1", "image_snippet_exp2", "image_snippet_exp3"],
    "instagram_showcase": ["instagram_showcase"],
    "new_foto_recipe": ["new_foto_recipe"],
    "news_gallery": ["media_turbo_bna", "news_bno"],
    "porn_big_bna": ["porn_big_bna"],
    "shiny_socsnipp": ["shiny_socsnipp"],
    "shinyserp_youtubecards": ["shinyserp_youtubecards_v1", "shinyserp_youtubecards_v2", "shinyserp_youtubecards_v3"],
    "shinyserp_travel_tripadvisor": ["shinyserp_travel_tripadvisor_snippet_hotel_kv",
                                     "shinyserp_travel_tripadvisor_snippet_attraction_kv",
                                     "shinyserp_travel_tripadvisor_snippet_restaurant_kv"],
    "shinyserp_travel_booking": ["shinyserp_travel_booking_hotel_snippet_qa",
                                 "shinyserp_travel_booking_hotel_snippet_site_links"],
    "snip-videothumb": ["snip-videothumb"],
    "snip_rating": ["snip_rating"],
    "watson_snippet_kinohost": ["watson_snippet_kinohost"],
    "wikipedia_article_clean_snippets_kv": ["wikipedia_article_clean_snippets_kv"],
    "microdata_snippet_breadcrumbs": ["microdata_snippet_breadcrumbs"],
    "microdata_snippet_faqpage": ["microdata_snippet_faqpage"],
    "microdata_snippet_qapage": ["microdata_snippet_qapage"],
    "doc-age": ["doc-age"],
    "snippet_with_gallery": ["snippet_with_gallery"],
}

yandex_services = {
    "afisha": ["afisha"],
    "alice": ["alice"],
    "auto": ["auto"],
    "avia": ["avia"],
    "beru-ru": ["beru.ru"],
    "eda-yandex": ["eda.yandex"],
    "edadeal-ru": ["edadeal.ru"],
    "efir": ["efir"],
    "games": ["games"],
    "health": ["health"],
    "images": ["images"],
    "kinopoisk-ru": ["kinopoisk.ru"],
    "local": ["local"],
    "maps": ["maps"],
    "market": ["market"],
    "music": ["music"],
    "news": ["news"],
    "o": ["o"],
    "oplata": ["oplata"],
    "plus": ["plus"],
    "pogoda": ["pogoda"],
    "q": ["q"],
    "rabota": ["rabota"],
    "rasp": ["rasp"],
    "realty": ["realty"],
    "sport": ["sport"],
    "support": ["support"],
    "thequestion-ru": ["thequestion.ru"],
    "trains": ["trains"],
    "translate": ["translate"],
    "travel": ["travel"],
    "uslugi": ["uslugi"],
    "video": ["video"],
    "weather": ["weather"],
    "zen": ["zen"],
}

