python3 ../common_proto_part.py -d ../../../bitbucket/private-api/yandex/cloud/priv/mdb/postgresql/v1/config/postgresql10.proto,../../../bitbucket/private-api/yandex/cloud/priv/mdb/postgresql/v1/config/postgresql10_1c.proto,../../../bitbucket/private-api/yandex/cloud/priv/mdb/postgresql/v1/config/postgresql11.proto,../../../bitbucket/private-api/yandex/cloud/priv/mdb/postgresql/v1/config/postgresql11_1c.proto,../../../bitbucket/private-api/yandex/cloud/priv/mdb/postgresql/v1/config/postgresql12.proto,../../../bitbucket/private-api/yandex/cloud/priv/mdb/postgresql/v1/config/postgresql12_1c.proto,../../../bitbucket/private-api/yandex/cloud/priv/mdb/postgresql/v1/config/postgresql13.proto,../../../bitbucket/private-api/yandex/cloud/priv/mdb/postgresql/v1/config/postgresql13_1c.proto,../../../bitbucket/private-api/yandex/cloud/priv/mdb/postgresql/v1/config/postgresql14.proto,../../../bitbucket/private-api/yandex/cloud/priv/mdb/postgresql/v1/config/postgresql14_1c.proto postgresql.common PostgresqlConfig10,PostgresqlConfig10_1C,PostgresqlConfig11,PostgresqlConfig11_1C,PostgresqlConfig12,PostgresqlConfig12_1C,PostgresqlConfig13,PostgresqlConfig13_1C,PostgresqlConfig14,PostgresqlConfig14_1C,PostgresqlConfig10Common,PostgresqlConfig11Common,PostgresqlConfig12Common,PostgresqlConfig13Common,PostgresqlConfig14Common PostgresqlConfig
python3 ../common_proto_part.py -c ../../../bitbucket/private-api/yandex/cloud/priv/mdb/postgresql/v1/config/postgresql10.proto,../../../bitbucket/private-api/yandex/cloud/priv/mdb/postgresql/v1/config/postgresql10_1c.proto postgresql.common PostgresqlConfig10,PostgresqlConfig10_1C PostgresqlConfig10Common
python3 ../common_proto_part.py -c ../../../bitbucket/private-api/yandex/cloud/priv/mdb/postgresql/v1/config/postgresql11.proto,../../../bitbucket/private-api/yandex/cloud/priv/mdb/postgresql/v1/config/postgresql11_1c.proto postgresql.common PostgresqlConfig11,PostgresqlConfig11_1C PostgresqlConfig11Common
python3 ../common_proto_part.py -c ../../../bitbucket/private-api/yandex/cloud/priv/mdb/postgresql/v1/config/postgresql12.proto,../../../bitbucket/private-api/yandex/cloud/priv/mdb/postgresql/v1/config/postgresql12_1c.proto postgresql.common PostgresqlConfig12,PostgresqlConfig12_1C PostgresqlConfig12Common
python3 ../common_proto_part.py -c ../../../bitbucket/private-api/yandex/cloud/priv/mdb/postgresql/v1/config/postgresql13.proto,../../../bitbucket/private-api/yandex/cloud/priv/mdb/postgresql/v1/config/postgresql13_1c.proto postgresql.common PostgresqlConfig13,PostgresqlConfig13_1C PostgresqlConfig13Common
python3 ../common_proto_part.py -c ../../../bitbucket/private-api/yandex/cloud/priv/mdb/postgresql/v1/config/postgresql14.proto,../../../bitbucket/private-api/yandex/cloud/priv/mdb/postgresql/v1/config/postgresql14_1c.proto postgresql.common PostgresqlConfig14,PostgresqlConfig14_1C PostgresqlConfig14Common
python3 ../common_proto_part.py -c postgresql.common postgresql.common PostgresqlConfig10Common,PostgresqlConfig11Common,PostgresqlConfig12Common,PostgresqlConfig13Common,PostgresqlConfig14Common PostgresqlConfig

python3 ../common_proto_part.py -d ../../../bitbucket/private-api/yandex/cloud/priv/mdb/postgresql/v1/config/host10.proto,../../../bitbucket/private-api/yandex/cloud/priv/mdb/postgresql/v1/config/host10_1c.proto,../../../bitbucket/private-api/yandex/cloud/priv/mdb/postgresql/v1/config/host11.proto,../../../bitbucket/private-api/yandex/cloud/priv/mdb/postgresql/v1/config/host11_1c.proto,../../../bitbucket/private-api/yandex/cloud/priv/mdb/postgresql/v1/config/host12.proto,../../../bitbucket/private-api/yandex/cloud/priv/mdb/postgresql/v1/config/host12_1c.proto,../../../bitbucket/private-api/yandex/cloud/priv/mdb/postgresql/v1/config/host13.proto,../../../bitbucket/private-api/yandex/cloud/priv/mdb/postgresql/v1/config/host13_1c.proto,../../../bitbucket/private-api/yandex/cloud/priv/mdb/postgresql/v1/config/host14.proto,../../../bitbucket/private-api/yandex/cloud/priv/mdb/postgresql/v1/config/host14_1c.proto host.common PostgresqlHostConfig10,PostgresqlHostConfig10_1C,PostgresqlHostConfig11,PostgresqlHostConfig11_1C,PostgresqlHostConfig12,PostgresqlHostConfig12_1C,PostgresqlHostConfig13,PostgresqlHostConfig13_1C,PostgresqlHostConfig14,PostgresqlHostConfig14_1C,PostgresqlHostConfig10Common,PostgresqlHostConfig11Common,PostgresqlHostConfig12Common,PostgresqlHostConfig13Common,PostgresqlHostConfig14Common PostgresqlHostConfig
python3 ../common_proto_part.py -c ../../../bitbucket/private-api/yandex/cloud/priv/mdb/postgresql/v1/config/host10.proto,../../../bitbucket/private-api/yandex/cloud/priv/mdb/postgresql/v1/config/host10_1c.proto host.common PostgresqlHostConfig10,PostgresqlHostConfig10_1C PostgresqlHostConfig10Common
python3 ../common_proto_part.py -c ../../../bitbucket/private-api/yandex/cloud/priv/mdb/postgresql/v1/config/host11.proto,../../../bitbucket/private-api/yandex/cloud/priv/mdb/postgresql/v1/config/host11_1c.proto host.common PostgresqlHostConfig11,PostgresqlHostConfig11_1C PostgresqlHostConfig11Common
python3 ../common_proto_part.py -c ../../../bitbucket/private-api/yandex/cloud/priv/mdb/postgresql/v1/config/host12.proto,../../../bitbucket/private-api/yandex/cloud/priv/mdb/postgresql/v1/config/host12_1c.proto host.common PostgresqlHostConfig12,PostgresqlHostConfig12_1C PostgresqlHostConfig12Common
python3 ../common_proto_part.py -c ../../../bitbucket/private-api/yandex/cloud/priv/mdb/postgresql/v1/config/host13.proto,../../../bitbucket/private-api/yandex/cloud/priv/mdb/postgresql/v1/config/host13_1c.proto host.common PostgresqlHostConfig13,PostgresqlHostConfig13_1C PostgresqlHostConfig13Common
python3 ../common_proto_part.py -c ../../../bitbucket/private-api/yandex/cloud/priv/mdb/postgresql/v1/config/host14.proto,../../../bitbucket/private-api/yandex/cloud/priv/mdb/postgresql/v1/config/host14_1c.proto host.common PostgresqlHostConfig14,PostgresqlHostConfig14_1C PostgresqlHostConfig14Common
python3 ../common_proto_part.py -c host.common host.common PostgresqlHostConfig10Common,PostgresqlHostConfig11Common,PostgresqlHostConfig12Common,PostgresqlHostConfig13Common,PostgresqlHostConfig14Common PostgresqlHostConfig
