#!/bin/bash

set -e

PKGNAME=yandex-media-common-cassandra-backup
DATADIR=/usr/share
YCONFDIR=${DATADIR}/yandex-configs/${PKGNAME}


case "$1" in
    configure)

        MONITORING_FILE=/var/lib/cassandra-backup/backup.rslt
        if [ ! -f ${MONITORING_FILE} ] ; then
            mkdir -vp "${MONITORING_FILE%/*}"
            echo "`date "+%s"` 0; Initial record" >> ${MONITORING_FILE}
        fi  

        #DEBHELPER#
    ;;  

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;  

    *)  
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;  

esac


exit 0

