data:
    images:
        - name: 'postgresql'
          short_name: 'pg'
          e2e_check_host: 'postgresql-e2e.db.yandex.net'
          e2e_check_service: 'dbaas-e2e-porto-qa-postgresql'
        - name: 'postgresql-10'
          short_name: 'pg-10'
          bootstrap_cmd: '/usr/local/yandex/porto/mdb_dbaas_pg_10_bionic.sh'
          e2e_check_host: 'postgresql-e2e.db.yandex.net'
          e2e_check_service: 'dbaas-e2e-porto-qa-postgresql'
        - name: 'postgresql-10-1c'
          short_name: 'pg-10-1c'
          bootstrap_cmd: '/usr/local/yandex/porto/mdb_dbaas_pg_10-1c_bionic.sh'
          e2e_check_host: 'postgresql-e2e.db.yandex.net'
          e2e_check_service: 'dbaas-e2e-porto-qa-postgresql'
        - name: 'postgresql-11'
          short_name: 'pg-11'
          bootstrap_cmd: '/usr/local/yandex/porto/mdb_dbaas_pg_11_bionic.sh'
          e2e_check_host: 'postgresql-e2e.db.yandex.net'
          e2e_check_service: 'dbaas-e2e-porto-qa-postgresql'
        - name: 'postgresql-11-1c'
          short_name: 'pg-11-1c'
          bootstrap_cmd: '/usr/local/yandex/porto/mdb_dbaas_pg_11-1c_bionic.sh'
          e2e_check_host: 'postgresql-e2e.db.yandex.net'
          e2e_check_service: 'dbaas-e2e-porto-qa-postgresql'
        - name: 'postgresql-12'
          short_name: 'pg-12'
          bootstrap_cmd: '/usr/local/yandex/porto/mdb_dbaas_pg_12_bionic.sh'
          e2e_check_host: 'postgresql-e2e.db.yandex.net'
          e2e_check_service: 'dbaas-e2e-porto-qa-postgresql'
        - name: 'postgresql-12-1c'
          short_name: 'pg-12-1c'
          bootstrap_cmd: '/usr/local/yandex/porto/mdb_dbaas_pg_12-1c_bionic.sh'
          e2e_check_host: 'postgresql-e2e.db.yandex.net'
          e2e_check_service: 'dbaas-e2e-porto-qa-postgresql'
        - name: 'postgresql-13'
          short_name: 'pg-13'
          bootstrap_cmd: '/usr/local/yandex/porto/mdb_dbaas_pg_13_bionic.sh'
          e2e_check_host: 'postgresql-e2e.db.yandex.net'
          e2e_check_service: 'dbaas-e2e-porto-qa-postgresql'
        - name: 'postgresql-13-1c'
          short_name: 'pg-13-1c'
          bootstrap_cmd: '/usr/local/yandex/porto/mdb_dbaas_pg_13-1c_bionic.sh'
          e2e_check_host: 'postgresql-e2e.db.yandex.net'
          e2e_check_service: 'dbaas-e2e-porto-qa-postgresql'
        - name: 'postgresql-14'
          short_name: 'pg-14'
          bootstrap_cmd: '/usr/local/yandex/porto/mdb_dbaas_pg_14_bionic.sh'
          e2e_check_host: 'postgresql-e2e.db.yandex.net'
          e2e_check_service: 'dbaas-e2e-porto-qa-postgresql'
        - name: 'postgresql-14-1c'
          short_name: 'pg-14-1c'
          bootstrap_cmd: '/usr/local/yandex/porto/mdb_dbaas_pg_14-1c_bionic.sh'
          e2e_check_host: 'postgresql-e2e.db.yandex.net'
          e2e_check_service: 'dbaas-e2e-porto-qa-postgresql'
        - name: 'clickhouse'
          short_name: 'ch'
          e2e_check_host: 'clickhouse-e2e.db.yandex.net'
          e2e_check_service: 'dbaas-e2e-porto-qa-clickhouse'
        - name: 'mongodb'
          short_name: 'mongodb'
          e2e_check_host: 'mongodb-e2e.db.yandex.net'
          e2e_check_service: 'dbaas-e2e-porto-qa-mongodb'
        - name: 'zookeeper'
          short_name: 'zk'
          e2e_check_host: 'clickhouse-e2e.db.yandex.net'
          e2e_check_service: 'dbaas-e2e-porto-qa-clickhouse'
        - name: 'redis'
          short_name: 'redis'
          e2e_check_host: 'redis-e2e.db.yandex.net'
          e2e_check_service: 'dbaas-e2e-porto-qa-redis'
        - name: 'redis-50'
          short_name: 'redis-50'
          bootstrap_cmd: '/usr/local/yandex/porto/mdb_dbaas_redis_50_bionic.sh'
          e2e_check_host: 'redis-e2e.db.yandex.net'
          e2e_check_service: 'dbaas-e2e-porto-qa-redis'
        - name: 'redis-60'
          short_name: 'redis-60'
          bootstrap_cmd: '/usr/local/yandex/porto/mdb_dbaas_redis_60_bionic.sh'
          e2e_check_host: 'redis-e2e.db.yandex.net'
          e2e_check_service: 'dbaas-e2e-porto-qa-redis'
        - name: 'redis-62'
          short_name: 'redis-62'
          bootstrap_cmd: '/usr/local/yandex/porto/mdb_dbaas_redis_62_bionic.sh'
          e2e_check_host: 'redis-e2e.db.yandex.net'
          e2e_check_service: 'dbaas-e2e-porto-qa-redis'
        - name: 'redis-70'
          short_name: 'redis-70'
          bootstrap_cmd: '/usr/local/yandex/porto/mdb_dbaas_redis_70_bionic.sh'
          e2e_check_host: 'redis-e2e.db.yandex.net'
          e2e_check_service: 'dbaas-e2e-porto-qa-redis'
        - name: 'mysql'
          short_name: 'mysql'
          e2e_check_host: 'mysql-e2e.db.yandex.net'
          e2e_check_service: 'dbaas-e2e-porto-qa-mysql'
        - name: 'elasticsearch'
          short_name: 'elasticsearch'
          bootstrap_cmd: '/usr/local/yandex/porto/mdb_dbaas_elasticsearch_bionic.sh'
          e2e_check_host: 'elasticsearch-e2e.db.yandex.net'
          e2e_check_service: 'dbaas-e2e-porto-qa-elasticsearch'
        - name: 'elasticsearch-710'
          bootstrap_cmd: '/usr/local/yandex/porto/mdb_dbaas_elasticsearch_710_bionic.sh'
          short_name: 'elasticsearch-710'
          e2e_check_host: 'elasticsearch-e2e.db.yandex.net'
          e2e_check_service: 'dbaas-e2e-porto-qa-elasticsearch'
        - name: 'elasticsearch-711'
          bootstrap_cmd: '/usr/local/yandex/porto/mdb_dbaas_elasticsearch_711_bionic.sh'
          short_name: 'elasticsearch-711'
          e2e_check_host: 'elasticsearch-e2e.db.yandex.net'
          e2e_check_service: 'dbaas-e2e-porto-qa-elasticsearch'
        - name: 'elasticsearch-712'
          bootstrap_cmd: '/usr/local/yandex/porto/mdb_dbaas_elasticsearch_712_bionic.sh'
          short_name: 'elasticsearch-712'
          e2e_check_host: 'elasticsearch-e2e.db.yandex.net'
          e2e_check_service: 'dbaas-e2e-porto-qa-elasticsearch'
        - name: 'elasticsearch-713'
          bootstrap_cmd: '/usr/local/yandex/porto/mdb_dbaas_elasticsearch_713_bionic.sh'
          short_name: 'elasticsearch-713'
          e2e_check_host: 'elasticsearch-e2e.db.yandex.net'
          e2e_check_service: 'dbaas-e2e-porto-qa-elasticsearch'
        - name: 'elasticsearch-714'
          bootstrap_cmd: '/usr/local/yandex/porto/mdb_dbaas_elasticsearch_714_bionic.sh'
          short_name: 'elasticsearch-714'
          e2e_check_host: 'elasticsearch-e2e.db.yandex.net'
          e2e_check_service: 'dbaas-e2e-porto-qa-elasticsearch'
        - name: 'elasticsearch-715'
          bootstrap_cmd: '/usr/local/yandex/porto/mdb_dbaas_elasticsearch_715_bionic.sh'
          short_name: 'elasticsearch-715'
          e2e_check_host: 'elasticsearch-e2e.db.yandex.net'
          e2e_check_service: 'dbaas-e2e-porto-qa-elasticsearch'
        - name: 'elasticsearch-716'
          bootstrap_cmd: '/usr/local/yandex/porto/mdb_dbaas_elasticsearch_716_bionic.sh'
          short_name: 'elasticsearch-716'
          e2e_check_host: 'elasticsearch-e2e.db.yandex.net'
          e2e_check_service: 'dbaas-e2e-porto-qa-elasticsearch'
        - name: 'elasticsearch-717'
          bootstrap_cmd: '/usr/local/yandex/porto/mdb_dbaas_elasticsearch_717_bionic.sh'
          short_name: 'elasticsearch-717'
          e2e_check_host: 'elasticsearch-e2e.db.yandex.net'
          e2e_check_service: 'dbaas-e2e-porto-qa-elasticsearch'
        - name: 'opensearch'
          short_name: 'opensearch'
          bootstrap_cmd: '/usr/local/yandex/porto/mdb_dbaas_opensearch_bionic.sh'
          no_check: true
        - name: 'opensearch-21'
          bootstrap_cmd: '/usr/local/yandex/porto/mdb_dbaas_opensearch_210_bionic.sh'
          short_name: 'opensearch-21'
          no_check: true
        - name: 'kafka'
          short_name: 'kafka'
          e2e_check_host: 'kafka-e2e.db.yandex.net'
          e2e_check_service: 'dbaas-e2e-porto-qa-kafka'
        - name: 'greenplum'
          short_name: 'gpdb'
          e2e_check_host: 'greenplum-e2e.db.yandex.net'
          e2e_check_service: 'dbaas-e2e-porto-qa-greenplum'
