#! /usr/bin/env python3


import sys
import os
from pkg_resources import resource_filename
from generate_awacs_config.generator import Generator


if __name__ == '__main__':
    if len(sys.argv) > 1:
        os.execvp('man', ['man', resource_filename('generate_awacs_config', 'generate-awacs-config.1')])
    Generator().run()
