#!/bin/bash
#
# Starts Yandex.Cloud Data-Proc Bootstrap script
#
# chkconfig: 2345 85 15
# description: Yandex.Cloud Data-Proc bootstrap script
### BEGIN INIT INFO
# Provides:          dataproc-bootstrap
# Short-Description: Data-Proc Bootstrap
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Required-Start:    $syslog $remote_fs $network
# Required-Stop:     $syslog $remote_fs
# Should-Start:
# Should-Stop:
### END INIT INFO

. /lib/lsb/init-functions

RETVAL_SUCCESS=0

STATUS_RUNNING=0
ERROR_PROGRAM_NOT_INSTALLED=5

RETVAL=0

DESC="Yandex.Cloud Data-Proc Bootstrap"
EXEC_PATH="/srv/dataproc-start.sh"
SVC_USER="root"
LOGFILE="/var/log/yandex-dataproc-bootstrap.log"

start() {
  [ -x ${EXEC_PATH} ] || exit ${ERROR_PROGRAM_NOT_INSTALLED}

  su -s /bin/bash ${SVC_USER} -c "${EXEC_PATH} >> ${LOGFILE} 2>&1"
  RETVAL=$?

  if [ ${RETVAL} -eq ${STATUS_RUNNING} ]; then
    log_success_msg "Started ${DESC}: "
  else
    log_failure_msg "Failed to start ${DESC}. Return value: $RETVAL"
  fi
  return $RETVAL
}

check_for_root() {
  if [ $(id -ur) -ne 0 ]; then
    echo 'Error: root user required'
    echo
    exit 1
  fi
}

service() {
  case "$1" in
    start)
      check_for_root
      start
      ;;
    status)
      ;;
    *)
      echo $"Usage: $0 {start}"
      exit 1
  esac
}

service "$@"

exit $RETVAL
