# This file is generated by
# https://bb.yandex-team.ru/projects/CLOUD/repos/cloud-go/browse/tools/cmd/syncapi
# in Teamcity Task
# https://teamcity.yandex-team.ru/buildConfiguration/Cloud_Api_ApiSync

OWNER(g:cloud-api)
PROTO_LIBRARY()

PROTO_NAMESPACE(GLOBAL cloud/bitbucket/private-api)
PY_NAMESPACE(yandex.cloud.priv.marketplace.v1alpha1)

GRPC()
SRCS(
    avatar.proto
    category.proto
    contact_info.proto
    deprecation.proto
    isv.proto
    os_product.proto
    os_product_family.proto
    os_product_family_version.proto
    partner_request.proto
    person.proto
    pricing_version.proto
    publisher.proto
    resource_spec.proto
    simple_product.proto
    sku.proto
    sku_draft.proto
    task.proto
    var.proto
)

USE_COMMON_GOOGLE_APIS(
    api/annotations
    rpc/code
    rpc/errdetails
    rpc/status
    type/timeofday
    type/dayofweek
)

IF (GO_PROTO)
    PEERDIR(
        cloud/bitbucket/common-api/yandex/cloud/api/tools
    )
ELSE()
    PEERDIR(
        cloud/bitbucket/common-api/yandex/cloud/api/tools
    )
ENDIF()
END()

