SELECT operation_id AS id,
       target_id,
       cluster_type,
       env AS environment,
       operation_type,
       created_by,
       created_at,
       started_at,
       modified_at,
       status,
       metadata,
       hidden,
       errors
  FROM code.add_operation(
        i_operation_id          => %(task_id)s,
        i_cid                   => %(cid)s,
        i_folder_id             => %(folder_id)s,
        i_time_limit            => %(time_limit)s,
        i_task_type             => %(task_type)s,
        i_operation_type        => %(operation_type)s,
        i_metadata              => %(metadata)s,
        i_task_args             => %(task_args)s,
        i_user_id               => %(user_id)s,
        i_hidden                => %(hidden)s,
        i_version               => %(version)s,
        i_delay_by              => %(delay_by)s,
        i_required_operation_id => %(required_operation_id)s,
        i_idempotence_data      => %(idempotence_data)s::code.idempotence_data,
        i_rev                   => %(rev)s,
        i_tracing               => %(tracing)s
)
