#!/bin/sh
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
exec 2>&1

sed -i 's/60/6/g' /opt/yandex/p2p/bin/common.sh
while :;
do
    while [ ! -f /usr/local/bin/sky ]
    do
        sleep 15
    done
    /opt/yandex/p2p/bin/cron-task.sh geodata6
    /opt/yandex/p2p/bin/cron-task.sh tzdata
    sleep 90
    if [ -f /var/cache/geobase/geodata6.bin ]
    then
       touch /var/tmp/ephemeral_ok
    fi
    sleep 30

    YASMLOGDIR="/var/log/yasmagent/"
    SizeK=$(du -s -m $YASMLOGDIR | cut -d/ -f 1)
    if (($SizeK > 10)); then
      echo `date`" Size of $YASMLOGDIR too large, clear logs now.."
      for f in $(ls -1 $YASMLOGDIR); do
        >$f
      done
    fi

done

