#!/usr/bin/env bash

source `dirname "${BASH_SOURCE[0]}"`/../scripts/run.sh

# Generate searcherlookup.conf (in w-generated).
run /usr/bin/time -f "[TIME]: %C %E" ./utils/postgen/write_searcherlookup.py -o w-generated/searcherlookup.conf -f "lambda x: x.card.name not in 'ALL_QLOUD ALL_QLOUD_HOSTS SAS_MAIL_LUCENE ALL_UNSORTED_SEARCH_INFRA_SEARCH_QLOUD ALL_UNSORTED SAS_KERNEL_UPDATE_3 SAS_PSI_YT_MASTER SAS_WEB_INT VLA_WEB_DEPLOY VLA_WEB_TIER0_JUPITER_BASE VLA_WEB_TIER0_JUPITER_BASE_HAMSTER SAS_PSI_DYNAMIC SAS_PSI_DYNAMIC_AGENTS MSK_PSI_RESERVED_ROTOR_PORTOVM MAN_PSI1_AGENTS MAN_PSI1_PORTOVM MAN_YT_BANACH SAS_YT_HAHN VLA_IMGS_THUMB_NEW VLA_IMGS_THUMB_NEW_NIDX SAS_WEB_TIER0_JUPITER_BASE SAS_WEB_TIER0_JUPITER_BASE_HAMSTER MSK_JUGGLER_CLIENT_STABLE MSK_YASM_YASMAGENT_STABLE ALL_IMGS_MR_THUMBS MAN_IMGS_MR_THUMBS MAN_IMGS_THUMB_NEW MAN_IMGS_THUMB_NEW_NIDX MAN_SEARCH MAN_RTC_SLA_TENTACLES_PROD MAN_RUNTIME VLA_SEARCH VLA_RTC_SLA_TENTACLES_PROD VLA_RUNTIME VLA_JUGGLER_CLIENT_STABLE VLA_YASM_YASMAGENT_STABLE VLA_PSI_DYNAMIC_ROTOR SAS_YASM_YASMAGENT_PRESTABLE SAS_RTC_SLA_TENTACLES_PROD SAS_RUNTIME SAS_SEARCH MAN_JUGGLER_CLIENT_STABLE MAN_YASM_YASMAGENT_STABLE SAS_PSI_DYNAMIC_ROTOR SAS_JUGGLER_CLIENT_STABLE SAS_YASM_YASMAGENT_STABLE MAN_PSI1_ROTOR_PORTOVM SAS_WEB_BASE ALL_SEARCH VLA_WEB_BASE ALL_ISS_AGENT ALL_RUNTIME VLA_YT_RTC'.split()"

run /usr/bin/time -f "[TIME]: %C %E" ./utils/check/check_searcherlookup.py
