#!/usr/bin/env bash

source `dirname "${BASH_SOURCE[0]}"`/../scripts/run.sh

MYARGS=()
MYARGS+=('/usr/bin/time -f "[TIME]: %C %E" ./utils/check/check_porto_limits.py -g ALL --check-net')
MYARGS+=('/usr/bin/time -f "[TIME]: %C %E" ./utils/check/check_porto_limits.py -g ALL_DYNAMIC --check-hdd --check-ssd --check-net')
MYARGS+=('/usr/bin/time -f "[TIME]: %C %E" ./utils/check/check_porto_limits.py -g MAN_WEB_BASE --check-hdd --check-ssd --check-net')
MYARGS+=('/usr/bin/time -f "[TIME]: %C %E" ./utils/check/check_porto_limits.py -g SAS_WEB_BASE --check-hdd --check-ssd --check-net')
MYARGS+=('/usr/bin/time -f "[TIME]: %C %E" ./utils/check/check_porto_limits.py -g VLA_YT_RTC')
MYARGS+=('/usr/bin/time -f "[TIME]: %C %E" ./utils/check/check_porto_limits.py -g VLA_WEB_TIER0_REMOTE_STORAGE_YP_BASE --check-hdd --check-ssd --check-net')
MYARGS+=('/usr/bin/time -f "[TIME]: %C %E" ./utils/check/check_porto_limits.py -g VLA_WEB_TIER0_REMOTE_STORAGE_YP_BASE_PIP --check-hdd --check-ssd --check-net')
MYARGS+=('/usr/bin/time -f "[TIME]: %C %E" ./utils/common/update_igroups.py -a checkcards')
MYARGS+=('/usr/bin/time -f "[TIME]: %C %E" ./utils/check/check_instances.py --workers 4')
MYARGS+=('/usr/bin/time -f "[TIME]: %C %E" ./utils/check/check_group_intersections.py')
MYARGS+=('/usr/bin/time -f "[TIME]: %C %E" ./utils/check/check_intlookups.py')
MYARGS+=('/usr/bin/time -f "[TIME]: %C %E" ./utils/check/check_unused_instances.py')
MYARGS+=('/usr/bin/time -f "[TIME]: %C %E" ./utils/check/check_tag_names.py')
MYARGS+=('/usr/bin/time -f "[TIME]: %C %E" ./utils/check/check_slave_groups_hosts.py')
MYARGS+=('/usr/bin/time -f "[TIME]: %C %E" ./utils/check/check_vm.py')
MYARGS+=('/usr/bin/time -f "[TIME]: %C %E" ./utils/check/check_missconfigured_machines.py -g ALLM -i repeatedinvnumhosts --fail-on-error')
MYARGS+=('/usr/bin/time -f "[TIME]: %C %E" ./utils/check/check_missconfigured_machines.py -i unknowninvnums -g ALL_SEARCH')
MYARGS+=('/usr/bin/time -f "[TIME]: %C %E" ./utils/check/check_replicas_count.py')
MYARGS+=('/usr/bin/time -f "[TIME]: %C %E" ./utils/check/check_missconfigured_machines.py -i unknownmodel -g ALLM -f "lambda x: \"search-regproxy\" not in x.card.tags.prj and x.card.properties.background_group == False and x.card.properties.fake_group == False and x.card.name not in \"ALL_PRENALIVKA ALL_ANTIVIRUS ALL_SITA MSK_IMGS_IMPROXY_R1 ALL_OSOL_HEAD_COMPILATION VLA_YT_RTC ALL_QLOUD_HOSTS ALL_YP_HOSTS RUNTIMECLOUD_8673 ALL_OPENSTACK ALL_DEV_IMGS_GPU RESERVE_NEW_HOSTS ALL_UNWORKING_NO_MTN\".split() and x.card.tags.metaprj != \"unsorted\"" --fail-on-error')
MYARGS+=('/usr/bin/time -f "[TIME]: %C %E" ./utils/check/check_inherited_tags.py')
MYARGS+=('/usr/bin/time -f "[TIME]: %C %E" ./utils/check/check_unassigned_hosts.py')
MYARGS+=('/usr/bin/time -f "[TIME]: %C %E" ./utils/check/check_hamster_shards.py')
MYARGS+=('/usr/bin/time -f "[TIME]: %C %E" ./utils/check/check_group_intlookups.py')
MYARGS+=('/usr/bin/time -f "[TIME]: %C %E" ./utils/check/check_hosts_attrs.py')
MYARGS+=('/usr/bin/time -f "[TIME]: %C %E" ./utils/api/searcherlookup_groups_instances.py -g MSK_RESERVED --silent')
MYARGS+=('/usr/bin/time -f "[TIME]: %C %E" ./utils/check/check_shifted_groups.py -g ALL')
MYARGS+=('/usr/bin/time -f "[TIME]: %C %E" ./utils/check/check_hbf.py')
MYARGS+=('/usr/bin/time -f "[TIME]: %C %E" ./utils/check/check_web_extra.py')
MYARGS+=('/usr/bin/time -f "[TIME]: %C %E" ./utils/check/check_tiers.py')
MYARGS+=('/usr/bin/time -f "[TIME]: %C %E" ./utils/check/check_indexerproxy_intersect.py')
MYARGS+=('/usr/bin/time -f "[TIME]: %C %E" ./utils/check/check_security_segments.py')
MYARGS+=('/usr/bin/time -f "[TIME]: %C %E" ./utils/check/check_ipv4tunnels.py')
MYARGS+=('/usr/bin/time -f "[TIME]: %C %E" ./utils/check/check_hbf_macroses.py')
MYARGS+=('/usr/bin/time -f "[TIME]: %C %E" ./utils/check/check_hbf_ranges.py')
MYARGS+=('/usr/bin/time -f "[TIME]: %C %E" ./utils/check/check_moved_to_yp.py')
MYARGS+=('/usr/bin/time -f "[TIME]: %C %E" ./utils/check/check_groups_metaprj.py')
MYARGS+=('/usr/bin/time -f "[TIME]: %C %E" ./utils/check/check_mtn_fqdn_collisions.py')
MYARGS+=('/usr/bin/time -f "[TIME]: %C %E" ./utils/check/check_dispenser_project_key.py')
MYARGS+=('/usr/bin/time -f "[TIME]: %C %E" ./utils/check/check_vlans_format.py')
MYARGS+=('/usr/bin/time -f "[TIME]: %C %E" ./utils/check/check_back_group_cpu_policy.py')
MYARGS+=('/usr/bin/time -f "[TIME]: %C %E" ./utils/check/check_models.py')

par "${MYARGS[@]}"
