#!/bin/bash

case "$1" in
  install)

    mkdir -p /var/{cache,lib,log}/yc || :
    useradd -rmd /var/lib/yc/token-agent -s /sbin/nologin yc-token-agent || :
    install -o yc-token-agent -g yc-token-agent -m 700 -d /var/{cache,lib,log}/yc/token-agent
  ;;

esac
