// Code generated by MockGen. DO NOT EDIT.
// Source: a.yandex-team.ru/cloud/mdb/internal/racktables (interfaces: Client)

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	racktables "a.yandex-team.ru/cloud/mdb/internal/racktables"
	gomock "github.com/golang/mock/gomock"
)

// MockClient is a mock of Client interface.
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
}

// MockClientMockRecorder is the mock recorder for MockClient.
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance.
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// GetMacro mocks base method.
func (m *MockClient) GetMacro(arg0 context.Context, arg1 string) (racktables.Macro, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMacro", arg0, arg1)
	ret0, _ := ret[0].(racktables.Macro)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMacro indicates an expected call of GetMacro.
func (mr *MockClientMockRecorder) GetMacro(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMacro", reflect.TypeOf((*MockClient)(nil).GetMacro), arg0, arg1)
}

// GetMacrosWithOwners mocks base method.
func (m *MockClient) GetMacrosWithOwners(arg0 context.Context) (racktables.MacrosWithOwners, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMacrosWithOwners", arg0)
	ret0, _ := ret[0].(racktables.MacrosWithOwners)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMacrosWithOwners indicates an expected call of GetMacrosWithOwners.
func (mr *MockClientMockRecorder) GetMacrosWithOwners(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMacrosWithOwners", reflect.TypeOf((*MockClient)(nil).GetMacrosWithOwners), arg0)
}
