non_moveable = [
    'SAS_ADV_RM_TIER_BUILD',
    'SAS_ADV_RSYA_RMP_TIER_BUILD',
    'SAS_ADV_SEARCH_TIER_BUILD',
    'SAS_ARCNEWS_BASE',
    'SAS_ARCNEWS_STORY_BASE',
    'SAS_MUSICMIC_BASE',
    'SAS_PORTAL_ANY_STABLE',
    'SAS_PORTAL_MORDA',
    'SAS_PORTAL_MORDA_YARU_STABLE',
    'SAS_RSYATIER_BUILD',
    'SAS_SELENIUM_2_CORE_BASE',
    'SAS_UZOR_WITH_BASE',
    'SAS_IMGS_ULTRA_REFRESH_DISTRIBUTOR',
    'SAS_IMGS_PPL_BASE',
    'SAS_IMGS_QUICK_THUMB_CACHER_NEW',
    'SAS_IMGS_SAAS_QUICK_BASE',
    'SAS_IMGS_CBIR_QUICK_BASE',
    'SAS_WEB_MMETA_PRS_HAMSTER',
    'SAS_WEB_REFRESH_DISTRIBUTOR_NEW',
    'SAS_WEB_GEMINI_SEARCHPROXY',
    'SAS_VIDEO_REFRESH_DISTRIBUTOR',
    'SAS_IMGS_THUMB_CACHER_NEW',
    'SAS_IMGS_LARGE_THUMB_CACHER_NEW',
    'SAS_IMGS_THUMB_TANK',
    'SAS_DISK_LUCENE',
    'SAS_MAIL_LUCENE',
]

deploy = [
    'SAS_CALLISTO_DEPLOY',
]

hdd_consumers = [
    'SAS_IMGS_LARGE_THUMB',
    'SAS_IMGS_LARGE_THUMB_NIDX',
    # mail and disk
]

to_remove = [
    'SAS_L7_THIN_BALANCER',
    'SAS_WEB_TIER0_JUPITER_BASE',
    'SAS_WEB_TIER0_JUPITER_BASE_HAMSTER',
    'SAS_WEB_TIER0_JUPITER_INT',
    'SAS_WEB_TIER0_JUPITER_INT_HAMSTER',
    'SAS_WEB_INT',
]

non_optimized = [
    'SAS_IMGS_RIM_3K',
    'SAS_IMGS_RIM_3K_DEPLOY',
    'SAS_IMGS_T1_BASE',
    'SAS_IMGS_T1_BASE_NIDX',
    'SAS_IMGS_T1_CBIR_BASE',
    'SAS_IMGS_T1_CBIR_BASE_NIDX',
    'SAS_IMGS_T1_CBIR_INT',
    'SAS_IMGS_T1_INT',
    'SAS_WEB_TIER1_JUPITER_BASE',
    'SAS_WEB_TIER1_JUPITER_BASE_HAMSTER',
    'SAS_WEB_TIER1_JUPITER_INT',
    'SAS_WEB_TIER1_JUPITER_INT_HAMSTER',
    'SAS_WEB_CALLISTO_CAM_BASE',
    'SAS_WEB_CALLISTO_CAM_INT',
    'SAS_WEB_CALLISTO_CAM_INTL2',
    'SAS_WEB_GEMINI_BASE',
]

ALL = [
    'SAS_IMGS_BASE',
    'SAS_IMGS_BASE_HAMSTER',
    'SAS_IMGS_BASE_NIDX',
    'SAS_IMGS_CBIR_BASE',
    'SAS_IMGS_CBIR_BASE_HAMSTER',
    'SAS_IMGS_CBIR_BASE_NIDX',
    'SAS_IMGS_CBIR_INT',
    'SAS_IMGS_CBIR_INT_HAMSTER',
    'SAS_IMGS_INT',
    'SAS_IMGS_INT_HAMSTER',
    'SAS_VIDEO_PLATINUM_BASE',
    'SAS_VIDEO_PLATINUM_BASE_HAMSTER',
    'SAS_VIDEO_PLATINUM_INT',
    'SAS_VIDEO_PLATINUM_INT_HAMSTER',
    'SAS_VIDEO_TIER0_BASE',
    'SAS_VIDEO_TIER0_BASE_HAMSTER',
    'SAS_VIDEO_TIER0_INT',
    'SAS_VIDEO_TIER0_INT_HAMSTER',
    'SAS_WEB_INTL2',
    'SAS_WEB_INTL2_HAMSTER',
    'SAS_WEB_REMOTE_STORAGE_BASE',
]
