#! /bin/bash

set -e
VENV=debian/venv
PYPI_URL="https://pypi.yandex-team.ru/simple/"

# [ -d $VENV ] && rm -r $VENV || true
virtualenv --always-copy $VENV
mkdir -p $VENV/whl
. $VENV/bin/activate
$VENV/bin/pip install -i ${PYPI_URL} setuptools==18.5
$VENV/bin/pip install --upgrade pip
$VENV/bin/pip install --upgrade wheel
$VENV/bin/pip wheel --wheel-dir=$VENV/whl -i ${PYPI_URL} -r requirements.txt
$VENV/bin/python setup.py bdist_wheel --dist-dir=$VENV/whl
$VENV/bin/pip install --no-index --find-links=$VENV/whl -r requirements.txt
$VENV/bin/pip install --no-index --find-links=$VENV/whl mysql-configurator
deactivate
virtualenv --relocatable $VENV
rm -fv $VENV/bin/python*
rm -fv $VENV/local/bin/python*
rm -rv $VENV/whl
find ${VENV} -type f -name '*.pyc' -delete
