#!/usr/bin/env bash

ENV="/usr/bin/env"
COMMON_PATH="/usr/local/bin:/usr/bin:/bin"

if [ ! -n "$1" ]
then
  echo "Usage: $(basename $0) JDK_PATH cmd [arguments]"
  exit 1
fi

JDK_PATH="$1"

shift
${ENV} --ignore-environment
    JAVA_HOME=${JDK_PATH}
    JDK_HOME=${JDK_PATH}
    PATH=${JDK_PATH}/bin:${COMMON_PATH}
    "$@"
