GRANT CONNECT ON DATABASE dbaas_metadb TO cms;
GRANT USAGE ON SCHEMA dbaas TO cms;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA dbaas TO cms;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA dbaas TO cms;
GRANT USAGE ON SCHEMA code TO cms;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA code TO cms;
