GRANT USAGE ON SCHEMA dbaas TO dbaas_worker;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA dbaas TO dbaas_worker;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA dbaas TO dbaas_worker;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA dbaas TO dbaas_worker;
GRANT USAGE ON SCHEMA code TO dbaas_worker;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA code TO dbaas_worker;
