GRANT USAGE ON SCHEMA dbaas TO katan_imp;
GRANT SELECT ON ALL TABLES IN SCHEMA dbaas TO katan_imp;

GRANT USAGE ON SCHEMA code TO katan_imp;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA code TO katan_imp;
