GRANT CONNECT ON DATABASE dbaas_metadb TO logs_api;
GRANT USAGE ON SCHEMA dbaas TO logs_api;
GRANT SELECT ON ALL TABLES IN SCHEMA dbaas TO logs_api;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA dbaas TO logs_api;
GRANT USAGE ON SCHEMA code TO logs_api;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA code TO logs_api;
