GRANT CONNECT ON DATABASE dbaas_metadb TO mdb_ui;
GRANT USAGE ON SCHEMA dbaas TO mdb_ui;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA dbaas TO mdb_ui;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA dbaas TO mdb_ui;
GRANT USAGE ON SCHEMA code TO mdb_ui;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA code TO mdb_ui;
