import yt.wrapper as yt
import yt.yson as yson
from cloud.analytics.scripts.yt_migrate import Table

TABLE_NAME = 'dyn_table'


def upgrade():
    table = Table(name=TABLE_NAME)
    schema = yson.YsonList([
        {'name': 'dwh_id', 'required': True, 'type': 'string', 'sort_order': 'ascending'},
        {'name': 'email', 'required': True, 'type': 'string', 'sort_order': 'ascending'},
        {'name': 'crm_id', 'required': False, 'type': 'string', 'sort_order': 'ascending'},
        {'name': 'mkto_id', 'required': False, 'type': 'uint64', 'sort_order': 'ascending'},
        {'name': 'dwh_updated_at', 'required': True, 'type': 'uint64'},
        {'name': 'account_id', 'required': False, 'type': 'string'},
        {'name': 'passport_uid', 'required': False, 'type': 'uint64'},
        {'name': 'ba_id', 'required': False, 'type': 'string'},
        {'name': 'preferred_language', 'required': False, 'type': 'string'},
        {'name': 'user_settings_email', 'required': False, 'type': 'string'},
        {'name': 'user_settings_email_history', 'required': False, 'type': 'any'},
        {'name': 'crm_email', 'required': False, 'type': 'string'},
        {'name': 'mkto_email', 'required': False, 'type': 'string'},
        {'name': 'mql_timestamp', 'required': False, 'type': 'uint64'},
        {'name': 'mql_sent_to_crm', 'required': False, 'type': 'boolean'},
        {'name': 'website', 'required': False, 'type': 'string'},
        {'name': 'first_name', 'required': False, 'type': 'string'},
        {'name': 'last_name', 'required': False, 'type': 'string'},

        # crm specific fields
        {'name': 'crm_status', 'required': False, 'type': 'string'},
        {'name': 'crm_type', 'required': False, 'type': 'string'},
        {'name': 'crm_account_description', 'required': False, 'type': 'string'},
        {'name': 'crm_account_name', 'required': False, 'type': 'string'},
        {'name': 'crm_alt_address_city', 'required': False, 'type': 'string'},
        {'name': 'crm_alt_address_country', 'required': False, 'type': 'string'},
        {'name': 'crm_alt_address_postalcode', 'required': False, 'type': 'string'},
        {'name': 'crm_alt_address_state', 'required': False, 'type': 'string'},
        {'name': 'crm_alt_address_street', 'required': False, 'type': 'string'},
        {'name': 'crm_assigned_user_login', 'required': False, 'type': 'string'},
        {'name': 'crm_primary_address_city', 'required': False, 'type': 'string'},
        {'name': 'crm_primary_address_country', 'required': False, 'type': 'string'},
        {'name': 'crm_primary_address_postalcode', 'required': False, 'type': 'string'},
        {'name': 'crm_primary_address_state', 'required': False, 'type': 'string'},
        {'name': 'crm_primary_address_street', 'required': False, 'type': 'string'},
        {'name': 'crm_birthdate', 'required': False, 'type': 'string'},
        {'name': 'crm_contact_id', 'required': False, 'type': 'string'},
        {'name': 'crm_converted', 'required': False, 'type': 'boolean'},
        {'name': 'crm_deleted', 'required': False, 'type': 'boolean'},
        {'name': 'crm_department', 'required': False, 'type': 'string'},
        {'name': 'crm_description', 'required': False, 'type': 'string'},
        {'name': 'crm_dimensions', 'required': False, 'type': 'any'},
        {'name': 'crm_do_not_call', 'required': False, 'type': 'boolean'},
        {'name': 'crm_do_not_mail', 'required': False, 'type': 'boolean'},
        {'name': 'crm_last_communication_date', 'required': False, 'type': 'string'},
        {'name': 'crm_lead_priority', 'required': False, 'type': 'string'},
        {'name': 'crm_lead_source', 'required': False, 'type': 'string'},
        {'name': 'crm_lead_source_description', 'required': False, 'type': 'string'},
        {'name': 'crm_lead_weight', 'required': False, 'type': 'uint64'},
        {'name': 'crm_opportunity_amount', 'required': False, 'type': 'string'},
        {'name': 'crm_opportunity_id', 'required': False, 'type': 'string'},
        {'name': 'crm_opportunity_name', 'required': False, 'type': 'string'},
        {'name': 'crm_phone_home', 'required': False, 'type': 'string'},
        {'name': 'crm_phone_mobile', 'required': False, 'type': 'string'},
        {'name': 'crm_phone_other', 'required': False, 'type': 'string'},
        {'name': 'crm_phone_work', 'required': False, 'type': 'string'},
        {'name': 'crm_status_description', 'required': False, 'type': 'string'},
        {'name': 'crm_title', 'required': False, 'type': 'string'},
        {'name': 'crm_date_modified', 'required': False, 'type': 'uint64'},

        # Marketo specific fields
        {'name': 'mkto_address', 'required': False, 'type': 'string'},
        {'name': 'mkto_ba_status', 'required': False, 'type': 'string'},
        {'name': 'mkto_city', 'required': False, 'type': 'string'},
        {'name': 'mkto_cloud_wallet', 'required': False, 'type': 'string'},
        {'name': 'mkto_company', 'required': False, 'type': 'string'},
        {'name': 'mkto_company_size', 'required': False, 'type': 'string'},
        {'name': 'mkto_console_registration_date', 'required': False, 'type': 'uint64'},
        {'name': 'mkto_country', 'required': False, 'type': 'string'},
        {'name': 'mkto_email_type', 'required': False, 'type': 'string'},
        {'name': 'mkto_industry', 'required': False, 'type': 'string'},
        {'name': 'mkto_inferred_city', 'required': False, 'type': 'string'},
        {'name': 'mkto_inferred_country', 'required': False, 'type': 'string'},
        {'name': 'mkto_is_individual', 'required': False, 'type': 'boolean'},
        {'name': 'mkto_lead_behaviour_score', 'required': False, 'type': 'uint64'},
        {'name': 'mkto_lead_demographic_score', 'required': False, 'type': 'uint64'},
        {'name': 'mkto_lead_product_score_ch', 'required': False, 'type': 'uint64'},
        {'name': 'mkto_lead_product_score_compute', 'required': False, 'type': 'uint64'},
        {'name': 'mkto_lead_product_score_datalens', 'required': False, 'type': 'uint64'},
        {'name': 'mkto_lead_product_score_iam', 'required': False, 'type': 'uint64'},
        {'name': 'mkto_lead_product_score_mdb', 'required': False, 'type': 'uint64'},
        {'name': 'mkto_lead_product_score_mg', 'required': False, 'type': 'uint64'},
        {'name': 'mkto_lead_product_score_mysql', 'required': False, 'type': 'uint64'},
        {'name': 'mkto_lead_product_score_pg', 'required': False, 'type': 'uint64'},
        {'name': 'mkto_lead_product_score_redis', 'required': False, 'type': 'uint64'},
        {'name': 'mkto_lead_product_score_s3', 'required': False, 'type': 'uint64'},
        {'name': 'mkto_lead_product_score_speechkit', 'required': False, 'type': 'uint64'},
        {'name': 'mkto_lead_product_score_translate', 'required': False, 'type': 'uint64'},
        {'name': 'mkto_lead_product_score_vpc', 'required': False, 'type': 'uint64'},
        {'name': 'mkto_lead_scenario_score_analytics', 'required': False, 'type': 'uint64'},
        {'name': 'mkto_lead_scenario_score_archive', 'required': False, 'type': 'uint64'},
        {'name': 'mkto_lead_scenario_score_dr', 'required': False, 'type': 'uint64'},
        {'name': 'mkto_lead_scenario_score_test_dev', 'required': False, 'type': 'uint64'},
        {'name': 'mkto_lead_scenario_score_web', 'required': False, 'type': 'uint64'},
        {'name': 'mkto_lead_score', 'required': False, 'type': 'uint64'},
        {'name': 'mkto_lead_source', 'required': False, 'type': 'string'},
        {'name': 'mkto_lead_status', 'required': False, 'type': 'string'},
        {'name': 'mkto_mail_billing', 'required': False, 'type': 'boolean'},
        {'name': 'mkto_mail_event', 'required': False, 'type': 'boolean'},
        {'name': 'mkto_mail_feature', 'required': False, 'type': 'boolean'},
        {'name': 'mkto_mail_info', 'required': False, 'type': 'boolean'},
        {'name': 'mkto_mail_marketing', 'required': False, 'type': 'boolean'},
        {'name': 'mkto_mail_promo', 'required': False, 'type': 'boolean'},
        {'name': 'mkto_mail_support', 'required': False, 'type': 'boolean'},
        {'name': 'mkto_mail_tech', 'required': False, 'type': 'boolean'},
        {'name': 'mkto_mail_technical', 'required': False, 'type': 'boolean'},
        {'name': 'mkto_mail_testing', 'required': False, 'type': 'boolean'},
        {'name': 'mkto_person_id', 'required': False, 'type': 'string'},
        {'name': 'mkto_role', 'required': False, 'type': 'string'},
        {'name': 'mkto_sales_owner_email', 'required': False, 'type': 'string'},
        {'name': 'mkto_sales_owner_first_name', 'required': False, 'type': 'string'},
        {'name': 'mkto_sales_owner_job_title', 'required': False, 'type': 'string'},
        {'name': 'mkto_sales_owner_last_name', 'required': False, 'type': 'string'},
        {'name': 'mkto_sales_owner_phone', 'required': False, 'type': 'string'}
    ])
    schema.attributes['unique_keys'] = True
    schema.attributes['strict'] = True
    yt.create('table', table.yt_table_path, attributes={"schema": schema, "dynamic": True})
    yt.mount_table(table.yt_table_path, sync=True)
