value_streams = {
    "searchqualityassessment": {"vs_name": "Краудсорсинг (VS)", "oebs_service": "SE902", "vs_abc_id": "2608"},
    "travel": {"vs_name": "Яндекс.Путешествия", "oebs_service": "SE950", "vs_abc_id": "2825"},
    "ymapsapi": {"vs_name": "API Карт", "oebs_service": "GE735", "vs_abc_id": "32989"},
    "voice": {"vs_name": "Алиса и Умные устройства (VS)", "oebs_service": "SE930", "vs_abc_id": "675"},
    "yauto": {"vs_name": "Яндекс Авто", "oebs_service": "GE715", "vs_abc_id": "32988"},
    "meta_personalandinfrastructure": {"vs_name": "Экосистема (VS)", "oebs_service": "IN100", "vs_abc_id": "4446"},
    "vsmarketing": {"vs_name": "Маркетинг (VS)", "oebs_service": "PS002", "vs_abc_id": "32986"},
    "security": {"vs_name": "Безопасность (VS)", "oebs_service": "YS100", "vs_abc_id": "909"},
    "meta_infra": {"vs_name": "Инфраструктура (VS)", "oebs_service": "IN119", "vs_abc_id": "850"},
    "mapscontent": {"vs_name": "Производство контента карт", "oebs_service": "GE726", "vs_abc_id": "32994"},
    "ymapsapisales": {"vs_name": "API Карт Sales", "oebs_service": "GE104", "vs_abc_id": "33710"},
    "mapsservices": {"vs_name": "Сервисы Геоплатформы", "oebs_service": "GE724", "vs_abc_id": "32996"},
    "orgsservices": {"vs_name": "Геопоисковые сервисы", "oebs_service": "GE725", "vs_abc_id": "32997"},
    "ad": {"vs_name": "Реклама", "oebs_service": "SE947", "vs_abc_id": "31735"},
    "b2cmaps": {"vs_name": "Геоприложения B2C", "oebs_service": "GE728", "vs_abc_id": "32990"},
    "b2broutingsales": {"vs_name": "Яндекс.Маршрутизация Sales", "oebs_service": "GE733", "vs_abc_id": "33190"},
    "vs_translator": {"vs_name": "Переводчик (VS)", "oebs_service": "MT100", "vs_abc_id": "31797"},
    "orgscontent": {"vs_name": "Производство контента справочника", "oebs_service": "VR330", "vs_abc_id": "32995"},
    "fintechnologies": {"vs_name": "Финансовые технологии", "oebs_service": "EX111", "vs_abc_id": "32937"},
    "discovery": {"vs_name": "Сервисы Дзен", "oebs_service": "DP800", "vs_abc_id": "1164"},
    "answ": {"vs_name": "Яндекс.Кью (VS)", "oebs_service": "SP350", "vs_abc_id": "1920"},
    "b2brouting": {"vs_name": "Яндекс.Маршрутизация", "oebs_service": "GE115", "vs_abc_id": "32987"},
    "ydo": {"vs_name": "Услуги (VS)", "oebs_service": "VR320", "vs_abc_id": "2776"},
    "meta_personal": {"vs_name": "Персональные сервисы", "oebs_service": "CM300", "vs_abc_id": "847"},
    "vs_search": {"vs_name": "Поиск (VS)", "oebs_service": "SE946", "vs_abc_id": "31752"},
    "onlineeducation": {"vs_name": "Сервисы Яндекс.Образования", "oebs_service": "HR110", "vs_abc_id": "1536"},
    "edadeal": {"vs_name": "Сервисы \"Едадил\"", "oebs_service": "EX105", "vs_abc_id": "1775"},
    "cloud": {"vs_name": "Яндекс.Облако", "oebs_service": "MA110", "vs_abc_id": "1415"},
    "fintech": {"vs_name": "Инвестиции", "oebs_service": "EX110", "vs_abc_id": "3173"},
    "tools": {"vs_name": "Tools (VS)", "oebs_service": "IN110", "vs_abc_id": "872"},
    "vspr": {"vs_name": "PR (VS)", "oebs_service": "PS001", "vs_abc_id": "32924"},
    "yandex-tanker": {"vs_name": "Заправки", "oebs_service": "GE119", "vs_abc_id": "2588"},
    "meta_portalservices": {"vs_name": "Платформа (VS)", "oebs_service": "SE948", "vs_abc_id": "4447"},
    "vs_infoservices": {"vs_name": "Информационные сервисы", "oebs_service": "SE949", "vs_abc_id": "31736"}
}
