#!/bin/sh
# postinst script for mdb-config-salt-v3
#
# see: dh_installdeb(1)

set -e

case "$1" in
    configure)
        if [[ $(which systemctl) ]]; then
            systemctl stop salt-minion || true
            systemctl disable salt-minion 2> /dev/null || true
        fi
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
