package patches.projects

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.Project
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a project with id = 'Nbs_RestoreTests'
in the project with id = 'Nbs', and delete the patch script.
*/
create(RelativeId("Nbs"), Project({
    id("Nbs_RestoreTests")
    name = "Restore Tests"
    description = "Под проект для restore тестов"
}))

