package patches.projects

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.CustomChart
import jetbrains.buildServer.configs.kotlin.v2019_2.CustomChart.*
import jetbrains.buildServer.configs.kotlin.v2019_2.Project
import jetbrains.buildServer.configs.kotlin.v2019_2.buildTypeCustomChart
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a project with id = 'Nbs_LocalTests_Stable224_FunctionalTests'
in the project with id = 'Nbs_LocalTests_Stable224', and delete the patch script.
*/
create(RelativeId("Nbs_LocalTests_Stable224"), Project({
    id("Nbs_LocalTests_Stable224_FunctionalTests")
    name = "Functional Tests"
    archived = true

    params {
        param("env.TEST_TARGETS", "cloud/blockstore/tests/functional")
    }

    features {
        buildTypeCustomChart {
            id = "PROJECT_EXT_1269"
            title = "Total build time"
            seriesTitle = "Serie"
            format = CustomChart.Format.DURATION
            series = listOf(
                Serie(title = "Build Duration (all stages)", key = SeriesKey.BUILD_DURATION)
            )
        }
    }
    buildTypesOrderIds = arrayListOf(RelativeId("Nbs_LocalTests_Stable224_FunctionalTests_FunctionalTestsRelwithdebinfo"), RelativeId("Nbs_LocalTests_Stable224_FunctionalTests_FunctionalTestsReleaseHardening"), RelativeId("Nbs_LocalTests_Stable224_FunctionalTests_FunctionalTestsReleaseAddressSanitizer"), RelativeId("Nbs_LocalTests_Stable224_FunctionalTests_FunctionalTestsReleaseMemorySanitizer"), RelativeId("Nbs_LocalTests_Stable224_FunctionalTests_FunctionalTestsReleaseThreadSanitizer"), RelativeId("Nbs_LocalTests_Stable224_FunctionalTests_FunctionalTestsReleaseUbSanitizer"))
}))

