package patches.projects

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.CustomChart
import jetbrains.buildServer.configs.kotlin.v2019_2.CustomChart.*
import jetbrains.buildServer.configs.kotlin.v2019_2.Project
import jetbrains.buildServer.configs.kotlin.v2019_2.buildTypeCustomChart
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a project with id = 'Nfs_LocalTests_Stable224_LoadTestsNoAgentBuilds'
in the project with id = 'Nfs_LocalTests_Stable224', and delete the patch script.
*/
create(RelativeId("Nfs_LocalTests_Stable224"), Project({
    id("Nfs_LocalTests_Stable224_LoadTestsNoAgentBuilds")
    name = "Load Tests (No-agent builds)"

    params {
        param("env.TEST_TARGETS", "cloud/blockstore/tests/functional")
    }

    features {
        buildTypeCustomChart {
            id = "PROJECT_EXT_1271"
            title = "Total build time"
            seriesTitle = "Serie"
            format = CustomChart.Format.DURATION
            series = listOf(
                Serie(title = "Build Duration (all stages)", key = SeriesKey.BUILD_DURATION)
            )
        }
    }
    buildTypesOrderIds = arrayListOf(RelativeId("Nfs_LocalTests_Stable224_LoadTestsNoAgentBuilds_LoadTestsRelwithdebinfo"), RelativeId("Nfs_LocalTests_Stable224_LoadTestsNoAgentBuilds_LoadTestsReleaseHardening"), RelativeId("Nfs_LocalTests_Stable224_LoadTestsNoAgentBuilds_LoadTestsReleaseAddressSanitizer"), RelativeId("Nfs_LocalTests_Stable224_LoadTestsNoAgentBuilds_LoadTestsReleaseMemorySanitizer"), RelativeId("Nfs_LocalTests_Stable224_LoadTestsNoAgentBuilds_LoadTestsReleaseThreadSanitizer"), RelativeId("Nfs_LocalTests_Stable224_LoadTestsNoAgentBuilds_LoadTestsReleaseUbSanitizer"))
}))

