# put data into node1
POST http://{{host1}}:{{http_port}}/{{test_index}}/_doc/
Content-Type: application/json


{
    "host": "{{host1}}",
    "N": {{$randomInt}},
    "user" : "kimchy",
    "post_date" : "{{$timestamp}}",
    "message" : "trying out Elasticsearch",
    "dc": "{{dc}}",
    "timestamp" : {{$timestamp}}
}

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 201, "Response status is not 201");
});
%}

### put data into node2
POST http://{{host2}}:{{http_port}}/{{test_index}}/_doc/
Content-Type: application/json


{
    "host": "{{host2}}",
    "N": {{$randomInt}},
    "user" : "kimchy",
    "post_date" : "{{$timestamp}}",
    "message" : "trying out Elasticsearch",
    "dc": "{{dc}}",
    "timestamp" : {{$timestamp}}
}

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 201, "Response status is not 201");
});
%}

### put data into node3
POST http://{{host3}}:{{http_port}}/{{test_index}}/_doc/
Content-Type: application/json


{
    "host": "{{host3}}",
    "N": {{$randomInt}},
    "user" : "kimchy",
    "post_date" : "{{$timestamp}}",
    "message" : "trying out Elasticsearch",
    "dc": "{{dc}}",
    "timestamp" : {{$timestamp}}
}

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 201, "Response status is not 201");
});
%}

### search query into node1
GET http://{{host1}}:{{http_port}}/{{test_index}}/_search?q=user:kimchy

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
});

client.test("Got search results", function() {
  client.assert(response.body.hasOwnProperty("hits"), "Cannot find 'hits' option in response");
});
%}

### search query into node2
GET http://{{host2}}:{{http_port}}/{{test_index}}/_search?q=user:kimchy

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
});

client.test("Got search results", function() {
  client.assert(response.body.hasOwnProperty("hits"), "Cannot find 'hits' option in response");
});
%}

### get list of indexes from node1
GET http://{{host1}}:{{http_port}}/_cat/indices?v&s=index:desc

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
});
%}

### get list of indexes from node2
GET http://{{host2}}:{{http_port}}/_cat/indices?v&s=index:desc

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
});
%}

### get list of indexes from node3
GET http://{{host3}}:{{http_port}}/_cat/indices?v&s=index:desc

> {%
client.test("Request executed successfully", function() {
  client.assert(response.status === 200, "Response status is not 200");
});
%}

###
GET http://{{host3}}:{{http_port}}/_nodes

###