#!/usr/bin/env python

"""Script for checking test environment."""

from __future__ import print_function

import os
import sys

sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '..')))
import gencfg

import core.db

print(core.db.__file__)
print(core.db.CURDB.PATH)
