Document: yandex-conf-repo-media-common-testing
Title: Debian yandex-conf-repo-media-common-testing Manual
Author: <insert document author here>
Abstract: This manual describes what yandex-conf-repo-media-common-testing is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/yandex-conf-repo-media-common-testing/yandex-conf-repo-media-common-testing.sgml.gz

Format: postscript
Files: /usr/share/doc/yandex-conf-repo-media-common-testing/yandex-conf-repo-media-common-testing.ps.gz

Format: text
Files: /usr/share/doc/yandex-conf-repo-media-common-testing/yandex-conf-repo-media-common-testing.text.gz

Format: HTML
Index: /usr/share/doc/yandex-conf-repo-media-common-testing/html/index.html
Files: /usr/share/doc/yandex-conf-repo-media-common-testing/html/*.html
