OWNER(g:cs_dev)

RECURSE(abstract)
RECURSE(api)
RECURSE(auth)
RECURSE(common)
RECURSE(geoareas)
RECURSE(geobase)
RECURSE(handlers)
RECURSE(library)
RECURSE(locks)
RECURSE(notifications)
RECURSE(personal_data)
RECURSE(processors)
RECURSE(proto)
RECURSE(report)
RECURSE(roles)
RECURSE(rt_background)
RECURSE(server)
RECURSE(settings)
RECURSE(tags)
RECURSE(user_auth)
RECURSE(user_role)
RECURSE(ut)
RECURSE(util)
RECURSE(solutions/server_template/src)
RECURSE(solutions/fallback_proxy/src)
RECURSE(solutions/fallback_proxy/ut)

IF (NOT OS_WINDOWS)
    RECURSE(service_monitor)
ENDIF()
