#!/bin/bash -e

#DEBHELPER#

USER="media-graphite-sender"
SYSV="/etc/init.d/media-graphite-sender"

if id -u $USER >/dev/null 2>&1; then
    chown -R ${USER}:${USER} /var/log/graphite-sender
    chown -R ${USER}:${USER} /var/spool/graphite-sender
    chown -R ${USER}:${USER} /etc/graphite-sender
fi

if [ -f $SYSV ]; then
    chmod 755 $SYSV
fi
if [ -d /run/systemd/system ]; then
    systemctl --system daemon-reload >/dev/null || true
fi

mkdir -vp /etc/graphite-sender/
touch /etc/graphite-sender/config.yaml
service media-graphite-sender start || true
