#!/bin/bash -e
#
# summary of how this script can be called:
#        * <new-preinst> install
#        * <new-preinst> install <old-version>
#        * <new-preinst> upgrade <old-version>
#        * <old-preinst> abort-upgrade <new-version>
#

#DEBHELPER#


# creating media-graphites-sender group if he isn't already there
if ! getent group media-graphite-sender >/dev/null; then
        # Adding system group: media-graphite-sender.
        addgroup --system media-graphite-sender >/dev/null
fi

# creating media-graphite-sender if he isn't already there
if ! getent passwd media-graphite-sender >/dev/null; then
        # Adding system user: media-graphite-sender.
        adduser \
          --system \
          --disabled-login \
          --ingroup media-graphite-sender \
          --no-create-home \
          --home /nonexistent \
          --gecos "media-graphite-sender" \
          --shell /bin/false \
          media-graphite-sender  >/dev/null
fi
exit 0
