# This file is generated by
# https://bb.yandex-team.ru/projects/CLOUD/repos/cloud-go/browse/tools/cmd/syncapi
# in Teamcity Task
# https://teamcity.yandex-team.ru/buildConfiguration/Cloud_Api_ApiSync

OWNER(g:cloud-api)
PROTO_LIBRARY()

PROTO_NAMESPACE(GLOBAL cloud/bitbucket/public-api)
PY_NAMESPACE(yandex.cloud.apploadbalancer.v1)

GRPC()
SRCS(
    backend_group.proto
    backend_group_service.proto
    http_router.proto
    http_router_service.proto
    load_balancer.proto
    load_balancer_service.proto
    payload.proto
    target_group.proto
    target_group_service.proto
    tls.proto
    virtual_host.proto
    virtual_host_service.proto
)

USE_COMMON_GOOGLE_APIS(
    api/annotations
    rpc/code
    rpc/errdetails
    rpc/status
    type/timeofday
    type/dayofweek
)

IF (GO_PROTO)
    PEERDIR(
        cloud/bitbucket/common-api/yandex/cloud/api
        cloud/bitbucket/common-api/yandex/cloud/api/tools
        cloud/bitbucket/public-api/yandex/cloud
        cloud/bitbucket/public-api/yandex/cloud/operation
    )
ELSE()
    PEERDIR(
        cloud/bitbucket/common-api/yandex/cloud/api
        cloud/bitbucket/common-api/yandex/cloud/api/tools
        cloud/bitbucket/public-api/yandex/cloud
        cloud/bitbucket/public-api/yandex/cloud/operation
    )
ENDIF()
END()

