CREATE OR REPLACE FUNCTION dbaas.active_cluster_status(
    dbaas.cluster_status
) RETURNS bool AS $$
SELECT $1 NOT IN (
    'RESTORING-OFFLINE',
    'RESTORE-OFFLINE-ERROR',
    'MAINTAINING-OFFLINE',
    'MAINTAIN-OFFLINE-ERROR',
    'STOPPING',
    'STOP-ERROR',
    'STOPPED',
    'DELETING',
    'DELETE-ERROR',
    'DELETED',
    'METADATA-DELETING',
    'METADATA-DELETE-ERROR',
    'METADATA-DELETED',
    'PURGING',
    'PURGE-ERROR',
    'PURGED'
);
$$ LANGUAGE SQL IMMUTABLE;
