#!/bin/bash

while getopts 'd:q:f:' OPT
do
  case "$OPT" in
    d)
      DB="$OPTARG"
      ;;
    q)
      QUERY="$OPTARG"
      ;;
    f)
      SQL_FILE="$OPTARG"
      ;;
    h|*)
      echo "Script usage: $(basename $0) -d DATABASE [-q QUERY] | [-f SQL_FILE]"
      exit 1
      ;;
  esac
done

# Check DB
if [ -z "$DB" ]
then
  echo "No DB provided"
  exit 1
fi


# Execute QUERY
if [ -n "$QUERY" ]
then
  /usr/bin/mysql --defaults-file=/root/.my.cnf --safe-updates -A "$DB" -e "$QUERY"
# Else execute SQL_FILE
elif [ -n "$SQL_FILE" ]
then
  if [ -f "$SQL_FILE" ]
  then
    /usr/bin/mysql --defaults-file=/root/.my.cnf --safe-updates -A "$DB" < "$SQL_FILE"
  else
    echo "SQL_FILE '$SQL_FILE' doesn't exist"
    exit 1
  fi
# Nothing to execute
else
  echo "Neither QUERY nor SQL_FILE provided"
  exit 1
fi
