install:
	install -d $(DESTDIR)/etc/yandex/salt/
	install -m755 $(CURDIR)/src/etc/yandex/salt/minion.tpl $(DESTDIR)/etc/yandex/salt/
	install -d $(DESTDIR)/usr/bin/
	install -m755 $(CURDIR)/src/usr/bin/salt_update $(DESTDIR)/usr/bin/
