GRANT USAGE ON SCHEMA s3 TO s3api;
GRANT ALL ON ALL SEQUENCES IN SCHEMA s3 TO s3api;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA s3 TO s3api;

GRANT USAGE ON SCHEMA v1_code TO s3api;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA v1_code TO s3api;

GRANT USAGE ON SCHEMA v1_impl TO s3api;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA v1_impl TO s3api;

GRANT USAGE ON SCHEMA util TO s3api;
REVOKE EXECUTE ON ALL FUNCTIONS IN SCHEMA util FROM s3api;
GRANT EXECUTE ON FUNCTION util.update_chunks_counters(int) TO s3api;
