PRAGMA Library("datetime.sql");
PRAGMA Library("helpers.sql");

IMPORT `datetime` SYMBOLS $get_datetime, $get_timestamp_from_days;
IMPORT `helpers` SYMBOLS $get_md5;

$src_table = {{ param["source_table_path"]->quote() }};
$dst_table = {{ input1->table_quote() }};
$pii_dst_table = {{ param["pii_destination_path"] -> quote() }};

$toString = ($data) -> (CAST($data AS String));
$decode_utf8 = ($data) -> (nvl(cast(String::Base64StrictDecode($data) as Utf8),$data));

$get_timestamp = ($ts) -> (CAST($ts AS TimeStamp));
$from_utc_ts_to_msk_dt = ($ts) -> (DateTime::MakeDatetime(DateTime::Update(AddTimeZone($ts, "Europe/Moscow"), "GMT"  as Timezone)));

$result = (
    SELECT
        $toString(`acl_team_set_id`)	                                                        AS	acl_crm_team_set_id,
        $toString(`alt_address_city`)	                                                        AS	alt_address_city,
        $toString(`alt_address_country`)	                                                    AS	alt_address_country,
        $toString(`alt_address_postalcode`)	                                                    AS	alt_address_postalcode,
        $toString(`alt_address_state`)	                                                        AS	alt_address_state,
        $toString(`alt_address_street`)	                                                        AS	alt_address_street,
        $toString(`assigned_user_id`)	                                                        AS	assigned_user_id,
        $toString(`assistant`)	                                                                AS	assistant,
        $toString(`assistant_phone`)	                                                        AS	assistant_phone,
        $toString(`birthdate`)	                                                                AS	birthdate,
        $toString(`campaign_id`)	                                                            AS	campaign_id,
        $toString(`country_name_phone_mobile`)	                                                AS	country_name_phone_mobile,
        CAST(`country_verified_phone_mobile` AS bool) 	                                        AS	country_verified_phone_mobile,
        $toString(`created_by`)	                                                                AS	created_by,
        $get_datetime($get_timestamp_from_days(CAST(`date_entered` AS Uint64)))                 AS	date_entered,
        $get_timestamp(`date_entered`)                                                          AS	date_entered_ts,
        $from_utc_ts_to_msk_dt($get_timestamp(`date_entered`))                                  AS	date_entered_dttm_local,
        $get_datetime($get_timestamp_from_days(CAST(`date_modified` AS Uint64)))                AS	date_modified,
        $get_timestamp(`date_modified`)                                                         AS	date_modified_ts,
        $from_utc_ts_to_msk_dt($get_timestamp(`date_modified`))                                 AS	date_modified_dttm_local,
        CAST(`deleted` AS bool) 	                                                            AS  deleted,
        $toString(`department`)	                                                                AS	department,
        $toString($decode_utf8(`description`))	                                                AS	crm_contact_description,
        $toString(`dnb_principal_id`)	                                                        AS	dnb_principal_id,
        CAST(`do_not_call` AS bool)	                                                            AS	do_not_call,
        CAST(`do_not_mail` AS bool)	                                                            AS	do_not_mail,
        $toString(`dp_business_purpose`)	                                                    AS	dp_business_purpose,
        `dp_consent_last_updated`	                                                            AS	dp_consent_last_updated,
        $toString(`dri_workflow_template_id`)	                                                AS	dri_workflow_template_id,
        $toString(`facebook`)	                                                                AS	facebook,
        $toString(`first_name`)	                                                                AS	first_name,
        $toString(`googleplus`)	                                                                AS	googleplus,
        $toString(`id`)	                                                                        AS	crm_contact_id,
        $get_timestamp_from_days(CAST(`last_communication_date` AS Uint64))                    AS	last_communication_date,
        $get_timestamp(`last_communication_date`)                                               AS	last_communication_date_ts,
        $from_utc_ts_to_msk_dt($get_timestamp(`last_communication_date`))                       AS	last_communication_date_dttm_local,
        $toString(`last_name`)	                                                                AS	last_name,
        $toString(`lead_source`)	                                                            AS	lead_source,
        $toString(`linkedin`)	                                                                AS	linkedin,
        $toString(`modified_user_id`)	                                                        AS	modified_user_id,
        CAST(`old_format_dimensions` AS bool)	                                                AS	old_format_dimensions,
        $toString(`phone_fax`)	                                                                AS	phone_fax,
        $toString(`phone_home`)	                                                                AS	phone_home,
        $toString(`phone_mobile`)	                                                            AS	phone_mobile,
        $toString(`phone_other`	)                                                               AS	phone_other,
        $toString(`phone_work`)	                                                                AS	phone_work,
        $toString(`picture`)	                                                                AS	picture,
        CAST(`portal_active` AS bool)	                                                        AS	portal_active,
        $toString(`portal_app`)	                                                                AS	portal_app,
        $toString(`portal_name`)	                                                            AS	portal_name,
        $toString(`portal_password`)	                                                        AS	portal_password,
        $toString(`preferred_language`)	                                                        AS	preferred_language,
        $toString(`primary_address_city`)	                                                    AS	primary_address_city,
        $toString(`primary_address_country`)	                                                AS	primary_address_country,
        $toString(`primary_address_postalcode`)	                                                AS	primary_address_postalcode,
        $toString(`primary_address_state`)	                                                    AS	primary_address_state,
        $toString(`primary_address_street`)	                                                    AS	primary_address_street,
        $toString(`reports_to_id`)	                                                            AS	reports_to_id,
        $toString(`salutation`)	                                                                AS	salutation,
        $toString(`team_id`)	                                                                AS	crm_team_id,
        $toString(`team_set_id`)	                                                            AS	crm_team_set_id,
        $toString(`telegram_account`)	                                                        AS	telegram_account,
        $toString(`timezone`)	                                                                AS	timezone,
        $toString(`title`)	                                                                    AS	title,
        $toString(`twitter`)	                                                                AS	twitter,
        $toString(`whatsapp_account`)	                                                        AS	whatsapp_account
    FROM $src_table
);

/* Save result in ODS */
INSERT INTO $dst_table WITH TRUNCATE
SELECT 
    acl_crm_team_set_id                                                             AS	acl_crm_team_set_id,
    $get_md5(alt_address_city)                                                      AS	alt_address_city_hash,
    $get_md5(alt_address_country)                                                   AS	alt_address_country_hash,
    $get_md5(alt_address_postalcode)                                                AS	alt_address_postalcode_hash,
    $get_md5(alt_address_state)                                                     AS	alt_address_state_hash,
    $get_md5(alt_address_street)                                                    AS	alt_address_street_hash,
    assigned_user_id                                                                AS	assigned_user_id,
    $get_md5(assistant)                                                             AS	assistant_hash,
    $get_md5(assistant_phone)                                                       AS	assistant_phone_hash,
    $get_md5(birthdate)                                                             AS	birthdate_hash,
    campaign_id                                                                     AS	campaign_id,
    country_name_phone_mobile                                                       AS	country_name_phone_mobile,
    country_verified_phone_mobile                                                   AS	country_verified_phone_mobile,
    created_by                                                                      AS	created_by,
    date_entered                                                                    AS	date_entered,
    date_entered_ts                                                                 AS	date_entered_ts,
    date_entered_dttm_local                                                         AS	date_entered_dttm_local,
    date_modified                                                                   AS	date_modified,
    date_modified_ts                                                                AS	date_modified_ts,
    date_modified_dttm_local                                                        AS	date_modified_dttm_local,
    deleted                                                                         AS  deleted,
    department                                                                      AS	department,
    crm_contact_description                                                         AS	crm_contact_description,
    dnb_principal_id                                                                AS	dnb_principal_id,
    do_not_call                                                                     AS	do_not_call,
    do_not_mail                                                                     AS	do_not_mail,
    dp_business_purpose                                                             AS	dp_business_purpose,
    dp_consent_last_updated                                                         AS	dp_consent_last_updated,
    dri_workflow_template_id                                                        AS	dri_workflow_template_id,
    $get_md5(facebook)                                                              AS	facebook_hash,
    $get_md5(first_name)                                                            AS	first_name_hash,
    $get_md5(googleplus)                                                            AS	googleplus_hash,
    crm_contact_id                                                                  AS	crm_contact_id,
    last_communication_date                                                         AS	last_communication_date,
    last_communication_date_ts                                                      AS	last_communication_date_ts,
    last_communication_date_dttm_local                                              AS	last_communication_date_dttm_local,
    $get_md5(last_name)                                                             AS	last_name_hash,
    lead_source                                                                     AS	lead_source,
    $get_md5(linkedin)                                                              AS	linkedin_hash,
    modified_user_id                                                                AS	modified_user_id,
    old_format_dimensions                                                           AS	old_format_dimensions,
    $get_md5(phone_fax)                                                             AS	phone_fax_hash,
    $get_md5(phone_home)                                                            AS	phone_home_hash,
    $get_md5(phone_mobile)                                                          AS	phone_mobile_hash,
    $get_md5(phone_other)                                                           AS	phone_other_hash,
    $get_md5(phone_work)                                                            AS	phone_work_hash,
    picture                                                                         AS	picture,
    portal_active                                                                   AS	portal_active,
    portal_app                                                                      AS	portal_app,
    portal_name                                                                     AS	portal_name,
    $get_md5(portal_password)                                                       AS	portal_password_hash,
    preferred_language                                                              AS	preferred_language,
    $get_md5(primary_address_city)                                                  AS	primary_address_city_hash,
    $get_md5(primary_address_country)                                               AS	primary_address_country_hash,
    $get_md5(primary_address_postalcode)                                            AS	primary_address_postalcode_hash,
    $get_md5(primary_address_state)                                                 AS	primary_address_state_hash,
    $get_md5(primary_address_street)                                                AS	primary_address_street_hash,
    reports_to_id                                                                   AS	reports_to_id,
    salutation                                                                      AS	salutation,
    crm_team_id                                                                     AS	crm_team_id,
    crm_team_set_id                                                                 AS	crm_team_set_id,
    $get_md5(telegram_account)                                                      AS	telegram_account_hash,
    timezone                                                                        AS	timezone,
    title                                                                           AS	title,
    $get_md5(twitter)                                                               AS	twitter_hash,
    $get_md5(whatsapp_account)                                                      AS	whatsapp_account_hash
FROM $result
;

/* Save result in ODS PII*/
INSERT INTO $pii_dst_table WITH TRUNCATE
SELECT 
    crm_contact_id                                                                  AS  crm_contact_id,
    alt_address_city                                                                AS  alt_address_city,
    alt_address_country                                                             AS  alt_address_country,
    alt_address_postalcode                                                          AS  alt_address_postalcode,
    alt_address_state                                                               AS  alt_address_state,
    alt_address_street                                                              AS  alt_address_street,
    assistant                                                                       AS  assistant,
    assistant_phone                                                                 AS  assistant_phone,
    birthdate                                                                       AS  birthdate,
    facebook                                                                        AS  facebook,
    first_name                                                                      AS  first_name,
    googleplus                                                                      AS  googleplus,
    last_name                                                                       AS  last_name,
    linkedin                                                                        AS  linkedin,
    phone_fax                                                                       AS  phone_fax,
    phone_home                                                                      AS  phone_home,
    phone_mobile                                                                    AS  phone_mobile,
    phone_other                                                                     AS  phone_other,
    phone_work                                                                      AS  phone_work,
    portal_password                                                                 AS  portal_password,
    primary_address_city                                                            AS  primary_address_city,
    primary_address_country                                                         AS  primary_address_country,
    primary_address_postalcode                                                      AS  primary_address_postalcode,
    primary_address_state                                                           AS  primary_address_state,
    primary_address_street                                                          AS  primary_address_street,
    telegram_account                                                                AS  telegram_account,
    twitter                                                                         AS  twitter,
    whatsapp_account                                                                AS  whatsapp_account
FROM $result
;
