Document: yandex-conf-repo-media-common-prestable
Title: Debian yandex-conf-repo-media-common-prestable Manual
Author: <insert document author here>
Abstract: This manual describes what yandex-conf-repo-media-common-prestable is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/yandex-conf-repo-media-common-prestable/yandex-conf-repo-media-common-prestable.sgml.gz

Format: postscript
Files: /usr/share/doc/yandex-conf-repo-media-common-prestable/yandex-conf-repo-media-common-prestable.ps.gz

Format: text
Files: /usr/share/doc/yandex-conf-repo-media-common-prestable/yandex-conf-repo-media-common-prestable.text.gz

Format: HTML
Index: /usr/share/doc/yandex-conf-repo-media-common-prestable/html/index.html
Files: /usr/share/doc/yandex-conf-repo-media-common-prestable/html/*.html
