RECURSE(
    adaptors
    adaptors/ut
    algorithm
    array4d
    blob_storage
    chunked_wad
    chunked_wad/protos
    chunked_wad/ut
    counts
    direct_io
    doc_lump_fetcher
    enums
    erasure
    erasure/ut
    flat_blob_storage/ut
    hits
    index_format_processor
    index_format_processor/ut
    info
    info/ut
    item_storage
    item_storage/proto
    item_storage/test
    key
    key/ut
    keyinv_offroad_portions
    keyinv_offroad_portions/standard_ranges
    keyinv_offroad_portions/ut
    kosher_offroad_portions
    kosher_offroad_portions/ut
    offroad
    offroad/ut
    offroad_ann_data_wad
    offroad_ann_data_wad/ut
    offroad_ann_data_wad_accessor
    offroad_ann_data_wad_accessor/ut
    offroad_attributes_wad
    offroad_block_string_wad
    offroad_block_wad
    offroad_common
    offroad_doc_attrs_wad
    offroad_doc_wad
    offroad_doc_wad/benchmark
    offroad_doc_wad/ut
    offroad_double_panther_wad
    offroad_erf_wad
    offroad_hashed_keyinv_wad
    offroad_hashed_keyinv_wad/benchmark
    offroad_hashed_keyinv_wad/ut
    offroad_herf_wad
    offroad_inv_wad
    offroad_inv_wad/ut
    offroad_invhash_wad
    offroad_invhash_wad/ut
    offroad_key_wad
    offroad_key_wad/ut
    offroad_keyinv_wad
    offroad_keyinv_wad/benchmark
    offroad_keyinv_wad/ut
    offroad_minhash_wad
    offroad_minhash_wad/ut
    offroad_omni_wad
    offroad_reg_herf_wad
    offroad_reg_herf_wad/ut
    offroad_sent_wad
    offroad_sent_wad_accessor
    offroad_sent_wad_accessor/ut
    offroad_struct_diff_wad
    offroad_struct_diff_wad/ut
    offroad_struct_wad
    offroad_struct_wad/benchmark
    offroad_struct_wad/ut
    offroad_wad
    offroad_wad/ut
    progress
    realtime
    search_fetcher
    simple_map
    simple_map/ut
    standard_models
    standard_models_storage
    wad
    wad/ut
    wrangler_layer
    yandex
    yandex/ut
)

IF (NOT OS_WINDOWS)
    RECURSE(
        offroad_minhash_wad/bench
    )
ENDIF()
