GRANT CONNECT ON DATABASE mlockdb TO mdb_ui;
GRANT USAGE ON SCHEMA mlock TO mdb_ui;
GRANT SELECT ON ALL TABLES IN SCHEMA mlock TO mdb_ui;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA mlock TO mdb_ui;
GRANT USAGE ON SCHEMA code TO mdb_ui;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA code TO mdb_ui;
