GRANT USAGE ON SCHEMA mlock TO mlock;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA mlock TO mlock;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA mlock TO mlock;
GRANT USAGE ON SCHEMA code TO mlock;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA code TO mlock;
GRANT SELECT ON TABLE public.schema_version TO mlock;
