{
 "title": "k8s-lights",
 "tags": [
  "ycp",
  "ycp-mk8s",
  "ycp-mk8s-lights",
  "ycp-duty"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": " 20s",
 "templating": {
  "list": [
   { "name": "cluster", "query": "prod,preprod" }
  ]
 },
 "panels": [
  {
   "title": "API Gateway Managed Kubernetes lights ($cluster)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "API Gateway Managed Kubernetes rps ($cluster) (current)",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 6, "x": 0, "y": 1 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "groupBy": [
        { "params": [ "15s" ], "type": "time" }
       ],
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         },
         {
          "params": [],
          "type": "non_negative_derivative"
         },
         { "params": [ "sum" ], "type": "group_lines" }
        ]
       ],
       "tags": {
        "cluster": "cloud_${cluster}_api-gateway",
        "grpc_method": "!all",
        "grpc_service": "yandex.cloud.k8s.v1.*",
        "host": "!cluster",
        "name": "grpc_server_request_total",
        "project": "platform",
        "service": "api_gateway_ma"
       },
       "target": "group_lines('sum', non_negative_derivative(group_by_time(15s, 'max', {'cluster'='cloud_${cluster}_api-gateway', 'grpc_method'!='all', 'grpc_service'='yandex.cloud.k8s.v1.*', 'host'!='cluster', 'name'='grpc_server_request_total', 'project'='platform', 'service'='api_gateway_ma'})))",
       "type": "timeserie"
      }
     ]
    },
    {
     "title": "API Gateway Managed Kubernetes 5xx errors ($cluster) (total)",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 6, "x": 6, "y": 1 },
     "format": "none",
     "valueName": "total",
     "targets": [
      {
       "groupBy": [
        { "params": [ "15s" ], "type": "time" }
       ],
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         },
         {
          "params": [],
          "type": "diff"
         },
         { "params": [ "0" ], "type": "drop_below" },
         { "params": [ "sum" ], "type": "group_lines" }
        ]
       ],
       "tags": {
        "cluster": "cloud_${cluster}_api-gateway",
        "grpc_code": "Unknown|DeadlineExceeded|Unimplemented|Internal|DataLoss|Unavailable",
        "grpc_method": "!all",
        "grpc_service": "yandex.cloud.k8s.v1.*",
        "host": "!cluster",
        "name": "grpc_server_response_total",
        "project": "platform",
        "service": "api_gateway_ma"
       },
       "target": "group_lines('sum', drop_below(diff(group_by_time(15s, 'max', {'cluster'='cloud_${cluster}_api-gateway', 'grpc_code'='Unknown|DeadlineExceeded|Unimplemented|Internal|DataLoss|Unavailable', 'grpc_method'!='all', 'grpc_service'='yandex.cloud.k8s.v1.*', 'host'!='cluster', 'name'='grpc_server_response_total', 'project'='platform', 'service'='api_gateway_ma'})), 0))",
       "type": "timeserie"
      }
     ]
    },
    {
     "title": "API Gateway Managed Kubernetes duration seconds p95 ($cluster) (current)",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 6, "x": 12, "y": 1 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "groupBy": [
        { "params": [ "15s" ], "type": "time" }
       ],
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         },
         {
          "params": [],
          "type": "non_negative_derivative"
         },
         {
          "params": [
           "sum",
           "bin"
          ],
          "type": "group_by_labels"
         },
         {
          "params": [
           "95",
           "bin"
          ],
          "type": "histogram_percentile"
         }
        ]
       ],
       "tags": {
        "bin": "*",
        "cluster": "cloud_${cluster}_api-gateway",
        "grpc_service": "yandex.cloud.k8s.v1.*",
        "host": "!cluster",
        "name": "grpc_server_response_duration_seconds",
        "project": "platform",
        "service": "api_gateway_ma"
       },
       "target": "histogram_percentile(95, 'bin', sum(non_negative_derivative(group_by_time(15s, 'max', {'bin'='*', 'cluster'='cloud_${cluster}_api-gateway', 'grpc_service'='yandex.cloud.k8s.v1.*', 'host'!='cluster', 'name'='grpc_server_response_duration_seconds', 'project'='platform', 'service'='api_gateway_ma'}))) by (bin))",
       "type": "timeserie"
      }
     ]
    },
    { "type": "text", "gridPos": { "h": 4, "w": 6, "x": 18, "y": 1 } }
   ]
  },
  {
   "title": "Managed Kubernetes API lights ($cluster)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 }
  },
  {
   "title": "Managed Kubernetes API rps $cluster (current)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 2 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "15s" ], "type": "time" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       {
        "params": [],
        "type": "non_negative_derivative"
       },
       { "params": [ "sum" ], "type": "group_lines" }
      ]
     ],
     "tags": {
      "cluster": "cloud_${cluster}_k8sapi",
      "grpc_method": "*",
      "grpc_service": "yandex.cloud.*",
      "host": "!cluster",
      "name": "grpc_server_request_total",
      "project": "platform",
      "service": "k8sapi_ma"
     },
     "target": "group_lines('sum', non_negative_derivative(group_by_time(15s, 'max', {'cluster'='cloud_${cluster}_k8sapi', 'grpc_method'='*', 'grpc_service'='yandex.cloud.*', 'host'!='cluster', 'name'='grpc_server_request_total', 'project'='platform', 'service'='k8sapi_ma'})))",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Managed Kubernetes API errors 5xx $cluster (total)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 2 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "15s" ], "type": "time" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       {
        "params": [],
        "type": "diff"
       },
       { "params": [ "0" ], "type": "drop_below" },
       { "params": [ "sum" ], "type": "group_lines" }
      ]
     ],
     "tags": {
      "cluster": "cloud_${cluster}_k8sapi",
      "grpc_code": "Unknown|DeadlineExceeded|Unimplemented|Internal|DataLoss|Unavailable",
      "grpc_method": "!all",
      "grpc_service": "yandex.cloud.*",
      "host": "!cluster",
      "name": "grpc_server_response_total",
      "project": "platform",
      "service": "k8sapi_ma"
     },
     "target": "group_lines('sum', drop_below(diff(group_by_time(15s, 'max', {'cluster'='cloud_${cluster}_k8sapi', 'grpc_code'='Unknown|DeadlineExceeded|Unimplemented|Internal|DataLoss|Unavailable', 'grpc_method'!='all', 'grpc_service'='yandex.cloud.*', 'host'!='cluster', 'name'='grpc_server_response_total', 'project'='platform', 'service'='k8sapi_ma'})), 0))",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Managed Kubernetes API duration seconds p95 ($cluster) (current)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 2 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "15s" ], "type": "time" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       {
        "params": [],
        "type": "non_negative_derivative"
       },
       {
        "params": [
         "sum",
         "bin"
        ],
        "type": "group_by_labels"
       },
       {
        "params": [
         "95",
         "bin"
        ],
        "type": "histogram_percentile"
       }
      ]
     ],
     "tags": {
      "bin": "*",
      "cluster": "cloud_${cluster}_k8sapi",
      "grpc_code": "*",
      "grpc_method": "*",
      "grpc_service": "yandex.cloud.*",
      "host": "!cluster",
      "name": "grpc_server_response_duration_seconds",
      "project": "platform",
      "service": "k8sapi_ma"
     },
     "target": "histogram_percentile(95, 'bin', sum(non_negative_derivative(group_by_time(15s, 'max', {'bin'='*', 'cluster'='cloud_${cluster}_k8sapi', 'grpc_code'='*', 'grpc_method'='*', 'grpc_service'='yandex.cloud.*', 'host'!='cluster', 'name'='grpc_server_response_duration_seconds', 'project'='platform', 'service'='k8sapi_ma'}))) by (bin))",
     "type": "timeserie"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 4, "w": 6, "x": 18, "y": 2 } },
  {
   "title": "Managed Kubernetes Controller lights ($cluster)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 }
  },
  {
   "title": "Mk8s operation errors ($cluster) (total)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 7 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "15s" ], "type": "time" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       {
        "params": [],
        "type": "diff"
       },
       { "params": [ "0" ], "type": "drop_below" },
       { "params": [ "sum" ], "type": "group_lines" }
      ]
     ],
     "tags": {
      "cluster": "cloud_${cluster}_mk8s-controller",
      "grpc_code": "Unknown|DeadlineExceeded|Unimplemented|Internal|DataLoss|Unavailable|Cancelled|InvalidArgument|NotFound|AlreadyExists|PermissionDenied|ResourceExhausted|FailedPrecondition|Aborted|OutOfRange|Unauthenticated",
      "host": "mk8s-controller-*",
      "name": "failed_operation_total",
      "project": "platform",
      "service": "mk8s-controller_ma",
      "target_method": "*",
      "target_resource_type": "*"
     },
     "target": "group_lines('sum', drop_below(diff(group_by_time(15s, 'max', {'cluster'='cloud_${cluster}_mk8s-controller', 'grpc_code'='Unknown|DeadlineExceeded|Unimplemented|Internal|DataLoss|Unavailable|Cancelled|InvalidArgument|NotFound|AlreadyExists|PermissionDenied|ResourceExhausted|FailedPrecondition|Aborted|OutOfRange|Unauthenticated', 'host'='mk8s-controller-*', 'name'='failed_operation_total', 'project'='platform', 'service'='mk8s-controller_ma', 'target_method'='*', 'target_resource_type'='*'})), 0))",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Mk8s hung NodeGroup Delete operations ($cluster) (total)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 7 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "15s" ], "type": "time" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       {
        "params": [],
        "type": "diff"
       },
       { "params": [ "0" ], "type": "drop_below" },
       { "params": [ "sum" ], "type": "group_lines" }
      ]
     ],
     "tags": {
      "cluster": "cloud_${cluster}_mk8s-controller",
      "host": "*",
      "name": "hung_operation_total",
      "project": "platform",
      "service": "mk8s-controller_ma",
      "target_method": "Delete",
      "target_resource_type": "NodeGroup"
     },
     "target": "group_lines('sum', drop_below(diff(group_by_time(15s, 'max', {'cluster'='cloud_${cluster}_mk8s-controller', 'host'='*', 'name'='hung_operation_total', 'project'='platform', 'service'='mk8s-controller_ma', 'target_method'='Delete', 'target_resource_type'='NodeGroup'})), 0))",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Mk8s hung Cluster operations ($cluster) (total)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 7 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "15s" ], "type": "time" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       {
        "params": [],
        "type": "diff"
       },
       { "params": [ "0" ], "type": "drop_below" },
       { "params": [ "sum" ], "type": "group_lines" }
      ]
     ],
     "tags": {
      "cluster": "cloud_${cluster}_mk8s-controller",
      "host": "*",
      "name": "hung_operation_total",
      "project": "platform",
      "service": "mk8s-controller_ma",
      "target_method": "*",
      "target_resource_type": "Cluster"
     },
     "target": "group_lines('sum', drop_below(diff(group_by_time(15s, 'max', {'cluster'='cloud_${cluster}_mk8s-controller', 'host'='*', 'name'='hung_operation_total', 'project'='platform', 'service'='mk8s-controller_ma', 'target_method'='*', 'target_resource_type'='Cluster'})), 0))",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Cpu user+system",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 7, "x": 9, "y": 7 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "15s" ], "type": "time" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       {
        "params": [],
        "type": "non_negative_derivative"
       },
       {
        "params": [
         "sum",
         "host"
        ],
        "type": "group_by_labels"
       },
       { "params": [ " / 2" ], "type": "math" }
      ]
     ],
     "tags": {
      "cluster": "cloud_${cluster}_mk8s-controller",
      "cpu": "*",
      "host": "!cluster",
      "mode": "user|system",
      "name": "node_cpu_seconds_total",
      "project": "platform",
      "service": "node-exporter_ma"
     },
     "target": "sum(non_negative_derivative(group_by_time(15s, 'max', {'project'='platform', 'cluster'='cloud_${cluster}_mk8s-controller', 'service'='node-exporter_ma', 'host'!='cluster', 'name'='node_cpu_seconds_total', 'cpu'='*', 'mode'='user|system'}))) by (\"host\")  / 2",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Master maj_pgfaults",
   "type": "bargauge",
   "gridPos": { "h": 4, "w": 7, "x": 16, "y": 7 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "15s" ], "type": "time" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       {
        "params": [],
        "type": "diff"
       },
       { "params": [ "0" ], "type": "drop_below" },
       {
        "params": [
         "sum",
         "host"
        ],
        "type": "group_by_labels"
       }
      ]
     ],
     "tags": {
      "cluster": "cloud_${cluster}_mk8s-controller",
      "host": "!cluster",
      "name": "node_vmstat_pgmajfault",
      "project": "platform",
      "service": "node-exporter_ma"
     },
     "target": "sum(drop_below(diff(group_by_time(15s, 'max', {'cluster'='cloud_${cluster}_mk8s-controller', 'host'!='cluster', 'name'='node_vmstat_pgmajfault', 'project'='platform', 'service'='node-exporter_ma'})), 0)) by (\"host\")",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Managed Kubernetes Master + Etcd Resources ($cluster)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 }
  },
  {
   "title": "Master CPU User+System",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "15s" ], "type": "time" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       {
        "params": [],
        "type": "non_negative_derivative"
       },
       {
        "params": [
         "sum",
         "host"
        ],
        "type": "group_by_labels"
       },
       { "params": [ " / 2" ], "type": "math" }
      ]
     ],
     "tags": {
      "cluster": "cloud_${cluster}_mk8s-master",
      "cpu": "*",
      "host": "!cluster",
      "mode": "user|system",
      "name": "node_cpu_seconds_total",
      "project": "platform",
      "service": "node-exporter_ma"
     },
     "target": "sum(non_negative_derivative(group_by_time(15s, 'max', {'cluster'='cloud_${cluster}_mk8s-master', 'cpu'='*', 'host'!='cluster', 'mode'='user|system', 'name'='node_cpu_seconds_total', 'project'='platform', 'service'='node-exporter_ma'}))) by (\"host\")  / 2",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Etcd CPU User+System ",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "15s" ], "type": "time" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       {
        "params": [],
        "type": "non_negative_derivative"
       },
       {
        "params": [
         "sum",
         "host"
        ],
        "type": "group_by_labels"
       },
       { "params": [ " / 4" ], "type": "math" }
      ]
     ],
     "tags": {
      "cluster": "cloud_${cluster}_mk8s-etcd",
      "cpu": "*",
      "host": "!cluster",
      "mode": "user|system",
      "name": "node_cpu_seconds_total",
      "project": "platform",
      "service": "node-exporter_ma"
     },
     "target": "sum(non_negative_derivative(group_by_time(15s, 'max', {'cluster'='cloud_${cluster}_mk8s-etcd', 'cpu'='*', 'host'!='cluster', 'mode'='user|system', 'name'='node_cpu_seconds_total', 'project'='platform', 'service'='node-exporter_ma'}))) by (\"host\")  / 4",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Master IO ",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "15s" ], "type": "time" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       {
        "params": [],
        "type": "non_negative_derivative"
       },
       {
        "params": [
         "sum",
         "host"
        ],
        "type": "group_by_labels"
       }
      ]
     ],
     "tags": {
      "cluster": "cloud_${cluster}_mk8s-master",
      "device": "*",
      "host": "!cluster",
      "name": "node_disk_io_time_seconds_total",
      "project": "platform",
      "service": "node-exporter_ma"
     },
     "target": "sum(non_negative_derivative(group_by_time(15s, 'max', {'cluster'='cloud_${cluster}_mk8s-master', 'project'='platform', 'service'='node-exporter_ma', 'host'!='cluster', 'name'='node_disk_io_time_seconds_total', 'device'='*'}))) by (\"host\")",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Etcd IO",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 15 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "15s" ], "type": "time" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       {
        "params": [],
        "type": "non_negative_derivative"
       },
       {
        "params": [
         "sum",
         "host"
        ],
        "type": "group_by_labels"
       },
       { "params": [ " / 2" ], "type": "math" }
      ]
     ],
     "tags": {
      "cluster": "cloud_${cluster}_mk8s-etcd",
      "device": "*",
      "host": "!cluster",
      "name": "node_disk_io_time_seconds_total",
      "project": "platform",
      "service": "node-exporter_ma"
     },
     "target": "sum(non_negative_derivative(group_by_time(15s, 'max', {'cluster'='cloud_${cluster}_mk8s-etcd', 'device'='*', 'host'!='cluster', 'name'='node_disk_io_time_seconds_total', 'project'='platform', 'service'='node-exporter_ma'}))) by (\"host\")  / 2",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Master anon_usage",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "15s" ], "type": "time" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [
         "sum",
         "host"
        ],
        "type": "group_by_labels"
       }
      ]
     ],
     "tags": {
      "cluster": "cloud_${cluster}_mk8s-master",
      "host": "!cluster",
      "name": "node_memory_Anon*",
      "project": "platform",
      "service": "node-exporter_ma"
     },
     "target": "sum({'project'='platform', 'cluster'='cloud_${cluster}_mk8s-master', 'service'='node-exporter_ma', 'host'!='cluster', 'name'='node_memory_Anon*'}) by (\"host\")",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Etcd anon_usage",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "15s" ], "type": "time" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [
         "sum",
         "host"
        ],
        "type": "group_by_labels"
       }
      ]
     ],
     "tags": {
      "cluster": "cloud_${cluster}_mk8s-etcd",
      "host": "!cluster",
      "name": "node_memory_Anon*",
      "project": "platform",
      "service": "node-exporter_ma"
     },
     "target": "sum({'cluster'='cloud_${cluster}_mk8s-etcd', 'host'!='cluster', 'name'='node_memory_Anon*', 'project'='platform', 'service'='node-exporter_ma'}) by (\"host\")",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Master maj_pgfaults",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 21 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "15s" ], "type": "time" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       {
        "params": [],
        "type": "diff"
       },
       { "params": [ "0" ], "type": "drop_below" },
       {
        "params": [
         "sum",
         "host"
        ],
        "type": "group_by_labels"
       }
      ]
     ],
     "tags": {
      "cluster": "cloud_${cluster}_mk8s-master",
      "host": "!cluster",
      "name": "node_vmstat_pgmajfault",
      "project": "platform",
      "service": "node-exporter_ma"
     },
     "target": "sum(drop_below(diff(group_by_time(15s, 'max', {'project'='platform', 'cluster'='cloud_${cluster}_mk8s-master', 'service'='node-exporter_ma', 'host'!='cluster', 'name'='node_vmstat_pgmajfault'})), 0)) by (\"host\")",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Etcd maj_pgfaults",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 21 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "15s" ], "type": "time" }
     ],
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       {
        "params": [],
        "type": "diff"
       },
       { "params": [ "0" ], "type": "drop_below" },
       {
        "params": [
         "sum",
         "host"
        ],
        "type": "group_by_labels"
       }
      ]
     ],
     "tags": {
      "cluster": "cloud_${cluster}_mk8s-etcd",
      "host": "!cluster",
      "name": "node_vmstat_pgmajfault",
      "project": "platform",
      "service": "node-exporter_ma"
     },
     "target": "sum(drop_below(diff(group_by_time(15s, 'max', {'cluster'='cloud_${cluster}_mk8s-etcd', 'host'!='cluster', 'name'='node_vmstat_pgmajfault', 'project'='platform', 'service'='node-exporter_ma'})), 0)) by (\"host\")",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "API Gateway Mk8s",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "Mk8s API Gateway ($cluster)",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 26 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "15s" ], "type": "time" }
       ],
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         },
         {
          "params": [],
          "type": "non_negative_derivative"
         },
         { "params": [ "sum" ], "type": "group_lines" },
         { "params": [ "rps" ], "type": "alias" }
        ]
       ],
       "tags": {
        "cluster": "cloud_${cluster}_api-gateway",
        "grpc_method": "!all",
        "grpc_service": "yandex.cloud.k8s.v1.*",
        "grpc_type": "*",
        "host": "!cluster",
        "name": "grpc_server_request_total",
        "project": "platform",
        "service": "api_gateway_ma",
        "system": "*"
       },
       "target": "alias(group_lines('sum', non_negative_derivative(group_by_time(15s, 'max', {'cluster'='cloud_${cluster}_api-gateway', 'grpc_method'!='all', 'grpc_service'='yandex.cloud.k8s.v1.*', 'grpc_type'='*', 'host'!='cluster', 'name'='grpc_server_request_total', 'project'='platform', 'service'='api_gateway_ma', 'system'='*'}))), 'rps')",
       "type": "timeserie"
      }
     ]
    },
    {
     "title": "Mk8s API Gateway errors ($cluster)",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 26 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "15s" ], "type": "time" }
       ],
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         },
         {
          "params": [],
          "type": "diff"
         },
         { "params": [ "0" ], "type": "drop_below" },
         {
          "params": [
           "sum",
           "grpc_code"
          ],
          "type": "group_by_labels"
         },
         { "params": [ "{{grpc_code}}" ], "type": "alias" }
        ]
       ],
       "tags": {
        "cluster": "cloud_${cluster}_api-gateway",
        "grpc_code": "Unknown|DeadlineExceeded|Unimplemented|Internal|DataLoss|Unavailable",
        "grpc_service": "yandex.cloud.k8s.v1.*",
        "grpc_type": "*",
        "host": "!cluster",
        "name": "grpc_server_response_total",
        "project": "platform",
        "service": "api_gateway_ma",
        "system": "*",
        "upstream_error": "true"
       },
       "target": "alias(sum(drop_below(diff(group_by_time(15s, 'max', {'cluster'='cloud_${cluster}_api-gateway', 'grpc_code'='Unknown|DeadlineExceeded|Unimplemented|Internal|DataLoss|Unavailable', 'grpc_service'='yandex.cloud.k8s.v1.*', 'grpc_type'='*', 'host'!='cluster', 'name'='grpc_server_response_total', 'project'='platform', 'service'='api_gateway_ma', 'system'='*', 'upstream_error'='true'})), 0)) by (grpc_code), '{{grpc_code}}')",
       "type": "timeserie"
      }
     ]
    },
    {
     "title": "Gateway response duration ($cluster)",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 26 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "15s" ], "type": "time" }
       ],
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         },
         {
          "params": [],
          "type": "non_negative_derivative"
         },
         {
          "params": [
           "sum",
           "bin"
          ],
          "type": "group_by_labels"
         },
         {
          "params": [
           "50",
           "bin"
          ],
          "type": "histogram_percentile"
         },
         { "params": [ "p50" ], "type": "alias" }
        ]
       ],
       "tags": {
        "bin": "*",
        "cluster": "cloud_${cluster}_api-gateway",
        "grpc_service": "yandex.cloud.k8s.v1.*",
        "grpc_type": "*",
        "host": "!cluster",
        "name": "grpc_server_response_duration_seconds",
        "project": "platform",
        "service": "api_gateway_ma",
        "system": "*"
       },
       "target": "alias(histogram_percentile(50, 'bin', sum(non_negative_derivative(group_by_time(15s, 'max', {'bin'='*', 'cluster'='cloud_${cluster}_api-gateway', 'grpc_service'='yandex.cloud.k8s.v1.*', 'grpc_type'='*', 'host'!='cluster', 'name'='grpc_server_response_duration_seconds', 'project'='platform', 'service'='api_gateway_ma', 'system'='*'}))) by (bin)), 'p50')",
       "type": "timeserie"
      },
      {
       "groupBy": [
        { "params": [ "15s" ], "type": "time" }
       ],
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         },
         {
          "params": [],
          "type": "non_negative_derivative"
         },
         {
          "params": [
           "sum",
           "bin"
          ],
          "type": "group_by_labels"
         },
         {
          "params": [
           "95",
           "bin"
          ],
          "type": "histogram_percentile"
         },
         { "params": [ "p95" ], "type": "alias" }
        ]
       ],
       "tags": {
        "bin": "*",
        "cluster": "cloud_${cluster}_api-gateway",
        "grpc_service": "yandex.cloud.k8s.v1.*",
        "grpc_type": "*",
        "host": "!cluster",
        "name": "grpc_server_response_duration_seconds",
        "project": "platform",
        "service": "api_gateway_ma",
        "system": "*"
       },
       "target": "alias(histogram_percentile(95, 'bin', sum(non_negative_derivative(group_by_time(15s, 'max', {'bin'='*', 'cluster'='cloud_${cluster}_api-gateway', 'grpc_service'='yandex.cloud.k8s.v1.*', 'grpc_type'='*', 'host'!='cluster', 'name'='grpc_server_response_duration_seconds', 'project'='platform', 'service'='api_gateway_ma', 'system'='*'}))) by (bin)), 'p95')",
       "type": "timeserie"
      },
      {
       "groupBy": [
        { "params": [ "15s" ], "type": "time" }
       ],
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         },
         {
          "params": [],
          "type": "non_negative_derivative"
         },
         {
          "params": [
           "sum",
           "bin"
          ],
          "type": "group_by_labels"
         },
         {
          "params": [
           "99",
           "bin"
          ],
          "type": "histogram_percentile"
         },
         { "params": [ "p99" ], "type": "alias" }
        ]
       ],
       "tags": {
        "bin": "*",
        "cluster": "cloud_${cluster}_api-gateway",
        "grpc_service": "yandex.cloud.k8s.v1.*",
        "grpc_type": "*",
        "host": "!cluster",
        "name": "grpc_server_response_duration_seconds",
        "project": "platform",
        "service": "api_gateway_ma",
        "system": "*"
       },
       "target": "alias(histogram_percentile(99, 'bin', sum(non_negative_derivative(group_by_time(15s, 'max', {'bin'='*', 'cluster'='cloud_${cluster}_api-gateway', 'grpc_service'='yandex.cloud.k8s.v1.*', 'grpc_type'='*', 'host'!='cluster', 'name'='grpc_server_response_duration_seconds', 'project'='platform', 'service'='api_gateway_ma', 'system'='*'}))) by (bin)), 'p99')",
       "type": "timeserie"
      }
     ]
    }
   ]
  },
  {
   "title": "Managed Kubernetes API",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 },
   "collapsed": true,
   "panels": [
    {
     "title": "Mk8s API rps ($cluster)",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "15s" ], "type": "time" }
       ],
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         },
         {
          "params": [],
          "type": "non_negative_derivative"
         },
         {
          "params": [
           "sum",
           "grpc_service"
          ],
          "type": "group_by_labels"
         },
         { "params": [ "{{grpc_service}}" ], "type": "alias" }
        ]
       ],
       "tags": {
        "cluster": "cloud_${cluster}_k8sapi",
        "grpc_service": "yandex.cloud.*",
        "host": "!cluster",
        "name": "grpc_server_request_total",
        "project": "platform",
        "service": "k8sapi_ma"
       },
       "target": "alias(sum(non_negative_derivative(group_by_time(15s, 'max', {'cluster'='cloud_${cluster}_k8sapi', 'grpc_service'='yandex.cloud.*', 'host'!='cluster', 'name'='grpc_server_request_total', 'project'='platform', 'service'='k8sapi_ma'}))) by (grpc_service), '{{grpc_service}}')",
       "type": "timeserie"
      }
     ]
    },
    {
     "title": "Mk8s API errors ($cluster)",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 27 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "15s" ], "type": "time" }
       ],
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         },
         {
          "params": [],
          "type": "diff"
         },
         { "params": [ "0" ], "type": "drop_below" },
         {
          "params": [
           "sum",
           "grpc_code"
          ],
          "type": "group_by_labels"
         },
         { "params": [ "{{grpc_code}}" ], "type": "alias" }
        ]
       ],
       "tags": {
        "cluster": "cloud_${cluster}_k8sapi",
        "grpc_code": "Unknown|DeadlineExceeded|Unimplemented|Internal|DataLoss|Unavailable",
        "grpc_method": "!all",
        "host": "!cluster",
        "name": "grpc_server_response_total",
        "project": "platform",
        "service": "k8sapi_ma"
       },
       "target": "alias(sum(drop_below(diff(group_by_time(15s, 'max', {'cluster'='cloud_${cluster}_k8sapi', 'grpc_code'='Unknown|DeadlineExceeded|Unimplemented|Internal|DataLoss|Unavailable', 'grpc_method'!='all', 'host'!='cluster', 'name'='grpc_server_response_total', 'project'='platform', 'service'='k8sapi_ma'})), 0)) by (grpc_code), '{{grpc_code}}')",
       "type": "timeserie"
      },
      {
       "groupBy": [
        { "params": [ "15s" ], "type": "time" }
       ],
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         },
         {
          "params": [],
          "type": "diff"
         },
         { "params": [ "0" ], "type": "drop_below" },
         {
          "params": [
           "sum",
           "grpc_code"
          ],
          "type": "group_by_labels"
         },
         { "params": [ "{{grpc_code}}" ], "type": "alias" }
        ]
       ],
       "tags": {
        "cluster": "cloud_${cluster}_k8sapi",
        "grpc_code": "Cancelled|InvalidArgument|NotFound|AlreadyExists|PermissionDenied|ResourceExhausted|FailedPrecondition|Aborted|OutOfRange|Unauthenticated",
        "grpc_method": "!all",
        "host": "!cluster",
        "name": "grpc_server_response_total",
        "project": "platform",
        "service": "k8sapi_ma"
       },
       "target": "alias(sum(drop_below(diff(group_by_time(15s, 'max', {'cluster'='cloud_${cluster}_k8sapi', 'grpc_code'='Cancelled|InvalidArgument|NotFound|AlreadyExists|PermissionDenied|ResourceExhausted|FailedPrecondition|Aborted|OutOfRange|Unauthenticated', 'grpc_method'!='all', 'host'!='cluster', 'name'='grpc_server_response_total', 'project'='platform', 'service'='k8sapi_ma'})), 0)) by (grpc_code), '{{grpc_code}}')",
       "type": "timeserie"
      }
     ]
    },
    {
     "title": "Mk8s API response duration ($cluster)",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 27 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "15s" ], "type": "time" }
       ],
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         },
         {
          "params": [],
          "type": "non_negative_derivative"
         },
         {
          "params": [
           "sum",
           "bin"
          ],
          "type": "group_by_labels"
         },
         {
          "params": [
           "50",
           "bin"
          ],
          "type": "histogram_percentile"
         },
         { "params": [ "p50" ], "type": "alias" }
        ]
       ],
       "tags": {
        "bin": "*",
        "cluster": "cloud_${cluster}_k8sapi",
        "grpc_code": "*",
        "host": "!cluster",
        "name": "grpc_server_response_duration_seconds",
        "project": "platform",
        "service": "k8sapi_ma"
       },
       "target": "alias(histogram_percentile(50, 'bin', sum(non_negative_derivative(group_by_time(15s, 'max', {'bin'='*', 'cluster'='cloud_${cluster}_k8sapi', 'grpc_code'='*', 'host'!='cluster', 'name'='grpc_server_response_duration_seconds', 'project'='platform', 'service'='k8sapi_ma'}))) by (bin)), 'p50')",
       "type": "timeserie"
      },
      {
       "groupBy": [
        { "params": [ "15s" ], "type": "time" }
       ],
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         },
         {
          "params": [],
          "type": "non_negative_derivative"
         },
         {
          "params": [
           "sum",
           "bin"
          ],
          "type": "group_by_labels"
         },
         {
          "params": [
           "95",
           "bin"
          ],
          "type": "histogram_percentile"
         },
         { "params": [ "p95" ], "type": "alias" }
        ]
       ],
       "tags": {
        "bin": "*",
        "cluster": "cloud_${cluster}_k8sapi",
        "grpc_code": "*",
        "host": "!cluster",
        "name": "grpc_server_response_duration_seconds",
        "project": "platform",
        "service": "k8sapi_ma"
       },
       "target": "alias(histogram_percentile(95, 'bin', sum(non_negative_derivative(group_by_time(15s, 'max', {'bin'='*', 'cluster'='cloud_${cluster}_k8sapi', 'grpc_code'='*', 'host'!='cluster', 'name'='grpc_server_response_duration_seconds', 'project'='platform', 'service'='k8sapi_ma'}))) by (bin)), 'p95')",
       "type": "timeserie"
      },
      {
       "groupBy": [
        { "params": [ "15s" ], "type": "time" }
       ],
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         },
         {
          "params": [],
          "type": "non_negative_derivative"
         },
         {
          "params": [
           "sum",
           "bin"
          ],
          "type": "group_by_labels"
         },
         {
          "params": [
           "99",
           "bin"
          ],
          "type": "histogram_percentile"
         },
         { "params": [ "p99" ], "type": "alias" }
        ]
       ],
       "tags": {
        "bin": "*",
        "cluster": "cloud_${cluster}_k8sapi",
        "grpc_code": "*",
        "host": "!cluster",
        "name": "grpc_server_response_duration_seconds",
        "project": "platform",
        "service": "k8sapi_ma"
       },
       "target": "alias(histogram_percentile(99, 'bin', sum(non_negative_derivative(group_by_time(15s, 'max', {'bin'='*', 'cluster'='cloud_${cluster}_k8sapi', 'grpc_code'='*', 'host'!='cluster', 'name'='grpc_server_response_duration_seconds', 'project'='platform', 'service'='k8sapi_ma'}))) by (bin)), 'p99')",
       "type": "timeserie"
      }
     ]
    }
   ]
  },
  {
   "title": "Managed Kubernetes Controller",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "Mk8s operation errors ($cluster)",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "15s" ], "type": "time" }
       ],
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         },
         {
          "params": [],
          "type": "diff"
         },
         { "params": [ "0" ], "type": "drop_below" },
         { "params": [ "sum" ], "type": "group_lines" },
         { "params": [ "5xx & 503" ], "type": "alias" }
        ]
       ],
       "tags": {
        "cluster": "cloud_${cluster}_mk8s-controller",
        "grpc_code": "Unknown|DeadlineExceeded|Unimplemented|Internal|DataLoss|Unavailable",
        "host": "*",
        "name": "failed_operation_total",
        "project": "platform",
        "service": "mk8s-controller_ma",
        "target_method": "*",
        "target_resource_type": "*"
       },
       "target": "alias(group_lines('sum', drop_below(diff(group_by_time(15s, 'max', {'cluster'='cloud_${cluster}_mk8s-controller', 'grpc_code'='Unknown|DeadlineExceeded|Unimplemented|Internal|DataLoss|Unavailable', 'host'='*', 'name'='failed_operation_total', 'project'='platform', 'service'='mk8s-controller_ma', 'target_method'='*', 'target_resource_type'='*'})), 0)), '5xx & 503')",
       "type": "timeserie"
      },
      {
       "groupBy": [
        { "params": [ "15s" ], "type": "time" }
       ],
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         },
         {
          "params": [],
          "type": "diff"
         },
         { "params": [ "0" ], "type": "drop_below" },
         { "params": [ "sum" ], "type": "group_lines" },
         { "params": [ "4xx" ], "type": "alias" }
        ]
       ],
       "tags": {
        "cluster": "cloud_${cluster}_mk8s-controller",
        "grpc_code": "Cancelled|InvalidArgument|NotFound|AlreadyExists|PermissionDenied|ResourceExhausted|FailedPrecondition|Aborted|OutOfRange|Unauthenticated",
        "host": "*",
        "name": "failed_operation_total",
        "project": "platform",
        "service": "mk8s-controller_ma",
        "target_method": "*",
        "target_resource_type": "*"
       },
       "target": "alias(group_lines('sum', drop_below(diff(group_by_time(15s, 'max', {'cluster'='cloud_${cluster}_mk8s-controller', 'grpc_code'='Cancelled|InvalidArgument|NotFound|AlreadyExists|PermissionDenied|ResourceExhausted|FailedPrecondition|Aborted|OutOfRange|Unauthenticated', 'host'='*', 'name'='failed_operation_total', 'project'='platform', 'service'='mk8s-controller_ma', 'target_method'='*', 'target_resource_type'='*'})), 0)), '4xx')",
       "type": "timeserie"
      }
     ]
    },
    {
     "title": "Mk8s hung operations ($cluster)",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 28 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "groupBy": [
        { "params": [ "15s" ], "type": "time" }
       ],
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         },
         {
          "params": [],
          "type": "diff"
         },
         { "params": [ "sum" ], "type": "group_lines" },
         { "params": [ ">20m NodeGroup Delete" ], "type": "alias" }
        ]
       ],
       "tags": {
        "cluster": "cloud_${cluster}_mk8s-controller",
        "host": "*",
        "name": "hung_operation_total",
        "project": "platform",
        "service": "mk8s-controller_ma",
        "target_method": "Delete",
        "target_resource_type": "NodeGroup"
       },
       "target": "alias(group_lines('sum', diff(group_by_time(15s, 'max', {'cluster'='cloud_${cluster}_mk8s-controller', 'host'='*', 'name'='hung_operation_total', 'project'='platform', 'service'='mk8s-controller_ma', 'target_method'='Delete', 'target_resource_type'='NodeGroup'}))), '>20m NodeGroup Delete')",
       "type": "timeserie"
      },
      {
       "groupBy": [
        { "params": [ "15s" ], "type": "time" }
       ],
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         },
         {
          "params": [],
          "type": "diff"
         },
         { "params": [ "sum" ], "type": "group_lines" },
         { "params": [ ">20m Cluster" ], "type": "alias" }
        ]
       ],
       "tags": {
        "cluster": "cloud_${cluster}_mk8s-controller",
        "host": "*",
        "name": "hung_operation_total",
        "project": "platform",
        "service": "mk8s-controller_ma",
        "target_method": "*",
        "target_resource_type": "Cluster"
       },
       "target": "alias(group_lines('sum', diff(group_by_time(15s, 'max', {'cluster'='cloud_${cluster}_mk8s-controller', 'host'='*', 'name'='hung_operation_total', 'project'='platform', 'service'='mk8s-controller_ma', 'target_method'='*', 'target_resource_type'='Cluster'}))), '>20m Cluster')",
       "type": "timeserie"
      }
     ]
    },
    { "type": "text", "gridPos": { "h": 6, "w": 8, "x": 16, "y": 28 } }
   ]
  }
 ]
}