#! /bin/bash

# We are called either with -ldebian/changelog or -lproject/debian/changelog
DIR=`echo $1 | sed s/-l// | sed 's/debian\/changelog//'`
if [ "x$DIR" != "x" ]; then cd $DIR; fi

# Extract info from git
AUTHOR=`git log -n 1 --format="format:%an <%ae>"`
DATE=`git log -n 1 --format="format:%aD"`
DATETAG=`date -d "$DATE" +%Y%m%d%H%M`
BRANCH=`git rev-parse --abbrev-ref HEAD | tr _ -`
ORIGIN=`git remote -v | fgrep fetch | awk '{print $2}'`
VERSION=`echo $DATETAG-$BRANCH | tr - + | tr / .`

#parameter from team-city agent like debuild --no-lintian --set-envvar TC_BUILD_NUMBER=%build.number%
if [[ -n "$TC_BUILD_NUMBER" ]]; then
    VERSION=$TC_BUILD_NUMBER
fi

SOURCE=`grep Source debian/control | cut -f2 -d' '`
THIS_TAG=$(git describe --tags --abbrev=0)
PREV_TAG=$(git describe --tags --abbrev=0 $THIS_TAG^1)

# Print out info
echo Changes:
echo " $SOURCE ($THIS_TAG) unstable; urgency=low"
echo " ."
echo "   See $ORIGIN for full log"
git log --oneline --no-merges $PREV_TAG..$THIS_TAG | sed 's/^/   * /'

echo Version: $THIS_TAG
echo Distribution: unstable
echo Urgency: low
echo Source: $SOURCE
echo Maintainer: $AUTHOR
echo Date: $DATE
