// Code generated by MockGen. DO NOT EDIT.
// Source: a.yandex-team.ru/cloud/mdb/dataproc-agent/pkg/yarn (interfaces: API)

// Package mocks is a generated GoMock package.
package mocks

import (
	yarn "a.yandex-team.ru/cloud/mdb/dataproc-agent/pkg/yarn"
	context "context"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockAPI is a mock of API interface.
type MockAPI struct {
	ctrl     *gomock.Controller
	recorder *MockAPIMockRecorder
}

// MockAPIMockRecorder is the mock recorder for MockAPI.
type MockAPIMockRecorder struct {
	mock *MockAPI
}

// NewMockAPI creates a new mock instance.
func NewMockAPI(ctrl *gomock.Controller) *MockAPI {
	mock := &MockAPI{ctrl: ctrl}
	mock.recorder = &MockAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAPI) EXPECT() *MockAPIMockRecorder {
	return m.recorder
}

// SearchApplication mocks base method.
func (m *MockAPI) SearchApplication(arg0 context.Context, arg1 string) ([]yarn.Application, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SearchApplication", arg0, arg1)
	ret0, _ := ret[0].([]yarn.Application)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SearchApplication indicates an expected call of SearchApplication.
func (mr *MockAPIMockRecorder) SearchApplication(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SearchApplication", reflect.TypeOf((*MockAPI)(nil).SearchApplication), arg0, arg1)
}
