#!/usr/bin/env python3
"""
This script starts docker container and passes secrets from /run/secrets via environment variables.
"""

import sys
import os
import os.path
import subprocess


SECRETS_DIR = "/run/secrets"


def read_secrets():
    result = {}
    for filename in os.listdir(SECRETS_DIR):        
        if os.path.isfile(os.path.join(SECRETS_DIR, filename)) and not filename.endswith(".encrypted"):
            with open(os.path.join(SECRETS_DIR, filename)) as f:
                file_content = f.read().strip()

            result[filename] = file_content

    return result


if len(sys.argv) < 2:
    print("USAGE: ./docker_run_with_secrets [<docker-args>]")
    print("I.e., ./docker_run_with_secrets --name my_service ubuntu /bin/bash -c 'sleep 1000'")
    sys.exit(1)


docker_args = ["docker", "run"]

for secret_name, secret_value in read_secrets().items():
    docker_args.extend(["-e", secret_name.upper() + "=" + secret_value])

docker_args.extend(sys.argv[1:])

print("Running docker command", docker_args)

process = subprocess.run(docker_args)
sys.exit(process.returncode)

