#!/bin/bash

export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8
export LANGUAGE=en_US.UTF-8

_SYSTEMCTL_SKIP_REDIRECT=1

DAEMON_BIN=/usr/bin/juggler-client
PIDFILE=juggler-client.pid

SPOOL_DIR=/var/spool/juggler-client
LOGS_DIR=/var/log/juggler-client
RUN_DIR=/var/run/juggler-client
VARLIB_DIR=/var/lib/juggler
DAEMON_USER=root

exec 2>&1

/usr/sbin/regenerate-monrun-tasks

if [ -f /etc/default/juggler-client ]
then
    . /etc/default/juggler-client
fi

test -x ${DAEMON_BIN} || exit 5

CONFIG_DIR=""
[ -n "${JUGGLER_ROOT}" ] && CONFIG_DIR="--config-dir ${JUGGLER_ROOT}/etc"

mkdir -p "${LOGS_DIR}" "${RUN_DIR}" "${VARLIB_DIR}"
chmod 1777 "${LOGS_DIR}"
chown -R ${DAEMON_USER} "${LOGS_DIR}" "${RUN_DIR}"

exec ${DAEMON_BIN} --pid-file "${RUN_DIR}/${PIDFILE}" ${CONFIG_DIR}


