RECURSE(
    algo
    archive
    archive/chooser
    archive/markup
    archive/unpacker
    archive/view
    archive/zone_checker
    base
    calc_dssm
    config
    custom
    custom/forums_handler
    custom/opengraph
    custom/preview_viewer
    custom/remove_emoji
    custom/remove_emoji/ut
    custom/schemaorg_viewer
    custom/sea_json
    custom/trash_classifier
    cut
    cut/ut
    data
    delink
    dynamic_data
    entityclassify
    explain
    factors
    formulae
    hits
    i18n
    idl
    iface
    iface/archive
    markers
    markers/ut
    passages
    passages/ut
    plm
    qtree
    read_helper
    replace
    schemaorg
    schemaorg/factor_calcer
    schemaorg/proto
    schemaorg/question
    schemaorg/ut
    sent_info
    sent_match
    sent_match/ut
    simple_cmp
    simple_textproc/capital
    simple_textproc/decapital
    simple_textproc/deyo
    smartcut
    smartcut/ut
    snip_builder
    snip_proto
    span
    static_annotation
    strhl
    strhl/ut
    telephone
    tests
    titles
    titles/make_title
    titles/make_title/ut
    title_trigram
    uni_span_iter
    urlcut
    urlcut/ut
    urlmenu
    util
    video
    weight
    wordstat
)
