#!/bin/bash
exec 2>&1
ulimit -c unlimited
#ulimit -p 131072
#if [ ! -p /tmp/cocaine_pushclient.pipe ]
#then
#    mkfifo /tmp/cocaine_pushclient.pipe
#    touch /var/tmp/pushclient_ok
#fi
#while :; do /usr/bin/push-client  -f --ident=cocaine-backend '--logger:timeformat=[%d/%b/%Y:%T %z]' --files=/var/log/runit/cocaine-runtime/current --logtype=cocaine-log --network:master-addr=logbroker.yandex.net; done
#while :; do cat < /tmp/cocaine_pushclient.pipe; done | /usr/local/bin/cocs2tskv.pl | /usr/bin/push-client  -f --stdin --ident=cocaine-backend '--logger:timeformat=[%d/%b/%Y:%T %z]' --logtype=cocaine-log --network:master-addr=logbroker.yandex.net
mkdir -p /var/log/mds_cleanup 2>/dev/null || true
ln -sf /var/log/runit/cocaine-runtime/current /var/log/cocaine-core/cocaine-tskv.log

exec /usr/bin/push-client -f -w -c /etc/yandex/statbox-push-client/cocaine-test-backend.yaml -c /etc/yandex/statbox-push-client/disk.yaml -c /etc/yandex/statbox-push-client/mds_cleanup.yaml -c /etc/yandex/statbox-push-client/rt.yaml

