"""
DBaaS Internal API Redis globals
"""
from typing import Dict

MY_CLUSTER_TYPE = 'redis_cluster'

DEFAULT_SHARD_NAME = 'shard1'
MIN_SHARDS_COUNT = 3
MAX_SHARDS_COUNT = 10
DEFAULT_REPLICA_PRIORITY = 100
MIN_HOSTS_IN_SHARD_FOR_HA = 2

ORDER = 1024
GIGABYTES_CLIENT_OUTPUT_BUFFER_LIMIT_MAX = 10
MEGABYTES_CLIENT_OUTPUT_BUFFER_LIMIT_MAX = GIGABYTES_CLIENT_OUTPUT_BUFFER_LIMIT_MAX * ORDER
KILOBYTES_CLIENT_OUTPUT_BUFFER_LIMIT_MAX = MEGABYTES_CLIENT_OUTPUT_BUFFER_LIMIT_MAX * ORDER
BYTES_CLIENT_OUTPUT_BUFFER_LIMIT_MAX = KILOBYTES_CLIENT_OUTPUT_BUFFER_LIMIT_MAX * ORDER
BUFFER_LIMITS_KEY_TO_ORDER = {'b': 1, 'kb': ORDER, 'mb': ORDER**2, 'gb': ORDER**3}
ALLOW_DEPRECATED_5_FEATURE_FLAG = 'MDB_REDIS_ALLOW_DEPRECATED_5'
ALLOW_DEPRECATED_6_FEATURE_FLAG = 'MDB_REDIS_ALLOW_DEPRECATED_6'

UPGRADE_PATHS: Dict[str, dict] = {
    '6.0': {
        'from': ['5.0'],
    },
    '6.2': {
        'from': ['6.0'],
    },
}
