#!/bin/bash

set -e

PKGNAME=config-monrun-cassandra
DATADIR=/usr/share
YCONFDIR=${DATADIR}/yandex-configs/${PKGNAME}


case "$1" in
    configure)

        #DEBHELPER#

    ;;  

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;  

    *)  
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;  

esac


exit 0

