#!/bin/bash
#
# see: dh_installdeb(1)

set -e

case "$1" in
    configure)
        adduser --system --group --home /var/log/tflow --no-create-home tflow
        chown -R tflow:tflow /var/log/tflow
        chown -R tflow:tflow /etc/tflow
        # Try systemd first
        if [ -d /run/systemd ]
        then
            if [ ! -e /etc/systemd/system/tflow.service ]
            then
                /bin/systemctl enable "/lib/systemd/system/tflow.service" || /bin/true
                systemctl daemon-reload
            fi
        fi
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

exit 0
