#pragma once
#include <util/system/types.h>

namespace NRandomLogFactors {
    enum class ERandomLogQueryFactor : size_t {
        RandomLogQueryAvgNews = 0,
        RandomLogQueryAvgAddTime = 1,
        RandomLogQueryAvgTxtHiRelSy = 2,
        RandomLogQueryAvgTextLike = 3,
        RandomLogQueryAvgHasNoAllWordsTRSy = 4,
        RandomLogQueryAvgIsForum = 5,
        RandomLogQueryAvgHasPayments = 6,
        RandomLogQueryAvgYabarHostAvgTime2 = 7,
        RandomLogQueryAvgYabarUrlVisitors = 8,
        RandomLogQueryAvgQueryDOwnerOnlyClickRate = 9,
        RandomLogQueryAvgDaterAge = 10,
        RandomLogQueryAvgLongestText = 11,
        RandomLogQueryAvgDifferentInternalLinks = 12,
        RandomLogQueryAvgQueryDOwnerOnlyClickRate_Reg = 13,
        RandomLogQueryAvgIsHub = 14,
        RandomLogQueryAvgIsTargetBussinessCard = 15,
        RandomLogQueryAvgBM25_0 = 16,
        RandomLogQueryAvgBocm = 17,
        RandomLogQueryAvgIsIndexPage = 18,
        RandomLogQueryAvgQueriesAvgCM2 = 19,
        RandomLogQueryAvgBrowserHostDownloadProbability = 20,
        RandomLogQueryAvgRegBrowserUserHub = 21,
        RandomLogQueryAvgAuxTitleBM25 = 22,
        RandomLogQueryAvgQueryUrlCorrectedCtrXfactor = 23,
        RandomLogQueryAvgQueryToDocAllSumFCountTextBm11Norm16384 = 24,
        RandomLogQueryAvgXfDtShowAllSumWFSumWBodyMinWindowSize = 25,
        RandomLogQueryClicksWeightedAvgIsMainPage = 26,
        RandomLogQueryClicksWeightedAvgYabarUrlAvgTime = 27,
        RandomLogQueryClicksWeightedAvgDifferentInternalLinks = 28,
        RandomLogQueryDwelltimeWeightedAvgUrlDomainFraction = 29,
        RandomLogQueryAvgIsBlog = 30,
        RandomLogQueryAvgYabarHostAvgTime = 31,
        RandomLogQueryAvgVerbsPortion = 32,
        RandomLogQueryAvgQfufAllMaxWFLinkAnnIndicatorFullMatchValue = 33,
        RandomLogQueryAvgRTBTraffOutShareDesktop = 34,
    };

    enum class ERandomLogWordBaseFactor : size_t {
        RandomLogWordAvgHasNoTr = 0,
        RandomLogWordAvgIsLJ = 1,
        RandomLogWordAvgIsVendor = 2,
        RandomLogWordAvgBclmLite = 3,
        RandomLogWordAvgDBM40 = 4,
        RandomLogWordAvgIsDesktopRequest = 5,
        RandomLogWordAvgRLQAvgHasNoAllWordsTrSyn = 6,
        RandomLogWordAvgDssmAggregatedAnnReg = 7,
        RandomLogWordAvgMetaNumUrlsPerHostFixed = 8,
        RandomLogWordAvgSDIsNavMxQueryMax = 9,
        RandomLogWordAvgQueryRegionSize = 10,
        RandomLogWordAvgNumLatinLetters = 11,
        RandomLogWordAvgAdjPronounsPortion = 12,
        RandomLogWordAvgQueryIsOrg = 13,
        RandomLogWordAvgRegionalUQueryNew = 14,
        RandomLogWordAvgQClassDownload = 15,
        RandomLogWordAvgGeoVQueryInAlienCity = 16,
        RandomLogWordAvgQueryIsGeo = 17,
        RandomLogWordAvgQueryMaxOne = 18,
        RandomLogWordAvgLongQuerySyn = 19,
        RandomLogWordAvgRankComGoodness = 20,
        RandomLogWordAvgQueriesAvgCM2 = 21,
        RandomLogWordAvgFractionOfQueriesWithGeoPrediction = 22,
        RandomLogWordAvgRLQAvgQueriesAvgCM2 = 23,
        RandomLogWordAvgDssmQueryEmbeddingCtrNoMinerPCA1 = 24,
        RandomLogWordAvgRLHUrlClicksMaxGeoRegionFrcRatioAvg = 25,
        RandomLogWordAvgMetaRMSEUrlClicksMaxAlienGeoCityFrcRatio = 26,
    };
}
