#! /bin/bash

set -e

[ -d debian/venv ] || virtualenv debian/venv
. debian/venv/bin/activate
python setup.py install
deactivate
virtualenv --relocatable debian/venv
rm -vr debian/venv/bin/{python,pip,easy_install}*
for d in  {pip,wheel,setuptools,pkg_resources}; do
    echo "Remove debian/venv/lib/python2.7/site-packages/$d"
    rm -r debian/venv/lib/python2.7/site-packages/$d
done
rm -vr debian/venv/lib/python2.7/site-packages/*.dist-info
