GRANT USAGE ON SCHEMA katan TO katan_imp;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA katan TO katan_imp;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA katan TO katan_imp;
GRANT CONNECT ON DATABASE katandb TO katan_imp;
