GRANT USAGE ON SCHEMA katan TO katan;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA katan TO katan;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA katan TO katan;
GRANT CONNECT ON DATABASE katandb TO katan;
