GRANT CONNECT ON DATABASE katandb TO mdb_ui;
GRANT USAGE ON SCHEMA katan TO mdb_ui;
GRANT SELECT ON ALL TABLES IN SCHEMA katan TO mdb_ui;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA katan TO mdb_ui;
