$destination_path = {{input1->table_quote()}};

INSERT INTO $destination_path WITH TRUNCATE
SELECT
  `date`,
  billing_account_id,
  billing_account_name,
  billing_account_month_cohort,
  currency,
  is_subaccount,
  country_code,
  crm_account_id,
  crm_account_name,
  client_id,
  person_type_current,
  person_type,
  usage_status_current,
  usage_status,
  state_current,
  state,
  is_fraud_current,
  is_fraud,
  is_suspended_by_antifraud_current,
  is_suspended_by_antifraud,
  payment_type_current,
  payment_type,
  is_isv_current,
  is_isv,
  is_var_current,
  is_var,
  segment_current,
  segment,
  crm_account_tags,
  crm_account_dimensions,
  account_owner_current,
  account_owner,
  architect_current,
  architect,
  bus_dev_current,
  bus_dev,
  partner_manager_current,
  partner_manager,
  tam_current,
  tam,
  sales_current,
  sales,
FROM {{concat_input2}}
ORDER BY `date`, `billing_account_id`;
