GRANT USAGE ON SCHEMA cms TO cms;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA cms TO cms;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA cms TO cms;
GRANT SELECT ON TABLE public.schema_version TO cms;
