GRANT CONNECT ON DATABASE cmsdb TO mdb_ui;
GRANT USAGE ON SCHEMA cms TO mdb_ui;
GRANT SELECT ON ALL TABLES IN SCHEMA cms TO mdb_ui;
GRANT UPDATE ON ALL TABLES IN SCHEMA cms TO mdb_ui;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA cms TO mdb_ui;
