# This file is generated by
# https://bb.yandex-team.ru/projects/CLOUD/repos/cloud-go/browse/tools/cmd/syncapi
# in Teamcity Task
# https://teamcity.yandex-team.ru/buildConfiguration/Cloud_Api_ApiSync

OWNER(g:cloud-api)
PROTO_LIBRARY()

PROTO_NAMESPACE(GLOBAL cloud/bitbucket/private-api)
PY_NAMESPACE(yandex.cloud.priv.datatransfer.v1.endpoint.airbyte)

GRPC()
SRCS(
    amazon_ads_source.proto
    amazon_seller_partner_source.proto
    aws_cloud_trail_source.proto
    bigquery_source.proto
    bing_ads_source.proto
    facebook_marketing_source.proto
    facebook_pages_source.proto
    google_ads_source.proto
    google_analytics_v4_source.proto
    google_sheets_source.proto
    instagram_source.proto
    linkedin_ads_source.proto
    mssql_source.proto
    redshift_source.proto
    s3_source.proto
    salesforce_source.proto
    snapchat_marketing_source.proto
    tiktok_marketing_source.proto
)

USE_COMMON_GOOGLE_APIS(
    api/annotations
    rpc/code
    rpc/errdetails
    rpc/status
    type/timeofday
    type/dayofweek
)

IF (GO_PROTO)
    PEERDIR(
        cloud/bitbucket/private-api/yandex/cloud/priv
    )
ELSE()
    PEERDIR(
        cloud/bitbucket/private-api/yandex/cloud/priv
    )
ENDIF()
END()

