Document: yandex-media-mongo-dumper
Title: Debian yandex-media-mongo-dumper Manual
Author: <insert document author here>
Abstract: This manual describes what yandex-media-mongo-dumper is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/yandex-media-mongo-dumper/yandex-media-mongo-dumper.sgml.gz

Format: postscript
Files: /usr/share/doc/yandex-media-mongo-dumper/yandex-media-mongo-dumper.ps.gz

Format: text
Files: /usr/share/doc/yandex-media-mongo-dumper/yandex-media-mongo-dumper.text.gz

Format: HTML
Index: /usr/share/doc/yandex-media-mongo-dumper/html/index.html
Files: /usr/share/doc/yandex-media-mongo-dumper/html/*.html
