#!/usr/bin/env sh
#
# Creates development virtual environment
#

set -eu

if [ "$(uname)" = Darwin ]; then
    alias find=gfind
fi

extra_projects_args=$(find -mindepth 2 -maxdepth 2 -name setup.py -exec dirname '{}' \; | xargs -n 1 basename | sed 's/^/-A /')
if [ -z "$extra_projects_args" ]; then
    echo "Unable to determine project's packages." >&2
    exit 1
fi

exec ./common/scripts/mkdevelvirtualenv/mkdevelvirtualenv \
    --python python3 --no-index --find-links $PWD/vendor --no-cache-dir \
    $extra_projects_args "$@"
