#!/usr/bin/env bash
#
# Returns debian package dependencies
#

set -eu -o pipefail

for package_path in "$@"; do
    sed -r '/^\s*$/d' "$package_path/debian/control" | formail -x Build-Depends -x Depends
done | sed -r 's/\([^)]*\)//g; s/\$\{[^\}]+\}//g' | tr '\n' ' ' | sed -r 's/[[:space:],]+/ /g; s/^\s+//; s/\s+$//' \
    | tr ' ' '\n' | sort -u