#!/bin/sh
# summary of how this script can be called:
# * <postinst> `configure' <most-recently-configured-version>
# * <old-postinst> `abort-upgrade' <new version>
# * <conflictor's-postinst> `abort-remove' `in-favour' <package> <new-version>
# * <postinst> `abort-remove'
# * <deconfigured's-postinst> `abort-deconfigure' `in-favour'
#   <failed-install-package> <version> `removing'
#   <conflicting-package> <version>
#
# for details, see dh_installdeb(1) or http://www.debian.org/doc/debian-policy/
set -e
case "$1" in
    configure)
        adduser --system --group --no-create-home --disabled-password --disabled-login jaeger || true
        systemctl daemon-reload
        ;;
    abort-upgrade|abort-remove|abort-deconfigure)
        ;;
    *)
        echo "postinst called with unknown argument '$1'" >&2
        exit 1
        ;;
esac

#DEBHELPER#
exit 0
