#!/bin/bash
# summary of how this script can be called:
# * <prerm> `remove'
# * <old-prerm> `upgrade' <new-version>
# * <new-prerm> `failed-upgrade' <old-version>
# * <conflictor's-prerm> `remove' `in-favour' <package> <new-version>
# * <deconfigured's-prerm> `deconfigure' `in-favour'
#   <package-being-installed> <version> `removing'
#   <conflicting-package> <version>
# for details, see http://www.debian.org/doc/debian-policy/ or
# the debian-policy package
set -e
case "$1" in
	remove|purge|abort-install|disappear)
        systemctl disable jaeger-agent || true
        systemctl stop jaeger-agent || true
	;;
	upgrade|failed-upgrade|abort-upgrade)
	;;
	*)
		echo "prerm called with unknown argument \`$1'" >&2
		exit 1
	;;
esac

#DEBHELPER#
exit 0
