#!/bin/bash
exec 2>&1
if [ ! -d /var/run/loggiver/ ]; then
  mkdir /var/run/loggiver/
fi
#ATTENTION. This is atimic kostyl. qloud add /sys/kernel/debug with zero, because perl divide on zero. this sed fix it
sed -i "s/\ |\"/\ |grep\ -v\ \/sys\/kernel\/debug|\"/g" /usr/lib/config-monitoring-common/unispace.pl
ln -s -f /dev/fd/1 /var/log/loggiver/loggiver.log
exec /usr/bin/loggiver

