{
 "title": "IAM Task Processor by Hosts",
 "tags": [
  "iam-duty",
  "iam-tp-host",
  "iam-duty-auto-drilldown"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "service",
    "query": "access-service,iam-control-plane,mfa-service,openid-server,org-service,rm-control-plane,reaper,team-integration,token-service"
   },
   { "name": "ds", "query": "prometheus" },
   { "name": "taskprocessor_pool", "query": "default" },
   {
    "name": "instance",
    "query": {
     "query": "label_values(grpc_statuses{instance=~'.*', yc_iam_app='${service}'}, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Task Processor - ${taskprocessor_pool} Pool - $instance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "repeat": "instance"
  },
  {
   "title": "Task RPS",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "rps" }
   ],
   "targets": [
    {
     "expr": "rate(taskprocessor_task_duration_count{instance=~'${instance}', pool='${taskprocessor_pool}', yc_iam_app='${service}'}[2m])",
     "legendFormat": "{{instance}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "non_negative_derivative"
       }
      ]
     ],
     "tags": {
      "instance": "${instance}",
      "pool": "${taskprocessor_pool}",
      "sensor": "taskprocessor_task_duration_count",
      "yc_iam_app": "${service}"
     },
     "target": "rate(taskprocessor_task_duration_count{instance=~'${instance}', pool='${taskprocessor_pool}', yc_iam_app='${service}'}[2m])",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Special Task States",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(taskprocessor_task_failed{instance=~'${instance}', meter_type='count', pool='${taskprocessor_pool}', yc_iam_app='${service}'}[2m])) by (sensor)",
     "legendFormat": "taskprocessor_task_failed",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "non_negative_derivative"
       },
       {
        "params": [
         "sum",
         "sensor"
        ],
        "type": "group_by_labels"
       }
      ]
     ],
     "tags": {
      "instance": "${instance}",
      "meter_type": "count",
      "pool": "${taskprocessor_pool}",
      "sensor": "taskprocessor_task_failed",
      "yc_iam_app": "${service}"
     },
     "target": "sum(rate(taskprocessor_task_failed{instance=~'${instance}', meter_type='count', pool='${taskprocessor_pool}', yc_iam_app='${service}'}[2m])) by (sensor)",
     "type": "timeserie"
    },
    {
     "expr": "sum(rate(taskprocessor_task_resurrected{instance=~'${instance}', meter_type='count', pool='${taskprocessor_pool}', yc_iam_app='${service}'}[2m])) by (sensor)",
     "legendFormat": "taskprocessor_task_resurrected",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "non_negative_derivative"
       },
       {
        "params": [
         "sum",
         "sensor"
        ],
        "type": "group_by_labels"
       }
      ]
     ],
     "tags": {
      "instance": "${instance}",
      "meter_type": "count",
      "pool": "${taskprocessor_pool}",
      "sensor": "taskprocessor_task_resurrected",
      "yc_iam_app": "${service}"
     },
     "target": "sum(rate(taskprocessor_task_resurrected{instance=~'${instance}', meter_type='count', pool='${taskprocessor_pool}', yc_iam_app='${service}'}[2m])) by (sensor)",
     "type": "timeserie"
    },
    {
     "expr": "sum(rate(taskprocessor_task_interrupted{instance=~'${instance}', meter_type='count', pool='${taskprocessor_pool}', yc_iam_app='${service}'}[2m])) by (sensor)",
     "legendFormat": "taskprocessor_task_interrupted",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "non_negative_derivative"
       },
       {
        "params": [
         "sum",
         "sensor"
        ],
        "type": "group_by_labels"
       }
      ]
     ],
     "tags": {
      "instance": "${instance}",
      "meter_type": "count",
      "pool": "${taskprocessor_pool}",
      "sensor": "taskprocessor_task_interrupted",
      "yc_iam_app": "${service}"
     },
     "target": "sum(rate(taskprocessor_task_interrupted{instance=~'${instance}', meter_type='count', pool='${taskprocessor_pool}', yc_iam_app='${service}'}[2m])) by (sensor)",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Task Start Delay",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(taskprocessor_task_delay_bucket{instance=~'${instance}', pool='${taskprocessor_pool}', yc_iam_app='${service}'}[2m])) by (le))",
     "legendFormat": "p50",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "non_negative_derivative"
       },
       {
        "params": [
         "sum",
         "le"
        ],
        "type": "group_by_labels"
       },
       {
        "params": [
         "50",
         "le"
        ],
        "type": "histogram_percentile"
       },
       { "params": [ "p50" ], "type": "alias" }
      ]
     ],
     "tags": { "instance": "${instance}", "pool": "${taskprocessor_pool}", "sensor": "taskprocessor_task_delay", "yc_iam_app": "${service}" },
     "target": "histogram_quantile(0.5, sum(rate(taskprocessor_task_delay_bucket{instance=~'${instance}', pool='${taskprocessor_pool}', yc_iam_app='${service}'}[2m])) by (le))",
     "type": "timeserie"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(taskprocessor_task_delay_bucket{instance=~'${instance}', pool='${taskprocessor_pool}', yc_iam_app='${service}'}[2m])) by (le))",
     "legendFormat": "p75",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "non_negative_derivative"
       },
       {
        "params": [
         "sum",
         "le"
        ],
        "type": "group_by_labels"
       },
       {
        "params": [
         "75",
         "le"
        ],
        "type": "histogram_percentile"
       },
       { "params": [ "p75" ], "type": "alias" }
      ]
     ],
     "tags": { "instance": "${instance}", "pool": "${taskprocessor_pool}", "sensor": "taskprocessor_task_delay", "yc_iam_app": "${service}" },
     "target": "histogram_quantile(0.75, sum(rate(taskprocessor_task_delay_bucket{instance=~'${instance}', pool='${taskprocessor_pool}', yc_iam_app='${service}'}[2m])) by (le))",
     "type": "timeserie"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(taskprocessor_task_delay_bucket{instance=~'${instance}', pool='${taskprocessor_pool}', yc_iam_app='${service}'}[2m])) by (le))",
     "legendFormat": "p90",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "non_negative_derivative"
       },
       {
        "params": [
         "sum",
         "le"
        ],
        "type": "group_by_labels"
       },
       {
        "params": [
         "90",
         "le"
        ],
        "type": "histogram_percentile"
       },
       { "params": [ "p90" ], "type": "alias" }
      ]
     ],
     "tags": { "instance": "${instance}", "pool": "${taskprocessor_pool}", "sensor": "taskprocessor_task_delay", "yc_iam_app": "${service}" },
     "target": "histogram_quantile(0.9, sum(rate(taskprocessor_task_delay_bucket{instance=~'${instance}', pool='${taskprocessor_pool}', yc_iam_app='${service}'}[2m])) by (le))",
     "type": "timeserie"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(taskprocessor_task_delay_bucket{instance=~'${instance}', pool='${taskprocessor_pool}', yc_iam_app='${service}'}[2m])) by (le))",
     "legendFormat": "p99",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "non_negative_derivative"
       },
       {
        "params": [
         "sum",
         "le"
        ],
        "type": "group_by_labels"
       },
       {
        "params": [
         "99",
         "le"
        ],
        "type": "histogram_percentile"
       },
       { "params": [ "p99" ], "type": "alias" }
      ]
     ],
     "tags": { "instance": "${instance}", "pool": "${taskprocessor_pool}", "sensor": "taskprocessor_task_delay", "yc_iam_app": "${service}" },
     "target": "histogram_quantile(0.99, sum(rate(taskprocessor_task_delay_bucket{instance=~'${instance}', pool='${taskprocessor_pool}', yc_iam_app='${service}'}[2m])) by (le))",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Task Duration",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 1 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(taskprocessor_task_duration_bucket{instance=~'${instance}', pool='${taskprocessor_pool}', yc_iam_app='${service}'}[2m])) by (le))",
     "legendFormat": "p50",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "non_negative_derivative"
       },
       {
        "params": [
         "sum",
         "le"
        ],
        "type": "group_by_labels"
       },
       {
        "params": [
         "50",
         "le"
        ],
        "type": "histogram_percentile"
       },
       { "params": [ "p50" ], "type": "alias" }
      ]
     ],
     "tags": { "instance": "${instance}", "pool": "${taskprocessor_pool}", "sensor": "taskprocessor_task_duration", "yc_iam_app": "${service}" },
     "target": "histogram_quantile(0.5, sum(rate(taskprocessor_task_duration_bucket{instance=~'${instance}', pool='${taskprocessor_pool}', yc_iam_app='${service}'}[2m])) by (le))",
     "type": "timeserie"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(taskprocessor_task_duration_bucket{instance=~'${instance}', pool='${taskprocessor_pool}', yc_iam_app='${service}'}[2m])) by (le))",
     "legendFormat": "p75",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "non_negative_derivative"
       },
       {
        "params": [
         "sum",
         "le"
        ],
        "type": "group_by_labels"
       },
       {
        "params": [
         "75",
         "le"
        ],
        "type": "histogram_percentile"
       },
       { "params": [ "p75" ], "type": "alias" }
      ]
     ],
     "tags": { "instance": "${instance}", "pool": "${taskprocessor_pool}", "sensor": "taskprocessor_task_duration", "yc_iam_app": "${service}" },
     "target": "histogram_quantile(0.75, sum(rate(taskprocessor_task_duration_bucket{instance=~'${instance}', pool='${taskprocessor_pool}', yc_iam_app='${service}'}[2m])) by (le))",
     "type": "timeserie"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(taskprocessor_task_duration_bucket{instance=~'${instance}', pool='${taskprocessor_pool}', yc_iam_app='${service}'}[2m])) by (le))",
     "legendFormat": "p90",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "non_negative_derivative"
       },
       {
        "params": [
         "sum",
         "le"
        ],
        "type": "group_by_labels"
       },
       {
        "params": [
         "90",
         "le"
        ],
        "type": "histogram_percentile"
       },
       { "params": [ "p90" ], "type": "alias" }
      ]
     ],
     "tags": { "instance": "${instance}", "pool": "${taskprocessor_pool}", "sensor": "taskprocessor_task_duration", "yc_iam_app": "${service}" },
     "target": "histogram_quantile(0.9, sum(rate(taskprocessor_task_duration_bucket{instance=~'${instance}', pool='${taskprocessor_pool}', yc_iam_app='${service}'}[2m])) by (le))",
     "type": "timeserie"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(taskprocessor_task_duration_bucket{instance=~'${instance}', pool='${taskprocessor_pool}', yc_iam_app='${service}'}[2m])) by (le))",
     "legendFormat": "p99",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "non_negative_derivative"
       },
       {
        "params": [
         "sum",
         "le"
        ],
        "type": "group_by_labels"
       },
       {
        "params": [
         "99",
         "le"
        ],
        "type": "histogram_percentile"
       },
       { "params": [ "p99" ], "type": "alias" }
      ]
     ],
     "tags": { "instance": "${instance}", "pool": "${taskprocessor_pool}", "sensor": "taskprocessor_task_duration", "yc_iam_app": "${service}" },
     "target": "histogram_quantile(0.99, sum(rate(taskprocessor_task_duration_bucket{instance=~'${instance}', pool='${taskprocessor_pool}', yc_iam_app='${service}'}[2m])) by (le))",
     "type": "timeserie"
    }
   ]
  }
 ]
}