{
 "title": "IAM Duty Dashboard",
 "tags": [
  "iam",
  "iam-duty",
  "iam-duty-dashboard"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "service",
    "query": "access-service,iam-control-plane,mfa-service,openid-server,org-service,rm-control-plane,reaper,team-integration,token-service"
   },
   { "name": "ds", "query": "prometheus" },
   { "name": "taskprocessor_pool", "query": "default" },
   {
    "name": "instance",
    "query": {
     "query": "label_values(grpc_statuses{instance=~'.*', yc_iam_app='${service}'}, instance)"
    }
   },
   {
    "name": "app",
    "query": {
     "query": "label_values(grpc_statuses{app=~'.*', instance=~'${instance:pipe}', method=~'.*', yc_iam_app='${service}'}, app)"
    }
   },
   {
    "name": "method",
    "query": {
     "query": "label_values(grpc_statuses{app='${app}', instance=~'${instance:pipe}', method=~'.*', yc_iam_app='${service}'}, method)"
    }
   }
  ]
 },
 "panels": [
  { "title": "IAM Singlestats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "AS",
   "type": "stat",
   "description": "Access Service",
   "gridPos": { "h": 4, "w": 1, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(grpc_statuses{instance=~'${instance:pipe}', service='access-service', status='UNKNOWN|UNIMPLEMENTED|INTERNAL|DATA_LOSS', yc_iam_app='${service}'})",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "diff"
       },
       { "params": [ "0" ], "type": "drop_below" },
       { "params": [ "sum" ], "type": "group_lines" }
      ]
     ],
     "tags": {
      "instance": "${instance:pipe}",
      "sensor": "grpc_statuses",
      "service": "access-service",
      "status": "UNKNOWN|UNIMPLEMENTED|INTERNAL|DATA_LOSS",
      "yc_iam_app": "${service}"
     },
     "target": "sum(grpc_statuses{instance=~'${instance:pipe}', service='access-service', status='UNKNOWN|UNIMPLEMENTED|INTERNAL|DATA_LOSS', yc_iam_app='${service}'})",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "IAM",
   "type": "stat",
   "description": "IAM CP",
   "gridPos": { "h": 4, "w": 1, "x": 1, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(grpc_statuses{instance=~'${instance:pipe}', service='iam-control-plane', status='UNKNOWN|UNIMPLEMENTED|INTERNAL|DATA_LOSS', yc_iam_app='${service}'})",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "diff"
       },
       { "params": [ "0" ], "type": "drop_below" },
       { "params": [ "sum" ], "type": "group_lines" }
      ]
     ],
     "tags": {
      "instance": "${instance:pipe}",
      "sensor": "grpc_statuses",
      "service": "iam-control-plane",
      "status": "UNKNOWN|UNIMPLEMENTED|INTERNAL|DATA_LOSS",
      "yc_iam_app": "${service}"
     },
     "target": "sum(grpc_statuses{instance=~'${instance:pipe}', service='iam-control-plane', status='UNKNOWN|UNIMPLEMENTED|INTERNAL|DATA_LOSS', yc_iam_app='${service}'})",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "MFA",
   "type": "stat",
   "description": "MFA Service",
   "gridPos": { "h": 4, "w": 1, "x": 2, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(grpc_statuses{instance=~'${instance:pipe}', service='mfa-service', status='UNKNOWN|UNIMPLEMENTED|INTERNAL|DATA_LOSS', yc_iam_app='${service}'})",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "diff"
       },
       { "params": [ "0" ], "type": "drop_below" },
       { "params": [ "sum" ], "type": "group_lines" }
      ]
     ],
     "tags": {
      "instance": "${instance:pipe}",
      "sensor": "grpc_statuses",
      "service": "mfa-service",
      "status": "UNKNOWN|UNIMPLEMENTED|INTERNAL|DATA_LOSS",
      "yc_iam_app": "${service}"
     },
     "target": "sum(grpc_statuses{instance=~'${instance:pipe}', service='mfa-service', status='UNKNOWN|UNIMPLEMENTED|INTERNAL|DATA_LOSS', yc_iam_app='${service}'})",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "OID",
   "type": "stat",
   "description": "OpenID Server",
   "gridPos": { "h": 4, "w": 1, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(grpc_statuses{instance=~'${instance:pipe}', service='openid-server', status='UNKNOWN|UNIMPLEMENTED|INTERNAL|DATA_LOSS', yc_iam_app='${service}'})",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "diff"
       },
       { "params": [ "0" ], "type": "drop_below" },
       { "params": [ "sum" ], "type": "group_lines" }
      ]
     ],
     "tags": {
      "instance": "${instance:pipe}",
      "sensor": "grpc_statuses",
      "service": "openid-server",
      "status": "UNKNOWN|UNIMPLEMENTED|INTERNAL|DATA_LOSS",
      "yc_iam_app": "${service}"
     },
     "target": "sum(grpc_statuses{instance=~'${instance:pipe}', service='openid-server', status='UNKNOWN|UNIMPLEMENTED|INTERNAL|DATA_LOSS', yc_iam_app='${service}'})",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "ORG",
   "type": "stat",
   "description": "Organization Service",
   "gridPos": { "h": 4, "w": 1, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(grpc_statuses{instance=~'${instance:pipe}', service='org-service', status='UNKNOWN|UNIMPLEMENTED|INTERNAL|DATA_LOSS', yc_iam_app='${service}'})",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "diff"
       },
       { "params": [ "0" ], "type": "drop_below" },
       { "params": [ "sum" ], "type": "group_lines" }
      ]
     ],
     "tags": {
      "instance": "${instance:pipe}",
      "sensor": "grpc_statuses",
      "service": "org-service",
      "status": "UNKNOWN|UNIMPLEMENTED|INTERNAL|DATA_LOSS",
      "yc_iam_app": "${service}"
     },
     "target": "sum(grpc_statuses{instance=~'${instance:pipe}', service='org-service', status='UNKNOWN|UNIMPLEMENTED|INTERNAL|DATA_LOSS', yc_iam_app='${service}'})",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "RM",
   "type": "stat",
   "description": "RM CP",
   "gridPos": { "h": 4, "w": 1, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(grpc_statuses{instance=~'${instance:pipe}', service='rm-control-plane', status='UNKNOWN|UNIMPLEMENTED|INTERNAL|DATA_LOSS', yc_iam_app='${service}'})",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "diff"
       },
       { "params": [ "0" ], "type": "drop_below" },
       { "params": [ "sum" ], "type": "group_lines" }
      ]
     ],
     "tags": {
      "instance": "${instance:pipe}",
      "sensor": "grpc_statuses",
      "service": "rm-control-plane",
      "status": "UNKNOWN|UNIMPLEMENTED|INTERNAL|DATA_LOSS",
      "yc_iam_app": "${service}"
     },
     "target": "sum(grpc_statuses{instance=~'${instance:pipe}', service='rm-control-plane', status='UNKNOWN|UNIMPLEMENTED|INTERNAL|DATA_LOSS', yc_iam_app='${service}'})",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "RR",
   "type": "stat",
   "description": "Reaper",
   "gridPos": { "h": 4, "w": 1, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(grpc_statuses{instance=~'${instance:pipe}', service='reaper', status='UNKNOWN|UNIMPLEMENTED|INTERNAL|DATA_LOSS', yc_iam_app='${service}'})",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "diff"
       },
       { "params": [ "0" ], "type": "drop_below" },
       { "params": [ "sum" ], "type": "group_lines" }
      ]
     ],
     "tags": {
      "instance": "${instance:pipe}",
      "sensor": "grpc_statuses",
      "service": "reaper",
      "status": "UNKNOWN|UNIMPLEMENTED|INTERNAL|DATA_LOSS",
      "yc_iam_app": "${service}"
     },
     "target": "sum(grpc_statuses{instance=~'${instance:pipe}', service='reaper', status='UNKNOWN|UNIMPLEMENTED|INTERNAL|DATA_LOSS', yc_iam_app='${service}'})",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "TI",
   "type": "stat",
   "description": "Team Integration",
   "gridPos": { "h": 4, "w": 1, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(grpc_statuses{instance=~'${instance:pipe}', service='team-integration', status='UNKNOWN|UNIMPLEMENTED|INTERNAL|DATA_LOSS', yc_iam_app='${service}'})",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "diff"
       },
       { "params": [ "0" ], "type": "drop_below" },
       { "params": [ "sum" ], "type": "group_lines" }
      ]
     ],
     "tags": {
      "instance": "${instance:pipe}",
      "sensor": "grpc_statuses",
      "service": "team-integration",
      "status": "UNKNOWN|UNIMPLEMENTED|INTERNAL|DATA_LOSS",
      "yc_iam_app": "${service}"
     },
     "target": "sum(grpc_statuses{instance=~'${instance:pipe}', service='team-integration', status='UNKNOWN|UNIMPLEMENTED|INTERNAL|DATA_LOSS', yc_iam_app='${service}'})",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "TS",
   "type": "stat",
   "description": "Token Service",
   "gridPos": { "h": 4, "w": 1, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(grpc_statuses{instance=~'${instance:pipe}', service='token-service', status='UNKNOWN|UNIMPLEMENTED|INTERNAL|DATA_LOSS', yc_iam_app='${service}'})",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "diff"
       },
       { "params": [ "0" ], "type": "drop_below" },
       { "params": [ "sum" ], "type": "group_lines" }
      ]
     ],
     "tags": {
      "instance": "${instance:pipe}",
      "sensor": "grpc_statuses",
      "service": "token-service",
      "status": "UNKNOWN|UNIMPLEMENTED|INTERNAL|DATA_LOSS",
      "yc_iam_app": "${service}"
     },
     "target": "sum(grpc_statuses{instance=~'${instance:pipe}', service='token-service', status='UNKNOWN|UNIMPLEMENTED|INTERNAL|DATA_LOSS', yc_iam_app='${service}'})",
     "type": "timeserie"
    }
   ]
  },
  { "title": "${service} GRPC Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "GRPC Errors",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(grpc_statuses{app='${app}', instance=~'${instance:pipe}', method=~'${method:pipe}', status='UNKNOWN|UNIMPLEMENTED|INTERNAL|DATA_LOSS', yc_iam_app='${service}'})",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "diff"
       },
       { "params": [ "0" ], "type": "drop_below" },
       { "params": [ "sum" ], "type": "group_lines" }
      ]
     ],
     "tags": {
      "app": "${app}",
      "instance": "${instance:pipe}",
      "method": "${method:pipe}",
      "sensor": "grpc_statuses",
      "status": "UNKNOWN|UNIMPLEMENTED|INTERNAL|DATA_LOSS",
      "yc_iam_app": "${service}"
     },
     "target": "sum(grpc_statuses{app='${app}', instance=~'${instance:pipe}', method=~'${method:pipe}', status='UNKNOWN|UNIMPLEMENTED|INTERNAL|DATA_LOSS', yc_iam_app='${service}'})",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "GRPC/HTTP statuses RPS",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 2, "y": 6 },
   "yaxes": [
    { "format": "short", "label": "rps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(grpc_statuses{app='${app}', instance=~'${instance:pipe}', method=~'${method:pipe}', yc_iam_app='${service}'}[2m])) by (status)",
     "legendFormat": "{{status}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "non_negative_derivative"
       },
       { "params": [ "1m" ], "type": "moving_avg" },
       {
        "params": [
         "sum",
         "status"
        ],
        "type": "group_by_labels"
       },
       { "params": [ "{{status}}" ], "type": "alias" }
      ]
     ],
     "tags": {
      "app": "${app}",
      "instance": "${instance:pipe}",
      "method": "${method:pipe}",
      "sensor": "grpc_statuses",
      "yc_iam_app": "${service}"
     },
     "target": "sum(rate(grpc_statuses{app='${app}', instance=~'${instance:pipe}', method=~'${method:pipe}', yc_iam_app='${service}'}[2m])) by (status)",
     "type": "timeserie"
    },
    {
     "expr": "sum(rate(servlet_statuses{app='${app}', instance=~'${instance:pipe}', method=~'${method:pipe}', yc_iam_app='${service}'}[2m])) by (status)",
     "legendFormat": "{{status}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "non_negative_derivative"
       },
       { "params": [ "1m" ], "type": "moving_avg" },
       {
        "params": [
         "sum",
         "status"
        ],
        "type": "group_by_labels"
       },
       { "params": [ "{{status}}" ], "type": "alias" }
      ]
     ],
     "tags": {
      "app": "${app}",
      "instance": "${instance:pipe}",
      "method": "${method:pipe}",
      "sensor": "servlet_statuses",
      "yc_iam_app": "${service}"
     },
     "target": "sum(rate(servlet_statuses{app='${app}', instance=~'${instance:pipe}', method=~'${method:pipe}', yc_iam_app='${service}'}[2m])) by (status)",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 9, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(grpc_statuses{app='${app}', instance=~'${instance:pipe}', method=~'${method:pipe}', status=~'DEADLINE_EXCEEDED', yc_iam_app='${service}'}[2m]))",
     "legendFormat": "499",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "1m" ], "type": "moving_avg" },
       {
        "params": [],
        "type": "non_negative_derivative"
       },
       { "params": [ "0" ], "type": "drop_below" },
       { "params": [ "sum" ], "type": "group_lines" },
       { "params": [ "499" ], "type": "alias" }
      ]
     ],
     "tags": {
      "app": "${app}",
      "instance": "${instance:pipe}",
      "method": "${method:pipe}",
      "sensor": "grpc_statuses",
      "status": "DEADLINE_EXCEEDED",
      "yc_iam_app": "${service}"
     },
     "target": "sum(rate(grpc_statuses{app='${app}', instance=~'${instance:pipe}', method=~'${method:pipe}', status=~'DEADLINE_EXCEEDED', yc_iam_app='${service}'}[2m]))",
     "type": "timeserie"
    },
    {
     "expr": "sum(rate(grpc_statuses{app='${app}', instance=~'${instance:pipe}', method=~'${method:pipe}', status=~'CANCELLED|INVALID_ARGUMENT|NOT_FOUND|ALREADY_EXISTS|PERMISSION_DENIED|RESOURCE_EXHAUSTED|FAILED_PRECONDITION|ABORTED|OUT_OF_RANGE|UNAUTHENTICATED', yc_iam_app='${service}'}[2m]))",
     "legendFormat": "4xx",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "1m" ], "type": "moving_avg" },
       {
        "params": [],
        "type": "non_negative_derivative"
       },
       { "params": [ "0" ], "type": "drop_below" },
       { "params": [ "sum" ], "type": "group_lines" },
       { "params": [ "4xx" ], "type": "alias" }
      ]
     ],
     "tags": {
      "app": "${app}",
      "instance": "${instance:pipe}",
      "method": "${method:pipe}",
      "sensor": "grpc_statuses",
      "status": "CANCELLED|INVALID_ARGUMENT|NOT_FOUND|ALREADY_EXISTS|PERMISSION_DENIED|RESOURCE_EXHAUSTED|FAILED_PRECONDITION|ABORTED|OUT_OF_RANGE|UNAUTHENTICATED",
      "yc_iam_app": "${service}"
     },
     "target": "sum(rate(grpc_statuses{app='${app}', instance=~'${instance:pipe}', method=~'${method:pipe}', status=~'CANCELLED|INVALID_ARGUMENT|NOT_FOUND|ALREADY_EXISTS|PERMISSION_DENIED|RESOURCE_EXHAUSTED|FAILED_PRECONDITION|ABORTED|OUT_OF_RANGE|UNAUTHENTICATED', yc_iam_app='${service}'}[2m]))",
     "type": "timeserie"
    },
    {
     "expr": "sum(rate(grpc_statuses{app='${app}', instance=~'${instance:pipe}', method=~'${method:pipe}', status='UNAVAILABLE', yc_iam_app='${service}'}[2m]))",
     "legendFormat": "503",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "1m" ], "type": "moving_avg" },
       {
        "params": [],
        "type": "non_negative_derivative"
       },
       { "params": [ "0" ], "type": "drop_below" },
       { "params": [ "sum" ], "type": "group_lines" },
       { "params": [ "503" ], "type": "alias" }
      ]
     ],
     "tags": {
      "app": "${app}",
      "instance": "${instance:pipe}",
      "method": "${method:pipe}",
      "sensor": "grpc_statuses",
      "status": "UNAVAILABLE",
      "yc_iam_app": "${service}"
     },
     "target": "sum(rate(grpc_statuses{app='${app}', instance=~'${instance:pipe}', method=~'${method:pipe}', status='UNAVAILABLE', yc_iam_app='${service}'}[2m]))",
     "type": "timeserie"
    },
    {
     "expr": "sum(rate(grpc_statuses{app='${app}', instance=~'${instance:pipe}', method=~'${method:pipe}', status=~'UNKNOWN|UNIMPLEMENTED|INTERNAL|DATA_LOSS', yc_iam_app='${service}'}[2m]))",
     "legendFormat": "5xx",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "1m" ], "type": "moving_avg" },
       {
        "params": [],
        "type": "non_negative_derivative"
       },
       { "params": [ "0" ], "type": "drop_below" },
       { "params": [ "sum" ], "type": "group_lines" },
       { "params": [ "5xx" ], "type": "alias" }
      ]
     ],
     "tags": {
      "app": "${app}",
      "instance": "${instance:pipe}",
      "method": "${method:pipe}",
      "sensor": "grpc_statuses",
      "status": "UNKNOWN|UNIMPLEMENTED|INTERNAL|DATA_LOSS",
      "yc_iam_app": "${service}"
     },
     "target": "sum(rate(grpc_statuses{app='${app}', instance=~'${instance:pipe}', method=~'${method:pipe}', status=~'UNKNOWN|UNIMPLEMENTED|INTERNAL|DATA_LOSS', yc_iam_app='${service}'}[2m]))",
     "type": "timeserie"
    },
    {
     "expr": "sum(rate(servlet_statuses{app='${app}', instance=~'${instance:pipe}', method=~'${method:pipe}', status='499', yc_iam_app='${service}'}[2m]))",
     "legendFormat": "h499",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "1m" ], "type": "moving_avg" },
       {
        "params": [],
        "type": "non_negative_derivative"
       },
       { "params": [ "0" ], "type": "drop_below" },
       { "params": [ "sum" ], "type": "group_lines" },
       { "params": [ "h499" ], "type": "alias" }
      ]
     ],
     "tags": {
      "app": "${app}",
      "instance": "${instance:pipe}",
      "method": "${method:pipe}",
      "sensor": "servlet_statuses",
      "status": "499",
      "yc_iam_app": "${service}"
     },
     "target": "sum(rate(servlet_statuses{app='${app}', instance=~'${instance:pipe}', method=~'${method:pipe}', status='499', yc_iam_app='${service}'}[2m]))",
     "type": "timeserie"
    },
    {
     "expr": "sum(rate(servlet_statuses{app='${app}', instance=~'${instance:pipe}', method=~'${method:pipe}', status=~'4*|3*', yc_iam_app='${service}'}[2m]))",
     "legendFormat": "h4xx",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "1m" ], "type": "moving_avg" },
       {
        "params": [],
        "type": "non_negative_derivative"
       },
       { "params": [ "0" ], "type": "drop_below" },
       { "params": [ "sum" ], "type": "group_lines" },
       { "params": [ "h4xx3xx" ], "type": "alias" }
      ]
     ],
     "tags": {
      "app": "${app}",
      "instance": "${instance:pipe}",
      "method": "${method:pipe}",
      "sensor": "servlet_statuses",
      "status": "4*|3*",
      "yc_iam_app": "${service}"
     },
     "target": "sum(rate(servlet_statuses{app='${app}', instance=~'${instance:pipe}', method=~'${method:pipe}', status=~'4*|3*', yc_iam_app='${service}'}[2m]))",
     "type": "timeserie"
    },
    {
     "expr": "sum(rate(servlet_statuses{app='${app}', instance=~'${instance:pipe}', method=~'${method:pipe}', status='503', yc_iam_app='${service}'}[2m]))",
     "legendFormat": "h503",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "1m" ], "type": "moving_avg" },
       {
        "params": [],
        "type": "non_negative_derivative"
       },
       { "params": [ "0" ], "type": "drop_below" },
       { "params": [ "sum" ], "type": "group_lines" },
       { "params": [ "h503" ], "type": "alias" }
      ]
     ],
     "tags": {
      "app": "${app}",
      "instance": "${instance:pipe}",
      "method": "${method:pipe}",
      "sensor": "servlet_statuses",
      "status": "503",
      "yc_iam_app": "${service}"
     },
     "target": "sum(rate(servlet_statuses{app='${app}', instance=~'${instance:pipe}', method=~'${method:pipe}', status='503', yc_iam_app='${service}'}[2m]))",
     "type": "timeserie"
    },
    {
     "expr": "sum(rate(servlet_statuses{app='${app}', instance=~'${instance:pipe}', method=~'${method:pipe}', status='5*', yc_iam_app='${service}'}[2m]))",
     "legendFormat": "h5xx",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "1m" ], "type": "moving_avg" },
       {
        "params": [],
        "type": "non_negative_derivative"
       },
       { "params": [ "0" ], "type": "drop_below" },
       { "params": [ "sum" ], "type": "group_lines" },
       { "params": [ "h5xx" ], "type": "alias" }
      ]
     ],
     "tags": {
      "app": "${app}",
      "instance": "${instance:pipe}",
      "method": "${method:pipe}",
      "sensor": "servlet_statuses",
      "status": "5*",
      "yc_iam_app": "${service}"
     },
     "target": "sum(rate(servlet_statuses{app='${app}', instance=~'${instance:pipe}', method=~'${method:pipe}', status='5*', yc_iam_app='${service}'}[2m]))",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "GRPC/HTTP Durations",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 6 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(grpc_durations_bucket{app='${app}', instance=~'${instance:pipe}', method=~'${method:pipe}', yc_iam_app='${service}'}[2m])) by (le))",
     "legendFormat": "p99",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "1m" ], "type": "moving_avg" },
       {
        "params": [],
        "type": "non_negative_derivative"
       },
       {
        "params": [
         "sum",
         "le"
        ],
        "type": "group_by_labels"
       },
       {
        "params": [
         "99",
         "le"
        ],
        "type": "histogram_percentile"
       },
       { "params": [ "p99" ], "type": "alias" }
      ]
     ],
     "tags": {
      "app": "${app}",
      "instance": "${instance:pipe}",
      "method": "${method:pipe}",
      "sensor": "grpc_durations",
      "yc_iam_app": "${service}"
     },
     "target": "histogram_quantile(0.99, sum(rate(grpc_durations_bucket{app='${app}', instance=~'${instance:pipe}', method=~'${method:pipe}', yc_iam_app='${service}'}[2m])) by (le))",
     "type": "timeserie"
    },
    {
     "expr": "histogram_quantile(0.999, sum(rate(grpc_durations_bucket{app='${app}', instance=~'${instance:pipe}', method=~'${method:pipe}', yc_iam_app='${service}'}[2m])) by (le))",
     "legendFormat": "p99.9",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "1m" ], "type": "moving_avg" },
       {
        "params": [],
        "type": "non_negative_derivative"
       },
       {
        "params": [
         "sum",
         "le"
        ],
        "type": "group_by_labels"
       },
       {
        "params": [
         "99.9",
         "le"
        ],
        "type": "histogram_percentile"
       },
       { "params": [ "p99.9" ], "type": "alias" }
      ]
     ],
     "tags": {
      "app": "${app}",
      "instance": "${instance:pipe}",
      "method": "${method:pipe}",
      "sensor": "grpc_durations",
      "yc_iam_app": "${service}"
     },
     "target": "histogram_quantile(0.999, sum(rate(grpc_durations_bucket{app='${app}', instance=~'${instance:pipe}', method=~'${method:pipe}', yc_iam_app='${service}'}[2m])) by (le))",
     "type": "timeserie"
    },
    {
     "expr": "histogram_quantile(0.9999, sum(rate(grpc_durations_bucket{app='${app}', instance=~'${instance:pipe}', method=~'${method:pipe}', yc_iam_app='${service}'}[2m])) by (le))",
     "legendFormat": "p99.99",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "1m" ], "type": "moving_avg" },
       {
        "params": [],
        "type": "non_negative_derivative"
       },
       {
        "params": [
         "sum",
         "le"
        ],
        "type": "group_by_labels"
       },
       {
        "params": [
         "99.99",
         "le"
        ],
        "type": "histogram_percentile"
       },
       { "params": [ "p99.99" ], "type": "alias" }
      ]
     ],
     "tags": {
      "app": "${app}",
      "instance": "${instance:pipe}",
      "method": "${method:pipe}",
      "sensor": "grpc_durations",
      "yc_iam_app": "${service}"
     },
     "target": "histogram_quantile(0.9999, sum(rate(grpc_durations_bucket{app='${app}', instance=~'${instance:pipe}', method=~'${method:pipe}', yc_iam_app='${service}'}[2m])) by (le))",
     "type": "timeserie"
    },
    {
     "expr": "histogram_quantile(1.0, sum(rate(grpc_durations_bucket{app='${app}', instance=~'${instance:pipe}', method=~'${method:pipe}', yc_iam_app='${service}'}[2m])) by (le))",
     "legendFormat": "p100",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "1m" ], "type": "moving_avg" },
       {
        "params": [],
        "type": "non_negative_derivative"
       },
       {
        "params": [
         "sum",
         "le"
        ],
        "type": "group_by_labels"
       },
       {
        "params": [
         "100",
         "le"
        ],
        "type": "histogram_percentile"
       },
       { "params": [ "p100" ], "type": "alias" }
      ]
     ],
     "tags": {
      "app": "${app}",
      "instance": "${instance:pipe}",
      "method": "${method:pipe}",
      "sensor": "grpc_durations",
      "yc_iam_app": "${service}"
     },
     "target": "histogram_quantile(1.0, sum(rate(grpc_durations_bucket{app='${app}', instance=~'${instance:pipe}', method=~'${method:pipe}', yc_iam_app='${service}'}[2m])) by (le))",
     "type": "timeserie"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(servlet_durations_bucket{app='${app}', instance=~'${instance:pipe}', method=~'${method:pipe}', yc_iam_app='${service}'}[2m])) by (le))",
     "legendFormat": "p99h",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "1m" ], "type": "moving_avg" },
       {
        "params": [],
        "type": "non_negative_derivative"
       },
       {
        "params": [
         "sum",
         "le"
        ],
        "type": "group_by_labels"
       },
       {
        "params": [
         "99",
         "le"
        ],
        "type": "histogram_percentile"
       },
       { "params": [ "http.p99" ], "type": "alias" }
      ]
     ],
     "tags": {
      "app": "${app}",
      "instance": "${instance:pipe}",
      "method": "${method:pipe}",
      "sensor": "servlet_durations",
      "yc_iam_app": "${service}"
     },
     "target": "histogram_quantile(0.99, sum(rate(servlet_durations_bucket{app='${app}', instance=~'${instance:pipe}', method=~'${method:pipe}', yc_iam_app='${service}'}[2m])) by (le))",
     "type": "timeserie"
    },
    {
     "expr": "histogram_quantile(0.999, sum(rate(servlet_durations_bucket{app='${app}', instance=~'${instance:pipe}', method=~'${method:pipe}', yc_iam_app='${service}'}[2m])) by (le))",
     "legendFormat": "p99.9h",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "1m" ], "type": "moving_avg" },
       {
        "params": [],
        "type": "non_negative_derivative"
       },
       {
        "params": [
         "sum",
         "le"
        ],
        "type": "group_by_labels"
       },
       {
        "params": [
         "99.9",
         "le"
        ],
        "type": "histogram_percentile"
       },
       { "params": [ "http.p99.9" ], "type": "alias" }
      ]
     ],
     "tags": {
      "app": "${app}",
      "instance": "${instance:pipe}",
      "method": "${method:pipe}",
      "sensor": "servlet_durations",
      "yc_iam_app": "${service}"
     },
     "target": "histogram_quantile(0.999, sum(rate(servlet_durations_bucket{app='${app}', instance=~'${instance:pipe}', method=~'${method:pipe}', yc_iam_app='${service}'}[2m])) by (le))",
     "type": "timeserie"
    },
    {
     "expr": "histogram_quantile(0.9999, sum(rate(servlet_durations_bucket{app='${app}', instance=~'${instance:pipe}', method=~'${method:pipe}', yc_iam_app='${service}'}[2m])) by (le))",
     "legendFormat": "p99.99h",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "1m" ], "type": "moving_avg" },
       {
        "params": [],
        "type": "non_negative_derivative"
       },
       {
        "params": [
         "sum",
         "le"
        ],
        "type": "group_by_labels"
       },
       {
        "params": [
         "99.99",
         "le"
        ],
        "type": "histogram_percentile"
       },
       { "params": [ "http.p99.99" ], "type": "alias" }
      ]
     ],
     "tags": {
      "app": "${app}",
      "instance": "${instance:pipe}",
      "method": "${method:pipe}",
      "sensor": "servlet_durations",
      "yc_iam_app": "${service}"
     },
     "target": "histogram_quantile(0.9999, sum(rate(servlet_durations_bucket{app='${app}', instance=~'${instance:pipe}', method=~'${method:pipe}', yc_iam_app='${service}'}[2m])) by (le))",
     "type": "timeserie"
    },
    {
     "expr": "histogram_quantile(1.0, sum(rate(servlet_durations_bucket{app='${app}', instance=~'${instance:pipe}', method=~'${method:pipe}', yc_iam_app='${service}'}[2m])) by (le))",
     "legendFormat": "p100h",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "1m" ], "type": "moving_avg" },
       {
        "params": [],
        "type": "non_negative_derivative"
       },
       {
        "params": [
         "sum",
         "le"
        ],
        "type": "group_by_labels"
       },
       {
        "params": [
         "100",
         "le"
        ],
        "type": "histogram_percentile"
       },
       { "params": [ "http.p100" ], "type": "alias" }
      ]
     ],
     "tags": {
      "app": "${app}",
      "instance": "${instance:pipe}",
      "method": "${method:pipe}",
      "sensor": "servlet_durations",
      "yc_iam_app": "${service}"
     },
     "target": "histogram_quantile(1.0, sum(rate(servlet_durations_bucket{app='${app}', instance=~'${instance:pipe}', method=~'${method:pipe}', yc_iam_app='${service}'}[2m])) by (le))",
     "type": "timeserie"
    }
   ]
  },
  { "title": "${service} GRPC Connections", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Active Connections",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(grpc_connections_active{instance=~'${instance:pipe}', yc_iam_app='${service}'})",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "sum" ], "type": "group_lines" }
      ]
     ],
     "tags": { "instance": "${instance:pipe}", "sensor": "grpc_connections_active", "yc_iam_app": "${service}" },
     "target": "sum(grpc_connections_active{instance=~'${instance:pipe}', yc_iam_app='${service}'})",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "GRPC Connections RPS",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 2, "y": 13 },
   "yaxes": [
    { "format": "short", "label": "rps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(grpc_connections_total{instance=~'${instance:pipe}', yc_iam_app='${service}'}[2m]))",
     "legendFormat": "rps",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "non_negative_derivative"
       },
       { "params": [ "sum" ], "type": "group_lines" },
       { "params": [ "1m" ], "type": "moving_avg" },
       { "params": [ "rps" ], "type": "alias" }
      ]
     ],
     "tags": { "instance": "${instance:pipe}", "sensor": "grpc_connections_total", "yc_iam_app": "${service}" },
     "target": "sum(rate(grpc_connections_total{instance=~'${instance:pipe}', yc_iam_app='${service}'}[2m]))",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "GRPC Active Connections",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 9, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(grpc_connections_active{instance=~'${instance:pipe}', yc_iam_app='${service}'})",
     "legendFormat": "count",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "sum" ], "type": "group_lines" },
       { "params": [ "count" ], "type": "alias" }
      ]
     ],
     "tags": { "instance": "${instance:pipe}", "sensor": "grpc_connections_active", "yc_iam_app": "${service}" },
     "target": "sum(grpc_connections_active{instance=~'${instance:pipe}', yc_iam_app='${service}'})",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Connections Durations",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 13 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.01, sum(rate(grpc_connections_durations_bucket{instance=~'${instance:pipe}', yc_iam_app='${service}'}[2m])) by (le))",
     "legendFormat": "p1",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "non_negative_derivative"
       },
       {
        "params": [
         "sum",
         "le"
        ],
        "type": "group_by_labels"
       },
       {
        "params": [
         "1",
         "le"
        ],
        "type": "histogram_percentile"
       },
       { "params": [ "1m" ], "type": "moving_avg" },
       { "params": [ "p1" ], "type": "alias" }
      ]
     ],
     "tags": { "instance": "${instance:pipe}", "sensor": "grpc_connections_durations", "yc_iam_app": "${service}" },
     "target": "histogram_quantile(0.01, sum(rate(grpc_connections_durations_bucket{instance=~'${instance:pipe}', yc_iam_app='${service}'}[2m])) by (le))",
     "type": "timeserie"
    },
    {
     "expr": "histogram_quantile(0.1, sum(rate(grpc_connections_durations_bucket{instance=~'${instance:pipe}', yc_iam_app='${service}'}[2m])) by (le))",
     "legendFormat": "p10",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "non_negative_derivative"
       },
       {
        "params": [
         "sum",
         "le"
        ],
        "type": "group_by_labels"
       },
       {
        "params": [
         "10",
         "le"
        ],
        "type": "histogram_percentile"
       },
       { "params": [ "1m" ], "type": "moving_avg" },
       { "params": [ "p10" ], "type": "alias" }
      ]
     ],
     "tags": { "instance": "${instance:pipe}", "sensor": "grpc_connections_durations", "yc_iam_app": "${service}" },
     "target": "histogram_quantile(0.1, sum(rate(grpc_connections_durations_bucket{instance=~'${instance:pipe}', yc_iam_app='${service}'}[2m])) by (le))",
     "type": "timeserie"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(grpc_connections_durations_bucket{instance=~'${instance:pipe}', yc_iam_app='${service}'}[2m])) by (le))",
     "legendFormat": "p50",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "non_negative_derivative"
       },
       {
        "params": [
         "sum",
         "le"
        ],
        "type": "group_by_labels"
       },
       {
        "params": [
         "50",
         "le"
        ],
        "type": "histogram_percentile"
       },
       { "params": [ "1m" ], "type": "moving_avg" },
       { "params": [ "p50" ], "type": "alias" }
      ]
     ],
     "tags": { "instance": "${instance:pipe}", "sensor": "grpc_connections_durations", "yc_iam_app": "${service}" },
     "target": "histogram_quantile(0.5, sum(rate(grpc_connections_durations_bucket{instance=~'${instance:pipe}', yc_iam_app='${service}'}[2m])) by (le))",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Task Processor - ${taskprocessor_pool} Pool",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 }
  },
  {
   "title": "Task RPS",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short", "label": "rps" }
   ],
   "targets": [
    {
     "expr": "rate(taskprocessor_task_duration_count{instance=~'${instance:pipe}', pool='${taskprocessor_pool}', yc_iam_app='${service}'}[2m])",
     "legendFormat": "{{instance}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "non_negative_derivative"
       }
      ]
     ],
     "tags": {
      "instance": "${instance:pipe}",
      "pool": "${taskprocessor_pool}",
      "sensor": "taskprocessor_task_duration_count",
      "yc_iam_app": "${service}"
     },
     "target": "rate(taskprocessor_task_duration_count{instance=~'${instance:pipe}', pool='${taskprocessor_pool}', yc_iam_app='${service}'}[2m])",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Special Task States",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(taskprocessor_task_failed{instance=~'${instance:pipe}', meter_type='count', pool='${taskprocessor_pool}', yc_iam_app='${service}'}[2m])) by (sensor)",
     "legendFormat": "failed",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "non_negative_derivative"
       },
       {
        "params": [
         "sum",
         "sensor"
        ],
        "type": "group_by_labels"
       }
      ]
     ],
     "tags": {
      "instance": "${instance:pipe}",
      "meter_type": "count",
      "pool": "${taskprocessor_pool}",
      "sensor": "taskprocessor_task_failed",
      "yc_iam_app": "${service}"
     },
     "target": "sum(rate(taskprocessor_task_failed{instance=~'${instance:pipe}', meter_type='count', pool='${taskprocessor_pool}', yc_iam_app='${service}'}[2m])) by (sensor)",
     "type": "timeserie"
    },
    {
     "expr": "sum(rate(taskprocessor_task_resurrected{instance=~'${instance:pipe}', meter_type='count', pool='${taskprocessor_pool}', yc_iam_app='${service}'}[2m])) by (sensor)",
     "legendFormat": "resurrected",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "non_negative_derivative"
       },
       {
        "params": [
         "sum",
         "sensor"
        ],
        "type": "group_by_labels"
       }
      ]
     ],
     "tags": {
      "instance": "${instance:pipe}",
      "meter_type": "count",
      "pool": "${taskprocessor_pool}",
      "sensor": "taskprocessor_task_resurrected",
      "yc_iam_app": "${service}"
     },
     "target": "sum(rate(taskprocessor_task_resurrected{instance=~'${instance:pipe}', meter_type='count', pool='${taskprocessor_pool}', yc_iam_app='${service}'}[2m])) by (sensor)",
     "type": "timeserie"
    },
    {
     "expr": "sum(rate(taskprocessor_task_interrupted{instance=~'${instance:pipe}', meter_type='count', pool='${taskprocessor_pool}', yc_iam_app='${service}'}[2m])) by (sensor)",
     "legendFormat": "interrupted",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "non_negative_derivative"
       },
       {
        "params": [
         "sum",
         "sensor"
        ],
        "type": "group_by_labels"
       }
      ]
     ],
     "tags": {
      "instance": "${instance:pipe}",
      "meter_type": "count",
      "pool": "${taskprocessor_pool}",
      "sensor": "taskprocessor_task_interrupted",
      "yc_iam_app": "${service}"
     },
     "target": "sum(rate(taskprocessor_task_interrupted{instance=~'${instance:pipe}', meter_type='count', pool='${taskprocessor_pool}', yc_iam_app='${service}'}[2m])) by (sensor)",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Task Start Delay",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(taskprocessor_task_delay_bucket{instance=~'${instance:pipe}', pool='${taskprocessor_pool}', yc_iam_app='${service}'}[2m])) by (le))",
     "legendFormat": "p50",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "non_negative_derivative"
       },
       {
        "params": [
         "sum",
         "le"
        ],
        "type": "group_by_labels"
       },
       {
        "params": [
         "50",
         "le"
        ],
        "type": "histogram_percentile"
       },
       { "params": [ "p50" ], "type": "alias" }
      ]
     ],
     "tags": { "instance": "${instance:pipe}", "pool": "${taskprocessor_pool}", "sensor": "taskprocessor_task_delay", "yc_iam_app": "${service}" },
     "target": "histogram_quantile(0.5, sum(rate(taskprocessor_task_delay_bucket{instance=~'${instance:pipe}', pool='${taskprocessor_pool}', yc_iam_app='${service}'}[2m])) by (le))",
     "type": "timeserie"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(taskprocessor_task_delay_bucket{instance=~'${instance:pipe}', pool='${taskprocessor_pool}', yc_iam_app='${service}'}[2m])) by (le))",
     "legendFormat": "p75",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "non_negative_derivative"
       },
       {
        "params": [
         "sum",
         "le"
        ],
        "type": "group_by_labels"
       },
       {
        "params": [
         "75",
         "le"
        ],
        "type": "histogram_percentile"
       },
       { "params": [ "p75" ], "type": "alias" }
      ]
     ],
     "tags": { "instance": "${instance:pipe}", "pool": "${taskprocessor_pool}", "sensor": "taskprocessor_task_delay", "yc_iam_app": "${service}" },
     "target": "histogram_quantile(0.75, sum(rate(taskprocessor_task_delay_bucket{instance=~'${instance:pipe}', pool='${taskprocessor_pool}', yc_iam_app='${service}'}[2m])) by (le))",
     "type": "timeserie"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(taskprocessor_task_delay_bucket{instance=~'${instance:pipe}', pool='${taskprocessor_pool}', yc_iam_app='${service}'}[2m])) by (le))",
     "legendFormat": "p90",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "non_negative_derivative"
       },
       {
        "params": [
         "sum",
         "le"
        ],
        "type": "group_by_labels"
       },
       {
        "params": [
         "90",
         "le"
        ],
        "type": "histogram_percentile"
       },
       { "params": [ "p90" ], "type": "alias" }
      ]
     ],
     "tags": { "instance": "${instance:pipe}", "pool": "${taskprocessor_pool}", "sensor": "taskprocessor_task_delay", "yc_iam_app": "${service}" },
     "target": "histogram_quantile(0.9, sum(rate(taskprocessor_task_delay_bucket{instance=~'${instance:pipe}', pool='${taskprocessor_pool}', yc_iam_app='${service}'}[2m])) by (le))",
     "type": "timeserie"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(taskprocessor_task_delay_bucket{instance=~'${instance:pipe}', pool='${taskprocessor_pool}', yc_iam_app='${service}'}[2m])) by (le))",
     "legendFormat": "p99",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "non_negative_derivative"
       },
       {
        "params": [
         "sum",
         "le"
        ],
        "type": "group_by_labels"
       },
       {
        "params": [
         "99",
         "le"
        ],
        "type": "histogram_percentile"
       },
       { "params": [ "p99" ], "type": "alias" }
      ]
     ],
     "tags": { "instance": "${instance:pipe}", "pool": "${taskprocessor_pool}", "sensor": "taskprocessor_task_delay", "yc_iam_app": "${service}" },
     "target": "histogram_quantile(0.99, sum(rate(taskprocessor_task_delay_bucket{instance=~'${instance:pipe}', pool='${taskprocessor_pool}', yc_iam_app='${service}'}[2m])) by (le))",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Task Duration",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 20 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(taskprocessor_task_duration_bucket{instance=~'${instance:pipe}', pool='${taskprocessor_pool}', yc_iam_app='${service}'}[2m])) by (le))",
     "legendFormat": "p50",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "non_negative_derivative"
       },
       {
        "params": [
         "sum",
         "le"
        ],
        "type": "group_by_labels"
       },
       {
        "params": [
         "50",
         "le"
        ],
        "type": "histogram_percentile"
       },
       { "params": [ "p50" ], "type": "alias" }
      ]
     ],
     "tags": { "instance": "${instance:pipe}", "pool": "${taskprocessor_pool}", "sensor": "taskprocessor_task_duration", "yc_iam_app": "${service}" },
     "target": "histogram_quantile(0.5, sum(rate(taskprocessor_task_duration_bucket{instance=~'${instance:pipe}', pool='${taskprocessor_pool}', yc_iam_app='${service}'}[2m])) by (le))",
     "type": "timeserie"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(taskprocessor_task_duration_bucket{instance=~'${instance:pipe}', pool='${taskprocessor_pool}', yc_iam_app='${service}'}[2m])) by (le))",
     "legendFormat": "p75",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "non_negative_derivative"
       },
       {
        "params": [
         "sum",
         "le"
        ],
        "type": "group_by_labels"
       },
       {
        "params": [
         "75",
         "le"
        ],
        "type": "histogram_percentile"
       },
       { "params": [ "p75" ], "type": "alias" }
      ]
     ],
     "tags": { "instance": "${instance:pipe}", "pool": "${taskprocessor_pool}", "sensor": "taskprocessor_task_duration", "yc_iam_app": "${service}" },
     "target": "histogram_quantile(0.75, sum(rate(taskprocessor_task_duration_bucket{instance=~'${instance:pipe}', pool='${taskprocessor_pool}', yc_iam_app='${service}'}[2m])) by (le))",
     "type": "timeserie"
    },
    {
     "expr": "histogram_quantile(0.9, sum(rate(taskprocessor_task_duration_bucket{instance=~'${instance:pipe}', pool='${taskprocessor_pool}', yc_iam_app='${service}'}[2m])) by (le))",
     "legendFormat": "p90",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "non_negative_derivative"
       },
       {
        "params": [
         "sum",
         "le"
        ],
        "type": "group_by_labels"
       },
       {
        "params": [
         "90",
         "le"
        ],
        "type": "histogram_percentile"
       },
       { "params": [ "p90" ], "type": "alias" }
      ]
     ],
     "tags": { "instance": "${instance:pipe}", "pool": "${taskprocessor_pool}", "sensor": "taskprocessor_task_duration", "yc_iam_app": "${service}" },
     "target": "histogram_quantile(0.9, sum(rate(taskprocessor_task_duration_bucket{instance=~'${instance:pipe}', pool='${taskprocessor_pool}', yc_iam_app='${service}'}[2m])) by (le))",
     "type": "timeserie"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(taskprocessor_task_duration_bucket{instance=~'${instance:pipe}', pool='${taskprocessor_pool}', yc_iam_app='${service}'}[2m])) by (le))",
     "legendFormat": "p99",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "non_negative_derivative"
       },
       {
        "params": [
         "sum",
         "le"
        ],
        "type": "group_by_labels"
       },
       {
        "params": [
         "99",
         "le"
        ],
        "type": "histogram_percentile"
       },
       { "params": [ "p99" ], "type": "alias" }
      ]
     ],
     "tags": { "instance": "${instance:pipe}", "pool": "${taskprocessor_pool}", "sensor": "taskprocessor_task_duration", "yc_iam_app": "${service}" },
     "target": "histogram_quantile(0.99, sum(rate(taskprocessor_task_duration_bucket{instance=~'${instance:pipe}', pool='${taskprocessor_pool}', yc_iam_app='${service}'}[2m])) by (le))",
     "type": "timeserie"
    }
   ]
  },
  { "title": "JVM and System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Threads",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(jvm_threads_state{instance=~'${instance:pipe}', yc_iam_app='${service}'}) by (state)",
     "legendFormat": "{{state}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "0" ], "type": "drop_below" },
       {
        "params": [
         "avg",
         "state"
        ],
        "type": "group_by_labels"
       }
      ]
     ],
     "tags": { "instance": "${instance:pipe}", "sensor": "jvm_threads_state", "yc_iam_app": "${service}" },
     "target": "avg(jvm_threads_state{instance=~'${instance:pipe}', yc_iam_app='${service}'}) by (state)",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Non-Heap Memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 27 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg(jvm_memory_bytes_used{area='nonheap', instance=~'${instance:pipe}', yc_iam_app='${service}'}) by (sensor)",
     "legendFormat": "jvm_memory_bytes_used",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "0" ], "type": "drop_below" },
       {
        "params": [
         "avg",
         "sensor"
        ],
        "type": "group_by_labels"
       }
      ]
     ],
     "tags": { "area": "nonheap", "instance": "${instance:pipe}", "sensor": "jvm_memory_bytes_used", "yc_iam_app": "${service}" },
     "target": "avg(jvm_memory_bytes_used{area='nonheap', instance=~'${instance:pipe}', yc_iam_app='${service}'}) by (sensor)",
     "type": "timeserie"
    },
    {
     "expr": "avg(jvm_memory_bytes_committed{area='nonheap', instance=~'${instance:pipe}', yc_iam_app='${service}'}) by (sensor)",
     "legendFormat": "jvm_memory_bytes_committed",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "0" ], "type": "drop_below" },
       {
        "params": [
         "avg",
         "sensor"
        ],
        "type": "group_by_labels"
       }
      ]
     ],
     "tags": { "area": "nonheap", "instance": "${instance:pipe}", "sensor": "jvm_memory_bytes_committed", "yc_iam_app": "${service}" },
     "target": "avg(jvm_memory_bytes_committed{area='nonheap', instance=~'${instance:pipe}', yc_iam_app='${service}'}) by (sensor)",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Heap Memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 27 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg(jvm_memory_bytes_used{area='heap', instance=~'${instance:pipe}', yc_iam_app='${service}'}) by (sensor)",
     "legendFormat": "jvm_memory_bytes_used",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "0" ], "type": "drop_below" },
       {
        "params": [
         "avg",
         "sensor"
        ],
        "type": "group_by_labels"
       }
      ]
     ],
     "tags": { "area": "heap", "instance": "${instance:pipe}", "sensor": "jvm_memory_bytes_used", "yc_iam_app": "${service}" },
     "target": "avg(jvm_memory_bytes_used{area='heap', instance=~'${instance:pipe}', yc_iam_app='${service}'}) by (sensor)",
     "type": "timeserie"
    },
    {
     "expr": "avg(jvm_memory_bytes_committed{area='heap', instance=~'${instance:pipe}', yc_iam_app='${service}'}) by (sensor)",
     "legendFormat": "jvm_memory_bytes_committed",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "0" ], "type": "drop_below" },
       {
        "params": [
         "avg",
         "sensor"
        ],
        "type": "group_by_labels"
       }
      ]
     ],
     "tags": { "area": "heap", "instance": "${instance:pipe}", "sensor": "jvm_memory_bytes_committed", "yc_iam_app": "${service}" },
     "target": "avg(jvm_memory_bytes_committed{area='heap', instance=~'${instance:pipe}', yc_iam_app='${service}'}) by (sensor)",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Sys VM & RSS",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(process_virtual_memory_bytes{instance=~'${instance:pipe}', yc_iam_app='${service}'}) by (sensor)",
     "legendFormat": "process_virtual_memory_bytes",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "0" ], "type": "drop_below" },
       {
        "params": [
         "max",
         "sensor"
        ],
        "type": "group_by_labels"
       }
      ]
     ],
     "tags": { "instance": "${instance:pipe}", "sensor": "process_virtual_memory_bytes", "yc_iam_app": "${service}" },
     "target": "max(process_virtual_memory_bytes{instance=~'${instance:pipe}', yc_iam_app='${service}'}) by (sensor)",
     "type": "timeserie"
    },
    {
     "expr": "max(process_resident_memory_bytes{instance=~'${instance:pipe}', yc_iam_app='${service}'}) by (sensor)",
     "legendFormat": "process_resident_memory_bytes",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "0" ], "type": "drop_below" },
       {
        "params": [
         "max",
         "sensor"
        ],
        "type": "group_by_labels"
       }
      ]
     ],
     "tags": { "instance": "${instance:pipe}", "sensor": "process_resident_memory_bytes", "yc_iam_app": "${service}" },
     "target": "max(process_resident_memory_bytes{instance=~'${instance:pipe}', yc_iam_app='${service}'}) by (sensor)",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Max File Descriptors",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_open_fds{instance=~'${instance:pipe}', yc_iam_app='${service}'}",
     "legendFormat": "{{instance}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": { "instance": "${instance:pipe}", "sensor": "process_open_fds", "yc_iam_app": "${service}" },
     "target": "process_open_fds{instance=~'${instance:pipe}', yc_iam_app='${service}'}",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Process CPU seconds total",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{instance=~'${instance:pipe}', yc_iam_app='${service}'}[2m])",
     "legendFormat": "{{instance}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "non_negative_derivative"
       }
      ]
     ],
     "tags": { "instance": "${instance:pipe}", "sensor": "process_cpu_seconds_total", "yc_iam_app": "${service}" },
     "target": "rate(process_cpu_seconds_total{instance=~'${instance:pipe}', yc_iam_app='${service}'}[2m])",
     "type": "timeserie"
    }
   ]
  }
 ]
}