{
 "title": "JVM and System by Hosts",
 "tags": [
  "iam-duty",
  "iam-jvm-sys-host",
  "iam-duty-auto-drilldown"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "service",
    "query": "access-service,iam-control-plane,mfa-service,openid-server,org-service,rm-control-plane,reaper,team-integration,token-service"
   },
   { "name": "ds", "query": "prometheus" },
   {
    "name": "instance",
    "query": {
     "query": "label_values(grpc_statuses{instance=~'.*', yc_iam_app='${service}'}, instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "JVM and System - $instance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "instance" },
  {
   "title": "Threads",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(jvm_threads_state{instance=~'${instance}', yc_iam_app='${service}'}) by (state)",
     "legendFormat": "{{state}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "0" ], "type": "drop_below" },
       {
        "params": [
         "avg",
         "state"
        ],
        "type": "group_by_labels"
       }
      ]
     ],
     "tags": { "instance": "${instance}", "sensor": "jvm_threads_state", "yc_iam_app": "${service}" },
     "target": "avg(jvm_threads_state{instance=~'${instance}', yc_iam_app='${service}'}) by (state)",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Non-Heap Memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg(jvm_memory_bytes_used{area='nonheap', instance=~'${instance}', yc_iam_app='${service}'}) by (sensor)",
     "legendFormat": "jvm_memory_bytes_used",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "0" ], "type": "drop_below" },
       {
        "params": [
         "avg",
         "sensor"
        ],
        "type": "group_by_labels"
       }
      ]
     ],
     "tags": { "area": "nonheap", "instance": "${instance}", "sensor": "jvm_memory_bytes_used", "yc_iam_app": "${service}" },
     "target": "avg(jvm_memory_bytes_used{area='nonheap', instance=~'${instance}', yc_iam_app='${service}'}) by (sensor)",
     "type": "timeserie"
    },
    {
     "expr": "avg(jvm_memory_bytes_committed{area='nonheap', instance=~'${instance}', yc_iam_app='${service}'}) by (sensor)",
     "legendFormat": "jvm_memory_bytes_committed",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "0" ], "type": "drop_below" },
       {
        "params": [
         "avg",
         "sensor"
        ],
        "type": "group_by_labels"
       }
      ]
     ],
     "tags": { "area": "nonheap", "instance": "${instance}", "sensor": "jvm_memory_bytes_committed", "yc_iam_app": "${service}" },
     "target": "avg(jvm_memory_bytes_committed{area='nonheap', instance=~'${instance}', yc_iam_app='${service}'}) by (sensor)",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Heap Memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "avg(jvm_memory_bytes_used{area='heap', instance=~'${instance}', yc_iam_app='${service}'}) by (sensor)",
     "legendFormat": "jvm_memory_bytes_used",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "0" ], "type": "drop_below" },
       {
        "params": [
         "avg",
         "sensor"
        ],
        "type": "group_by_labels"
       }
      ]
     ],
     "tags": { "area": "heap", "instance": "${instance}", "sensor": "jvm_memory_bytes_used", "yc_iam_app": "${service}" },
     "target": "avg(jvm_memory_bytes_used{area='heap', instance=~'${instance}', yc_iam_app='${service}'}) by (sensor)",
     "type": "timeserie"
    },
    {
     "expr": "avg(jvm_memory_bytes_committed{area='heap', instance=~'${instance}', yc_iam_app='${service}'}) by (sensor)",
     "legendFormat": "jvm_memory_bytes_committed",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "0" ], "type": "drop_below" },
       {
        "params": [
         "avg",
         "sensor"
        ],
        "type": "group_by_labels"
       }
      ]
     ],
     "tags": { "area": "heap", "instance": "${instance}", "sensor": "jvm_memory_bytes_committed", "yc_iam_app": "${service}" },
     "target": "avg(jvm_memory_bytes_committed{area='heap', instance=~'${instance}', yc_iam_app='${service}'}) by (sensor)",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Sys VM & RSS",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(process_virtual_memory_bytes{instance=~'${instance}', yc_iam_app='${service}'}) by (sensor)",
     "legendFormat": "process_virtual_memory_bytes",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "0" ], "type": "drop_below" },
       {
        "params": [
         "max",
         "sensor"
        ],
        "type": "group_by_labels"
       }
      ]
     ],
     "tags": { "instance": "${instance}", "sensor": "process_virtual_memory_bytes", "yc_iam_app": "${service}" },
     "target": "max(process_virtual_memory_bytes{instance=~'${instance}', yc_iam_app='${service}'}) by (sensor)",
     "type": "timeserie"
    },
    {
     "expr": "max(process_resident_memory_bytes{instance=~'${instance}', yc_iam_app='${service}'}) by (sensor)",
     "legendFormat": "process_resident_memory_bytes",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "0" ], "type": "drop_below" },
       {
        "params": [
         "max",
         "sensor"
        ],
        "type": "group_by_labels"
       }
      ]
     ],
     "tags": { "instance": "${instance}", "sensor": "process_resident_memory_bytes", "yc_iam_app": "${service}" },
     "target": "max(process_resident_memory_bytes{instance=~'${instance}', yc_iam_app='${service}'}) by (sensor)",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Max File Descriptors",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_open_fds{instance=~'${instance}', yc_iam_app='${service}'}",
     "legendFormat": "{{instance}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" }
      ]
     ],
     "tags": { "instance": "${instance}", "sensor": "process_open_fds", "yc_iam_app": "${service}" },
     "target": "process_open_fds{instance=~'${instance}', yc_iam_app='${service}'}",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Process CPU seconds total",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{instance=~'${instance}', yc_iam_app='${service}'}[2m])",
     "legendFormat": "{{instance}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "non_negative_derivative"
       }
      ]
     ],
     "tags": { "instance": "${instance}", "sensor": "process_cpu_seconds_total", "yc_iam_app": "${service}" },
     "target": "rate(process_cpu_seconds_total{instance=~'${instance}', yc_iam_app='${service}'}[2m])",
     "type": "timeserie"
    }
   ]
  }
 ]
}