{
 "title": "IAM GRPC Connections by Hosts",
 "tags": [
  "iam-duty",
  "iam-grpc-connections",
  "iam-grpc-connections-host",
  "iam-duty-auto-drilldown"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "service",
    "query": "access-service,iam-control-plane,mfa-service,openid-server,org-service,rm-control-plane,reaper,team-integration,token-service"
   },
   { "name": "ds", "query": "prometheus" },
   {
    "name": "instance",
    "query": {
     "query": "label_values(grpc_statuses{instance=~'.*', yc_iam_app='${service}'}, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "${service} GRPC Connections - $instance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "repeat": "instance"
  },
  {
   "title": "Active Connections",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(grpc_connections_active{instance=~'${instance}', yc_iam_app='${service}'})",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "sum" ], "type": "group_lines" }
      ]
     ],
     "tags": { "instance": "${instance}", "sensor": "grpc_connections_active", "yc_iam_app": "${service}" },
     "target": "sum(grpc_connections_active{instance=~'${instance}', yc_iam_app='${service}'})",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "GRPC Connections RPS",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 2, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "rps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(grpc_connections_total{instance=~'${instance}', yc_iam_app='${service}'}[2m]))",
     "legendFormat": "rps",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "non_negative_derivative"
       },
       { "params": [ "sum" ], "type": "group_lines" },
       { "params": [ "1m" ], "type": "moving_avg" },
       { "params": [ "rps" ], "type": "alias" }
      ]
     ],
     "tags": { "instance": "${instance}", "sensor": "grpc_connections_total", "yc_iam_app": "${service}" },
     "target": "sum(rate(grpc_connections_total{instance=~'${instance}', yc_iam_app='${service}'}[2m]))",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "GRPC Active Connections",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 9, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(grpc_connections_active{instance=~'${instance}', yc_iam_app='${service}'})",
     "legendFormat": "total",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "sum" ], "type": "group_lines" },
       { "params": [ "count" ], "type": "alias" }
      ]
     ],
     "tags": { "instance": "${instance}", "sensor": "grpc_connections_active", "yc_iam_app": "${service}" },
     "target": "sum(grpc_connections_active{instance=~'${instance}', yc_iam_app='${service}'})",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Connections Durations",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.01, sum(rate(grpc_connections_durations_bucket{instance=~'${instance}', yc_iam_app='${service}'}[2m])) by (le))",
     "legendFormat": "p1",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "non_negative_derivative"
       },
       {
        "params": [
         "sum",
         "le"
        ],
        "type": "group_by_labels"
       },
       {
        "params": [
         "1",
         "le"
        ],
        "type": "histogram_percentile"
       },
       { "params": [ "1m" ], "type": "moving_avg" },
       { "params": [ "p1" ], "type": "alias" }
      ]
     ],
     "tags": { "instance": "${instance}", "sensor": "grpc_connections_durations", "yc_iam_app": "${service}" },
     "target": "histogram_quantile(0.01, sum(rate(grpc_connections_durations_bucket{instance=~'${instance}', yc_iam_app='${service}'}[2m])) by (le))",
     "type": "timeserie"
    },
    {
     "expr": "histogram_quantile(0.1, sum(rate(grpc_connections_durations_bucket{instance=~'${instance}', yc_iam_app='${service}'}[2m])) by (le))",
     "legendFormat": "p10",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "non_negative_derivative"
       },
       {
        "params": [
         "sum",
         "le"
        ],
        "type": "group_by_labels"
       },
       {
        "params": [
         "10",
         "le"
        ],
        "type": "histogram_percentile"
       },
       { "params": [ "1m" ], "type": "moving_avg" },
       { "params": [ "p10" ], "type": "alias" }
      ]
     ],
     "tags": { "instance": "${instance}", "sensor": "grpc_connections_durations", "yc_iam_app": "${service}" },
     "target": "histogram_quantile(0.1, sum(rate(grpc_connections_durations_bucket{instance=~'${instance}', yc_iam_app='${service}'}[2m])) by (le))",
     "type": "timeserie"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(grpc_connections_durations_bucket{instance=~'${instance}', yc_iam_app='${service}'}[2m])) by (le))",
     "legendFormat": "p50",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "non_negative_derivative"
       },
       {
        "params": [
         "sum",
         "le"
        ],
        "type": "group_by_labels"
       },
       {
        "params": [
         "50",
         "le"
        ],
        "type": "histogram_percentile"
       },
       { "params": [ "1m" ], "type": "moving_avg" },
       { "params": [ "p50" ], "type": "alias" }
      ]
     ],
     "tags": { "instance": "${instance}", "sensor": "grpc_connections_durations", "yc_iam_app": "${service}" },
     "target": "histogram_quantile(0.5, sum(rate(grpc_connections_durations_bucket{instance=~'${instance}', yc_iam_app='${service}'}[2m])) by (le))",
     "type": "timeserie"
    }
   ]
  }
 ]
}