{
 "title": "IAM GRPC by Methods",
 "tags": [
  "iam-duty",
  "iam-grpc",
  "iam-grpc-method",
  "iam-duty-auto-drilldown"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "service",
    "query": "access-service,iam-control-plane,mfa-service,openid-server,org-service,rm-control-plane,reaper,team-integration,token-service"
   },
   { "name": "ds", "query": "prometheus" },
   {
    "name": "instance",
    "query": {
     "query": "label_values(grpc_statuses{instance=~'.*', yc_iam_app='${service}'}, instance)"
    }
   },
   {
    "name": "app",
    "query": {
     "query": "label_values(grpc_statuses{app=~'.*', instance=~'${instance:pipe}', method=~'.*', yc_iam_app='${service}'}, app)"
    }
   },
   {
    "name": "method",
    "query": {
     "query": "label_values(grpc_statuses{app='${app}', instance=~'${instance:pipe}', method=~'.*', yc_iam_app='${service}'}, method)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "${service} GRPC Metrics - $method",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "repeat": "method"
  },
  {
   "title": "GRPC Errors",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(grpc_statuses{app='${app}', instance=~'${instance:pipe}', method=~'${method}', status='UNKNOWN|UNIMPLEMENTED|INTERNAL|DATA_LOSS', yc_iam_app='${service}'})",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "diff"
       },
       { "params": [ "0" ], "type": "drop_below" },
       { "params": [ "sum" ], "type": "group_lines" }
      ]
     ],
     "tags": {
      "app": "${app}",
      "instance": "${instance:pipe}",
      "method": "${method}",
      "sensor": "grpc_statuses",
      "status": "UNKNOWN|UNIMPLEMENTED|INTERNAL|DATA_LOSS",
      "yc_iam_app": "${service}"
     },
     "target": "sum(grpc_statuses{app='${app}', instance=~'${instance:pipe}', method=~'${method}', status='UNKNOWN|UNIMPLEMENTED|INTERNAL|DATA_LOSS', yc_iam_app='${service}'})",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "GRPC/HTTP statuses RPS",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 2, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "rps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(grpc_statuses{app='${app}', instance=~'${instance:pipe}', method=~'${method}', yc_iam_app='${service}'}[2m])) by (status)",
     "legendFormat": "{{status}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "non_negative_derivative"
       },
       { "params": [ "1m" ], "type": "moving_avg" },
       {
        "params": [
         "sum",
         "status"
        ],
        "type": "group_by_labels"
       },
       { "params": [ "{{status}}" ], "type": "alias" }
      ]
     ],
     "tags": {
      "app": "${app}",
      "instance": "${instance:pipe}",
      "method": "${method}",
      "sensor": "grpc_statuses",
      "yc_iam_app": "${service}"
     },
     "target": "sum(rate(grpc_statuses{app='${app}', instance=~'${instance:pipe}', method=~'${method}', yc_iam_app='${service}'}[2m])) by (status)",
     "type": "timeserie"
    },
    {
     "expr": "sum(rate(servlet_statuses{app='${app}', instance=~'${instance:pipe}', method=~'${method}', yc_iam_app='${service}'}[2m])) by (status)",
     "legendFormat": "{{status}}",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "non_negative_derivative"
       },
       { "params": [ "1m" ], "type": "moving_avg" },
       {
        "params": [
         "sum",
         "status"
        ],
        "type": "group_by_labels"
       },
       { "params": [ "{{status}}" ], "type": "alias" }
      ]
     ],
     "tags": {
      "app": "${app}",
      "instance": "${instance:pipe}",
      "method": "${method}",
      "sensor": "servlet_statuses",
      "yc_iam_app": "${service}"
     },
     "target": "sum(rate(servlet_statuses{app='${app}', instance=~'${instance:pipe}', method=~'${method}', yc_iam_app='${service}'}[2m])) by (status)",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 9, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(grpc_statuses{app='${app}', instance=~'${instance:pipe}', method=~'${method}', status=~'DEADLINE_EXCEEDED', yc_iam_app='${service}'}[2m]))",
     "legendFormat": "499",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "1m" ], "type": "moving_avg" },
       {
        "params": [],
        "type": "non_negative_derivative"
       },
       { "params": [ "0" ], "type": "drop_below" },
       { "params": [ "sum" ], "type": "group_lines" },
       { "params": [ "499" ], "type": "alias" }
      ]
     ],
     "tags": {
      "app": "${app}",
      "instance": "${instance:pipe}",
      "method": "${method}",
      "sensor": "grpc_statuses",
      "status": "DEADLINE_EXCEEDED",
      "yc_iam_app": "${service}"
     },
     "target": "sum(rate(grpc_statuses{app='${app}', instance=~'${instance:pipe}', method=~'${method}', status=~'DEADLINE_EXCEEDED', yc_iam_app='${service}'}[2m]))",
     "type": "timeserie"
    },
    {
     "expr": "sum(rate(grpc_statuses{app='${app}', instance=~'${instance:pipe}', method=~'${method}', status=~'CANCELLED|INVALID_ARGUMENT|NOT_FOUND|ALREADY_EXISTS|PERMISSION_DENIED|RESOURCE_EXHAUSTED|FAILED_PRECONDITION|ABORTED|OUT_OF_RANGE|UNAUTHENTICATED', yc_iam_app='${service}'}[2m]))",
     "legendFormat": "4xx",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "1m" ], "type": "moving_avg" },
       {
        "params": [],
        "type": "non_negative_derivative"
       },
       { "params": [ "0" ], "type": "drop_below" },
       { "params": [ "sum" ], "type": "group_lines" },
       { "params": [ "4xx" ], "type": "alias" }
      ]
     ],
     "tags": {
      "app": "${app}",
      "instance": "${instance:pipe}",
      "method": "${method}",
      "sensor": "grpc_statuses",
      "status": "CANCELLED|INVALID_ARGUMENT|NOT_FOUND|ALREADY_EXISTS|PERMISSION_DENIED|RESOURCE_EXHAUSTED|FAILED_PRECONDITION|ABORTED|OUT_OF_RANGE|UNAUTHENTICATED",
      "yc_iam_app": "${service}"
     },
     "target": "sum(rate(grpc_statuses{app='${app}', instance=~'${instance:pipe}', method=~'${method}', status=~'CANCELLED|INVALID_ARGUMENT|NOT_FOUND|ALREADY_EXISTS|PERMISSION_DENIED|RESOURCE_EXHAUSTED|FAILED_PRECONDITION|ABORTED|OUT_OF_RANGE|UNAUTHENTICATED', yc_iam_app='${service}'}[2m]))",
     "type": "timeserie"
    },
    {
     "expr": "sum(rate(grpc_statuses{app='${app}', instance=~'${instance:pipe}', method=~'${method}', status='UNAVAILABLE', yc_iam_app='${service}'}[2m]))",
     "legendFormat": "503",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "1m" ], "type": "moving_avg" },
       {
        "params": [],
        "type": "non_negative_derivative"
       },
       { "params": [ "0" ], "type": "drop_below" },
       { "params": [ "sum" ], "type": "group_lines" },
       { "params": [ "503" ], "type": "alias" }
      ]
     ],
     "tags": {
      "app": "${app}",
      "instance": "${instance:pipe}",
      "method": "${method}",
      "sensor": "grpc_statuses",
      "status": "UNAVAILABLE",
      "yc_iam_app": "${service}"
     },
     "target": "sum(rate(grpc_statuses{app='${app}', instance=~'${instance:pipe}', method=~'${method}', status='UNAVAILABLE', yc_iam_app='${service}'}[2m]))",
     "type": "timeserie"
    },
    {
     "expr": "sum(rate(grpc_statuses{app='${app}', instance=~'${instance:pipe}', method=~'${method}', status=~'UNKNOWN|UNIMPLEMENTED|INTERNAL|DATA_LOSS', yc_iam_app='${service}'}[2m]))",
     "legendFormat": "5xx",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "1m" ], "type": "moving_avg" },
       {
        "params": [],
        "type": "non_negative_derivative"
       },
       { "params": [ "0" ], "type": "drop_below" },
       { "params": [ "sum" ], "type": "group_lines" },
       { "params": [ "5xx" ], "type": "alias" }
      ]
     ],
     "tags": {
      "app": "${app}",
      "instance": "${instance:pipe}",
      "method": "${method}",
      "sensor": "grpc_statuses",
      "status": "UNKNOWN|UNIMPLEMENTED|INTERNAL|DATA_LOSS",
      "yc_iam_app": "${service}"
     },
     "target": "sum(rate(grpc_statuses{app='${app}', instance=~'${instance:pipe}', method=~'${method}', status=~'UNKNOWN|UNIMPLEMENTED|INTERNAL|DATA_LOSS', yc_iam_app='${service}'}[2m]))",
     "type": "timeserie"
    },
    {
     "expr": "sum(rate(servlet_statuses{app='${app}', instance=~'${instance:pipe}', method=~'${method}', status='499', yc_iam_app='${service}'}[2m]))",
     "legendFormat": "h499",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "1m" ], "type": "moving_avg" },
       {
        "params": [],
        "type": "non_negative_derivative"
       },
       { "params": [ "0" ], "type": "drop_below" },
       { "params": [ "sum" ], "type": "group_lines" },
       { "params": [ "h499" ], "type": "alias" }
      ]
     ],
     "tags": {
      "app": "${app}",
      "instance": "${instance:pipe}",
      "method": "${method}",
      "sensor": "servlet_statuses",
      "status": "499",
      "yc_iam_app": "${service}"
     },
     "target": "sum(rate(servlet_statuses{app='${app}', instance=~'${instance:pipe}', method=~'${method}', status='499', yc_iam_app='${service}'}[2m]))",
     "type": "timeserie"
    },
    {
     "expr": "sum(rate(servlet_statuses{app='${app}', instance=~'${instance:pipe}', method=~'${method}', status=~'4*|3*', yc_iam_app='${service}'}[2m]))",
     "legendFormat": "h4xx",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "1m" ], "type": "moving_avg" },
       {
        "params": [],
        "type": "non_negative_derivative"
       },
       { "params": [ "0" ], "type": "drop_below" },
       { "params": [ "sum" ], "type": "group_lines" },
       { "params": [ "h4xx3xx" ], "type": "alias" }
      ]
     ],
     "tags": {
      "app": "${app}",
      "instance": "${instance:pipe}",
      "method": "${method}",
      "sensor": "servlet_statuses",
      "status": "4*|3*",
      "yc_iam_app": "${service}"
     },
     "target": "sum(rate(servlet_statuses{app='${app}', instance=~'${instance:pipe}', method=~'${method}', status=~'4*|3*', yc_iam_app='${service}'}[2m]))",
     "type": "timeserie"
    },
    {
     "expr": "sum(rate(servlet_statuses{app='${app}', instance=~'${instance:pipe}', method=~'${method}', status='503', yc_iam_app='${service}'}[2m]))",
     "legendFormat": "h503",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "1m" ], "type": "moving_avg" },
       {
        "params": [],
        "type": "non_negative_derivative"
       },
       { "params": [ "0" ], "type": "drop_below" },
       { "params": [ "sum" ], "type": "group_lines" },
       { "params": [ "h503" ], "type": "alias" }
      ]
     ],
     "tags": {
      "app": "${app}",
      "instance": "${instance:pipe}",
      "method": "${method}",
      "sensor": "servlet_statuses",
      "status": "503",
      "yc_iam_app": "${service}"
     },
     "target": "sum(rate(servlet_statuses{app='${app}', instance=~'${instance:pipe}', method=~'${method}', status='503', yc_iam_app='${service}'}[2m]))",
     "type": "timeserie"
    },
    {
     "expr": "sum(rate(servlet_statuses{app='${app}', instance=~'${instance:pipe}', method=~'${method}', status='5*', yc_iam_app='${service}'}[2m]))",
     "legendFormat": "h5xx",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "1m" ], "type": "moving_avg" },
       {
        "params": [],
        "type": "non_negative_derivative"
       },
       { "params": [ "0" ], "type": "drop_below" },
       { "params": [ "sum" ], "type": "group_lines" },
       { "params": [ "h5xx" ], "type": "alias" }
      ]
     ],
     "tags": {
      "app": "${app}",
      "instance": "${instance:pipe}",
      "method": "${method}",
      "sensor": "servlet_statuses",
      "status": "5*",
      "yc_iam_app": "${service}"
     },
     "target": "sum(rate(servlet_statuses{app='${app}', instance=~'${instance:pipe}', method=~'${method}', status='5*', yc_iam_app='${service}'}[2m]))",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "GRPC/HTTP Durations",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 1 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(grpc_durations_bucket{app='${app}', instance=~'${instance:pipe}', method=~'${method}', yc_iam_app='${service}'}[2m])) by (le))",
     "legendFormat": "p99",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "1m" ], "type": "moving_avg" },
       {
        "params": [],
        "type": "non_negative_derivative"
       },
       {
        "params": [
         "sum",
         "le"
        ],
        "type": "group_by_labels"
       },
       {
        "params": [
         "99",
         "le"
        ],
        "type": "histogram_percentile"
       },
       { "params": [ "p99" ], "type": "alias" }
      ]
     ],
     "tags": {
      "app": "${app}",
      "instance": "${instance:pipe}",
      "method": "${method}",
      "sensor": "grpc_durations",
      "yc_iam_app": "${service}"
     },
     "target": "histogram_quantile(0.99, sum(rate(grpc_durations_bucket{app='${app}', instance=~'${instance:pipe}', method=~'${method}', yc_iam_app='${service}'}[2m])) by (le))",
     "type": "timeserie"
    },
    {
     "expr": "histogram_quantile(0.999, sum(rate(grpc_durations_bucket{app='${app}', instance=~'${instance:pipe}', method=~'${method}', yc_iam_app='${service}'}[2m])) by (le))",
     "legendFormat": "p99.9",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "1m" ], "type": "moving_avg" },
       {
        "params": [],
        "type": "non_negative_derivative"
       },
       {
        "params": [
         "sum",
         "le"
        ],
        "type": "group_by_labels"
       },
       {
        "params": [
         "99.9",
         "le"
        ],
        "type": "histogram_percentile"
       },
       { "params": [ "p99.9" ], "type": "alias" }
      ]
     ],
     "tags": {
      "app": "${app}",
      "instance": "${instance:pipe}",
      "method": "${method}",
      "sensor": "grpc_durations",
      "yc_iam_app": "${service}"
     },
     "target": "histogram_quantile(0.999, sum(rate(grpc_durations_bucket{app='${app}', instance=~'${instance:pipe}', method=~'${method}', yc_iam_app='${service}'}[2m])) by (le))",
     "type": "timeserie"
    },
    {
     "expr": "histogram_quantile(0.9999, sum(rate(grpc_durations_bucket{app='${app}', instance=~'${instance:pipe}', method=~'${method}', yc_iam_app='${service}'}[2m])) by (le))",
     "legendFormat": "p99.99",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "1m" ], "type": "moving_avg" },
       {
        "params": [],
        "type": "non_negative_derivative"
       },
       {
        "params": [
         "sum",
         "le"
        ],
        "type": "group_by_labels"
       },
       {
        "params": [
         "99.99",
         "le"
        ],
        "type": "histogram_percentile"
       },
       { "params": [ "p99.99" ], "type": "alias" }
      ]
     ],
     "tags": {
      "app": "${app}",
      "instance": "${instance:pipe}",
      "method": "${method}",
      "sensor": "grpc_durations",
      "yc_iam_app": "${service}"
     },
     "target": "histogram_quantile(0.9999, sum(rate(grpc_durations_bucket{app='${app}', instance=~'${instance:pipe}', method=~'${method}', yc_iam_app='${service}'}[2m])) by (le))",
     "type": "timeserie"
    },
    {
     "expr": "histogram_quantile(1.0, sum(rate(grpc_durations_bucket{app='${app}', instance=~'${instance:pipe}', method=~'${method}', yc_iam_app='${service}'}[2m])) by (le))",
     "legendFormat": "p100",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "1m" ], "type": "moving_avg" },
       {
        "params": [],
        "type": "non_negative_derivative"
       },
       {
        "params": [
         "sum",
         "le"
        ],
        "type": "group_by_labels"
       },
       {
        "params": [
         "100",
         "le"
        ],
        "type": "histogram_percentile"
       },
       { "params": [ "p100" ], "type": "alias" }
      ]
     ],
     "tags": {
      "app": "${app}",
      "instance": "${instance:pipe}",
      "method": "${method}",
      "sensor": "grpc_durations",
      "yc_iam_app": "${service}"
     },
     "target": "histogram_quantile(1.0, sum(rate(grpc_durations_bucket{app='${app}', instance=~'${instance:pipe}', method=~'${method}', yc_iam_app='${service}'}[2m])) by (le))",
     "type": "timeserie"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(servlet_durations_bucket{app='${app}', instance=~'${instance:pipe}', method=~'${method}', yc_iam_app='${service}'}[2m])) by (le))",
     "legendFormat": "p99h",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "1m" ], "type": "moving_avg" },
       {
        "params": [],
        "type": "non_negative_derivative"
       },
       {
        "params": [
         "sum",
         "le"
        ],
        "type": "group_by_labels"
       },
       {
        "params": [
         "99",
         "le"
        ],
        "type": "histogram_percentile"
       },
       { "params": [ "http.p99" ], "type": "alias" }
      ]
     ],
     "tags": {
      "app": "${app}",
      "instance": "${instance:pipe}",
      "method": "${method}",
      "sensor": "servlet_durations",
      "yc_iam_app": "${service}"
     },
     "target": "histogram_quantile(0.99, sum(rate(servlet_durations_bucket{app='${app}', instance=~'${instance:pipe}', method=~'${method}', yc_iam_app='${service}'}[2m])) by (le))",
     "type": "timeserie"
    },
    {
     "expr": "histogram_quantile(0.999, sum(rate(servlet_durations_bucket{app='${app}', instance=~'${instance:pipe}', method=~'${method}', yc_iam_app='${service}'}[2m])) by (le))",
     "legendFormat": "p99.9h",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "1m" ], "type": "moving_avg" },
       {
        "params": [],
        "type": "non_negative_derivative"
       },
       {
        "params": [
         "sum",
         "le"
        ],
        "type": "group_by_labels"
       },
       {
        "params": [
         "99.9",
         "le"
        ],
        "type": "histogram_percentile"
       },
       { "params": [ "http.p99.9" ], "type": "alias" }
      ]
     ],
     "tags": {
      "app": "${app}",
      "instance": "${instance:pipe}",
      "method": "${method}",
      "sensor": "servlet_durations",
      "yc_iam_app": "${service}"
     },
     "target": "histogram_quantile(0.999, sum(rate(servlet_durations_bucket{app='${app}', instance=~'${instance:pipe}', method=~'${method}', yc_iam_app='${service}'}[2m])) by (le))",
     "type": "timeserie"
    },
    {
     "expr": "histogram_quantile(0.9999, sum(rate(servlet_durations_bucket{app='${app}', instance=~'${instance:pipe}', method=~'${method}', yc_iam_app='${service}'}[2m])) by (le))",
     "legendFormat": "p99.99h",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "1m" ], "type": "moving_avg" },
       {
        "params": [],
        "type": "non_negative_derivative"
       },
       {
        "params": [
         "sum",
         "le"
        ],
        "type": "group_by_labels"
       },
       {
        "params": [
         "99.99",
         "le"
        ],
        "type": "histogram_percentile"
       },
       { "params": [ "http.p99.99" ], "type": "alias" }
      ]
     ],
     "tags": {
      "app": "${app}",
      "instance": "${instance:pipe}",
      "method": "${method}",
      "sensor": "servlet_durations",
      "yc_iam_app": "${service}"
     },
     "target": "histogram_quantile(0.9999, sum(rate(servlet_durations_bucket{app='${app}', instance=~'${instance:pipe}', method=~'${method}', yc_iam_app='${service}'}[2m])) by (le))",
     "type": "timeserie"
    },
    {
     "expr": "histogram_quantile(1.0, sum(rate(servlet_durations_bucket{app='${app}', instance=~'${instance:pipe}', method=~'${method}', yc_iam_app='${service}'}[2m])) by (le))",
     "legendFormat": "p100h",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       { "params": [ "1m" ], "type": "moving_avg" },
       {
        "params": [],
        "type": "non_negative_derivative"
       },
       {
        "params": [
         "sum",
         "le"
        ],
        "type": "group_by_labels"
       },
       {
        "params": [
         "100",
         "le"
        ],
        "type": "histogram_percentile"
       },
       { "params": [ "http.p100" ], "type": "alias" }
      ]
     ],
     "tags": {
      "app": "${app}",
      "instance": "${instance:pipe}",
      "method": "${method}",
      "sensor": "servlet_durations",
      "yc_iam_app": "${service}"
     },
     "target": "histogram_quantile(1.0, sum(rate(servlet_durations_bucket{app='${app}', instance=~'${instance:pipe}', method=~'${method}', yc_iam_app='${service}'}[2m])) by (le))",
     "type": "timeserie"
    }
   ]
  }
 ]
}