{
 "title": "IAM Service Errors by Hosts",
 "tags": [
  "iam-duty",
  "iam-system-singlestats-host",
  "iam-duty-auto-drilldown"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "service",
    "query": "access-service,iam-control-plane,mfa-service,openid-server,org-service,rm-control-plane,reaper,team-integration,token-service"
   },
   { "name": "ds", "query": "prometheus" },
   {
    "name": "instance",
    "query": {
     "query": "label_values(grpc_statuses{instance=~'.*', yc_iam_app='${service}'}, instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "IAM Singlestats - $instance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "instance" },
  {
   "title": "AS",
   "type": "stat",
   "description": "Access Service",
   "gridPos": { "h": 4, "w": 1, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(grpc_statuses{instance=~'${instance}', service='access-service', status='UNKNOWN|UNIMPLEMENTED|INTERNAL|DATA_LOSS', yc_iam_app='${service}'})",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "diff"
       },
       { "params": [ "0" ], "type": "drop_below" },
       { "params": [ "sum" ], "type": "group_lines" }
      ]
     ],
     "tags": {
      "instance": "${instance}",
      "sensor": "grpc_statuses",
      "service": "access-service",
      "status": "UNKNOWN|UNIMPLEMENTED|INTERNAL|DATA_LOSS",
      "yc_iam_app": "${service}"
     },
     "target": "sum(grpc_statuses{instance=~'${instance}', service='access-service', status='UNKNOWN|UNIMPLEMENTED|INTERNAL|DATA_LOSS', yc_iam_app='${service}'})",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "IAM",
   "type": "stat",
   "description": "IAM CP",
   "gridPos": { "h": 4, "w": 1, "x": 1, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(grpc_statuses{instance=~'${instance}', service='iam-control-plane', status='UNKNOWN|UNIMPLEMENTED|INTERNAL|DATA_LOSS', yc_iam_app='${service}'})",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "diff"
       },
       { "params": [ "0" ], "type": "drop_below" },
       { "params": [ "sum" ], "type": "group_lines" }
      ]
     ],
     "tags": {
      "instance": "${instance}",
      "sensor": "grpc_statuses",
      "service": "iam-control-plane",
      "status": "UNKNOWN|UNIMPLEMENTED|INTERNAL|DATA_LOSS",
      "yc_iam_app": "${service}"
     },
     "target": "sum(grpc_statuses{instance=~'${instance}', service='iam-control-plane', status='UNKNOWN|UNIMPLEMENTED|INTERNAL|DATA_LOSS', yc_iam_app='${service}'})",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "MFA",
   "type": "stat",
   "description": "MFA Service",
   "gridPos": { "h": 4, "w": 1, "x": 2, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(grpc_statuses{instance=~'${instance}', service='mfa-service', status='UNKNOWN|UNIMPLEMENTED|INTERNAL|DATA_LOSS', yc_iam_app='${service}'})",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "diff"
       },
       { "params": [ "0" ], "type": "drop_below" },
       { "params": [ "sum" ], "type": "group_lines" }
      ]
     ],
     "tags": {
      "instance": "${instance}",
      "sensor": "grpc_statuses",
      "service": "mfa-service",
      "status": "UNKNOWN|UNIMPLEMENTED|INTERNAL|DATA_LOSS",
      "yc_iam_app": "${service}"
     },
     "target": "sum(grpc_statuses{instance=~'${instance}', service='mfa-service', status='UNKNOWN|UNIMPLEMENTED|INTERNAL|DATA_LOSS', yc_iam_app='${service}'})",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "OID",
   "type": "stat",
   "description": "OpenID Server",
   "gridPos": { "h": 4, "w": 1, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(grpc_statuses{instance=~'${instance}', service='openid-server', status='UNKNOWN|UNIMPLEMENTED|INTERNAL|DATA_LOSS', yc_iam_app='${service}'})",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "diff"
       },
       { "params": [ "0" ], "type": "drop_below" },
       { "params": [ "sum" ], "type": "group_lines" }
      ]
     ],
     "tags": {
      "instance": "${instance}",
      "sensor": "grpc_statuses",
      "service": "openid-server",
      "status": "UNKNOWN|UNIMPLEMENTED|INTERNAL|DATA_LOSS",
      "yc_iam_app": "${service}"
     },
     "target": "sum(grpc_statuses{instance=~'${instance}', service='openid-server', status='UNKNOWN|UNIMPLEMENTED|INTERNAL|DATA_LOSS', yc_iam_app='${service}'})",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "ORG",
   "type": "stat",
   "description": "Organization Service",
   "gridPos": { "h": 4, "w": 1, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(grpc_statuses{instance=~'${instance}', service='org-service', status='UNKNOWN|UNIMPLEMENTED|INTERNAL|DATA_LOSS', yc_iam_app='${service}'})",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "diff"
       },
       { "params": [ "0" ], "type": "drop_below" },
       { "params": [ "sum" ], "type": "group_lines" }
      ]
     ],
     "tags": {
      "instance": "${instance}",
      "sensor": "grpc_statuses",
      "service": "org-service",
      "status": "UNKNOWN|UNIMPLEMENTED|INTERNAL|DATA_LOSS",
      "yc_iam_app": "${service}"
     },
     "target": "sum(grpc_statuses{instance=~'${instance}', service='org-service', status='UNKNOWN|UNIMPLEMENTED|INTERNAL|DATA_LOSS', yc_iam_app='${service}'})",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "RM",
   "type": "stat",
   "description": "RM CP",
   "gridPos": { "h": 4, "w": 1, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(grpc_statuses{instance=~'${instance}', service='rm-control-plane', status='UNKNOWN|UNIMPLEMENTED|INTERNAL|DATA_LOSS', yc_iam_app='${service}'})",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "diff"
       },
       { "params": [ "0" ], "type": "drop_below" },
       { "params": [ "sum" ], "type": "group_lines" }
      ]
     ],
     "tags": {
      "instance": "${instance}",
      "sensor": "grpc_statuses",
      "service": "rm-control-plane",
      "status": "UNKNOWN|UNIMPLEMENTED|INTERNAL|DATA_LOSS",
      "yc_iam_app": "${service}"
     },
     "target": "sum(grpc_statuses{instance=~'${instance}', service='rm-control-plane', status='UNKNOWN|UNIMPLEMENTED|INTERNAL|DATA_LOSS', yc_iam_app='${service}'})",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "RR",
   "type": "stat",
   "description": "Reaper",
   "gridPos": { "h": 4, "w": 1, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(grpc_statuses{instance=~'${instance}', service='reaper', status='UNKNOWN|UNIMPLEMENTED|INTERNAL|DATA_LOSS', yc_iam_app='${service}'})",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "diff"
       },
       { "params": [ "0" ], "type": "drop_below" },
       { "params": [ "sum" ], "type": "group_lines" }
      ]
     ],
     "tags": {
      "instance": "${instance}",
      "sensor": "grpc_statuses",
      "service": "reaper",
      "status": "UNKNOWN|UNIMPLEMENTED|INTERNAL|DATA_LOSS",
      "yc_iam_app": "${service}"
     },
     "target": "sum(grpc_statuses{instance=~'${instance}', service='reaper', status='UNKNOWN|UNIMPLEMENTED|INTERNAL|DATA_LOSS', yc_iam_app='${service}'})",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "TI",
   "type": "stat",
   "description": "Team Integration",
   "gridPos": { "h": 4, "w": 1, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(grpc_statuses{instance=~'${instance}', service='team-integration', status='UNKNOWN|UNIMPLEMENTED|INTERNAL|DATA_LOSS', yc_iam_app='${service}'})",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "diff"
       },
       { "params": [ "0" ], "type": "drop_below" },
       { "params": [ "sum" ], "type": "group_lines" }
      ]
     ],
     "tags": {
      "instance": "${instance}",
      "sensor": "grpc_statuses",
      "service": "team-integration",
      "status": "UNKNOWN|UNIMPLEMENTED|INTERNAL|DATA_LOSS",
      "yc_iam_app": "${service}"
     },
     "target": "sum(grpc_statuses{instance=~'${instance}', service='team-integration', status='UNKNOWN|UNIMPLEMENTED|INTERNAL|DATA_LOSS', yc_iam_app='${service}'})",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "TS",
   "type": "stat",
   "description": "Token Service",
   "gridPos": { "h": 4, "w": 1, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "sum(grpc_statuses{instance=~'${instance}', service='token-service', status='UNKNOWN|UNIMPLEMENTED|INTERNAL|DATA_LOSS', yc_iam_app='${service}'})",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "diff"
       },
       { "params": [ "0" ], "type": "drop_below" },
       { "params": [ "sum" ], "type": "group_lines" }
      ]
     ],
     "tags": {
      "instance": "${instance}",
      "sensor": "grpc_statuses",
      "service": "token-service",
      "status": "UNKNOWN|UNIMPLEMENTED|INTERNAL|DATA_LOSS",
      "yc_iam_app": "${service}"
     },
     "target": "sum(grpc_statuses{instance=~'${instance}', service='token-service', status='UNKNOWN|UNIMPLEMENTED|INTERNAL|DATA_LOSS', yc_iam_app='${service}'})",
     "type": "timeserie"
    }
   ]
  }
 ]
}