#!/bin/sh
# postinst script for mdb-config-salt
#
# see: dh_installdeb(1)

set -e

case "$1" in
    configure)
        # Replace upstart init
        cp -f /etc/init/salt-minion.conf.yandex /etc/init/salt-minion.conf

        # Reload systemd units
        if [[ $(which systemctl) ]]; then
            systemctl daemon-reload
        fi

        # Tell mdb-ping-salt-master that config changed
        echo '{"NONEXISTENT":-1}' > /tmp/mdb-salt-config-checksum
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
