"""added cluster slug & prober slug

Revision ID: 1dd38766cb96
Revises: 11dcddad1e7b
Create Date: 2021-06-11 15:17:01.180712

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
from sqlalchemy import text

revision = '1dd38766cb96'
down_revision = '11dcddad1e7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clusters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slug', sa.String(length=100), server_default='', nullable=False))

    with op.batch_alter_table('probers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('slug', sa.String(length=100), server_default='', nullable=False))

    # ### end Alembic commands ###

    query = r"""
        UPDATE clusters SET slug=name
    """

    connection = op.get_bind()
    connection.execute(text(query))

    query = r"""
        UPDATE probers SET slug=name
    """

    connection = op.get_bind()
    connection.execute(text(query))


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('probers', schema=None) as batch_op:
        batch_op.drop_column('slug')

    with op.batch_alter_table('clusters', schema=None) as batch_op:
        batch_op.drop_column('slug')

    # ### end Alembic commands ###
