"""Hosts_mask can be empty

Revision ID: ac45f3fc2fdd
Revises: c1d84ba0730f
Create Date: 2021-02-24 11:49:28.414154

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac45f3fc2fdd'
down_revision = 'c1d84ba0730f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prober_configs', schema=None) as batch_op:
        batch_op.alter_column('hosts_mask',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('prober_configs', schema=None) as batch_op:
        batch_op.alter_column('hosts_mask',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)

    # ### end Alembic commands ###
