PRAGMA Library("datetime.sql");
PRAGMA Library("helpers.sql");

IMPORT `datetime` SYMBOLS $get_datetime, $get_timestamp_from_days;
IMPORT `helpers` SYMBOLS $get_md5;

$src_table = {{ param["source_table_path"]->quote() }};
$dst_table = {{ input1->table_quote() }};
$pii_dst_table = {{ param["pii_destination_path"] -> quote() }};

$toString = ($data) -> (CAST($data AS String));
$decode_utf8 = ($data) -> (nvl(cast(String::Base64StrictDecode($data) as Utf8),$data));

$get_timestamp = ($ts) -> (CAST($ts AS TimeStamp));
$from_utc_ts_to_msk_dt = ($ts) -> (DateTime::MakeDatetime(DateTime::Update(AddTimeZone($ts, "Europe/Moscow"), "GMT"  as Timezone)));

$result = (
    SELECT
        $toString(`ac_full_name`)                                                           AS ac_full_name,
        $toString(`account_description`)                                                    AS crm_account_description,
        $toString(`account_id`)                                                             AS crm_account_id,
        $toString(`account_name`)                                                           AS crm_account_name,
        $toString(`acl_team_set_id`)                                                        AS acl_crm_team_set_id,
        CAST(`allow_restore` AS bool)                                                       AS allow_restore,
        $toString(`alt_address_city`)                                                       AS alt_address_city,
        $toString(`alt_address_country`)                                                    AS alt_address_country,
        $toString(`alt_address_postalcode`)                                                 AS alt_address_postalcode,
        $toString(`alt_address_state`)                                                      AS alt_address_state,
        $toString(`alt_address_street`)                                                     AS alt_address_street,
        $toString(`assigned_user_id`)                                                       AS assigned_user_id,
        $toString(`assistant`)                                                              AS assistant,
        $toString(`assistant_phone`)                                                        AS assistant_phone,
        `ba_base_rate`                                                                      AS ba_base_rate,
        $toString(`ba_currency_id`)                                                         AS ba_currency_id,
        `base_rate`                                                                         AS base_rate,
        $toString(`billing_address_city`)                                                   AS billing_address_city,
        $toString(`billing_address_country`)                                                AS billing_address_country,
        $toString(`billing_address_postalcode`)                                             AS billing_address_postalcode,
        $toString(`billing_address_state`)                                                  AS billing_address_state,
        $toString(`billing_address_street`)                                                 AS billing_address_street,
        `birthdate`                                                                         AS birthdate,
        $toString(`block_reason`)                                                           AS block_reason,
        $get_timestamp(`callback_date`)                                                     AS callback_date_ts,
        $from_utc_ts_to_msk_dt($get_timestamp(`callback_date`))                             AS callback_date_dttm_local,
        $toString(`campaign_id`)                                                            AS crm_campaign_id,
        $toString(`client_request_type`)                                                    AS client_request_type,
        $toString(`cloud_iam_id`)                                                           AS cloud_iam_id,
        $toString(`cloud_id_project`)                                                       AS cloud_id_project,
        $toString(`cloud_name`)                                                             AS cloud_name,
        $toString(`consumption_type`)                                                       AS consumption_type,
        $toString(`contact_id`)                                                             AS crm_contact_id,
        CAST(`converted` AS bool)                                                           AS converted,
        $toString($decode_utf8(`country_directory`))                                        AS country_directory,
        $toString(`country_name_phone_mobile`)                                              AS country_name_phone_mobile,
        CAST(`country_verified_phone_mobile` AS bool)                                       AS country_verified_phone_mobile,
        $toString(`created_by`)                                                             AS created_by,
        $toString(`currency_id`)                                                            AS crm_currency_id,
        $toString(`data_from_unsuccessful_attempt`)                                         AS data_from_unsuccessful_attempt,
        $toString(`data_from_unsuccessful_attempt_support`)                                 AS data_from_unsuccessful_attempt_support,
        $get_timestamp(`date_entered`)                                                      AS date_entered_ts,
        $from_utc_ts_to_msk_dt($get_timestamp(`date_entered`))                              AS date_entered_dttm_local,
        $get_timestamp(`date_modified`)                                                     AS date_modified_ts,
        $from_utc_ts_to_msk_dt($get_timestamp(`date_modified`))                             AS date_modified_dttm_local,
        $get_timestamp($get_datetime(`date_modified_from_yt`))                              AS date_modified_from_yt_ts,
        $from_utc_ts_to_msk_dt($get_datetime(`date_modified_from_yt`))                      AS date_modified_from_yt_dttm_local,
        CAST(`deleted` AS bool)                                                             AS deleted,
        $toString(`department`)                                                             AS department,
        $toString($decode_utf8(`description`))                                              AS crm_lead_description,
        `discount`                                                                          AS discount,
        $toString(`display_status`)                                                         AS display_status,
        $toString(`disqualified_reason`)                                                    AS disqualified_reason,
        $toString(`disqualified_reason_description`)                                        AS disqualified_reason_description,
        CAST(`do_not_call` AS bool)                                                         AS do_not_call,
        CAST(`do_not_mail` AS bool)                                                         AS do_not_mail,
        $toString(`employees`)                                                              AS employees,
        $toString(`facebook`)                                                               AS facebook,
        $toString(`first_name`)                                                             AS first_name,
        `first_trial_consumption_date`                                                      AS first_trial_consumption_date,
        $toString(`folder_id_project`)                                                      AS folder_id_project,
        $toString(`googleplus`)                                                             AS googleplus,
        $toString(`iam_id`)                                                                 AS iam_id,
        $toString(`id`)                                                                     AS crm_lead_id,
        $toString($decode_utf8(`industry`))                                                 AS industry,
        $toString(`inn`)                                                                    AS inn,
        $get_timestamp(`last_communication_date`)                                           AS last_communication_date_ts,
        $from_utc_ts_to_msk_dt($get_timestamp(`last_communication_date`))                   AS last_communication_date_dttm_local,
        $toString(`last_name`)                                                              AS last_name,
        $toString(`lead_priority`)                                                          AS lead_priority,
        $toString(`lead_source`)                                                            AS lead_source,
        $toString(`lead_source_description`)                                                AS lead_source_description,
        `lead_weight`                                                                       AS lead_weight,
        `linked_total_billing_accounts`                                                     AS linked_total_billing_accounts,
        `linked_total_calls`                                                                AS linked_total_calls,
        `linked_total_emails`                                                               AS linked_total_emails,
        `linked_total_notes`                                                                AS linked_total_notes,
        `linked_total_tasks`                                                                AS linked_total_tasks,
        $toString(`modified_user_id`)                                                       AS modified_user_id,
        CAST(`old_format_dimensions` AS bool)                                               AS old_format_dimensions,
        $toString(`opportunity_amount`)                                                     AS opportunity_amount,
        `opportunity_amount_currency`                                                       AS opportunity_amount_currency,
        `opportunity_date_closed`                                                           AS opportunity_date_closed,
        `opportunity_date_closed_month`                                                     AS opportunity_date_closed_month,
        `opportunity_id`                                                                    AS crm_opportunity_id,
        `opportunity_likely`                                                                AS opportunity_likely,
        `opportunity_likely_usdollar`                                                       AS opportunity_likely_usdollar,
        $toString(`opportunity_name`)                                                       AS crm_opportunity_name,
        $toString(`org_type`)                                                               AS org_type,
        `paid_consumption`                                                                  AS paid_consumption,
        $toString(`partner_id`)                                                             AS crm_partner_id,
        $toString(`passport_uid`)                                                           AS passport_uid,
        $toString(`person_type`)                                                            AS person_type,
        $toString(`phone_fax`)                                                              AS phone_fax,
        $toString(`phone_home`)                                                             AS phone_home,
        $toString(`phone_mobile`)                                                           AS phone_mobile,
        $toString(`phone_other`)                                                            AS phone_other,
        $toString(`phone_work`)                                                             AS phone_work,
        $toString(`picture`)                                                                AS picture,
        $toString(`portal_app`)                                                             AS portal_app,
        $toString(`portal_name`)                                                            AS portal_name,
        $toString(`preferred_language`)                                                     AS preferred_language,
        $toString(`primary_address_city`)                                                   AS primary_address_city,
        $toString(`primary_address_country`)                                                AS primary_address_country,
        $toString(`primary_address_postalcode`)                                             AS primary_address_postalcode,
        $toString(`primary_address_state`)                                                  AS primary_address_state,
        $toString(`primary_address_street`)                                                 AS primary_address_street,
        `project_end_date`                                                                  AS project_end_date,
        `project_start_date`                                                                AS project_start_date,
        $toString(`promocode`)                                                              AS promocode,
        `promocode_activation_date`                                                         AS promocode_activation_date,
        `promocode_sum`                                                                     AS promocode_sum,
        $toString(`refered_by`)                                                             AS refered_by,
        `release_date_consumption`                                                          AS release_date_consumption,
        $toString(`reports_to_id`)                                                          AS reports_to_id,
        $toString(`salutation`)                                                             AS salutation,
        `scoring_results`                                                                   AS scoring_results,
        $toString(`segment_ba`)                                                             AS segment_ba,
        CAST(`send_to_isv_team` AS bool)                                                    AS send_to_isv_team,
        $toString(`shipping_address_city`)                                                  AS shipping_address_city,
        $toString(`shipping_address_country`)                                               AS shipping_address_country,
        $toString(`shipping_address_postalcode`)                                            AS shipping_address_postalcode,
        $toString(`shipping_address_state`)                                                 AS shipping_address_state,
        $toString(`shipping_address_street`)                                                AS shipping_address_street,
        $toString(`status`)                                                                 AS crm_lead_status,
        $toString(`status_description`)                                                     AS status_description,
        CAST(`synced_with_main_ba` AS bool)                                                 AS synced_with_main_ba,
        $toString(`team_id`)                                                                AS crm_team_id,
        $toString(`team_set_id`)                                                            AS crm_team_set_id,
        $toString(`timezone`)                                                               AS timezone,
        $toString(`title`)                                                                  AS title,
        $toString(`tracker_id`)                                                             AS tracker_id,
        $toString(`tracker_number`)                                                         AS tracker_number,
        $toString(`training_status`)                                                        AS training_status,
        `trial_consumption`                                                                 AS trial_consumption,
        $toString(`twitter`)                                                                AS twitter,
        $toString(`utm_campaign`)                                                           AS utm_campaign,
        $toString(`utm_content`)                                                            AS utm_content,
        $toString(`utm_medium`)                                                             AS utm_medium,
        $toString(`utm_source`)                                                             AS utm_source,
        $toString(`utm_term`)                                                               AS utm_term,
        CAST(`was_pending` AS bool)                                                         AS was_pending,
        CAST(`was_round_robin` AS bool)                                                     AS was_round_robin,
        $toString(`website`)                                                                AS website,
        CAST(`whatsapp_message_sent` AS bool)                                               AS whatsapp_message_sent,
        $toString(`yandex_login`)                                                           AS yandex_login
    FROM $src_table
);

/* Save result in ODS */
INSERT INTO $dst_table WITH TRUNCATE
SELECT 
    ac_full_name                                                                    AS ac_full_name,
    crm_account_description                                                         AS crm_account_description,
    crm_account_id                                                                  AS crm_account_id,
    $get_md5(crm_account_name)                                                      AS crm_account_name_hash,
    acl_crm_team_set_id                                                             AS acl_crm_team_set_id,
    allow_restore                                                                   AS allow_restore,
    alt_address_city                                                                AS alt_address_city,
    $get_md5(alt_address_country)                                                   AS alt_address_country_hash,
    $get_md5(alt_address_postalcode)                                                AS alt_address_postalcode_hash,
    $get_md5(alt_address_state)                                                     AS alt_address_state_hash,
    $get_md5(alt_address_street)                                                    AS alt_address_street_hash,
    assigned_user_id                                                                AS assigned_user_id,
    $get_md5(assistant)                                                             AS assistant_hash,
    $get_md5(assistant_phone)                                                       AS assistant_phone_hash,
    ba_base_rate                                                                    AS ba_base_rate,
    ba_currency_id                                                                  AS ba_currency_id,
    base_rate                                                                       AS base_rate,
    billing_address_city                                                            AS billing_address_city,
    $get_md5(billing_address_country)                                               AS billing_address_country_hash,
    $get_md5(billing_address_postalcode)                                            AS billing_address_postalcode_hash,
    $get_md5(billing_address_state)                                                 AS billing_address_state_hash,
    $get_md5(billing_address_street)                                                AS billing_address_street_hash,
    $get_md5(birthdate)                                                             AS birthdate_hash,
    block_reason                                                                    AS block_reason,
    callback_date_ts                                                                AS callback_date_ts,
    callback_date_dttm_local                                                        AS callback_date_dttm_local,
    crm_campaign_id                                                                 AS crm_campaign_id,
    client_request_type                                                             AS client_request_type,
    cloud_iam_id                                                                    AS cloud_iam_id,
    cloud_id_project                                                                AS cloud_id_project,
    cloud_name                                                                      AS cloud_name,
    consumption_type                                                                AS consumption_type,
    crm_contact_id                                                                  AS crm_contact_id,
    converted                                                                       AS converted,
    country_directory                                                               AS country_directory,
    country_name_phone_mobile                                                       AS country_name_phone_mobile,
    country_verified_phone_mobile                                                   AS country_verified_phone_mobile,
    created_by                                                                      AS created_by,
    crm_currency_id                                                                 AS crm_currency_id,
    data_from_unsuccessful_attempt                                                  AS data_from_unsuccessful_attempt,
    data_from_unsuccessful_attempt_support                                          AS data_from_unsuccessful_attempt_support,
    date_entered_ts                                                                 AS date_entered_ts,
    date_entered_dttm_local                                                         AS date_entered_dttm_local,
    date_modified_ts                                                                AS date_modified_ts,
    date_modified_dttm_local                                                        AS date_modified_dttm_local,
    date_modified_from_yt_ts                                                        AS date_modified_from_yt_ts,
    date_modified_from_yt_dttm_local                                                AS date_modified_from_yt_dttm_local,
    deleted                                                                         AS deleted,
    department                                                                      AS department,
    crm_lead_description                                                            AS crm_lead_description,
    discount                                                                        AS discount,
    display_status                                                                  AS display_status,
    disqualified_reason                                                             AS disqualified_reason,
    disqualified_reason_description                                                 AS disqualified_reason_description,
    do_not_call                                                                     AS do_not_call,
    do_not_mail                                                                     AS do_not_mail,
    employees                                                                       AS employees,
    $get_md5(facebook)                                                              AS facebook_hash,
    $get_md5(first_name)                                                            AS first_name_hash,
    first_trial_consumption_date                                                    AS first_trial_consumption_date,
    folder_id_project                                                               AS folder_id_project,
    $get_md5(googleplus)                                                            AS googleplus_hash,
    iam_id                                                                          AS iam_id,
    crm_lead_id                                                                     AS crm_lead_id,
    industry                                                                        AS industry,
    inn                                                                             AS inn,
    last_communication_date_ts                                                      AS last_communication_date_ts,
    last_communication_date_dttm_local                                              AS last_communication_date_dttm_local,
    $get_md5(last_name)                                                             AS last_name_hash,
    lead_priority                                                                   AS lead_priority,
    lead_source                                                                     AS lead_source,
    lead_source_description                                                         AS lead_source_description,
    lead_weight                                                                     AS lead_weight,
    linked_total_billing_accounts                                                   AS linked_total_billing_accounts,
    linked_total_calls                                                              AS linked_total_calls,
    linked_total_emails                                                             AS linked_total_emails,
    linked_total_notes                                                              AS linked_total_notes,
    linked_total_tasks                                                              AS linked_total_tasks,
    modified_user_id                                                                AS modified_user_id,
    old_format_dimensions                                                           AS old_format_dimensions,
    opportunity_amount                                                              AS opportunity_amount,
    opportunity_amount_currency                                                     AS opportunity_amount_currency,
    opportunity_date_closed                                                         AS opportunity_date_closed,
    opportunity_date_closed_month                                                   AS opportunity_date_closed_month,
    crm_opportunity_id                                                              AS crm_opportunity_id,
    opportunity_likely                                                              AS opportunity_likely,
    opportunity_likely_usdollar                                                     AS opportunity_likely_usdollar,
    crm_opportunity_name                                                            AS crm_opportunity_name,
    org_type                                                                        AS org_type,
    paid_consumption                                                                AS paid_consumption,
    crm_partner_id                                                                  AS crm_partner_id,
    passport_uid                                                                    AS passport_uid,
    person_type                                                                     AS person_type,
    $get_md5(phone_fax)                                                             AS phone_fax_hash,
    $get_md5(phone_home)                                                            AS phone_home_hash,
    $get_md5(phone_mobile)                                                          AS phone_mobile_hash,
    $get_md5(phone_other)                                                           AS phone_other_hash,
    $get_md5(phone_work)                                                            AS phone_work_hash,
    picture                                                                         AS picture,
    portal_app                                                                      AS portal_app,
    portal_name                                                                     AS portal_name,
    preferred_language                                                              AS preferred_language,
    primary_address_city                                                            AS primary_address_city,
    $get_md5(primary_address_country)                                               AS primary_address_country_hash,
    $get_md5(primary_address_postalcode)                                            AS primary_address_postalcode_hash,
    $get_md5(primary_address_state)                                                 AS primary_address_state_hash,
    $get_md5(primary_address_street)                                                AS primary_address_street_hash,
    project_end_date                                                                AS project_end_date,
    project_start_date                                                              AS project_start_date,
    promocode                                                                       AS promocode,
    promocode_activation_date                                                       AS promocode_activation_date,
    promocode_sum                                                                   AS promocode_sum,
    refered_by                                                                      AS refered_by,
    release_date_consumption                                                        AS release_date_consumption,
    reports_to_id                                                                   AS reports_to_id,
    $get_md5(salutation)                                                            AS salutation_hash,
    scoring_results                                                                 AS scoring_results,
    segment_ba                                                                      AS segment_ba,
    send_to_isv_team                                                                AS send_to_isv_team,
    shipping_address_city                                                           AS shipping_address_city,
    $get_md5(shipping_address_country)                                              AS shipping_address_country_hash,
    $get_md5(shipping_address_postalcode)                                           AS shipping_address_postalcode_hash,
    $get_md5(shipping_address_state)                                                AS shipping_address_state_hash,
    $get_md5(shipping_address_street)                                               AS shipping_address_street_hash,
    crm_lead_status                                                                 AS crm_lead_status,
    status_description                                                              AS status_description,
    synced_with_main_ba                                                             AS synced_with_main_ba,
    crm_team_id                                                                     AS crm_team_id,
    crm_team_set_id                                                                 AS crm_team_set_id,
    timezone                                                                        AS timezone,
    $get_md5(title)                                                                 AS title_hash,
    tracker_id                                                                      AS tracker_id,
    tracker_number                                                                  AS tracker_number,
    training_status                                                                 AS training_status,
    trial_consumption                                                               AS trial_consumption,
    $get_md5(twitter)                                                               AS twitter_hash,
    utm_campaign                                                                    AS utm_campaign,
    utm_content                                                                     AS utm_content,
    utm_medium                                                                      AS utm_medium,
    utm_source                                                                      AS utm_source,
    utm_term                                                                        AS utm_term,
    was_pending                                                                     AS was_pending,
    was_round_robin                                                                 AS was_round_robin,
    website                                                                         AS website,
    whatsapp_message_sent                                                           AS whatsapp_message_sent,
    $get_md5(yandex_login)                                                          AS yandex_login_hash
FROM $result
ORDER BY `crm_lead_id`;

/* Save result in ODS PII*/
INSERT INTO $pii_dst_table WITH TRUNCATE
SELECT 
    crm_lead_id                                                         AS crm_lead_id,
    crm_account_name                                                    AS crm_account_name,
    alt_address_country                                                 AS alt_address_country,
    alt_address_postalcode                                              AS alt_address_postalcode,
    alt_address_state                                                   AS alt_address_state,
    alt_address_street                                                  AS alt_address_street,
    assistant                                                           AS assistant,
    assistant_phone                                                     AS assistant_phone,
    billing_address_country                                             AS billing_address_country,
    billing_address_postalcode                                          AS billing_address_postalcode,
    billing_address_state                                               AS billing_address_state,
    billing_address_street                                              AS billing_address_street,
    birthdate                                                           AS birthdate,
    facebook                                                            AS facebook,
    first_name                                                          AS first_name,
    googleplus                                                          AS googleplus,
    last_name                                                           AS last_name,
    phone_fax                                                           AS phone_fax,
    phone_home                                                          AS phone_home,
    phone_mobile                                                        AS phone_mobile,
    phone_other                                                         AS phone_other,
    phone_work                                                          AS phone_work,
    primary_address_country                                             AS primary_address_country,
    primary_address_postalcode                                          AS primary_address_postalcode,
    primary_address_state                                               AS primary_address_state,
    primary_address_street                                              AS primary_address_street,
    salutation                                                          AS salutation,
    shipping_address_country                                            AS shipping_address_country,
    shipping_address_postalcode                                         AS shipping_address_postalcode,
    shipping_address_state                                              AS shipping_address_state,
    shipping_address_street                                             AS shipping_address_street,
    title                                                               AS title,
    twitter                                                             AS twitter,
    yandex_login                                                        AS yandex_login
FROM $result
ORDER BY `crm_lead_id`;
