#!/bin/sh
set -e

pkg=config-disable-checkarray
conf="/etc/cron.d/mdadm"
conf2="/etc/cron.daily/mdadm"

rm_diversion() {
  dpkg-divert --package $pkg  --rename --remove "$1"
}

if [ "$1" = "remove" -o "$1" = "abort-install" -o "$1" = "disappear" ]; then
  [ -e $conf ] && rm $conf
  rm_diversion $conf
  [ -e $conf2 ] && rm $conf2
  rm_diversion $conf2
fi



exit 0
