import "proto/idl2.idl";

struct Address based on "yandex/maps/proto/search/address.proto":Address {
    struct Component based on "yandex/maps/proto/search/address.proto":Address.Component {
        enum Kind based on "yandex/maps/proto/search/kind.proto":Kind {
            Country,
            Region,
            Province,
            Area,
            Locality,
            District,
            Street,
            House,

            // railways, metro lines, etc
            Route,
            Station,
            MetroStation,
            RailwayStation,

            // miscelannea
            Vegetation,
            Hydro,
            Airport,
            Other
        }

        enum InnerEnum based on "yandex/maps/proto/search/address.proto":Address.Component.InnerEnum {
            FieldOne,
            FieldTwo
        }

        string name based on name;
        vector<Kind> kinds based on kind;

        InnerEnum innerEnum based on innerEnum;
        vector<InnerEnum> repeatedInnerEnum based on repeatedInnerEnum;
    }

    string formattedAddress based on formattedAddress;
    optional string postalCode based on postal_code;
    optional string countryCode based on country_code;
    vector<Component> components based on component;
    optional St st based on proto_st;
    color color based on proto_color;
}
