#pragma once

enum EBaseType {
    btUnknown /* "unk" */,
    btRus /* "rus" */,
    btForeign /* "for" */,
    btQuick /* "quick" */,
    btUltra /* "ultra" */,
    btMusic /* "music" */,
    btYMusic /* "ymusic" */,
    btAudio /* "audio" */,
    btAudioMatching /* "audiomatching" */,
    btQueryDb /* "querydb" */,
    btRTQueryDb /* "rtquerydb" */,
    btMemory /* "memory" */,
    btBook /* "book" */,
    btNews /* "news" */,
    btProg /* "programmer" */,
    btGoldenForeign /* "gldfor" */,
    btVideo /* "video" */,
    btVideoQuick /* "videoquick" */,
    btVideoUltra /* "videoultra" */,
    btImages /* "images" */,
    btImagesQuick /* "imagesquick" */,
    btCbir /* "cbir" */,
    btImagesUltra /* "imagesultra" */,
    btGoods /* "goods" */,
};

enum ETierType {
    ttUnknown /* "unk" */,
    ttRegional /* "geo" */,
    ttUkrain /* "ukr" */,
    ttGarbage /* "grb" */,
    ttWebTier1 /* "web1" */,
    ttPlatinum /* "plt" */,
    ttPlatinum0 /* "platinum0" */,
    ttWebFresh /* "webfresh" */,
    ttQuick /* "quick" */,
    ttQuickMed /* "quickmed" */,
    ttQuickRt /* "quickrt" */,
};
