LIBRARY()

OWNER(g:remorph)

INCLUDE(${ARCADIA_ROOT}/kernel/remorph/version.cmake)

CFLAGS(
    -DREMORPH_VERSION_MAJOR=${REMORPH_EXTVER_MAJOR}
    -DREMORPH_VERSION_MINOR=${REMORPH_EXTVER_MINOR}
    -DREMORPH_VERSION_PATCH=${REMORPH_EXTVER_PATCH}
)

SRCS(
    info.cpp
)

END()
