#!/bin/bash

if [[ "$1" =~ (-h|--h) ]];then
  echo -e "Example usage:"
  echo -e "  \e[34mList groups\e[0m"
  echo -e "    \e[1;32m`basename $0`\e[0m"
  echo -e "  \e[34mList dumps (note last /)\e[0m"
  echo -e "    \e[1;32m`basename $0` \e[36mmusic-stable-worker/\e[0m"
  echo -e "  \e[34mGet dump (note last destination folder)\e[0m"
  echo -e "    \e[1;32m`basename $0` \e[36mmusic-stable-worker/2016-02-04_15.22.24-worker01g.1035112.hprof.gz \e[1;33m./\e[0m"
else
  rsync -h -P --progress --stats rsync://eclipse01d.music.dev.yandex.net/cores/$@
fi

