# This file is generated by
# https://bb.yandex-team.ru/projects/CLOUD/repos/cloud-go/browse/tools/cmd/syncapi
# in Teamcity Task
# https://teamcity.yandex-team.ru/buildConfiguration/Cloud_Api_ApiSync

OWNER(g:cloud-api)
PROTO_LIBRARY()

PROTO_NAMESPACE(GLOBAL cloud/bitbucket/private-api)
PY_NAMESPACE(yandex.cloud.priv.iam.v1.transitional)

GRPC()
SRCS(
    agreement_service.proto
    auth_service.proto
    health_check_service.proto
    passport_federation_service.proto
    policy_service.proto
    roles_service.proto
    service_account_access_key_service.proto
    user_service.proto
)

USE_COMMON_GOOGLE_APIS(
    api/annotations
    rpc/code
    rpc/errdetails
    rpc/status
    type/timeofday
    type/dayofweek
)

IF (GO_PROTO)
    PEERDIR(
        cloud/bitbucket/common-api/yandex/cloud/api
        cloud/bitbucket/common-api/yandex/cloud/api/tools
        cloud/bitbucket/private-api/yandex/cloud/priv
        cloud/bitbucket/private-api/yandex/cloud/priv/iam/v1
        cloud/bitbucket/private-api/yandex/cloud/priv/operation
    )
ELSE()
    PEERDIR(
        cloud/bitbucket/common-api/yandex/cloud/api
        cloud/bitbucket/common-api/yandex/cloud/api/tools
        cloud/bitbucket/private-api/yandex/cloud/priv
        cloud/bitbucket/private-api/yandex/cloud/priv/iam/v1
        cloud/bitbucket/private-api/yandex/cloud/priv/operation
    )
ENDIF()
END()

