#!/bin/bash

grpcurl -H "Authorization: Bearer $IAM_TOKEN" -d "{\"id\": \"$1\"}" node-deployer.private-api.ycp.cloud.yandex.net:443 ru.yandex.cloud.ml.platform.nodedeployer.v1.NodeDeployerService/GetNode
