bitfield enum IncompleteKind based on "yandex/maps/proto/search/kind.proto":Kind {
    COUNTRY = 0,
    REGION = COUNTRY + 1
}

lite struct NotFound based on "yandex/maps/proto/search/kind.proto":NotFound {
    int i;
}

struct Address based on "yandex/maps/proto/search/address.proto":Address {
    any_collection anyAddress based on formattedAddress;
    float unknownField based on unknown_field;
    optional string optionalFormattedAddress based on formattedAddress;
    string requiredPostalCode based on postal_code;
    int intAddress based on formattedAddress;
    dictionary<string, string> mapAddress based on formattedAddress;
    IncompleteKind kind based on cc;
    optional Component component based on proto_st;
}

struct Component based on "yandex/maps/proto/search/address.proto":Address.Component {
    Address address based on innerEnum;
}

struct CustomHeaderMessage based on "yandex/maps/proto/search/kind.proto":CustomHeaderMessage {
    vector<string> repeatedS based on s;
    int notRepeated based on r;
    vector<vector<int>> vectorVector based on r;
}
