#!/bin/bash

[ -z "${YC_TOKEN}" ] && echo "You must set YC_TOKEN env" && exit 1
[ -z "${YAV_TOKEN}" ] && echo "You must set YAV_TOKEN env" && exit 1

SKM_MD_FILE="./files/skm-md.yaml"
echo "# Generated by update_secrets.sh" > ${SKM_MD_FILE}

YC_TOKEN=${YC_TOKEN} skm encrypt-md --config skm.yaml --format raw > ${SKM_MD_FILE}
